### ISSUE TITLE
Setting custom connection scopes not working

### ISSUE THREAD

**Issue by tadeaspetak** [auth0/lock#1000]
Hi there,

I have just discovered that the option to set custom `connectionScopes` in a Lock constructor stopped working at version `10.16.0`. I have experimented a little and the bug occurs from `10.12.0` and above.

This is how I construct the lock:

``` js
return new Auth0Lock(config.clientId, config.domain, {
  auth: {
    connectionScopes: {
      'google-oauth2': ['https://www.googleapis.com/auth/gmail.metadata']
    },
    params: {
      scope: 'openid offline_access',
      device: 'Chrome browser'
    },
    redirect: false
  }
});
```

Works flawlessly in `10.11.0` but  in `10.12.0`, `10.13.0` and `10.16.0`, no custom scopes are ever set.

**Comment by maksymilian-majer** [comment]
I experienced the same issue. @tadeaspetak thanks for your info about working version. I downgraded to `10.11.0` and it's working :)

**Comment by Faulik** [comment]
I can confirm this. And downgrade helped.

**Comment by cocojoe** [comment]
@luisrudge Had this reported in ZD so I'll up vote on their behalf 😄 
I did a bit of debugging to compare 10.11 and 10.12 (the breaking change).

In 10.12 the `connection_scope` now runs through `normalizeAuthParams`, when it comes to building the authorizeurl this param is no longer available to be added to the URL.

*10.11*
<img width="744" alt="screen shot 2017-06-15 at 11 22 10" src="https://user-images.githubusercontent.com/928115/27178527-8464178a-51c2-11e7-980f-4a2e2756bfab.png">

*10.12+*
<img width="757" alt="screen shot 2017-06-15 at 11 23 30" src="https://user-images.githubusercontent.com/928115/27178548-952d1788-51c2-11e7-8dd4-8ec8d2ed3a1c.png">

Hope that helps.
