### ISSUE TITLE
Error messages cut off

### ISSUE THREAD

**Issue by thearrow** [auth0/lock#1002]
- Using lock in embedded mode (providing a container id to the constructor)
- Lock version 10.16.0, installed via npm
- macOS 10.12.4, Chrome 58.0.3029.110 (64-bit)

Current behavior trying to log in with blank username/password:
(error messages are cut off due to css overflow setting)

<img width="447" alt="screen shot 2017-05-10 at 3 56 44 pm" src="https://cloud.githubusercontent.com/assets/447736/25923206/a93ddd9c-3599-11e7-8195-e59223fb897b.png">

Expected behavior:
(achieved by removing `overflow-y: auto` property on `.auth0-lock-center` div)

<img width="479" alt="screen shot 2017-05-10 at 3 56 54 pm" src="https://cloud.githubusercontent.com/assets/447736/25923254/d54a4d26-3599-11e7-9e60-eebf22926418.png">

Looks like this was changed in https://github.com/auth0/lock/pull/990

**Comment by luisrudge** [comment]
Hi, that PR actually fixed the issue. You're probably using a custom css that's affecting the end result.
Here's the standard lock style:
![image](https://cloud.githubusercontent.com/assets/941075/25955836/a83bc556-3640-11e7-8375-b649b02ad5cd.png)

**Comment by thearrow** [comment]
@luisrudge This is not a custom CSS issue - I made a test page with exactly the HTML and scripts from the Lock (Inline) example in the [docs](https://auth0.com/docs/libraries/lock/v10):

<img width="367" alt="screen shot 2017-05-11 at 9 12 00 am" src="https://cloud.githubusercontent.com/assets/447736/25956852/1a4d5a68-362a-11e7-9c91-7b7c0ec195aa.png">

Also tried taking away the style in that example:

<img width="365" alt="screen shot 2017-05-11 at 9 14 33 am" src="https://cloud.githubusercontent.com/assets/447736/25956943/5d5d17f8-362a-11e7-83d5-78aed317edb8.png">

Please try it yourself (after inserting your proper auth0 key and url) with the html file here: 

https://gist.github.com/thearrow/f65ca3a2757b3d182bd708f9b0a93e68

Again, let me reiterate: removing the `overflow-y: auto` property (or setting it to `visible`) on the `.auth0-lock-center` div fixes this issue (once you set overflow in one direction, the other automatically inherits it).

**Comment by luisrudge** [comment]
ahhh.. I tested on our example page, but it uses the modal approach, not the inline. thanks for the heads up!

**Comment by timsuchanek** [comment]
having the same issue here, @thearrow 's solution (removing `overflow-y: auto`) also worked for me

**Comment by thearrow** [comment]
Looks like this was fixed in the 10.17.0 release (https://github.com/auth0/lock/commit/4cdffbcb45e21f01feab432834a7d60a377391c4) - tested in our app and it looks good. Thanks @beneliflo + @luisrudge! 

Going ahead and closing this issue.

**Comment by luisrudge** [comment]
Ops, I forgot to close this. Thanks @thearrow 🎉
