### ISSUE TITLE
Default icon for Custom OAuth connection cropped on mobile

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/lock#1003]
When displaying the _Universal Login Page_ on some mobile devices while having the "Custom Social Connections" extension enabled and configured, those social buttons are shown with their icon wrongly cropped.

Device used on test: Samsung S2 (480x800) running Android API 16.

![image](https://cloud.githubusercontent.com/assets/3900123/25971968/8496405c-3674-11e7-8fe4-3e8ca054f8d3.png)

**EDIT 04/19/2018:** The issue still persists as of today:

GIF: http://recordit.co/YrkzvewXGa

**EDIT 07/24/2018:** The issue still persists as of today

**Comment by luisrudge** [comment]
duplicated #1223

**Comment by lbalmaceda** [comment]
@luisrudge that issue you mentioned is not a dupe of this one. In this one, the problem is the "social connection icon" like the title says. I'm reopening this one and updating the description.

**Comment by lbalmaceda** [comment]
BTW I don't think the "design" label applies here, as this looks more like a render/code issue instead.

**Comment by luisrudge** [comment]
my bad, I only looked at the image and saw that the submit button wasn't showing 😬

**Comment by luisrudge** [comment]
Can't repro on Galaxy S4

![image](https://user-images.githubusercontent.com/941075/46434730-d58ad700-c72a-11e8-95d0-a92f155ed79d.png)

![image](https://user-images.githubusercontent.com/941075/46434785-0834cf80-c72b-11e8-95dd-0038ec1e6b9d.png)
