### ISSUE TITLE
Perform login if user attempting to signup exists

### ISSUE THREAD

**Issue by dariobanfi** [auth0/lock#1005]
It would be nice if, when a user attempts to register, there would be some option that allows to automatically perform a login if the given registration mail/password combination exists.

As far as I understood this is currently not possible and an error message is shown.
However during the registration something similar is done through the `loginAfterSignUp` flag.

Would this feature make sense for you? Is a PR welcome?

**Comment by luisrudge** [comment]
Hi @dariobanfi. We certainly welcome PR's, but this feature is not something we're interested in having. Thanks for reaching out 🎉
