### ISSUE TITLE
Not able to add a select additionalSignUpFields

### ISSUE THREAD

**Issue by rbarcelos** [auth0/lock#1006]
I am getting the following error message:

C:/Users/rbarcelo/Documents/std/distribuidora/src/app/shared/services/auth.service.ts (16,73): Argument of type '{ additionalSignUpFields: { type: string; name: string; placeholder: string; options: { value: st...' is not assignable to parameter of type 'Auth0LockConstructorOptions'.
  Types of property 'additionalSignUpFields' are incompatible.
    Type '{ type: string; name: string; placeholder: string; options: { value: string; label: string; }[]; ...' is not assignable to type 'Auth0LockAdditionalSignUpField[]'.
      Type '{ type: string; name: string; placeholder: string; options: { value: string; label: string; }[]; ...' is not assignable to type 'Auth0LockAdditionalSignUpField'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type '"select" | "text"'. 

This is how I am configuring the select field:

this.lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, LOCK_CONFIG);

where 

export const LOCK_CONFIG =
    {
        additionalSignUpFields: [{
            type: "select",
            name: "location",
            placeholder: "choose your location",
            options: [
                { value: "us", label: "United States" },
                { value: "fr", label: "France" },
                { value: "ar", label: "Argentina" }
            ],
            // The following properties are optional
            icon: "https://example.com/assests/location_icon.png",
            prefill: "us"
        }]
    }

I am pretty sure that I was able to make it work on the past.. Not sure what broke it..
Thanks

**Comment by rbarcelos** [comment]
I tried Lock version 10.14 and 10.16

**Comment by luisrudge** [comment]
Hi, this is a typescript issue and we're not the ones maintaining those definition files. You probably want to open an issue in the repo that contains that definition file, which is probably https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by rbarcelos** [comment]
Do you guys know the latest version that this was working so I can keep working until they fix it?

Thanks

**Comment by luisrudge** [comment]
Nope, sorry. We don't maintain those definition files :(

**Comment by rbarcelos** [comment]
Filed https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16556 and also I was able to make it work locally.

Thanks
