### ISSUE TITLE
Ionic2 Login Not calling back properly

### ISSUE THREAD

**Issue by mibzman** [auth0/lock#1008]
I've reproduced my issue here:
https://github.com/mibzman/Ionic2Auth0

After following all instructions in the Ionic2+ Getting Started, I am unable to authenticate a user.
## Steps to Reproduce:

1. Build application from github.com/mibzman/Ionic2Auth0
2. open chrome://inspect/#devices
3. connect android device
4. run `ionic run android`
5. Observe one instance of sample application and 0 chrome instances
![image](https://cloud.githubusercontent.com/assets/5358449/26258055/042d9db6-3c91-11e7-8649-1b918e20b1fe.png)
6. press login
7. attempt to signup
8. browser window appears to close
9. new instance of cordova application opens in android WebView, instead of returning to the 'original' application instance
![image](https://cloud.githubusercontent.com/assets/5358449/26258124/4b10e3aa-3c91-11e7-9732-171a0707378f.png)

also note that the lock browser doesn't actually close.  In the sample application provided by Auth0 the chrome browser fully closes and there is only one instance in the webview.

**Comment by seiyria** [comment]
Can you add `<preference name="AndroidLaunchMode" value="singleTask" />` to your config.xml and try again?

**Comment by hzalaz** [comment]
This is not the correct repo for  [autho-cordova](https://github.com/auth0/auth0-cordova). And the solution to you issue is the one mentioned in https://github.com/auth0/lock/issues/1008#issuecomment-302794959

**Comment by mibzman** [comment]
@seiyria, this fixed the multiple task issue, but the user is still not authenticated

**Comment by seiyria** [comment]
Can you tell me what you've done that makes that repo different from the sample?

**Comment by mibzman** [comment]
The only difference between the sample and my repo is that I created a new ionic-cli project and then followed the instructions to integrate auth0 into it.  I wanted to try and isolate the issue since I'm integrating Auth0 into an existing application.

**Comment by seiyria** [comment]
That's interesting, because that's basically what I did when writing it out. What do you mean by not authenticated? Can you see anything in localstorage? Where is it failing in the process?

**Comment by mibzman** [comment]
What I mean by not authenticated is that auth.isAuthenticated() still returns false after the lock window closes.  

I'll get back to you on the other questions, I'm new to ionic development and I'm not sure how to address the last question

**Comment by mibzman** [comment]
I just checked the logs, the callback passed into client.authorize() is getting called, but it's throwing an error
```
Failed to load resource APP_NAME.auth0.com/oauth/token
```
I'm guessing this is an issue with my Auth0 account configuration?

**Comment by seiyria** [comment]
Does it literally say APP_NAME? Or does it have hungerperks in there? I checked your code and saw hungerperks but I want to be 100% sure. If it's that particular error, make sure you [Set up CORS](https://auth0.com/docs/quickstart/native/ionic2#set-up-the-client).

**Comment by mibzman** [comment]
yeah It did say hungerperks

**Comment by mibzman** [comment]
My CORS setting is
```
file://*, file://\*
```

I added the cordova one just to be sure.  no change.

**Comment by hzalaz** [comment]
Does your Auth0 client type (In Auth0 Dashboard) is Native?

**Comment by mibzman** [comment]
Yes, Client type is native

**Comment by mibzman** [comment]
based on what I have learned since creating this issue is that this issue probably has to do with client-side CORS, combined with ionic livereload. when deployed on a device with `ionic cordova run android -l` the requests are routed through the dev machine, which messes with the CORS request.  I don't have this issue when running without livereload.

**Comment by larsbrenna** [comment]
@mibzman I had the same issue on the iOS emulator. client.authorize() came back with an empty error message. When I checked the auth0 logs on their website, the error stated was "origin not allowed" with my origin value being set to my external IP. 

Running the emulator without live reload or console logging alleviated the issue, but leaves me wondering how to best to debugging now.

**Comment by mibzman** [comment]
I was actually playing with live reload this morning and wondering the same thing.  I think you can enable cross-origin logins in the dashboard, Perhaps I could set up a dev testing api with that enabled and use a different on in prod

**Comment by maxpaj** [comment]
This is seriously not great - how can I work efficiently with this? 

I can't run my application in the browser with `ionic serve` since I'm now using `cordova-plugin-safariviewcontroller` for the login flow which is not available in the laptop browser. 

I can't run my application with livereload on my phone since this issue appears.

My option at the moment is to make some changes and then push the code again to the phone, wait for 30 seconds or something and then see the change. 30 seconds is a lot.

**Comment by mibzman** [comment]
I don't have time to look into this issue again, but a quick google for 'ionic livereload cors issues' lead to this article: https://blog.ionicframework.com/handling-cors-issues-in-ionic/

maybe give that a shot?

**Comment by eauslander94** [comment]
I was had this same issue - runtime error when successfully logging into auth0 in an ionic 2+ app. I was able to fix it by putting the IP of my external dev server into the list of allowed origins (CORS) in my auth0 dashboard.  That IP is shown when I run the app from the command line and looks something like http://192.168.1.1:8100.  Hope this helps!
