### ISSUE TITLE
Limits logins to usernames only not working

### ISSUE THREAD

**Issue by ehtashamulhaq** [auth0/lock#1009]
var options = {
  // Limits logins to usernames only, not emails
  usernameStyle: 'username'
};

This option only affect the UI and ask for username but not limit the user to enter email. If I try to login using email instead of username I get authenticated successfully.

Lock version 10.13.0
Chrome (Windows 10)

**Comment by luisrudge** [comment]
This is a UI option only. The backend will log you in with either username or email (when you have username enabled for your connection).
