### ISSUE TITLE
`Code` is Null when user is redirected to `redirectUrl` from Lock Login/SignUp

### ISSUE THREAD

**Issue by jfmyers** [auth0/lock#1010]
Hi there, I'm experiencing an issue (a few times a day) where Lock does not return a `code` when redirecting to my back-end. 

Lock Version: `10.15.1`

Here is my lock configuration:
```
new Auth0Lock(
      "<#######>",
      "<#######>",
      {
        auth: {
          responseType: "code",
          responseMode: "form_post",
          redirectUrl: `${DOMAIN}/auth/jwt?redirect_url=${redirect_url}`
        },
        initialScreen: "signUp"
      }
    );
```

When the user is redirected to `/auth/jwt` the `code` is null in the form data. 

Any ideas why auth0 would send a null code after login/signup?

Thanks in advance for any suggestions/help!

**Comment by luisrudge** [comment]
Did you figure it out?
