### ISSUE TITLE
Browser error for development version of React

### ISSUE THREAD

**Issue by codejnki** [auth0/lock#1011]
I'm using lock v10.6 in an Angular2 app built using the Angular cli.

When doing our production builds we get a browser error because the development version of React has been minified.

![react-error](https://cloud.githubusercontent.com/assets/700104/26428721/43e343b0-40b1-11e7-8c17-0017a2251025.PNG)

I've got a repo with [example code here](https://github.com/codejnki/angularcliauth0)

Any ideas?

**Comment by luisrudge** [comment]
That's very weird indeed. The angular-cli adds NODE_ENV, as you can see [here](https://github.com/angular/angular-cli/blob/a34cf2c9d7425b47498247b958e744bddd34a529/docs/documentation/build.md#--dev-vs---prod-builds) and [here](https://github.com/angular/angular-cli/blob/3d9a7ff24d89f3b7c8520f7706493529e7ca4174/packages/%40angular/cli/models/webpack-configs/production.ts#L86). You're better of asking them why this is not being applied in your case. If you open an issue in their repo, please tag this issue so I can follow the issue there. Thanks 🎉
