### ISSUE TITLE
providing custom redirectUrl results in wrong redirect

### ISSUE THREAD

**Issue by timsuchanek** [auth0/lock#1016]
When setting the `redirectUrl` to `location.href`, the redirect isn't performed correctly with the hash in the url, but just appends `?code=VkpsA9ZxjjSiiCsA`.
Without the `redirectUrl` option everything works fine.
Using `auth-lock@10.16.0`.

We need this feature, because the url can change in our SPA after `Auth0Lock` has been instantiated. Another solution to the problem would be that Auth0Lock detects the url change.
Thanks!

**Comment by luisrudge** [comment]
Hi @timsuchanek! I'm not sure I understand what's happening here. Can you build a sample so I can test it out? You can use [this page](https://github.com/auth0/lock/blob/master/support/index.html) as a starting point.

**Comment by luisrudge** [comment]
It's been a while since you opened this issue. Are you still having this issue with the latest lock version? If so, please reopen this issue.

**Comment by UnsungHero97** [comment]
@luisrudge I'm not entirely sure what @timsuchanek's case is, but I'm noticing something similar. If I set `redirectUrl: `${window.location.href}`` when initializing the Auth0 Lock, the redirect location is not what I would expect.

For example, using `redirectUrl: 'http://localhost:9000/#/'` results in `http://localhost:9000/#access_token=...`. The way I know this is by preserving the logs in the Network tab in Chrome Dev Tools, where I see the following:

<img width="927" alt="screen shot 2017-08-17 at 8 13 33 pm" src="https://user-images.githubusercontent.com/440299/29442789-aecdcec4-8388-11e7-93f1-270b957de8c1.png">
<img width="926" alt="screen shot 2017-08-17 at 8 13 50 pm" src="https://user-images.githubusercontent.com/440299/29442788-aecd7e38-8388-11e7-8369-ae65f2986fab.png">

In the first screenshot, `Request URL` contains `redirect_uri=http%3A%2F%2Flocalhost%3A9000%2F%23%2F&connection=...`, which is the same as `redirect_uri=http://localhost:9000/#/&connection=...`.

So far, so good.

In the second screenshot, `location` is set to `http://localhost:9000/#access_token=...`. This is unexpected.

**Comment by luisrudge** [comment]
If the backend redirect is sending you to the wrong URL, even though the URL we send in the first call is correct, you should open a support ticket so the backend team can take a look on this. Please reach out to our amazing support team at https://support.auth0.com so they route this to the backend team. It will be super helpful if you can build a repro project. Maybe it's an issue with the `#`s in the url, but I'm not sure.
