### ISSUE TITLE
Username-Password SignUp Error!

### ISSUE THREAD

**Issue by AGutan** [auth0/lock#1020]
Hello!

Username-Password sign up returns "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO SIGN UP."

Even the live example on the main page auth0.com doesn't work.

Please, notify if you fix this issue!

**Comment by luisrudge** [comment]
Hi. We're having some issues with signup at the moment. Please follow the status page: https://status.auth0.com/incidents/3v27jkb65z3x
