### ISSUE TITLE
Add additional events for analytics

### ISSUE THREAD

**Issue by ntotten** [auth0/lock#1028]
To support gathering data on registration completion rate, we would like to add more events to lock. The Auth0.com home page currently attaches the following events by manually parsing the DOM. To avoid breaking changes in our analytics integrations, we want to make this more robust.

The events we would like to create are:

- [ ] Show Forgot Password (`forgot_password ready`)
- [ ] Submit Login (`signin submit`)
- [ ] Submit Register (`register submit`)
- [ ] Submit Forgot Password (`forgot_password submit`)
- [ ] Submit OAuth connection (`federated login`) - would need event data, `signin/register` and `connection`

Implementation would be the same as other events.

```
lock.on('signin ready', function() {
});
```

**Comment by ntotten** [comment]
It looks like we may already have events for showing register and login, they arent documented though.

**Comment by francocorreasosa** [comment]
Working on this at #1036

**Comment by ntotten** [comment]
Feedback from @hzalaz is that we dont need to add the mfa_login or last_login events since those will be going away soon. 

The "social" event maybe should be renamed to "federated" or "connection" because as @hzalaz pointed out these could be AD, SAML, etc. connections, not just social.

**Comment by francocorreasosa** [comment]
No problem, I removed them. 

Maybe `passwordless` fits better? Since connection can be `Username-And-Password` also.

**Comment by ntotten** [comment]
We decided on `federated login`

**Comment by francocorreasosa** [comment]
I'll implement that one as soon as I get the dev server running

**Comment by francocorreasosa** [comment]
Current status:
- [x] Show Forgot Password (forgot_password ready)
- [x] Submit Login (signin submit)
- [x] Submit Register (register submit)
- [x] Submit Forgot Password (forgot_password submit)
- [ ] Submit OAuth connection (federated login) - would need event data, signin/register and connection

**Comment by francocorreasosa** [comment]
Fully implemented in #1036
