### ISSUE TITLE
Add the ability to change the user's password (authenticated user)

### ISSUE THREAD

**Issue by crrobinson14** [auth0/lock#103]
Feature request: Some workflows provide an option where a user, on his/her account details screen, as a "change password" option. In Auth0 this is currently only possible during login, which requires the user to log OUT and then back in to reset it. Typically there is some sort of "old, new, confirm" dialog that can be triggered in an auth flow to do this for users without forcing them to sign out.

**Comment by jfromaniello** [comment]
:+1: indeed.

This requires a new endpoint at the api level as well.

I think the main issue is that we have the "forget passwod" flow , but we don't have yet the "change password" flow. This is "I know what's my current password but I want to change it", the main different is that this flow doesn't need a verification email, it should use a token/jwt.

**Comment by hzalaz** [comment]
Moved to internal backlog
