### ISSUE TITLE
Add bundled lock.min.js to npm module as bower is deprecating

### ISSUE THREAD

**Issue by ivarprudnikov** [auth0/lock#1037]
Provided that dependency in `NPM` **does not have** `lock.min.js` the way it does in Bower and because Bower itself is *deprecating* and [suggesting yarn, webpack instead](https://github.com/bower/bower), and because the only alternative then is to use CDN to get a bundle, would it not be sensible to include `build/lock.min.js` in NPM module `auth0-lock`.

I have just tried ditching bower in one project and moving dependencies to NPM, but the only dependency that did not have bundled script was `auth0-lock`, as you might understand in these scenarios refactoring of application (to use webpack for instance) just for the sake to use your library is a bit too much, otherwise downloading a file from CDN contradicts to good development and project management practices.

- Lock version: 10.17.0
- Registry: NPM

**Comment by amitfou** [comment]
+1 from me. I have the same concern

**Comment by mastilver** [comment]
This would also allow us to use different CDN more easily (like https://unpkg.org)

**Comment by celloist** [comment]
Any updates on this? I'm having problems moving auth0 in bower to webpack and npm in my angular 1.x project because of the bundling issue.

**Comment by luisrudge** [comment]
no news yet. Can anyone make a PR to add this in the build step? I'm happy to review and merge

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉
