### ISSUE TITLE
Unable to get id_token using just accessToken

### ISSUE THREAD

**Issue by Geczy** [auth0/lock#1040]
Using auth0lock, I cannot get an id_token if all i have is an accessToken

I can do getUserInfo() using this accessToken, but that doesn't return id_token

How do I get id_token using accessToken?

**Comment by darkyen** [comment]
You'll need to send the response type as "token id_token" to get an idToken.

**Comment by Geczy** [comment]
@darkyen keep in mind all i have is accessToken. the user has already logged in elsewhere, and is redirected to my app using accessToken 

we don't want to have them login twice

**Comment by darkyen** [comment]
If you send the `responseType: "token id_token"` you'll recieve an accessToken and an idToken in the authResult.

**Comment by Geczy** [comment]
where would i send it to, @darkyen ? what am i calling to get that response?? 

i can't call lock.show() and retrieve it on the lock`authenticated` event, because that requires them to sign in again.

all i have is

```jsx
      lock.getUserInfo(metaOptions.accessToken, (error, profile) => {
        if (!error) {
          lock.hide()
          resolve({ profile, idToken: metaOptions.idToken })
        } else {
          reject(error)
        }
      })
```

**Comment by luisrudge** [comment]
you add `id_token` to the `scope` parameter

**Comment by Geczy** [comment]
lol, read my above comment @luisrudge 

token won't return from the getuserinfo profile variable

**Comment by luisrudge** [comment]
Can you please share the snippet of code that you're using? Not just the `getUserInfo` call, but how you instantiate Lock, how you call `show`

**Comment by Geczy** [comment]
that's what you guys aren't getting, i don't call `show` 

this is an SSO application, they are logged in somewhere else and are redirected to my web page and im given an accessToken, *nothing else*

**Comment by luisrudge** [comment]
And why do you need an id_token if you can fetch all the user's information?

**Comment by hzalaz** [comment]
Hey, can we start from scratch and get a brief of your use case? (With as much detail as you can)

**Comment by Geczy** [comment]
I need the idtoken to set as my authorization bearer when making calls to my own backend api.domain.com

**Comment by Geczy** [comment]
1. user visits `app.domain.com/login/{accessToken}`
2. i get the user's profile via `getUserInfo` and log them in that way to my app
3. i need to make calls to an `api.domain.com` with an authorization bearer of `idToken`

**Comment by Geczy** [comment]
@darkyen please re-open, you didn't read my question
