### ISSUE TITLE
Login Password Bug

### ISSUE THREAD

**Issue by ftitina** [auth0/lock#1042]
Creating a password that ends with ```\``` results in a broken json request.

Status code - 500
![image](https://user-images.githubusercontent.com/28537707/27453391-44ed0b82-5764-11e7-9bb1-3e044cf901ec.png)

Browser - Chrome
OS - Ubuntu

**Comment by luisrudge** [comment]
It's working on Windows. Can you test in another OS to see if this is ubuntu specific?

![slash](https://user-images.githubusercontent.com/941075/27481197-cb08cc14-57f1-11e7-9f76-fd186dce34a6.gif)
