### ISSUE TITLE
Bad layout when using Lock on mobile

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/lock#1050]
Notice the height of the widget is not calculated properly.
![image](https://user-images.githubusercontent.com/3900123/27657662-d50f5058-5c23-11e7-8a2a-988759a49775.png)

**EDIT 07/24/2018:** The issue still persists as of today

**Comment by lbalmaceda** [comment]
Happens on **Stock Android Browser** too. 

Tested using Genymotion "Custom Phone" API 16

![image](https://user-images.githubusercontent.com/3900123/43164522-c61dd6d2-8f67-11e8-929b-ee570e0f49d2.png)

![image](https://user-images.githubusercontent.com/3900123/43164468-96a7f842-8f67-11e8-820f-f5414b8f181d.png)

**Comment by luisrudge** [comment]
Same as https://github.com/auth0/lock/issues/1050, will keep tracking there
