### ISSUE TITLE
Module not found exception when importing on Mac

### ISSUE THREAD

**Issue by mattwhetton** [auth0/lock#1057]
I'm getting the error below when trying to build my webpack based solution on a Mac:

`Module not found: Error: Can't resolve 'qs' in .../node_modules/auth0-lock/lib/core/web_api`

I'm importing like this `import Auth0Lock from 'auth0-lock';` and have installed using npm. It seems to be working fine on my windows machine, but wont build on my Mac.

Some more of the output for information:

`@ ./~/auth0-lock/lib/core/web_api/legacy_api.js 25:10-23`
`@ ./~/auth0-lock/lib/core/web_api.js`
`@ ./~/auth0-lock/lib/core.js`
`@ ./~/auth0-lock/lib/index.js`
`@ ./app/components/LoginConnectorComponent/LoginConnectorComponent.js`
`@ ./app/componentLocator.js`
`@ ./app/index.js`

**Comment by luisrudge** [comment]
What version?

**Comment by mattwhetton** [comment]
Lock.js 10.18.0
webpack 2.3.2

**Comment by luisrudge** [comment]
Can you try: 

```
rm -rf node_modules
npm install (or yarn if you're using yarn)
```

`qs` is a dependency of auth0.js (https://github.com/auth0/auth0.js/blob/master/package.json#L41), so it has to be downloaded

**Comment by mattwhetton** [comment]
Removing and reinstalling the node packages didn't help, but I manually added `qs` to my project and that has seemed to resolve it.

**Comment by luisrudge** [comment]
what node/npm version you have?

**Comment by mattwhetton** [comment]
Node: 4.2.3
NPM: 2.14.7

**Comment by luisrudge** [comment]
That's probably it.. npm2 is not supported anymore. This shouldn't happen in npm 3+. If it does, please reopen this issue.
