### ISSUE TITLE
Blurriness behind the lock logo cannot be removed

### ISSUE THREAD

**Issue by smosgr** [auth0/lock#1058]
Following the suggestion of Auth0 support, I am opening a new issue regarding the Auth0 lock. 

I have been trying for a while to remove the blurriness behind the logo on the header of my lock with no susccess. I have used some css tricks, such as “filter: blur(0px)“, but nothing. Could anyone help with that?

I am also attaching a screenshot that shows the issue (yellow arrow). Just to make it clear, the header background is a flat red (i.e. "red") and the actual logo does not include any fade out.

I am referring to lock version 10.18.0 and tried it on Firefox and Google Chrome browsers.

![pasted image at 2017_07_12 09_50 am](https://user-images.githubusercontent.com/6523694/28115969-ec45ed50-66fe-11e7-882d-767c8be7012a.png)

**Comment by luisrudge** [comment]
you have to use `!important` to override the blur, because we're adding it via inline styles: https://github.com/auth0/lock/blob/650767dd4f472ce144ee3e3dd55c4fb4f5fbd0df/src/ui/box/header.jsx#L75

**Comment by smosgr** [comment]
By the way this is what I am doing in regards to the header background. The blur is still there.

`      .auth0-lock.auth0-lock .auth0-lock-header-bg{
        background-color:#eb1701 !important;
        /*filter: blur(0px) !important; */
        } `

**Comment by luisrudge** [comment]
Can you please provide your lock configuration?

**Comment by smosgr** [comment]
Do you mean the content of the "options" variable? Is it a good idea to post everything on a public website?

**Comment by luisrudge** [comment]
Yup, no problem. You can hide the clientId and tenant if you want.

**Comment by smosgr** [comment]
I have uploaded the code in the attached text file.

[login.txt](https://github.com/auth0/lock/files/1142243/login.txt)

**Comment by luisrudge** [comment]
Try this:
```css
.auth0-lock-header-bg-blur {
  display: none !important;
}
```

**Comment by smosgr** [comment]
that worked fine. Thanks for the help. 

Last question. Is there a document where I can find all the css tags of auth0?

**Comment by luisrudge** [comment]
Nope. We're not committed to any css classes or dom structure and relying on them to modify Lock's behaviour or design is not something we support or recommend. I'm glad you got your setup working 🎉
