### ISSUE TITLE
Change icons from input fields on lock

### ISSUE THREAD

**Issue by smosgr** [auth0/lock#1059]
In the process of customizing our lock I would like to change the icons in the input field (i.e. identity icon and locker icon). By inspecting the auth0 lock on chrome and firefox, I found that this part of the css class is disabled. Could you please help? Thank you

I am attaching a printscreen and the [link](https://www.dropbox.com/s/rxyty0z5pe22aie/login.html?dl=0) with the relevant code. 

Lock version is 10.19.

The printscreen is below. 

<img width="323" alt="icons" src="https://user-images.githubusercontent.com/6523694/28163472-3496900e-67c3-11e7-9e02-dd87d1a5d98a.png">

**Comment by luisrudge** [comment]
The icons are svg elements, so I'm not sure you'll be able to change them with css only. This is not supported at the moment.
