### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by dixso** [auth0/lock#106]
Hi,
Is necessary this?
https://github.com/auth0/lock/blob/master/index.js#L212
Regards.

**Comment by pose** [comment]
Hi dixso,

How are you? It's important from a troubleshooting point of view. Can you describe a bit what problem are you experiencing with that?

Thanks in advance,

**Comment by dixso** [comment]
Hi,
In my application I'm using:
- angular-jwt
- angular-storage
- auth0-angular
- auth0-lock

And my console show this message.
I think you could put a debug flag and prevent the message from being displayed.
Thanks!

**Comment by pose** [comment]
Hi @dixso,

We've decided that we will remove all `console.log` from the code and use instead [visionmedia/debug](https://github.com/visionmedia/debug). I'll let you know when the change has been made.

Thanks again,
