### ISSUE TITLE
Password criteria area not collapsed when criteria met on smaller screens

### ISSUE THREAD

**Issue by cfoxcfox** [auth0/lock#1061]
Hello,

If using a mobile device with a smaller screen, when a user is entering a password when creating an account with auth0, once that password has met the criteria provided, the expanded area which the criteria fit in does not collapse until the user selects something else. This is a usability issue where there is a blank area shown when it should be collapsed.

Entered password has not yet met all the criteria:
![password not yet valid](https://user-images.githubusercontent.com/13558660/28378874-6460ae42-6c77-11e7-963c-081415af6161.PNG)

Password meets all the criteria:
![password valid](https://user-images.githubusercontent.com/13558660/28378879-689a3cee-6c77-11e7-9f9b-5fefc246fcae.PNG)

**Comment by nemccarthy** [comment]
+1 This is a big issue for us as well - pretty much finding the lock component isnt responsive

**Comment by mikelax** [comment]
I think this issue is resolved in the new version of Lock, [v11](https://auth0.com/docs/libraries/lock/v11/migration-v10-v11). 
I just set up a password policy using v11 and the Password "Requirements" are displayed a an overlay until they are all satisfied and then it disappears automatically.

**Comment by luisrudge** [comment]
I believe this is true for older versions (10.x) of the libraries as well. v11 had little to none breaking changes 🎉 I'll close this one. If you still have this with the latest version, please reopen.

**Comment by luisrudge** [comment]
Also, thanks @mikelax for confirming it's working today 😊
