### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'descriptor.get') in Safari 10.1.1

### ISSUE THREAD

**Issue by michabaur** [auth0/lock#1062]
I get this error with Safari 10.1.1 and lock 10.18.0 during show(). With the unminified lock.js, the error is thrown in line 24366 (inputValueTracking.track):

if (node.hasOwnProperty(valueField) || typeof descriptor.get !== 'function' || typeof descriptor.set !== 'function') {

descriptor is defined like this and undefined in my case:

var descriptor = Object.getOwnPropertyDescriptor(node.constructor.prototype, valueField);

**Comment by luisrudge** [comment]
Can you reproduce this in a brand new project? Or only inside your project?

**Comment by luisrudge** [comment]
It's been a while since you opened this issue. Are you still having this issue with the latest lock version? If so, please reopen this issue.

**Comment by mivanyna** [comment]
![image](https://user-images.githubusercontent.com/10868397/107641571-759e8680-6c7c-11eb-90b9-59bc0228bae3.png)
Receiving the same error on Safari, but not sure what is the reason :(

**Comment by mivanyna** [comment]
As well before that received 403 error:
![image](https://user-images.githubusercontent.com/10868397/107641980-f3fb2880-6c7c-11eb-8c88-21c6f1548211.png)

**Comment by mivanyna** [comment]
As well before that received 403 error
![image](https://user-images.githubusercontent.com/10868397/107642090-13925100-6c7d-11eb-9aff-fed3d8776a42.png)

**Comment by mivanyna** [comment]
@michabaur have you found how to fix it?

**Comment by mivanyna** [comment]
And some local variables:
![image](https://user-images.githubusercontent.com/10868397/107644116-adf39400-6c7f-11eb-9b5e-adc5b508d979.png)

**Comment by mivanyna** [comment]
@luisrudge And it happens only if there is no auth0 cookies. Can you help me with this?

**Comment by michabaur** [comment]
Sorry, I don't have a solution. I no longer needed to use auth0 and didn't spend more time investigating this.

**Comment by mivanyna** [comment]
Ok, I see, thanks
