### ISSUE TITLE
rememberLastLogin does not work. Auth0-lock always display login form.

### ISSUE THREAD

**Issue by vladotesanovic** [auth0/lock#1064]
Lock version: auth0-lock@10.19.0
Browser & OS: Chrome

```javascript
new auth.default(config.auth0LockUsername, config.auth0LockURL, {
      auth: {
        redirectUrl: config.callbackURLAuth,
        redirect: false,
        responseType: 'token',
        audience: 'https://OURDOMAIN.eu.auth0.com/api/v2/',
        params: {
          scope: 'openid profile'
        },
        sso: true
      },
      rememberLastLogin: true,
      allowSignUp: false,
      oidcConformant: true,
      closable: false,
});
```

As mentioned in title, After Logout in app - Login Form is always displayed instead of having button with last logged in user.

That worked before i set: oidcConformant and audience attributes.

**Comment by luisrudge** [comment]
`rememberLastLogin` doesn't work with oidc clients. We'll have docs when `oidcConformant` is fully supported.

**Comment by vladotesanovic** [comment]
@luisrudge Is there any way to use **audience** attribute without **oidcConformant: true** ?

**Comment by luisrudge** [comment]
You can't. We have a check to don't let that happen. https://github.com/auth0/lock/blob/146abaea36fa828584468eb3ddf47401c6c7f27d/src/core/index.js#L280-L284

**Comment by zatziky** [comment]
@luisrudge 

you said:

> rememberLastLogin doesn't work with oidc clients. We'll have docs when oidcConformant is fully supported.

Does it mean it doesn't work now OR it's not ever supposed to work?

**Comment by luisrudge** [comment]
@zatziky v10 of lock won't support oidc+ rememberLastLogin. In v11, though, we added support for that again, although it requires a bit of configuration.

**Comment by luisrudge** [comment]
If you want to test it, you can try with version `11.0.0-beta.2`. Since it uses `checkSession` internally, you'll have to follow this docs to make it work: https://auth0.com/docs/libraries/auth0js/v8#using-checksession-to-acquire-new-tokens
