### ISSUE TITLE
Can't authenticate when using a Progressive Web App

### ISSUE THREAD

**Issue by tmpg** [auth0/lock#1065]
My web app is a Progressive Web App: https://developers.google.com/web/progressive-web-apps/

When I am using Lock and trying to authenticate through a social account. It redirects but does not actually authenticate. It works fine in the browser.

Below is a video of the issue:

https://drive.google.com/file/d/0ByRGN39YqCdhdU9NZmxSak5sV28/view

As you can see using a progressive web app and accessing it by means of the home screen causes the redirect to not work properly to log in. I show at the end that it works fine via the Chrome browser.

Stack: Meteor Reactjs Auth0 lock

**Comment by luisrudge** [comment]
Can you make sure the redirect to the app has all the information somehow? Like.. access token, id token etc?

**Comment by tmpg** [comment]
A bit confused what you are asking. Do you mean from the auth0 authentication back to the progressive web app when it tries to authenticate?

**Comment by luisrudge** [comment]
Yes. We redirect you back to your app, right? When we redirect, we send some query string parameters. Can you make sure your app is receiving those parameters? It works in chrome because it's a normal browser and the url thing just works. So, when your PWA loads after the redirect, can you make sure you have the query string parameters available?

**Comment by tmpg** [comment]
It is not getting the query string. The redirect causes the app to just reload. I am looking into the way you redirect in the Lock lib. Perhaps an exception could be added for PWA's. Looks like something like this may work:

https://stackoverflow.com/questions/37985784/redirection-in-progressive-web-app

**Comment by luisrudge** [comment]
We don't test specifically against PWAs, but we have an API to make it work.

You'll have to set `autoParseHash` to `false` and then use  [`resumeAuth`](https://github.com/auth0/lock#resumeauthhash-callback) when you actually load your application. How you can get the hash, it's up to you and your PWA implementation. It'll be something like this:

```js
var options = {
  auth: {
   autoParseHash: false
  }
};
var lock = new Auth0Lock(clientId, domain, options);


//when your PWA loads:
var hash = getHashFromPWALaunch();
lock.resumeAuth(hash, function(error, authResult) {
  if (error) {
    alert("Could not parse hash");
  }
  console.log(authResult.accessToken);
});
```
