### ISSUE TITLE
Cannot read property 'getUserInfo' of undefined

### ISSUE THREAD

**Issue by yidongw** [auth0/lock#1068]
I'm using ionic to develop an App. I used web lock, but it gave me this error, "Cannot read property 'getUserInfo' of undefined". It's okay if I use "getProfile".

I shared my file here. Please take a look.
https://drive.google.com/file/d/0ByiKXb6LVsWyUGIzckk0MmFXV0E/view?usp=sharing OR
https://drive.google.com/open?id=0B8B2NRn4-gCkQ21yOXJfdHpHdUE

I just followed a doc here. https://auth0.com/docs/libraries/lock/v10

Error message:
core.es5.js:1084 ERROR TypeError: Cannot read property 'getUserInfo' of undefined
at e.<anonymous> (auth.ts:13)
at e.n.emit (events.js:81)
at index.js:481
at t.invokeTask (polyfills.js:3)
at Object.onInvokeTask (core.es5.js:4140)
at t.invokeTask (polyfills.js:3)
at r.runTask (polyfills.js:3)
at invoke (polyfills.js:3)
at n (polyfills.js:2)

I included the js files
  
  <script src="https://cdn.auth0.com/js/auth0/8.0.4/auth0.min.js"></script>
  
  <script src="http://cdn.auth0.com/js/lock/10.19.0/lock.min.js"></script>

**Comment by luisrudge** [comment]
Sorry, I ran your sample but the `authenticated` event is never fired. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by yidongw** [comment]
I was able to run this no problem.
`this.lock.on('authenticated', (authResult:any) => {
      this.lock.getProfile(authResult.idToken, function(error:any, profile:any){
        if(error){
          throw new Error(error);
        }
        localStorage.setItem('id_token', authResult.idToken);
        localStorage.setItem('profile', JSON.stringify(profile));
      });
    });`

But I keep having this error "Cannot read property 'getUserInfo' of undefined" when i have this code
`    this.lock.on("authenticated", function(authResult) {
      this.lock.getUserInfo(authResult.accessToken, function(error, profile) {
        if (error) {
          throw new Error(error);
        }
    
        localStorage.setItem('accessToken', authResult.accessToken);
        localStorage.setItem('profile', JSON.stringify(profile));
      });
    });`

Support team didn't answer my question so I reached out here.

Please please help.

**Comment by luisrudge** [comment]
As I said, I ran your sample but the code never hit that specific part of the code (it didn't emit the 'authenticated' event at all). Please give me your ticket number so I can take a look and escalate it. Thanks.

**Comment by yidongw** [comment]
Maybe your configuration is different than mine. Ticket number is #26225.

Thanks. I really want to get it working

**Comment by luisrudge** [comment]
I just pinged someone internally. Let's see how it goes. Did you try our quickstarts?
ionic1: https://auth0.com/docs/quickstart/native/ionic/01-login
ionic2+: https://auth0.com/docs/quickstart/native/ionic2/01-login

**Comment by yidongw** [comment]
In quickstarts: 
Cannot read property 'isAvailable' of undefined
This means that you're attempting to test this in a browser. At this time you'll need to run this either in an emulator or on a device.

I need to test it in browser, if we have to run in an emulator, it will take way too much time.

So I used the web lock instead.

**Comment by luisrudge** [comment]
What about this one? https://auth0.com/docs/quickstart/spa/angular2 ionic2 is just angular2, so you can follow the same concepts

**Comment by yidongw** [comment]
I haven't try that. I'll try it today

So you are not recommend to use the Lock?

**Comment by luisrudge** [comment]
Ah! Sorry. I thought the QuickStart used Lock. So don't use that. Your best bet are the ionic quickstarts then.

**Comment by yidongw** [comment]
No quickstart uses the lock...

I followed the lock document from here  https://auth0.com/docs/libraries/lock/v10
