### ISSUE TITLE
lock.show(options) does not override redirect url

### ISSUE THREAD

**Issue by strin** [auth0/lock#1071]
I tried

```
this.lock.show({
        auth: {
          redirectUrl: document.location.host + '/new'.
        }
    });
```

but the lock still redirects me to `/`.

**Comment by luisrudge** [comment]
The docs mention which properties are being overwritten: https://github.com/auth0/lock/blob/master/README.md#showoptions

The `auth` property will not be overridden by the options passed in the `show` method.
