### ISSUE TITLE
Supported special characters not allowed in Lock

### ISSUE THREAD

**Issue by Annyv2** [auth0/lock#1072]
Our [documentation](https://auth0.com/docs/connections/database/require-username#allowed-characters) says that we allow `.` characters in usernames, but Lock 10.18 doesn't allow to use them. 

![image](https://user-images.githubusercontent.com/5016479/29019344-5f918684-7b5e-11e7-8836-63dd5ea98efe.png)

**Comment by justinclift** [comment]
Thanks @luisrudge, is there an ETA for the next release (which includes this)? :smile:

**Comment by luisrudge** [comment]
If all goes well, today 🎉

**Comment by justinclift** [comment]
Awesome, thanks. 😁
