### ISSUE TITLE
Lack of spacing in Lock 10.19 additional signup fields

### ISSUE THREAD

**Issue by Annyv2** [auth0/lock#1075]
When adding additional signup fields to Lock 10.19 or Lock 10.18, there is a lack of space between a couple of fields, which looks odd. If lock 10.17 is used then it works fine

You can see a screenshot of the issue here:
![image](https://user-images.githubusercontent.com/5016479/29063857-7e466332-7c27-11e7-81a4-27c0c7371704.png)

Lock 10.17 version here:

![image](https://user-images.githubusercontent.com/5016479/29063881-8c41d976-7c27-11e7-9a11-56f8529ce533.png)

**Comment by luisrudge** [comment]
Thanks! This will be fixed in the next release 🎉

**Comment by iceman3000** [comment]
This bug was re-introduced in version 10.18
