### ISSUE TITLE
Undocumented setting in v10: defaultADUsernameFromEmailPrefix

### ISSUE THREAD

**Issue by gdestuynder** [auth0/lock#1077]
The PR: https://github.com/auth0/lock/pull/754 adds supports for the lock setting `defaultADUsernameFromEmailPrefix` in lock v10 but fails to document it.

In addition it reverts the new default of using the full email for AD enterprise connections login, to chopping it down to the first part of the email (eg: 'bob' for 'bob@example.net').

This should be documented, at the minimum

**Comment by luisrudge** [comment]
Hi, this option is in our docs page: https://auth0.com/docs/libraries/lock/v10/customization#defaultadusernamefromemailprefix-boolean-
