### ISSUE TITLE
SAML 2.0 IDP: issuer problem

### ISSUE THREAD

**Issue by paulocheque** [auth0/lock#1078]
Hi, I am using Auth0 as a Identity Provider for an external SAML 2.0 Service Provider.

I got this error from the Service Provider: **The SAML Response issuer is not the same entity to whom the corresponding request was sent.**

Checking the SAML response the Auth0 generates in the http://samltool.io website, I saw Auth0 adds a LINE BREAK CHAR in the end of the issuer. I was wondering this could be the problem. Could you confirm?

I got this:

    <saml:Issuer
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">MY_ISSUER
    </saml:Issuer>

instead of this:

    <saml:Issuer
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">MY_ISSUER</saml:Issuer>

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
