### ISSUE TITLE
Selenium on Safari/Mac don't work

### ISSUE THREAD

**Issue by mariwing** [auth0/lock#1080]
Hi guys!

Since version 18 (also tested with 19) my Selenium scripts that types username/passwords into the username/password boxes don't work on Safari/Mac (running on Saucelabs). The text gets inputed but the javascript validation ("Can't be blank") are shown when the form is submitted and the form is not submitted. The same script works on the rest of the browsers I test with. This test worked in Safari with lock version 17.

Link to test where it fails (Lock 19): https://saucelabs.com/beta/tests/a7468e2916aa47beb896864cbf4f0459/watch

Link to test that works: (Lock 17):
https://saucelabs.com/beta/tests/513c0ed51dfa4778bc20ba280fccf2d2/watch

I know the identifiers for finding the elements have changed and I have updated my script accordingly. As you can see from the video, the text gets entered so I don't think the changed locators are the reason for the failure to submit the form. It would be great if it is possible for you guys to fix this so it works with Selenium as before. Thanks!

Regards, Marius Wingerei

**Comment by luisrudge** [comment]
I can't see the videos because I don't have flash installed. 😞 
Can you provide more info? How are you using Lock (cdn or npm)? We didn't change Lock much from 17 to 18, but we upgraded react because IE11 wasn't triggering some input events, so maybe that's the issue you're seeing.

**Comment by mariwing** [comment]
Thanks for getting back to me! The videos play in Chrome on my Windows computer but regardless; they are not very interesting since they basically just shows what I tried to explain in the text. 

We are using the version from cdn. I had to update the locator (the name of the password box changed) to make the selenium script run on v18/19. To me it sounds like the IE11 fix somehow made Safari on Mac (when driven from Selenium) break. I understand that this is probably a minor defect since it don't affect very many people but it is a big deal to us since we no longer can run Selenium to verify the rest of our web app on Safari/Mac. Everything in our app are behind the Auth0 lock...

**Comment by luisrudge** [comment]
The ie11 fix was just a react upgrade [here](https://github.com/auth0/lock/pull/1039). Can you try doing a test with selenium + react 15.3.9 and selenium + react 15.6.1? You can have just a single input and see if selenium works with both react versions.

**Comment by mariwing** [comment]
I am not very knowledgeable in react but let me see what I can do and get back to you with the results. It will take some days before I have the time to try to create what you ask for.

**Comment by ctrast2** [comment]
I am experiencing the same issues with- MacOS. Sierra 10.12 Safari 10.0 running in Sauce Labs

Any updates?

**Comment by luisrudge** [comment]
@ctrast2 can you build a repro I can test it out?

**Comment by ctrast2** [comment]
I could build a test repo for you to use. This repo would require you to add the URL and your credentials to Sauce Labs which you will receive after you create a free trail account on Sauce Labs.

Make sense?

**Comment by luisrudge** [comment]
Yes. I have an account on SL already.

**Comment by ctrast2** [comment]
Ok, I’ll let you know when its there- day or two.  I will add a simple test which exercises the current log in.

Thanks

**Comment by ctrast2** [comment]
Should I create a Support ticket for this? There are two logins that don’t work through Selenium. OSX and Edge browsers. I have even tried using Robot – Java.awt

**Comment by luisrudge** [comment]
what you mean by two logins?

**Comment by ctrast2** [comment]
The log in for the platform OSX = Sierra and Browser Safari and the Platform for Windows and Browser Edge.

**Comment by luisrudge** [comment]
Alright. Let's see the tests then.

**Comment by ctrast2** [comment]
These are the lines of code that deal with the login objects. These work for all platforms we are supporting except for Sierra/Safari and Win/Edge browser combination.

So this works for
Win/Chrome
Sierra/Chrome
Sierra/Firefox
Win/Firefox
Win/IE



void username_edt_sendKeys(String string){
WebElement element = ContextUtil.get().getWebDriverInstance().findElement(By.cssSelector("input[type='email']"))

    element.sendKeys(string)
}

static void passsword_edt_sendKeys(String string){
    WebElement element = ContextUtil.get().getWebDriverInstance().findElement(By.cssSelector("input[type='password']"))
    element.click()
    element.sendKeys(string)


}

static void signin_btn_click(){
  WebElement submit = ContextUtil.get().getWebDriverInstance().findElement(By.cssSelector("button[type='submit']"))
    submit.click()
    sleep(6000)

}

**Comment by luisrudge** [comment]
Are you using lock@latest? how's your page etc? it's impossible for me to help you with limited information and no access to your tests.
For now, please test with a simple page like this one and tell me what happens: https://github.com/auth0/lock/blob/master/support/index.html

**Comment by ctrast2** [comment]
You are an employee of Auth0 yes?

**Comment by luisrudge** [comment]
Yes.

**Comment by JeremyPDonahue** [comment]
I'm having the same problem in both Firefox and Chrome on Windows 10. I use the Selenium IDE to create the script and no matter what I try I am faced with this issue.

**Comment by saltukalakus** [comment]
The issue might be related with Saucelabs. Could you run same test with BrowserStack? They have free plan too.

**Comment by mklobe** [comment]
I have the same issue.  Selenium IDE 2.9.1 on Firefox 54.0.1, with React 15.0.1 and an admittedly older Lock 10.15.0.

Considering this issue is still open I'm assuming upgrading to the latest Lock isn't going to help.  Has anyone found a workaround?

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
