### ISSUE TITLE
connectionResolver fails to fire if username pre-loaded from password manager

### ISSUE THREAD

**Issue by NicoleDaleyFinnegan** [auth0/lock#1081]
### [connectionResolver](https://github.com/auth0/lock#other-options) fails to fire if the username and password are preloaded from a password manager.
**auth0-lock@10.19.0**
**Browsers: Chrome and Firefox**
**(Chrome using LastPass, Firefox using the Mozilla password manager)**

If the username and password are pre-loader in the auth-lock widget (using LastPass... for example), the connectionRevolver in the Auth0Lock options does not fire. Possibly due to the function being fired on a onBlur event? Simply clicking in the username box fires the event.

![connectionresolver_bug](https://user-images.githubusercontent.com/10135076/29220542-5cc4e8dc-7e89-11e7-8644-5e2105f0abdc.gif)

**Comment by luisrudge** [comment]
ouch. that's true. We call it onBlur, but this event is never being called. We also can't call it onChange because it will trigger on every key press. What do you think we can do to make this work? Call it when you click on the submit button?

**Comment by NicoleGrondin** [comment]
Yes I think that should do it. The submit button onClick/onEnter would always have to be called, thus connectionResolver() would get executed.

**Comment by luisrudge** [comment]
Alright. I'll see what I can do. We've other priorities right now, so, if you can send a PR, I can review and a cut a new release. If not, this will probably be fixed in the next release or the one after the next.

**Comment by GavinOsborn** [comment]
This would also be a blocker for our adoption of this feature.
We have significant investment in LastPass.

**Comment by luisrudge** [comment]
@GavinOsborn the PR is missing a couple of tests. Can you help with this? If not, I'll try to write them before the next release so we can ship this.

**Comment by GavinOsborn** [comment]
@luisrudge Apologies for the late follow-up here.
Do I take it from #1113 that this works and this issue can now be closed?

**Comment by luisrudge** [comment]
I don't know if #1113 fixed the integration with password managers. Can you try and see if it works?

**Comment by GavinOsborn** [comment]
Hey @luisrudge as we have been working through a related support ticket we appear to have found a bug that _may_ have been introduced by this change. Notably to do with when you have > 50 connections. See @mostekcm who can loop you into the support ticket.

**Comment by luisrudge** [comment]
this was was fixed in #1113
