### ISSUE TITLE
RelayState, CORS, where? how?

### ISSUE THREAD

**Issue by paulocheque** [auth0/lock#1085]
Hi, is there any example of how to use Auth0-Lock when Auth0 is the Identity Provider and Where IdP Initiates SSO? https://auth0.com/docs/protocols/saml/saml-configuration/special-configuration-scenarios/idp-initiated-sso

https://MY_APP.auth0.com/samlp/MY_CLIENT_ID?RelayState=http://FINAL_DESTINATION_URL

```
  var MY_ENCODED_URL = encodeURI('MY_SERVICE_PROVIDER_SERVICE_URL');
  var lock = new Auth0Lock('MY_CLIENT_ID', 'MYAPP.auth0.com/samlp/MY_CLIENT_ID?RelayState=MY_ENCODED_URL',{

  })
  lock.show();
```

I am receiving a CORS error:

> XMLHttpRequest cannot load https://MY_APP.auth0.com/samlp/MY_CLIENT_ID/user/ssodata/. The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:4567' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

> index.js:404 There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "http://localhost:4567" to the "Allowed Origins (CORS)" list in the Auth0 dashboard: https://manage.auth0.com/#/applications/MY_CLIENT_ID/settings
> U @ index.js:404
> errorFn @ remote_data.js:36
> (anonymous) @ sync.js:64
> 

But I have already put this URL in the **Allowed Origins (CORS)** but the error persists. Any ideas?

Thanks in advance.

![screen shot 2017-08-14 at 15 41 53](https://user-images.githubusercontent.com/94350/29286098-2917eb94-8107-11e7-9091-804aa6cfcc39.png)

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
