### ISSUE TITLE
Have you stopped publishing release info here?

### ISSUE THREAD

**Issue by SteveALee** [auth0/lock#1086]
latest version on npm is 10.20.0 but here is 10.18.0

**Comment by luisrudge** [comment]
The release is actually there, only the changelogs aren't. We're looking to fix it. Currently, it's a manual step and I forgot to add them. You can also check the changelog file https://github.com/auth0/lock/blob/master/CHANGELOG.md

**Comment by SteveALee** [comment]
Oh, good point. I've only been checking https://github.com/auth0/lock/releases
