### ISSUE TITLE
oidcConformant does not work with MFA

### ISSUE THREAD

**Issue by xumx** [auth0/lock#1088]
oidcConformant: true does not work with MFA

```
var options = {
  oidcConformant: true,
  auth: {
    responseType: 'token id_token',
    params: {
      audience: 'https://example.com',
      scope: 'openid name'
    }
  }
}
```
- [x] Lock version: 10.19.0
- [x] Browser & OS: Chrome Windows

**Comment by luisrudge** [comment]
what happens?

**Comment by thearrow** [comment]
@luisrudge I'm trying this as well and just get a `403` from `https://<tenant>.auth0.com/oauth/token` with:

```json
{
    "error":"mfa_required",
    "error_description":"Multifactor authentication required",
    "mfa_token":"<token>"
}
```

And lock just displays a message:
> WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

**Comment by deivkk** [comment]
I am having exactly the same issue. The only way I can make MFA works is when using webAuth.authorize() but now with Auth0Lock

**Comment by luisrudge** [comment]
Does it work with you use `oidcConformant: false`?

**Comment by thearrow** [comment]
If I use both `oidcConformant: false` in the lock options and turn the OIDC Conformant switch off in the client settings, it redirects successfully to the MFA page.

Honestly I've had so much trouble with the embedded version of lock over the past few months I'm considering just using the hosted login page.

**Comment by luisrudge** [comment]
The hosted login page is the easiest and most secure way to handle logins. If you can go that route, that will be the best indeed. In any case, MFA won't work with the flag `oidcConformant` set to `true` in older versions, but it should work with the new version (`v10.22.0`), which is the first version that we actually support the `oidcConformant` flag. To make it work, you'll have to enable cross origin authentication. You can read more here: https://github.com/auth0/lock#oidc-conformant-mode
Please reopen the issue if the problem persists after upgrading to the latest lock.
