### ISSUE TITLE
Auth0 Lock won't show if hidden within 1 second

### ISSUE THREAD

**Issue by UnsungHero97** [auth0/lock#1089]
Auth0 Lock v10.20.0

I'm working on a React app for which I'm setting up the Auth0 Lock, and I came across an unexpected bug (or feature?). The Lock will not show if I navigate away from an authenticated route (requires the user to be authenticated/logged in) to a public route (does not require authentication), and then quickly navigate back to the authenticated route. So the flow looks like:

`/login -> /public -> /login`

When I navigate away from `/login`, I invoke `lock.hide()` in `componentWillUnmount()`, and when I navigate back to `/login`, I invoke `lock.show()`.

When this flow is done slowly, everything works as expected. However, when I navigate quickly, the lock **does not** show when I'm back at `/login`. Here, "quickly" is less than 1 second. After looking at the source, this makes sense. There's a `setTimeout(() => {}, 1000)` in `closeLock()` that seems to be the culprit for this (mis?)behavior:

https://github.com/auth0/lock/blob/master/src/core/actions.js#L125

To reproduce...

1. Go to https://wypmzpox25.codesandbox.io. `react-router` will route this to `.../#/login`.
2. Change the URL to `/#/public`.
3. Click the back button to go back to `/#/login`. Now, click the forward button and immediately click the back button to reproduce the `/login -> /public -> /login` flow. You should end up back on `/#/login` without a lock.
4. If you were to try step 3 again, but wait 1 second before going back to `/#/login`, the lock will be shown.

I can get around this by invoking `lock.show()` after 1 second, however, this doesn't seem like the right solution. Any suggestions on how to address this race condition?

**Comment by luisrudge** [comment]
We use the setTimeout to wait for the css transitions to happen before actually doing work with lock (something that was discussed a lot [here](https://github.com/auth0/lock/issues/840)). Your best bet is to show after 1s or to use lock in inline-mode, which should fix the issue.
