### ISSUE TITLE
Problematic comparison in store : observe() : subscribe()

### ISSUE THREAD

**Issue by UnsungHero97** [auth0/lock#1090]
Auth0 Lock v10.20.0

I'm using an undocumented API method, `lock.destroy()`, and I encountered issue https://github.com/auth0/lock/issues/907. After tracing the code, I think I've found a problematic comparison that leads to that issue:

https://github.com/auth0/lock/blob/7f0e0b59a9785d2b887d24591ebea2e61f2d69d8/src/store/index.js#L8-L10

Once `destroy()` is invoked, `getEntity()` returns `undefined` for both `m` and `oldM`, which means `f(m)` will be invoked with `m` being `undefined`, which then causes `Uncaught TypeError: Cannot read property 'getIn' of undefined` in https://github.com/auth0/lock/issues/907.

Shouldn't this check instead be:

`if (m && oldM && m != oldM) f(m);`

...? Furthermore, since both `m` and `oldM` are both `immutable-js` Maps, shouldn't `m != oldM` instead be `!m.equals(oldM)`?

**Comment by UnsungHero97** [comment]
@luisrudge, here you go!

https://github.com/auth0/lock/pull/1091

**Comment by luisrudge** [comment]
fixed in #1653
