### ISSUE TITLE
Translate Login in Portuguese

### ISSUE THREAD

**Issue by cyancdesign** [auth0/lock#1093]
Is there no Portuguese translation for `Login` ?
Is it not `entrar` ?

```
  loginAtLabel: 'Login em %s',
  loginLabel: 'Login',
  loginSubmitLabel: 'Log in',
  loginWithLabel: 'Login com %s',
```

https://github.com/auth0/lock/blob/master/src/i18n/pt-br.js

**Comment by luisrudge** [comment]
Hi. I'm from Brazil. Both options are used in many Brazilian websites. If you prefer 'Entrar', you can customize it like this:

```
var options = {
  languageDictionary: {
    loginLabel: 'Entrar'
  }
};
```
