### ISSUE TITLE
Error messages overflow!

### ISSUE THREAD

**Issue by andoanwkm** [auth0/lock#1094]
<img width="327" alt="screen shot 2017-08-28 at 9 36 59 am" src="https://user-images.githubusercontent.com/29110569/29757326-3fa8795e-8bd5-11e7-8413-74485cf5354f.png">

- When login with blank fields, the error messages are overflow.
- Follow #1002 remove overflow-y: auto from class .auth0-lock-center but it's not work.
- Lock version 10.20.0
- Browser & OS: Chrome Version 60.0.3112.101 & MacOS Sierra 10.12.6

**Comment by luisrudge** [comment]
This is supposed to be fixed. Can you create a sample repro so we can dig deeper?

**Comment by andoanwkm** [comment]
@luisrudge I've just find the reason. Because I import lock-passwordless-2.2.3.min.js, so the css import from this script override the css of lock.min.js
In this case, I remove overflow: hidden of .auth0-lock-widget-container and  .auth0-lock-cred-pane from css created by lock-passwordless and it's work normally.
May be It's an error from lock-passwordless. Please check it, thanks.

**Comment by luisrudge** [comment]
We're deprecating lock-pwdless and joining both in this project, so this problem will go away when we migrate that. Thanks for finding that out!
