### ISSUE TITLE
Terms & Conditions checkbox should be at top of Lock interface when using social singups

### ISSUE THREAD

**Issue by mobiusnz** [auth0/lock#1098]
I've set `mustAcceptTerms: true` in my Lock.js and whilst the functionality is good, the social signup buttons are greyed out until the user accepts the terms. This is fine, but as the terms are at the bottom of the form users won't see it. Instead they'll see the inactive social buttons and assume they are broken. It will only be after they fill in their details for the old style username/password signup that they will tick the button, and I can imagine seeing the social logins become active then will cause frustration. I feel like this could be fixed by moving the terms checkbox and text to the top of the signup form.

![image](https://user-images.githubusercontent.com/629254/30047814-2db143e6-9267-11e7-90b7-7f403a44b8ce.png)

**Comment by luisrudge** [comment]
I'll ping someone from the ux team. We'll definitely not put the terms on the top, but maybe they have another idea how to solve this.

**Comment by luisrudge** [comment]
Hi. Just got back from the ux team. They said they added to the backlog but there are no plans in the near future to change the way it behaves right now. This will probably be handled in the next lock overhaul, which has no ETA yet.

**Comment by gmontard** [comment]
That UX is very problematic.. sad to hear it's not going to change for some time.

**Comment by luisrudge** [comment]
@gmontard feel free to send feedback here: https://auth0.com/feedback - It will get routed to the design team 🎉

**Comment by carlosMedrano27** [comment]
Hi @luisrudge, Is there any update for this issue?
