### ISSUE TITLE
Urls in Login/SignUp tabs

### ISSUE THREAD

**Issue by EvgenStudent** [auth0/lock#1101]
Hello everyone!

I use an Angular v1 and I faced a next challenge:
Click by Login, SignUp, etc buttons redirect me to a root url.
![screenshot_1](https://user-images.githubusercontent.com/5446744/30176453-280ebaae-940b-11e7-8c13-101e30c9e5ea.png)

In this case I have to make a lot of hardcode (js+css) for replacing these urls to "javascript:void(0)".

**Comment by luisrudge** [comment]
can you send a PR with this fix? That would be awesome.

**Comment by luisrudge** [comment]
I fixed in this pr
