### ISSUE TITLE
New Connections Resolver doesn't set the realm for signup, just for login

### ISSUE THREAD

**Issue by mostekcm** [auth0/lock#1104]
- [x] Code snippet or sample project that reproduces the bug
https://github.com/auth0-samples/multi-tenant-db-per-tenant-lock, if you use this sample it successfully logs in if you create the user first, but doesn't work for signup.  It will create a user in the default database instead of the tenant specific database.
- [x] Lock version
10.20
- [x] Browser & OS
Chrome on MBP

I will see if I can get a PR going for this.  But in the mean time, here are the steps to reproduce.

Follow all instructions [here](https://github.com/auth0-samples/multi-tenant-db-per-tenant-lock/blob/master/README.md).

Instead of logging in, try to "Sign Up".

After sign up, try logging in with the new user, it will fail because they don't exist in that database.

What should happen: login should succeed because the user was added to the right database.

**Comment by mostekcm** [comment]
This is, of course, more complex than it first seems.  I am able to get it working, but not with username.

**Comment by luisrudge** [comment]
this should be fixed in #1111, can you check?
