### ISSUE TITLE
Empty Email/Password Validation Styles in Firefox

### ISSUE THREAD

**Issue by gpbmike** [auth0/lock#1106]
The validation tooltips that pop up if you leave a field blank could use some love in Firefox.

## Chrome 61 / MacOS ✅  
![image](https://user-images.githubusercontent.com/8754/30291527-156b35e6-96e8-11e7-8366-6811a1d09927.png)

## Firefox 55 / MacOS ❌ 
![image](https://user-images.githubusercontent.com/8754/30291606-4655bb5e-96e8-11e7-8d4d-85101d438aa9.png)

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by gpbmike** [comment]
Thanks for the update. We have moved off of the Auth0 platform. Cheers.
