### ISSUE TITLE
Getting Module not found: Can't resolve 'package.version' in React

### ISSUE THREAD

**Issue by kschroeder** [auth0/lock#1109]
I have the following class code

```
import React, { Component } from 'react';
import Lock from 'auth0-react-lock';
import './App.css';

class App extends Component {

  render() {
    return (
      <div className="App">
        <Lock
            clientID={'xxxxxxxxxxxx}
            domain={'xxxxxxxxxxxxxxx'}
            ref={"lock1"}
            connections={['google-oauth2', 'facebook']}
            socialBigButtons={false}
            hashHandler={this.hashHandler}
        />
      </div>
    );
  }
}

export default App;
```

When I run it in the browser I get

```
Failed to compile
./node_modules/auth0-lock/index.js
Module not found: Can't resolve 'package.version' in 'xxxxxx\pub\node_modules\auth0-lock'
This error occurred during the build time and cannot be dismissed.
```

```
node.exe --version
v7.10.0
```

```
npm.cmd --version
4.2.0
```

I have version
```
+-- auth0-react-lock@1.0.4
| +-- auth0-lock@9.2.3
| | +-- auth0-js@6.8.4
```

I've looked around at some of the other bugs and I think I've tried what they suggest, but to no avail.  I'm not a native React or JS developer so it's possible that I missed something simple.

**Comment by kschroeder** [comment]
Looks like I missed one of the simple ones.  I changed this line of code

```
Auth0Lock.version = require('./package.json').version;
```

and now it works (getting another error right now saying  fs.readFileSync is not a function).  I don't mind making the change for my environment but it would seem like this would be a problem once I run through a build process or an upgrade.

**Comment by luisrudge** [comment]
This is probably an issue with the auth0-react-lock package. I'm not sure how that works and it's using a super outdated version of Lock. You're better of removing that from your project and following our react quickstarts [here](https://auth0.com/docs/quickstart/spa/react/01-login)

**Comment by kschroeder** [comment]
Yep.  That's what I did and it's working.  So, basically, don't use auth0-react-lock.
