### ISSUE TITLE
Title selection in Sign up page seems to be missing top of page after scrolling

### ISSUE THREAD

**Issue by itdevelopmentapps** [auth0/lock#1112]
Used Auth0 Version: 10.20.0
Phone: Iphone 7 with Ios 11

Our signup page has the 'Title' selection option:
In our case, we scroll the Auth0 sign-up page down, so we are able to interact with the lowest button.
![2017-09-20_signuppage](https://user-images.githubusercontent.com/31443120/30643307-a4379b3e-9e0e-11e7-9317-7afc9c3fe0d1.jpeg)

If we interact with the 'Title' selection, a new page will open with the available options. In our case 'Mrs' and 'Mr'. But due to the previous scrolling this page is also scrolled down, and the page head seems to be missing(On smaller devices this will generate an empty looking page). So the user has to scroll up to see the full page. 
Page:
![2017-09-20_missinghead](https://user-images.githubusercontent.com/31443120/30643533-a474e6b4-9e0f-11e7-92fb-22455f851c09.jpeg)

Should be: 
![2017-09-20_goodhead](https://user-images.githubusercontent.com/31443120/30643539-adcf85fc-9e0f-11e7-8b9c-de66f11007a7.jpeg)

This is confusing for the user since the page seem to miss information.

**Comment by luisrudge** [comment]
Are you overriding any css styles? If so, does it happen without the overrides? How are you scrolling the page? Can you provide a sample so we can reproduce the issue?

**Comment by itdevelopmentapps** [comment]
Yes. we are overriding the style. We are zooming in so the page is a little larger and have added some buttons / input fields.
scrolling problem is 001.mp4 in the zip
Which it should be is 002.mp4 in the zip
(The moving white space on top is a blur our of a temporary link. Thanks to our professional movie editing skills.)
[Auth0_ScrollingIssue.zip](https://github.com/auth0/lock/files/1324528/Auth0_ScrollingIssue.zip)

**Comment by luisrudge** [comment]
Does the issue happens when you disable the overridden styles?

**Comment by itdevelopmentapps** [comment]
When we disable the override. There is no scroll option. so the issue does not happen.
If the 'Sign up' page is scroll-able you will have this issue

**Comment by luisrudge** [comment]
Then there is nothing we can do, since we don't support style overrides. If you figure out the issue and fix it, we'll happily evaluate your pull request with the fix, providing that it doesn't affect current behavior.
