### ISSUE TITLE
Additional sign up field - password

### ISSUE THREAD

**Issue by EvgenStudent** [auth0/lock#1120]
Can you add supporting for an additional sign up field with "password" type? I'm trying to implement "Confirm Password" text box.
For now I have fixed input type replacing through JQuery, but it works badly (text in the textBox appears/disappears randomly),

If it will be an embedded feature, it will be great.

**Comment by luisrudge** [comment]
Can you send a PR with that? There's no plans to add that, but I'd  review a PR if you send one.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉
