### ISSUE TITLE
I18N for 'change password' lock screen

### ISSUE THREAD

**Issue by gebrits** [auth0/lock#1122]
It seems i18N is not supported out of the box for the lock 'change password' screen. 
Are there plans to support this, including just referencing a dictionary file?

**Comment by luisrudge** [comment]
How are you getting the change password screen?

**Comment by gebrits** [comment]
I'm using the Hosted Pages Password Reset. 

I now realise it's not build on top of lock but uses a Auth0 provided script [https://cdn.auth0.com/js/change-password-1.1.js]. Still, it does provide a `dict`-property in which to hook your own language. 

Would be great if I could just plugin an auth0-provided dictionary (or just extend the Lock-dictionary with a couple of extra template variables to cover this screen)

**Comment by luisrudge** [comment]
As you said, this is a different project. I'm still not sure what you're asking for. You can fully customize the widget i18n entries:


```js
new Auth0ChangePassword({
  container: "container",         // required
  email: "someone@auth0.com",     // required, it would normally be "<%= @email %>"
  csrf_token: "some token",       // required, it would normally be "<%= @csrf_token %>"
  ticket: "some ticket",          // required, it would normally be "<%= @ticket %>"
  password_policy: "low",         // required, it would normally be "<%= @password_policy %>"
  theme: {
    icon: "//cdn.auth0.com/styleguide/1.0.0/img/badge.png",
    primaryColor: "#ea5323",
    showBadge: false //defaults to true
  },
  dict: {
    passwordPlaceholder: "your new password",
    passwordConfirmationPlaceholder: "confirm your new password",
    passwordConfirmationMatchError: "Please ensure the password and the confirmation are the same.",
    passwordStrength: {
      containsAtLeast: "Contain at least %d of the following %d types of characters:",
      identicalChars: "No more than %d identical characters in a row (e.g., \"%s\" not allowed)",
      nonEmpty: "Non-empty password required",
      numbers: "Numbers (i.e. 0-9)",
      lengthAtLeast: "At least %d characters in length",
      lowerCase: "Lower case letters (a-z)",
      shouldContain: "Should contain:",
      specialCharacters: "Special characters (e.g. !@#$%^&*)",
      upperCase: "Upper case letters (A-Z)"
    },
    successMessage: "Your password has been reset successfully.",
    configurationError: "An error ocurred. There appears to be a misconfiguration in the form.",
    networkError: "The server cannot be reached, there is a problem with the network.",
    timeoutError: "The server cannot be reached, please try again.",
    serverError: "There was an error processing the password reset.",
    headerText: "Enter a new password for<br />{email}",
    title: "Change Password",
    weakPasswordError: "Password is too weak.",
    passwordHistoryError: "Password has previously been used",
    passwordDictError: "Password is too common",
    passwordNoUserInfoError: "Password is based on user information"
  },
  successCallback: function() {
    console.log('Password changed');
  }
});
```

I'll close this issue because it's not a Lock issue, but let's continue the discussion here.

**Comment by benleen** [comment]
Luis, I landed here as I was searching for i18n for the password reset screen.

Was there supposed to be a link on the "here" of your last comment? ;-)

**Comment by benleen** [comment]
If with "here" you meant this issue:

My question is simple. As the OP seemed to have asked initially. Is there an easily integrated i18n for the password reset screen? The dictionary is a cumbersome workaround, especially for us since we have an Auth0 appliance with multiple tenants. We have little interest in hosting our own dictionary files if we can avoid it and we're not deviating from the original wording of the screen.

The reset password screen may not be Lock, but it is the closest relative and might as well be managed by the same team imho. ;-)

**Comment by luisrudge** [comment]
It's managed by my team, that why I said we should continue the conversation in this issue. We have plans to add Lock's i18n strategy to the change password widget, but there is no ETA yet.

**Comment by cgcote** [comment]
The "lang" property documented there https://auth0.com/docs/hosted-pages/password-reset seems to indicate i18n is already implemented. Adding more details on what "lang" does exactly would be helpful!

**Comment by luisrudge** [comment]
@cgcote keep in mind `lang` has nothing to do with the change password widget. it's just a variable that you can use like `{{lang}}`, in the same way that you use `{{email}}` etc

**Comment by luisrudge** [comment]
@dilger I'm not sure you have access to this kind of information from that page, to be honest. Ping our amazing support team at https://support.auth0.com and I'm sure they'll give you a better answer. You can easily customize based on the browser language though: `window.navigator.language`

**Comment by pierreboissinot** [comment]
Hi there, any news about i18n support ?

**Comment by luisrudge** [comment]
Not at this moment. The previous recommendation still is the best you can do today.

**Comment by olegchursin** [comment]
Hi guys, any updates on this issue? 

We are building a language selector on the password reset page, storing the selected value to localStorage. With Lock we can simply reassign a `language` variable. How do we implement the same functionality here? Thanks!

**Comment by luisrudge** [comment]
You’ll have to create a dictionary yourself and use the language param to pick one set of strings som that dictionary.

Luís
________________________________
De: Oleg Chursin <notifications@github.com>
Enviado: Wednesday, May 1, 2019 11:26:45 AM
Para: auth0/lock
Cc: Luís Rudge; Mention
Assunto: Re: [auth0/lock] I18N for 'change password' lock screen (#1122)


Hi guys, any updates on this issue?

We are building a language selector on the password reset page, storing the selected value to localStorage. With Lock we can simply reassign a language variable. How do we implement the same functionality here? Thanks!

**Comment by olegchursin** [comment]
Thanks for a quick response, @luisrudge . That's exactly what we are currently doing. Just thought there was some progress with `Auth0ChangePassword` to handle i18n the same way Lock Widget does.

**Comment by conan** [comment]
I'd like this very much, it seems odd to provide internationalisation support for login but not for password reset.

**Comment by vinispag** [comment]
> @cgcote keep in mind `lang` has nothing to do with the change password widget. it's just a variable that you can use like `{{lang}}`, in the same way that you use `{{email}}` etc

But what does this `lang` variable contains, and how to set this variable to a specific user?

**Comment by luisrudge** [comment]
@vinispag https://auth0.com/docs/universal-login/password-reset#custom-variables I don't think you can set it.

**Comment by vinispag** [comment]
Thanks for the quick response.

But, I don't understand, in this link you sent the variable `lang` is described as `The user's language`. But how can I use this variable? The only thing this I can print from this variable is `PT-BR,PT;Q=0.9,EN-US;Q=0.8,EN;Q=0.7,ES;Q=0.6,IT;Q=0.5,DE;Q=0.4` and I don't know what this means and how to use it.

A more detailed description of this variable maybe can be useful, or if I can access some `user_metadata` variable should be useful as well

**Comment by luisrudge** [comment]
@vinispag this is the language header that the browser sends:

`Accept-Language: pt-BR,pt;q=0.9,en-BR;q=0.8,en-US;q=0.7,en;q=0.6`

You can try using `navigator.language` or `navigator.languages` as well. You can't use `user_metadata` fields, though.

**Comment by iandeherdt** [comment]
If you send custom mails you could send append the user language to the url `href={{ url }}&lang=pt`. Next you can get the language from the change password widget url.

**Comment by Axel-Hatem-HV** [comment]
Hi there, I know this has been closed and I understand we need to do a manual i18n on this.
But I can't find the values inside the `dict: {...}` for this:
![image](https://user-images.githubusercontent.com/97127188/204019683-db19fc9e-46e2-4b0b-ad14-b26195550319.png)
Any idea on how to change this one the correct way?
Thanks.
