### ISSUE TITLE
&nbsp shows up when the language set to French

### ISSUE THREAD

**Issue by h-jin** [auth0/lock#1131]
Here is code snipe, lang value in this code is "fr"
![screen shot 2017-09-29 at 11 22 15 am](https://user-images.githubusercontent.com/10803706/31023050-a66e1562-a508-11e7-847a-2e8e9e691408.png)
Here is the screen of login page, there is &nbsp besides  French "Don't remember your password?"
![screen shot 2017-09-29 at 11 28 53 am](https://user-images.githubusercontent.com/10803706/31023400-aaf0507c-a509-11e7-8904-492556ee9260.png)

Thanks.

**Comment by luisrudge** [comment]
This is probably an issue with your page's encoding:
![image](https://user-images.githubusercontent.com/941075/31026187-db03ff90-a51b-11e7-9029-3cd714f76252.png)

try adding this to your html:

`<meta charset="utf-8">`

**Comment by h-jin** [comment]
Thank you for the reply. We already have <meta charset="utf-8"> on the html page.  Could you please advise some other reason? Thanks.

**Comment by luisrudge** [comment]
I don't know. If you run [this page](https://github.com/auth0/lock/blob/master/support/index.html) and add `language: 'fr'`, it works.

**Comment by h-jin** [comment]
OK, thank you.

**Comment by h-jin** [comment]
Turns out it is old version lock problem, updated to the newest version of auth0 lock solved the problem.

**Comment by luisrudge** [comment]
Thanks for mentioning that. Do you know which version you were using?

**Comment by h-jin** [comment]
the old version of lock I used is 10.3.0.
