### ISSUE TITLE
auth0-lock React DevTools spam

### ISSUE THREAD

**Issue by Sieabah** [auth0/lock#1133]
`Download the React DevTools for a better development experience: http://fb.me/react-devtools`

I've pulled this project into my Angular front-end and I guess I'm using a dev dependency version which requires me to put a snippet into my code so this doesn't run. Could the auth0 team either opt in/out with suppressing the log message for their published package?

`window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = {};`

[Related Issue](https://github.com/facebook/react/issues/3877#issuecomment-321714174)

**Comment by luisrudge** [comment]
Does this happen at dev time? or prod?

**Comment by Sieabah** [comment]
Dev and prod unless you override that hook or use a webpack plugin which does that same thing.

**Comment by luisrudge** [comment]
Alright. Let me think about this for a while. We can't remove the dev tools in the window, because it will mess up with anyone using react. What do you suggest? An option to disable it?

**Comment by Sieabah** [comment]
On the issue I've been trying to figure out a way for FB to allow a way for the logging to take place inside of the bootstrapping phase so it can be disabled/enabled.

**Comment by luisrudge** [comment]
I added more info about how to prevent this (and other things) from happening in development/production environments. I hope this clear things out. https://github.com/auth0/lock/pull/1143
