### ISSUE TITLE
There is a bug when rendering the additional SignUp fields in hosted page.

### ISSUE THREAD

**Issue by dragosholban** [auth0/lock#1140]
I added some additionalSignUpFields to the hosted login page but when rendered there are some problems:
1. There is no space between the password field and the next one.
2. On iOS the select types look wrong. (Please check the attached image)

![screen shot 2017-10-10 at 16 44 13](https://user-images.githubusercontent.com/1357968/31405283-3d9e52c4-ae07-11e7-824d-db82f8f83c16.png)

**Comment by luisrudge** [comment]
what version are you using?

**Comment by luisrudge** [comment]
We fixed something like that here: https://github.com/auth0/lock/pull/1076

**Comment by dragosholban** [comment]
Thanks @luisrudge ! This seems to fix the first issue, but it is not working on the current Auth0 Login hosted page. Is there a way to select the lock version or we just have to wait for Auth0 to update?

What about the second one, do you know what's going wrong in safari on iOS?

**Comment by luisrudge** [comment]
Can you send a new screenshot so I can talk with the design team?

**Comment by dragosholban** [comment]
Sure. Thanks for helping!
![img_3154](https://user-images.githubusercontent.com/1357968/31449150-d71ccc76-aeae-11e7-8ae0-9eba4b14c015.PNG)

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
