### ISSUE TITLE
Rough timeline of "Future roadmap of Lock v2 for iOS"

### ISSUE THREAD

**Issue by superarts** [auth0/lock#1141]
Hi,

Is there any (even very rough) timeline for those cool features mentioned in the link below please? Are they likely to be implemented in this year? Thanks!

https://auth0.com/docs/libraries/lock-ios/v2#future-roadmap-of-lock-v2-for-ios

## Future roadmap of Lock v2 for iOS

- Native Authentication with third party SDKs (Facebook, Google, Twitter)
- Secure Token storage and automatic token refresh
- Remember me like feature using Touch ID
- Universal Link support for browser based Auth
- Improved UI Styling
- Bundle more i18n translation in Lock.framework

**Comment by luisrudge** [comment]
Hi. Thanks for the interest. Can you open this issue in the swift repo? https://github.com/auth0/Lock.swift

Thanks!

**Comment by superarts** [comment]
Thanks! Moved to https://github.com/auth0/Lock.swift/issues/471
