### ISSUE TITLE
Select additionalSignupField doesn't scroll to top of list

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/lock#1149]
On mobile devices, when a user scrolls down to a select additionalSignupField, the select list doesn't scroll up, causing the options to be hidden.

![33a5a50a3e6944cea3ca93bfc7c6dfcb](https://user-images.githubusercontent.com/6582826/31589200-287e3696-b25a-11e7-87d3-a6d653587031.gif)

Browser/OS: Happens on any browser/OS where the user has to scroll to the select element.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
