### ISSUE TITLE
Lack of spacing before first new input field

### ISSUE THREAD

**Issue by ahmadabdul3** [auth0/lock#1155]
You can close this, I saw that it was fixed in a newer version. SORRY!

I saw a similar issue before and it looked like it was fixed but I'm seeing the same thing. I'm adding 2 additional fields to the signup page and before the FIRST new field, there is a space missing. I believe this is lock 10.18, I'm just customizing the hosted page and this is the script:

`<script src="https://cdn.auth0.com/js/lock/10.18/lock.min.js"></script>`

here's what it looks like:

<img width="302" alt="screen shot 2017-10-20 at 4 19 57 pm" src="https://user-images.githubusercontent.com/5860834/31840262-91ad9be2-b5b2-11e7-80a8-9ee55edcca58.png">

Hope I didn't miss anything, let me know if more clarification is required.

Thanks!

**Comment by ahmadabdul3** [comment]
Oh my bad, the issue I saw was for 10.19/10.18 and I see it says it will be closed in the next release. You can close this

**Comment by ahmadabdul3** [comment]
Anddd I see that I'm way behind and you guys have version 11.0 up...

**Comment by luisrudge** [comment]
v11 was not released yet. But your issue was fixed in 10.20.0
