### ISSUE TITLE
rude behaviour on forcing to use Husky without asking if user like it ;-)

### ISSUE THREAD

**Issue by nonnenmacher** [auth0/lock#1156]
Discovered when removed 'npm' in my list of dependencies from one of my project,
that there is a LOT of `git hooks` file that seems to pertain to auth0-lock.

They are all the same format : 
```
#!/bin/sh
#husky 0.13.4

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

load_nvm () {
  export $1=$2
  [ -s "$2/nvm.sh" ] && . $2/nvm.sh
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd app/bower_components/auth0-lock

has_hook_script update || exit 0

export PATH=$PATH:/usr/local/bin:/usr/local
load_nvm BREW_NVM_DIR /usr/local/opt/nvm

load_nvm NVM_DIR /Users/whisky/.nvm

command_exists npm || {
  echo >&2 "> husky - Can't find npm in PATH. Skipping update script in package.json"
  exit 0
}

echo
echo "> husky - npm run -s update"
echo "> husky - node `node -v`"
echo

export GIT_PARAMS="$*"
npm run -s update || {
  echo
  echo "> husky - update hook failed (add --no-verify to bypass)"
  echo "> husky - to debug, use 'npm run update'"
  exit 1
}
```

and basically goes to my `bower` version of Auth0-lock and execute the specific git hook for any git command.

I don't remember any time where I was asked to install such hooks and et biten by this Husky by surprise. A quick note could be usefull for user not aware of this, as it could have been lying here for years.

**Comment by luisrudge** [comment]
husky is a dev dependency. the hooks are only used by our repo. It's not clear to me how this is affecting projects depending on auth0-lock. Can you clarify what's going on?

**Comment by nonnenmacher** [comment]
I din't know how it ended up here, but somehow (i.e some code) injected those `git hooks` for me and it get apparent when I removed `npm` from my `package.json` dependencies (I guess it exited without disrupting git).

I noticed that all this hooks were on the 21-july-2107 and didn't know who generated them, as this sound very like a template and the `cd app/bower_components/auth0-lock` is the `pwd` where the bower module for `auth0-lock` is seems the *usual suspect* here.

(beside the pleasure to put `husky` and `rude` in a sentence about 'contentment' ;-)

**Comment by luisrudge** [comment]
This is probably bower not behaving like it should. We currently don't support bower and even the bower project recommends using npm or yarn, so there's not much we can do here.

**Comment by nonnenmacher** [comment]
yep certainly, I should follow the advice to transit to yarn.

Thanks for your time (and sorry for my weird 'french' humour), it could help people when searching on the git errors :  
```
> husky - npm run -s precommit
> husky - node v8.7.0

sh: lint-staged: command not found

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

and not understanding this suggestion of npm script `npm run precommit` where they don't see it in their own package.json (took me some time to find this)

**Comment by luisrudge** [comment]
Yeah, certainly. That's very weird that this ends up in your project. Did it reformat your committed files?

**Comment by nonnenmacher** [comment]
got to the bottom of it and could be related around #977

I installed `husky` as a `dev-dependencie` and ended with the same `git hooks` but with a path pointing to the working directory : 

```
#!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if postcommit script is defined, skip if not
has_hook_script {git hook name here} || exit 0
...
```

So I guess somehow, `auth0-lock` run its `husky` install into my project due to a mistake made by me on the CLI or a monkey thing like this, around this glitch.
