### ISSUE TITLE
[v11.0.0-beta.1] Wrong error message and event not firing on wrong email/password.

### ISSUE THREAD

**Issue by francocorreasosa** [auth0/lock#1157]
Hello guys!

After upgrading to Lock 11, when I type a wrong email/password and submit, the API returns an HTTP 403 `{"error":"access_denied","error_description":"Wrong email or password."}` and Lock shows this error message:
<img width="306" alt="screen shot 2017-10-23 at 2 48 08 pm" src="https://user-images.githubusercontent.com/4152942/31905326-2adfaeb0-b804-11e7-9020-602dca7fab25.png">

As an user I'd assume it's a configuration error and not mine. Also, Lock won't emit the `authorization_error` event.

The event is being listened to with the following code:
```js
lock.on('authorization_error', function (e) {  
  console.debug('Authorization Error:', e);
});
```

This repo can be used as a sample project to reproduce the issue: https://github.com/francocorreasosa/auth0-analytics.js/ 
Clone, npm-install, and run the following:
```bash
sh './tests/scripts/pre_test.sh'
serve ./tests/app -T -p 1337 # npm i -g serve
# Go to https://localhost:1337/
```

Env details:
```
Lib: Lock v11.0.0-beta.1
Browser: Firefox Developer Edition 57.0b10
OS: macOS Sierra 10.12.6 (16G29)
```

**Comment by luisrudge** [comment]
what do you see in your dashboard logs? do you have Cross Origin Authentication enabled?

**Comment by francocorreasosa** [comment]
Yeah, I do.

```js
{
  "date": "2017-10-23T17:43:35.329Z",
  "type": "fcoa",
  "description": "Wrong email or password.",
  "connection_id": "",
  "ip": "167.57.89.175",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0",
  "details": {
    "body": {
      "client_id": "*****",
      "username": "some-false-email@example.com",
      "password": "*****",
      "realm": "Username-Password-Authentication",
      "credential_type": "http://auth0.com/oauth/grant-type/password-realm"
    },
    "qs": {},
    "connection": "Username-Password-Authentication",
    "error": {
      "message": "Wrong email or password.",
      "oauthError": "Wrong email or password.",
      "type": "access_denied",
      "uri": null
    }
  },
  "auth0_client": {
    "name": "lock.js",
    "version": "11.0.0-beta.1",
    "lib_version": "9.0.0-beta.2"
  },
  "log_id": "49574419589858254662356544675318597537672124173763215394"
}
```

**Comment by luisrudge** [comment]
do you get the same thing with v10.23.1?

**Comment by francocorreasosa** [comment]
No, with v10.23.1 i get "Wrong username or password."
<img width="392" alt="screen shot 2017-10-23 at 5 55 58 pm" src="https://user-images.githubusercontent.com/4152942/31912806-87abff6a-b81b-11e7-915b-33c0d758c2af.png">

**Comment by francocorreasosa** [comment]
The API response is different, though.
```json
{
  "name":"ValidationError",
  "code":"invalid_user_password",
  "description":"Wrong email or password.",
  "statusCode":400
}
```

**Comment by luisrudge** [comment]
in 10.23.1, are you setting the flag `oidcConformant: true`?

**Comment by francocorreasosa** [comment]
No, should I?

**Comment by luisrudge** [comment]
Yeah, let's try with that.
when `oidcConformant` is `false` it uses a different endpoint (non-oidc conformant endpoint)

**Comment by francocorreasosa** [comment]
I get exactly the same situation as v11 if I set `oidcConformant` to true.

**Comment by actionshrimp** [comment]
Same issue here on 10.23.1 with oidcConformant set to true. Spent a significant amount of time getting this all working with the various additional parameters after switching to oidcConformant and then hit by this issue which has been a bit frustrating. Please let me know if I can provide any additional debug info to help resolve.

**Comment by luisrudge** [comment]
This was fixed in https://github.com/auth0/lock/pull/1187 and will be released with v11. Sorry to keep you all waiting 😁
