### ISSUE TITLE
Issues with radio options and prefills after overlay closed and reopened

### ISSUE THREAD

**Issue by rebeccaspixel** [auth0/lock#1158]
We have included the lock for web version 10.23 as an overlay in our webpage.
Some additional custom fields with prefills are set in the options:

```
var lockSignUp = new Auth0Lock('<?= $client_id ?>', '<?= $client_domain ?>',
{
    allowLogin: false,
    allowForgotPassword: false,
    allowedConnections: ['Username-Password-Authentication'],
    allowShowPassword: true,
    language: 'de',
    loginAfterSignUp: false,
    mustAcceptTerms: true,
    additionalSignUpFields:
    [
        {
            type: "select",
            name: "title",
            placeholder: "Title",
            options:
            [
                {
                    value: "Mr",
                    label: "Mr"
                },
                {
                    value: "Mrs",
                    label: "Mrs"
                }
            ]
        },
        {
            name: "type",
            placeholder: "Type",
            prefill: "Private"
        },
        {
            name: "interest",
            placeholder: "Interest",
            prefill: "20"
        }
    ]
}
```

The lock overlay can be opened by clicking the register button:
```
<a href="" onclick="lockSignUp.show();">Register</a>
```

When the lock overlay is opened for the first time all options are set.
But once the overlay has been closed and reopened all the prefills are empty.
Also the select field throws an error upon trying to open the option selection 
in the List.prototype.render function because this.props.items are undefined:
Uncaught TypeError: Cannot read property 'map' of undefined at e.render (list.jsx:135)

![bildschirmfoto 2017-10-26 um 10 08 53](https://user-images.githubusercontent.com/28860191/32041904-29417b36-ba36-11e7-84f4-e75337208021.png)

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
