### ISSUE TITLE
Auth0 Lock ES6 module compatibility

### ISSUE THREAD

**Issue by katrotz** [auth0/lock#117]
Does the ES6 module loader compatibility feature exist in the library roadmap?

**Use Case**: I am using the systemJS which currently provides ES6 module loader API. It can load modules written in CJS and AMD format, but as the lock library is using server side dependencies ```var fs = require('fs');```, the loading of lock is impossible:
```
'format es6';
import 'lock';
```

**Comment by pose** [comment]
@katrotz What happens if you load the built version? Maybe we can add something here to export it as a ES6 module: https://github.com/auth0/lock/blob/master/standalone.js#L15

**Comment by katrotz** [comment]
@pose Not sure it will help, might be it is too early for this feature.

I was trying to load it using the SystemJS (ES6 module loader). 
Not sure if the bundled version will work. 

Anyway, added it to the page using standard script tag.

**Comment by pose** [comment]
@katrotz That should do the trick for now. Probably, we will need to revisit that in the future. Feel free to re-open if required.
