### ISSUE TITLE
add ids to inputs and buttons so it's easier to automate tests

### ISSUE THREAD

**Issue by luisrudge** [auth0/lock#1174]

**Comment by luisrudge** [comment]
@verde79 absolutely! 😬 This was marked as low priority to us, but it's definitely something we need 🎉

**Comment by verde79** [comment]
@luisrudge for clarification, is it just the playground/index.html that needs id's or are there others I'm not seeing?  Also is there any specific naming conventions for your id's?

**Comment by luisrudge** [comment]
@verde79 no, it's actually the IDs inside lock itself.

For example: 
- https://github.com/auth0/lock/blob/ab7c94ff0f813227d667b2059028282b89dc926f/src/ui/input/text_input.jsx
- https://github.com/auth0/lock/blob/ab7c94ff0f813227d667b2059028282b89dc926f/src/ui/input/checkbox_input.jsx
- https://github.com/auth0/lock/blob/1c9bcc22b861abb9676b8a2247f3f117a10fd7d7/src/ui/input/mfa_code_input.jsx

**Comment by luisrudge** [comment]
fixed in #1517
