### ISSUE TITLE
'unrecoverable_error' not emited when offline

### ISSUE THREAD

**Issue by oscilate** [auth0/lock#1176]
Lock version: v10.24.1
OS: 
- Windows
- Electron 1.6.11
- Angular 4.4.3

```javascript 
const lock = new Auth0Lock('secret', 'domain', {
      allowedConnections: ['google-oauth2'],
      closable: false,
      allowSignUp: false,
      auth: {
        responseType: 'id_token token',
        redirect: false,
        sso: false,
        params: {
          scope: 'openid profile email'
        }
      }
    });
    lock.on('unrecoverable_error', (error) => {
      console.error(error);
    });
```

When running solution offline, 'unrecoverable_error' event is not emited.

**Comment by luisrudge** [comment]
I get the error when using a browser (chrome and firefox).
![firefox](https://user-images.githubusercontent.com/941075/33215380-a93919c4-d116-11e7-9428-54e27456899b.png)
![chrome](https://user-images.githubusercontent.com/941075/33215381-a9607be0-d116-11e7-9271-9dd00a3841ce.png)


Can you test in a web browser?

**Comment by oscilate** [comment]
Hi @luisrudge Sory for the delay.

Indeed the event is triggered if you are offline when the lock is initialized. 

The issue arises when you go offline after that. 

In my scenario, we have google accounts as the only login option for the app.

Here's a screenshot of the app if you are offline when you try to login:

![during google offline](https://user-images.githubusercontent.com/5073361/33434263-aed3b4f6-d5d6-11e7-906f-65ce90ab6fae.png)

After the user closes the blank window: 
![after goolge offline](https://user-images.githubusercontent.com/5073361/33434287-c7338bde-d5d6-11e7-97b3-dc106df0e93a.png)

So the widget neither: 

1. Detects an error loading the google auth popup, making it so the user has to close the popup to proceed.
2. Fire any event so the hosting app can react to the error in an apropriate manner after the user closes the app.

**Comment by luisrudge** [comment]
We can't detect if a popup or iframe throws an error. We can only detect if the popup is closed, which is what we're doing in that case. We don't consider that an `unrecoverable_error` because you can still click to log in after that.

How often a user loses connectivity right after opening Lock? Is this something that is happening a lot with your users?
