### ISSUE TITLE
Whitespace not being trimmed for email input when username_required

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/lock#1180]
If connection does not require username, entering email with trailing spaces authenticates successfully (Lock trims the whitespace). If connection requires username, Lock doesn't trim the whitespace, causing auth to fail.

Repro on Lock v10.20.0:

1. Enable `requires username` on connection associated with client
2. Attempt to loginon Lock with trailing whitespace on email input `prashant@auth0.com ` 
3. Auth will fail. Monitoring network call, can see that whitespace is not trimmed:

```
//request payload to usernamepassword/login

{
  ...
  "connection": "Username-Password-Authentication",
  "username": "prashant@auth0.com ",
  "password": "<password>",
  ...
}
```

The same request, disabling `requires username` in the connection settings, results in Lock trimming the whitespace and successful auth.

**Comment by e1senh0rn** [comment]
Any updates here?

**Comment by luisrudge** [comment]
Hi. Not yet. We have other priorities right now. Do you mind sending a PR? I can review it and ship it if that's the case

**Comment by brassier** [comment]
This is also a fairly large issue for us.  This was causing lots of our users to be "blocked", when they really were not blocked.  Invalid users were being reported as blocked (e.g. `blah@gmail.com<SPACE>`), confusing lots of users and support staff.

We really need this fixed before we can upgrade to 11.x.

**Comment by brassier** [comment]
@luisrudge - I spent some time trying to dig through the Auth0 layers in GitHub.  It looks to me like this may boil down to an Auth0.js change and not Lock.  Does that sound right to you?  If this is correct, would we need to wait for a change in that library, and then a change for Lock to pull in that new version?  We need this fixed so we can upgrade to Lock v11 prior to the deprecation in April.

Add trim here:
https://github.com/auth0/auth0.js/blob/master/src/web-auth/username-password.js#L21

And possibly here:
https://github.com/auth0/auth0.js/blob/master/src/web-auth/cross-origin-authentication.js#L48

See (very old) auth.js library that used to trim similar code:
https://github.com/auth0/auth0.js/blob/038945972264ec4ef8dae5ca055f82f6fda0d888/index.js
`username:   trim(options.username || options.email || ''),`
