### ISSUE TITLE
Lock element sometimes disappears after loading animation

### ISSUE THREAD

**Issue by Svajoklis86** [auth0/lock#1185]
In my React project I have a component that creates a the lock on mount and then immediately calls the show() method. Occasionally the lock displays its loading animation and then disappears. I haven't been able to pinpoint why that happens, I see all the usual api calls return, but lock still disappears and doesn't show any errors in the console window. If I do everything the same way, but call the show method on a button click it works every time.

The issue happens on latest Chrome on Mac and Windows. I'm using the latest version of lock and React 15.

**Comment by luisrudge** [comment]
Can you build a repro? Are you sure your react component is not being unmounted?

**Comment by Svajoklis86** [comment]
Here's the gist of it. Auth0 callback doesn't finish with 400 for some reason, but it does in my environment

https://jsfiddle.net/svajoklis/v2cy57wm/14/

**Comment by luisrudge** [comment]
it's throwing a 400 error because you have to add https://jsfiddle.net to your allowed web origins urls.

**Comment by Svajoklis86** [comment]
I did it but it seems auth0 lock doesn't want to work in an iframe.

https://jsfiddle.net/svajoklis/v2cy57wm/17/

**Comment by luisrudge** [comment]
Ah, yeah. it's a cross domain issue. Can you setup a create-react-app so I can test it?

**Comment by Svajoklis86** [comment]
Here's a login screen in a live staging environment: http://app-staging.unboxed.social:32449

**Comment by luisrudge** [comment]
What do you I have to do to make it disappear?

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by jonathanadler** [comment]
Hey @svajoklis-1 did you manage to figure this out?
I'm getting the same issue.
