### ISSUE TITLE
Error fetching client data for Lock when users profile data above a certain size

### ISSUE THREAD

**Issue by chambois** [auth0/lock#1192]
Lock version: 10.22.0
Browser & OS: Firefox 57, Chrome 57+, MacOS, Windows 10
Application: React-based

### Steps to reproduce:
1. Insert enough data into your user profile, either through having a lot of long permission names and or role names and or group names
1. Log in as that user

### Result:
`Error: An error occurred when fetching client data for Lock: https://cdn.au.auth0.com/client/... could not be loaded.`

We have proved that by reducing the amount of data in the users profile through reducing either one of their permissions, roles or groups has resulted in this error not occurring. The tipping point for us seems to be around 750 characters in the users `app_metadata` (no whitespace, or ~1050 pretty-formatted). 

The user receives an access token and can successfully log in though no profile is returned from the `getUserInfo` call which our application currently depends on.

Any help would be much appreciated.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK itself. Most likely, something weird is happening in the backend. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario and/or route your request to the appropriate team.
