### ISSUE TITLE
Is there a way to force a particular event to be emitted for testing purposes?

### ISSUE THREAD

**Issue by morphatic** [auth0/lock#1197]
- [x] Code snippet or sample project that reproduces the bug

I'm building a PWA using the Ionic Framework (Angular) and using `@ngrx/store` for managing state. I'm trying to write unit tests to determine whether or not my actions are dispatched correctly when various `Auth0Lock` events are emitted. Here's a snippet of the `constructor()` of my `AuthProvider` class (`auth.ts`):

```typescript
@Injectable()
export class AuthProvider {

  lock: Auth0Lock;

  constructor(public store: Store<AuthState>) {
    // set up the Auth0Lock configuration options
    const options = { /* ... */};

    // create a new Auth0Lock
    this.lock = new Auth0Lock(ENV.auth0.client_id, ENV.auth0.domain, options);

    // listen for "authenticated" events
    this.lock.on("authenticated", (authResult: AuthResult) => {
      this.store.dispatch({type: LOGIN_SUCCESS, payload: authResult}); // <-- WANT TO DETERMINE IF THIS FIRES, for example
      this.store.dispatch({type: PROFILE_REQUEST});
      this.lock.getUserInfo(authResult.accessToken, (err: any, profile: UserProfile) => {
        if (err) {
          this.store.dispatch({type: PROFILE_FAILURE});
        }
        this.store.dispatch({type: PROFILE_SUCCESS, payload: profile});
      });
    });
  }
  /* ... the rest of the AuthProvider implementation ... */
}
```

And here's a snippet of my test (`auth.spec.ts`):

```typescript
describe('The AuthProvider service', () => {
  let auth: AuthProvider;
  let store: Store<AuthState>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ StoreModule.forRoot({ auth: authReducer }), ],
      declarations: [],
      providers: [ AuthProvider ]
    });
    store = TestBed.get(Store);
    spyOn(store, 'dispatch').and.callThrough();
    auth = new AuthProvider(store);
  });

  it('should dispatch LOGIN_SUCCESS when authenticated fires', () => {
    let authResult: AuthState = { /* ...basically the AuthResult plus a couple other fields... */};
    const login_success = new LoginSuccess(authResult);
    auth.lock.emitAuthenticatedEvent(); // <-- THIS IS WHAT I'M TRYING TO DO
    expect(store.dispatch).toHaveBeenCalledWith(login_success);
  });
```

Of course, the error message I'm getting is:

**`TypeError: auth.lock.emitAuthenticatedEvent is not a function`**

**Is there some way that I can trigger various events (authenticated, show, hide, unrecoverable_error, etc.) programmatically?** If not, do you have another suggestion about how I might go about this? I'm a HUGE fan of Auth0 and Lock! Thanks for all of your effort on this library!!!

- [x] Lock version **v10.24.1**

**Comment by luisrudge** [comment]
Nope. It doesn't make sense to expose those methods in the public API of Lock. You can use only these public methods: https://github.com/auth0/lock/blob/master/src/core.js
In your case, you probably need to mock Lock itself and handle the event handler by yourself.

**Comment by morphatic** [comment]
Ok. That makes sense. Thanks for the feedback.
