### ISSUE TITLE
[ENHANCEMENT] Back button for Google Authenticator 2FA

### ISSUE THREAD

**Issue by andoanwkm** [auth0/lock#1198]
**- Screenshots:**

<img width="1440" alt="screen shot 2017-12-18 at 9 57 47 am" src="https://user-images.githubusercontent.com/29110569/34088131-f273d1a8-e3d9-11e7-923b-12c47f069821.png">

Actual: Not have back button in top-left

Expect:

<img width="403" alt="33900457-064b2088-dfa1-11e7-9203-b8094dedc7fd" src="https://user-images.githubusercontent.com/29110569/34088166-1e2b9ae2-e3da-11e7-8eea-60d554a050e9.png">

**- Lock version:** 10.20.0

**- Browser & OS:** Chrome & MacOS

**Comment by luisrudge** [comment]
Hi, this looks like lock, but it isn't actually lock 😝. Please reach out to our amazing support team at https://support.auth0.com so they can route this to the proper team! Thanks 🎉

**Comment by andoanwkm** [comment]
@luisrudge can I post this issue to another repository of auth0? ^^ Maybe in this repo: https://github.com/auth0/auth0.js

**Comment by luisrudge** [comment]
@andoanwkm nope.. it's not auth0.js either. the MFA widget is part of another team. If you want, I can ping them internally about this, but then you'll have no follow up. If you open a ticket, then they'll keep you posted if anything changes.

**Comment by andoanwkm** [comment]
@luisrudge okay, I will send them a ticket. Thanks for your supporting 👍 👍 👍
