### ISSUE TITLE
Make React a Webpack external

### ISSUE THREAD

**Issue by xiongtx** [auth0/lock#1199]
Seems to me that `lock` should make `react`, `react-dom` etc. externals in `webpack.config.js`, so it doesn't pull in an extra copy. Any reason this shouldn't be the case?

**Comment by luisrudge** [comment]
because we can't do that without breaking our customers. We plan to do this in another major version, but not on v11.

**Comment by xiongtx** [comment]
<-- Not a Webpack expert

Cool. But if I wanted to do it myself, I'd add the following to the top-level `webpack.config.js`?

```js
externals: {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-dom/test-utils": "React.addons.TestUtils",
    "react-transition-group/CSSTransition": "React.addons.CSSTransition",
    "react-transition-group/ReplaceTransition": "React.addons.ReplaceTransition",
    "react-transition-group/Transition": "React.addons.Transition",
    "react-transition-group/TransitionGroup": "React.addons.TransitionGroup"
  }
```

**Comment by luisrudge** [comment]
are you using react from the cdn?

**Comment by xiongtx** [comment]
No.

The context here is that we're using [ClojureScript](https://clojurescript.org/) packages from [`CLJSJS`](https://github.com/cljsjs/packages), so we want to be able to use the React package and `:exclude` the React versions pulled in by other packages (e.g. `lock`).

**Comment by luisrudge** [comment]
hmm, right.. so that's probably what you should do, yeah.
