### ISSUE TITLE
Widget + Phonegap does not look good (Android)

### ISSUE THREAD

**Issue by pose** [auth0/lock#12]
This is how the widget inside phonegap looks on Samsung Galaxy S3:

![widget_s3](https://cloud.githubusercontent.com/assets/419703/4066791/5cf7e224-2e27-11e4-8560-194c569c2703.png)

**Comment by blablapolicja** [comment]
same on 
```
Cordova 4.3.0
Android 4.1.2
auth0-angular 4.0.1
```
![screenshot_2015-03-31-22-59-11](https://cloud.githubusercontent.com/assets/7767522/6938201/460e4718-d86a-11e4-82d0-bb9a05fa6029.png)
