### ISSUE TITLE
`connections: ['Username-Password-Database-Connection']` shows empty widget

### ISSUE THREAD

**Issue by alexanderteinum** [auth0/lock#120]
I’d like to have a widget with only username and password – i.e. without Facebook and Google+. I would assume that the following accomplished that, but it only shows a popup with the avatar and title.

    lock.show({
      connections: ['Username-Password-Database-Connection']
    }, function(err, profile, token) {});

**Comment by woloski** [comment]
make sure the connection name matches the one in your Auth0 dashboard






On Sat, Feb 7, 2015 at 7:04 AM -0800, "Alexander Teinum" <notifications@github.com> wrote:












I’d like to have a widget with only username and password – i.e. without Facebook and Google+. I would assume that the following accomplished that, but it only shows a popup with the avatar and title.

lock.show({
  connections: ['Username-Password-Database-Connection'],
}

**Comment by alexanderteinum** [comment]
That fixed it. Thank you!
