### ISSUE TITLE
Migration guide now not available for v11

### ISSUE THREAD

**Issue by mcrawshaw** [auth0/lock#1205]
The URL specified for the v11 migration guide is now not working at:
https://github.com/auth0/lock/blob/master/CHANGELOG.md

`https://auth0.com/docs/libraries/lock/v11/migration-guide`

It was working earlier, now `404`.

**Comment by luisrudge** [comment]
I pinged the docs team to know what's going on. I'll let you know when it's back again

**Comment by luisrudge** [comment]
we're back online! https://auth0.com/docs/libraries/lock/v11/migration-guide

sorry for the inconvenient
