### ISSUE TITLE
Error trying to create Auth0Lock instance - V11.0.0

### ISSUE THREAD

**Issue by nicosampler** [auth0/lock#1206]
Hi, since I updated to v11.0.0, every time that I create a new instance of Auth0Lock I'm having this error:
![image](https://user-images.githubusercontent.com/4376509/34320221-5e49c264-e7d3-11e7-82a6-71a889734f8b.png)
The log in auth0 says: 
![image](https://user-images.githubusercontent.com/4376509/34320222-64d9414a-e7d3-11e7-8b0e-aa93e31811b5.png)

Lock version: 11.0.0
chrome 62.0.3202.94 (Official Build) (64-bit)  / Debian Stretch

**Comment by luisrudge** [comment]
How are you initializing lock? Can you post a code snippet? Did you follow the migration guide?

**Comment by nicosampler** [comment]
The problem was produced because the "Customize Login Page" flag in Hosted pages was enabled. Even if you didn't change anything in the template, it must be turned off.

**Comment by luisrudge** [comment]
Ok. I'll take a look. Thanks! 🎉
