### ISSUE TITLE
Uncaught Error: accessToken parameter is not valid

### ISSUE THREAD

**Issue by mikicat** [auth0/lock#1210]
_Hello there_,
I was trying to set up a lock for an **_Electron_** app just copying the sample, but it returns this error after the user successfully logs in using Google social login:
 `assert.js:12 Uncaught Error: accessToken parameter is not valid`
    `at o (assert.js:12)` 
    `at Object.r [as check] (assert.js:24)`
    `at o.userInfo (index.js:420)`
    `at t.getUserInfo (p2_api.js:94)`
    `at t.getUserInfo (web_api.js:49)`
    `at e.getUserInfo (core.js:166)`
    `at e.getProfile (core.js:162)`
    `at e.lock.on (login.js:30)`
    `at e.n.emit (events.js:81)`
    `at index.js:468`

The code in `login.js` is the jQuery sample from the Electron sample app:

 `lock.on('authenticated', (authResult) => {`
 `       localStorage.setItem('id_token', authResult.idToken);` <- **Here** is where it has the problem
 `       lock.getProfile(authResult.idToken, (err, profile) => {`
 `         localStorage.setItem('profile', JSON.stringify(profile));`
 `         $('.profile-section').classList.remove('hidden');`
 `         $('.avatar').src = profile.picture;`
 `         $('.name').textContent = profile.nickname;`
 `         $('.email').textContent = profile.email;`
 `         $('.btn-login').classList.add('hidden');`
 `         $('.btn-logout').classList.remove('hidden');`
 `       });`
 `       lock.hide();`
 `     });`

The lock is set up without redirect, and without sso, like this:
`      var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {`
        `auth: {`
          `redirect: false,`
          `scope: 'openid profile',`
          `sso: false`
        `}`
      `});`

I am using lock v. _11.0.1_

**Comment by mikicat** [comment]
This is what looks like:
![problem](https://user-images.githubusercontent.com/10796244/34469882-3ad22500-ef27-11e7-844c-887a56ece658.PNG)

**Comment by mikicat** [comment]
Ok, after debugging the _authResult_, I've found that the code provided is wrong, because instead of `authResult.idToken` there should be `authResult.accessToken`, and then it returns the value OK.

**Comment by luisrudge** [comment]
`lock.getProfile(authResult.idToken, (err, profile) => {})`

Did you get this from one of our quickstarts/tutorials or you made the mistake yourself?

**Comment by mikicat** [comment]
This is a copy of the electron sample 01-login

**Comment by mikicat** [comment]
I've already submitted a pull request

**Comment by sirnornur** [comment]
The code sample provided in https://auth0.com/docs/libraries/lock/v11 is also wrong:
```ts
// ...
this.getUserInfo(authResult.idToken, function(error, profile) {
    // ...
});
// ...
```
