### ISSUE TITLE
Feature - Add support for custom background color for Auth Button "icon"

### ISSUE THREAD

**Issue by mikelax** [auth0/lock#1211]
Overview
===
I would like to use a custom social provider, ie. Twitch, as a social connection for log in / sign up. To conform to [Twitch brand guidelines](https://www.twitch.tv/p/brand/) and make the log in form look nice I want to customize the Twitch button with the correct colors and logo. 

Use Case
===
Lock version 11

Here is a code snippet of an options object for the `auth0-lock` where I [customize the auth buttons](https://auth0.com/docs/libraries/lock/v11/ui-customization#authbuttons-object-) `primaryColor` and `icon` attributes for twitch. 

```js
  {
      container: 'auth0Lock',
      initialScreen: 'login',
      theme: {
        primaryColor: '#985e6d', // default #ea5323
        authButtons: {
          'twitch': {
            primaryColor: '#6441A4',  // Twitch Purple
            icon: 'https://path_to_logo/twitch_glitch_wh_logo.svg'
          }
        }
      }, ......
  }
```

With this code snippet the background color of the login textfield with the text "Log in with Twitch" is correct, but the background color behind the icon is a "complimentary" color but I would like that to also be the standard "Twitch Purple".

Screenshot showing request
---
<img width="328" alt="auth0_custom_button" src="https://user-images.githubusercontent.com/2080701/34469795-e93c947e-eef3-11e7-8db7-028affeebec7.png">

**Comment by luisrudge** [comment]
You can't customize that color, but you can override the css class `auth0-lock-social-button-icon`.
So, something like this should work:

```css
.auth0-lock-social-button-icon {
  background-color: none;
}
```

Keep in mind that we can change this and other css class names at any time and any changes to css class names itself won't be considered breaking changes (it's not that common though).
