### ISSUE TITLE
Terms and conditions checkbox and social connections

### ISSUE THREAD

**Issue by Annyv2** [auth0/lock#1216]
**[Feedback from customer]:** "Sign Up with Facebook" and "Sign Up" are greyed out and unclickable (until you click "terms"), which is very confusing and counter-intuitive. Hardly anyone understands that this is because "terms" is not clicked.

![image](https://user-images.githubusercontent.com/5016479/34575346-aa22548e-f17a-11e7-947c-d0cfbfd24973.png)

**Comment by luisrudge** [comment]
I shared with the design team. If they feel like they need to change something, I'll reopen it.

**Comment by citegirl** [comment]
+1, we have the same issue. Are there any workarounds?

**Comment by corne-alant** [comment]
+1, we received complaints from users

**Comment by sobstel** [comment]
As a workaround, we did some custom scripting on top of lock.js where we highlight terms checkbox to draw user attention. You can see it in the wild at https://www.appjobs.com/.
