### ISSUE TITLE
Additional flashMessage type: `info`

### ISSUE THREAD

**Issue by selaux** [auth0/lock#1220]
Would you accept a PR which introduces a new `flashMessage` type? Currently afaik only `success` and `error` are possible. We want to have a third option `info`, which would show in blue. This way we could inform the user about things without having them thinking that something good/bad happened...

**Comment by luisrudge** [comment]
What types of auth related things would you inform there?

**Comment by selaux** [comment]
All sorts of auth related things 😉 . E.g.

- if the user just changed his email it should show him a message saying something like: "Please verify your new email before logging in"
- if the user just did a booking with us, it should show something like: "Please login to see your booking details" (or "... register ..." for non-registered users)

Basically we want to be able to show auth related messages without communicating them as "successful" or "error" messages.

**Comment by luisrudge** [comment]
Hmm. I guess it makes sense. Ok, let's see that PR 🎉 If we don't have an 'info color', please use #44C7F4 as background color to follow our [styleguide](https://styleguide.auth0.com/#/design/status-colors)

**Comment by fstoerkle** [comment]
We just opened a PR for this: https://github.com/auth0/lock/pull/1233

**Comment by selaux** [comment]
PR was merged. Will close.
