### ISSUE TITLE
Is requirejs support deprecated?

### ISSUE THREAD

**Issue by Haraldson** [auth0/lock#1222]
Lock v11.0.1 with my four year old project:

```javascript
define(['auth0-lock'], function(Auth0Lock) {
    console.log(Auth0Lock); // undefined
});
```

The config/lookup is not the problem – Lock 11 is at the exact same file path where Lock 9 used to sit.

**Comment by luisrudge** [comment]
Can you try auth0lock instead of auth0-lock?

**Comment by Haraldson** [comment]
Not sure what you mean. My file is called `auth0-lock.js`.

**Comment by luisrudge** [comment]
But we define with a different module name:
`global.window.define('auth0Lock'`

**Comment by Haraldson** [comment]
There’s no difference if I rename my file and require `auth0lock` instead. There’s no `auth0lock` in the global scope, either.

**Comment by luisrudge** [comment]
The js from the cdn puts `Auth0Lock` in the global scope. Can you use that while we figure it out requirejs support?

**Comment by Haraldson** [comment]
Sure! I’m not in a big rush – as long as I can get it upgraded properly before support for Lock 9 is deprecated. 👍

**Comment by luisrudge** [comment]
How are you installing the file? Just copying from the cdn into your project?

**Comment by Haraldson** [comment]
Yup.

**Comment by luisrudge** [comment]
Since you know requirejs better than I do, can you help me understand why the define I pasted is not working?

**Comment by Haraldson** [comment]
I never really created a library that’s to be distributed and depended on by other projects like this, but you could have a look at [Backbone’s factory](https://github.com/jashkenas/backbone/blob/master/backbone.js#L8-L34), for instance.

When I define a module in my own project, what I do is

```javascript
define(['dep1', 'dep2'], function(Dependency1, Dependency2) {
    return Dependency1.extend({
        ...
    });
});
```

A couple of key points:
– I don’t name the module, I leave it up to the compiler (`r.js` in my case)
– I always return the module from within the define block

**Comment by luisrudge** [comment]
we have this as well:
https://github.com/auth0/lock/blob/master/src/browser.js#L14

**Comment by luisrudge** [comment]
which is the same as the v9 version over here: https://github.com/auth0/lock/blob/v9/standalone.js#L21

We just renamed auth0-lock to auth0lock

It looks like a configuration in your project. Can you build a new barebones and try to reproduce the issue? If you can, put on github and reopen this issue with the proper reproduction steps so I can test it. Thanks!

**Comment by Haraldson** [comment]
Huh? Why did you close the issue?

There’s no configuration needed. I should be able to point to the file and have it loaded. This is not the case, which _is_ the entire issue. Which is now closes. Your factory and the one any major library use are quite different. You _have_ something, but not _it_.

**Comment by luisrudge** [comment]
If you compare the [v9 file](https://github.com/auth0/lock/blob/v9/standalone.js#L22) and the [v11 file](https://github.com/auth0/lock/blob/master/src/browser.js#L14), you'll see they're pretty much the same, we only changed the name from the `define` function from `auth0-lock` to `auth0lock`. They also look very much like Backbone's file and the [docs on how to define a module with a name](http://requirejs.org/docs/api.html#modulename). Because we're doing what the doc says we should do, I closed the issue and asked you to create a new project with only lock and see if it works. If it doesn't, please reopen the issue and point me to the repo with instructions on how to run the project and I'll try to help. Thanks 🎉

**Comment by Haraldson** [comment]
I would totally expect and understand your response if this was a typical free OSS project, but as it stands, we pay $770 a year for Auth0 and I don’t really see why I should debug and then provide the solution for you.

If I’m supposed to add something to my configuration because of the changes introduced between Lock 9 and 11, I expect to find details on that in the documentation.

**Comment by luisrudge** [comment]
Hi, I'm sorry you feel this way. All I'm asking from you is to create a project that reproduces the issue so I can take a look. This is standard procedure with all non-trivial issues we have in this repo.

Requirejs wasn't documented on v9 and it's not documented on v11 either, that's why you didn't see anything mentioned in the migration guide.

**Comment by luisrudge** [comment]
According to [this comment](https://github.com/auth0/lock/issues/1222#issuecomment-357230627), you tried requiring `auth0lock`.  I guess you misspelled the module name I pasted in [this comment](https://github.com/auth0/lock/issues/1222#issuecomment-357230368). The correct module name is `auth0Lock`.

I just created a new project (based on this project starter https://github.com/volojs/create-template) and it works as expected:

![image](https://user-images.githubusercontent.com/941075/34907543-7d3a1bfc-f867-11e7-8c70-5bcb1679b57f.png)
![image](https://user-images.githubusercontent.com/941075/34907558-a836b02c-f867-11e7-9036-354e1cc7e49e.png)

**Comment by Haraldson** [comment]
Thanks for the updates. I think the problems here are caused by a combination of naming the module, and changing that named module’s name to something different than what seems to still be the project’s name, `auth0-lock` (as per the readme).

So what worked earlier mostly due to a coincidence (I called my file `auth0-lock.js` since that’s what the project name was and is, and this name in turn matched the module’s name) doesn’t work anymore because there’s now a mismatch between the project’s name (as I interpret it, based on its NPM package name for instance) and the defined name.

I would still prefer an unnamed module, which is how it mostly works in RequireJS, but if that’s out of the question I think this inconsistency should be documented.

**Comment by luisrudge** [comment]
I totally agree we shouldn't have changed the module name :( When you say unnamed module, do you mean just not specifying the module name? Like:

`global.window.define(function() { return Auth0Lock; });`

What are the drawbacks of doing this? If this doesn't break anyone currently using requirejs and v11, I can patch our version to do that.

**Comment by Haraldson** [comment]
After having looked through a bunch of my project’s dependencies, where there are both named and unnamed modules, I think this mostly boils down to naming consistently and intuitively. 

– Unnamed modules are often aliased by defining a `name: filepath` pair in `requirejs.config.paths`. Useful for stuff like `marionette: 'backbone.marionette'`, so you can `require('marionette')` later on.

I would be able to
– Call my file copy `lock.js` and do `define(['lock'], function(Auth0Lock) { ... })` right out of the box
– Call my file copy `auth0lock.js`, and do

```javascript
requirejs.config({ paths: { lock: 'auth0lock' } });
...
define(['lock'], function(Auth0Lock) { ... })
```

– The modules that are named, are most often also quite intuitively named. jQuery defines itself as `'jquery'`, for instance.

I would still be able to alias the dependency in this case, but would need to know implementation details about the project – like knowing that it’s supposed to be `auth0Lock`, camel cased, no dash etc.
