### ISSUE TITLE
Documentation Discrepancy 

### ISSUE THREAD

**Issue by gorillapower** [auth0/lock#1228]
It looks like there is a discrepancy between the github readme and whats on the lock 11 documentation page.

Specifically, the `scope` location inside the `auth: {}` is different. In the readme its `auth: { scope: "openid"}` in the documentation its 
`auth:{ params: { scope: "openid"}}}`

Im having trouble getting lock 11 to respect my scope parameter and so am wondering which is the correct way to specify it?

ReadMe:
![image](https://user-images.githubusercontent.com/8879065/35158875-1faf3f10-fd41-11e7-9187-60008bc68283.png)

Docs:
![image](https://user-images.githubusercontent.com/8879065/35158914-36341238-fd41-11e7-8b83-86852c4bb754.png)

**Comment by luisrudge** [comment]
Ops! Thanks for catching that. 🎉
