### ISSUE TITLE
When using Enterprise Connection (LDAP) and NO Database connection SSO does not work

### ISSUE THREAD

**Issue by ntotten** [auth0/lock#123]
Repo steps:

1. Create App
2. Create and enabled LDAP Enterprise Connection, set email address (mit.edu)
3. Disable Database connection
4. Go to lock, type in email address jon@mit.edu
5. Lock will not change from "Access" to "Login with mit.edu"

![screenshot 2015-02-17 13 37 33](https://cloud.githubusercontent.com/assets/282782/6237774/7b7922ba-b6aa-11e4-88a5-e81af5c37c11.png)

**Comment by hzalaz** [comment]
Already fixed
