### ISSUE TITLE
Heights not respected in password-only lock resulting in overlapping content [v10]

### ISSUE THREAD

**Issue by davidharting** [auth0/lock#1230]
# Environment
### Lock version
`10.24.1`
Grabbing it from this CDN: https://cdn.auth0.com/js/lock/10.24.1/lock.min.js

### OS
Mac OS High Sierra 10.13.2

### Browsers
Reproduced in
* Firefox 58.0 (64-bit)
* Chrome 63.0.3239.132 (Official Build) (64-bit)

### Code
We are using the Auth0 hosted page.

We have both a passwordless and a regular lock instantiated, and the user can interact with some buttons to determine which lock they want to use. 

Our regular lock is instantiated with this code:

```js
var config = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));
var options = {
  allowedConnections: ['Username-Password-Authentication'],
  closeable: true,
  auth: {
    params: config.internalOptions,
    redirect: true,
    redirectUrl: config.callbackURL,
    responseType: 'token'
  },
  allowShowPassword: true
}
var lock = new Auth0Lock(config.clientID, config.auth0Domain, options);
```

# Defect
Here are some screen shots of the defect in action

### Logging in fresh
*Reproduced in Firefox and Chrome*
![image](https://user-images.githubusercontent.com/6146772/35281630-58e410ca-0021-11e8-90c2-ee4208feabe7.png)

### Logging in when the lock remembers you from last time
*Reproduced in Firefox only*
![image](https://user-images.githubusercontent.com/6146772/35281661-70ba7766-0021-11e8-8ec0-023796aba1bc.png)

### Video of resizing and clicking around
[Video](https://www.useloom.com/share/84f00a7dc03c47a7a09b8e9ab15b6fcf)

**Comment by davidharting** [comment]
Hey @beneliflo! Let me know if I can provide you any more detail.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
