### ISSUE TITLE
v11 no longer includes `exp` in idTokenPayload

### ISSUE THREAD

**Issue by Geczy** [auth0/lock#1231]
`exp` is missing, why? I have scope defined as `openid offline_access`

# v10
![image](https://user-images.githubusercontent.com/1036968/35292318-1b41e054-003e-11e8-800c-45f47aad5a11.png)

# v11
![image](https://user-images.githubusercontent.com/1036968/35292357-31c868a2-003e-11e8-8782-2296b5305be7.png)

**Comment by luisrudge** [comment]
how are you setting the scope?

**Comment by Geczy** [comment]
Same as v10:

![image](https://user-images.githubusercontent.com/1036968/35293055-88c93170-0040-11e8-80ff-be9e38f9f9eb.png)

**Comment by luisrudge** [comment]
You can see that the v11 version is bringing a whole lot more information (we changed the default to `openid profile email`). Can you check what scope is being sent to the authorize call in the dev tools?

**Comment by Geczy** [comment]
I see two requests to `authorize` after trying to login

First one
![image](https://user-images.githubusercontent.com/1036968/35293655-5937c8fc-0042-11e8-8424-ce0d945dbc81.png)

Second one
![image](https://user-images.githubusercontent.com/1036968/35293664-641d9576-0042-11e8-89e8-9bc7182e6a2d.png)

**Comment by luisrudge** [comment]
how do you have an idtoken if your responseType is only 'token'? Is your client marked as oidc conformant in the dashboard?

**Comment by Geczy** [comment]
No it's not 

![image](https://user-images.githubusercontent.com/1036968/35293867-039780c6-0043-11e8-8b13-d8f3211cacbd.png)

**Comment by luisrudge** [comment]
I have no idea what's going on. Can you please create a repro project so I can test it out?

**Comment by Geczy** [comment]
Does it have to do with the two requests being sent to authorize? In v10, only one request is sent

**Comment by Geczy** [comment]
It's as if the default authorize params are sent first, and then my configs are sent second

**Comment by luisrudge** [comment]
hmm. it shouldn't. The first request is only checking if you have an active session. You can disable that if you want. Try adding `sso:false` to your `options.auth` :

```js
var options = {
  auth: {
    sso: false
  }
}
```

**Comment by Geczy** [comment]
You're right, turned it off and only see one now with my correct scope `openid offline_access`

**Comment by Geczy** [comment]
Can't make a repro repo but happy to provide Teamviewer ID + PW to someone

**Comment by luisrudge** [comment]
but it sill has the wrong idtoken?

**Comment by Geczy** [comment]
It has an idtoken still, yes, response type only token

**Comment by luisrudge** [comment]
for non-oidc clients, you'll always get an idToken. are you just switching versions when testing both cases?

**Comment by Geczy** [comment]
Yes I am, package.json change and yarn install

**Comment by luisrudge** [comment]
can you build a repro sample? You can use this file as a starting point:

```html
<!DOCTYPE html>
<html>
<title>Dev</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
<style>
  body {
    background-color: #1f1f24;
  }
</style>

<body>
  <div id="container"></div>
  <script src="http://cdn.auth0.com/js/lock/11.1.0/lock.min.js"></script>
  <script>
    const cid = "";
    const domain = "";
    const options = {};
    const lock = new Auth0Lock(cid, domain, options);
    window.lock = lock;
    lock.on("authenticated", function (authResult) {
      console.log(authResult);
    });
    lock.on("authorization_error", function (error) {
      console.log('authorization_error', error);
    });
    lock.show();
  </script>
</body>

</html>
```

**Comment by Geczy** [comment]
No, I probably can't..

**Comment by Geczy** [comment]
Still receiving this issue on auth0-lock 11.2.3

**Comment by luisrudge** [comment]
Please create a repro so I can test this. You can use this cdn files in the html file I mentioned above.
https://cdn.auth0.com/js/lock/10.24/lock.js
http://cdn.auth0.com/js/lock/11.2.0/lock.min.js

**Comment by Geczy** [comment]
I can give you access to a private repo if you'd like

**Comment by luisrudge** [comment]
@Geczy sorry, we can't do that. You can create a simple repro based on what I sent to you. If you can't do that, please reach out to our amazing support team at https://support.auth0.com
