### ISSUE TITLE
Support or fail safe version for Safari < 11 in private mode

### ISSUE THREAD

**Issue by jackblackCH** [auth0/lock#1242]
Users with Safari version <= 11 and browsing in private are stuck after clicking the login button in the modal window. 

Console output: 
`QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.`

Can we at least handle this case and show a warning?

- [ 10.24.2 ] Lock version
- [ Safari < 11 ] Browser & OS

**Comment by luisrudge** [comment]
Do you know what fails in that mode?

**Comment by jackblackCH** [comment]
Not exactly, it hangs after clicking, I updated console error in the message above.

**Comment by luisrudge** [comment]
so, it's failing to use localStorage. It's an issue downstream then: https://github.com/auth0/auth0.js/issues/623
