### ISSUE TITLE
Event lock.once has been deprecated starting with version 10. What is the replacement for it?

### ISSUE THREAD

**Issue by maeni70** [auth0/lock#1244]
The event lock.once was available in version 9. However, it is gone starting with version 10.

**Comment by luisrudge** [comment]
what do you need to do?

**Comment by maeni70** [comment]
Hi Luis
I have managed to use .on() method with corresponding event instead of .once().
There is special logic on our login form in SharePoint - injecting additional consent for external users. It needed be upgraded to from Lock 9 to 11.
Thanks,
Roger
