### ISSUE TITLE
Emit an event when network/service is unavailable

### ISSUE THREAD

**Issue by gdjennings** [auth0/lock#125]
In a cordova app with locally deployed JS, if the network or service is unavailabe/inaccessible there is no event triggered. The first point of failure is in onclientloaderror, it would be nice if an event was emitted from here so the app can gracefully enter an offline mode.

**Comment by pose** [comment]
Yes, that's correct. I think the right name for it would be: `client error` but I don't know if that's going to be too generic: https://github.com/auth0/lock/wiki/Events

**Comment by dhiva** [comment]
+1

**Comment by hzalaz** [comment]
It could be solved by checking network state before showing lock.

**Comment by cristiandouce** [comment]
https://github.com/auth0/lock#onevent-callback

> `unrecoverable_error`: emitted when there is an unrecoverable error, for instance when no connection is available. Has the error as the only argument.
