### ISSUE TITLE
Consider HRD configuration of enterprise connections in forgot password

### ISSUE THREAD

**Issue by jmangelo** [auth0/lock#1250]
The available forgot password functionality can be confusing in the following scenario:

- there's a database and an enterprise connection enabled (the enterprise one has HRD configured for `@contoso.com` emails).
- an end-user inputs an SSO-enabled email address in the forgot password field.

The forgot password should detect when an enterprise connection email address is entered, and suggest that it isn't possible to reset that password via Lock. However, currently the end-user can continue with the reset password request even though that if the same email is entered in login in SSO will be forced.

Tested with Lock 10.24.3 and 11.2 version.

**Comment by luisrudge** [comment]
related: ZD: 34486
