### ISSUE TITLE
v11 Passwordless doesn't support Lock option `rememberLastLogin`, but LockPasswordless@2.x did

### ISSUE THREAD

**Issue by emmoistner** [auth0/lock#1255]
### Background
LockPasswordless supported the concept of a `cred` which on login would be stored with the method `sms`, `magiclink`, or `emailcode`  into localStorage. This was used to rehydrate lastLoginCred per each auth method. 

Reference -  https://github.com/auth0/lock-passwordless/blob/5ba3f93acd1946eb2ff2a5f5b93f3cb8643e9231/src/lock/actions.js#L40

### Issue
The new v11 PasswordlessLock module doesn't support the previous workflow. When passing `rememberLastLogin` to PasswordLessLock now, it doesn't autofill with previous login information. 

### Question
Was this an intentional change or a bug? Maybe there is better approach coming down the pipeline?

### Helpful information
**Lock Version** - 11.2.2

**Comment by luisrudge** [comment]
Lock only shows that screen if you have sso enabled, so use this option:

```js
var options = {
  auth: {
    sso: true
  }
}
```

**Comment by emmoistner** [comment]
@luisrudge `sso` and `rememberLastLogin` enabled does not work with the **passwordless** engine, but it does work for the **classic** engine.

The change I'm seeing is going from using `lock-passwordless@2.x` to passwordless with `auth0-lock@11.2.2`. `rememberLastLogin` for the passwordless engine doesn't work that way it did for `lock-passwordless@2.x`.

## Gif Example
**lock-passwordless-2.x**
![lock-passwordless](https://user-images.githubusercontent.com/5419727/35983695-89e659ac-0cc0-11e8-9e73-a982ce274b43.gif)


**Passordless engine with auth0-lock-11.2.2**
![lock 11](https://user-images.githubusercontent.com/5419727/35983703-90973ee2-0cc0-11e8-98cf-ac30b349d708.gif)

**Comment by luisrudge** [comment]
If you refresh the page in the first case, you'd still lose the state. This was probably a bug in the old lock. Everytime you call `lock.show()`, it should have a clean state (everything should be empty). This is the correct behavior.

**Comment by emmoistner** [comment]
[I think the difference I'm seeing is that if you pass `rememberLastLogin` it would fill the lock input with the previous login stored in localStorage.](https://github.com/auth0/lock-passwordless/blob/5ba3f93acd1946eb2ff2a5f5b93f3cb8643e9231/src/lock/actions.js#L40) If you refreshed the page it would pull previousLogin information from localStorage. 

> This is the correct behavior

I assume going forward auth0 doesn't want login information stored into localStorage?

**Comment by luisrudge** [comment]
We use localStorage in a few places, but not for this same reason.

**Comment by emmoistner** [comment]
Issue is posted again here https://github.com/auth0/lock/issues/1263

**Comment by emmoistner** [comment]
A parity feature was added to PasswordlessLock  to support `sso` & `rememberLastLogin` with PR https://github.com/auth0/lock/pull/1267
