### ISSUE TITLE
Auth0LockPasswordless showing username & password

### ISSUE THREAD

**Issue by de-code** [auth0/lock#1256]
Excited that https://github.com/auth0/lock/pull/1070 had been merged... I am now trying to migrate from `auth0-lock-passwordless` to this module, using React.

My code:

```javascript
import WebAuth from 'auth0-js';
import Auth0LockPasswordless from 'auth0-lock';

lock = new Auth0LockPasswordless(
  CLIENT_ID, DOMAIN, {
    passwordlessMethod: "link",
    allowShowPassword: false,
    allowSignUp: false
  }
);
# lock.on...

# deferred / when button is clicked:

lock.show();
```

(previously I would have called `lock.magiclink()`)

This is still showing a form with the username/password instead of just an email.

On the connections tab, the client has Passwordless (email) enabled and Username-Password-Authentication database disabled.

BTW The [migration guide](https://auth0.com/docs/libraries/lock/v11/migration-lock-passwordless) mentions `auth0-lock/passwordless` which perhaps should be `auth0-lock`?

**Comment by luisrudge** [comment]
The migration guide is correct and this is the reason you're getting the normal lock showing up. We have a different entry point for passwordless, so you have to import it like this: `import Auth0LockPasswordless from 'auth0-lock/passwordless';`

**Comment by de-code** [comment]
Okay, thank you for confirming. I wasn't thinking straight I think. That import isn't working for me. I will have to debug why.
