### ISSUE TITLE
History.md is outdated

### ISSUE THREAD

**Issue by gjungb** [auth0/lock#126]
First of all, I want to state that Auth0 is awesome :+1: 
Nonetheless the ```History.md``` is totally outdated (last change mentioning version 6.1.3 from Aug. 2014). For a security related project this file should be updated more frequently.

**Comment by pose** [comment]
Hi @gjungb,

You are definitely right. We will get that updated soon.

Thanks,

**Comment by pose** [comment]
@gjungb This has just been fixed. Thanks!
