### ISSUE TITLE
Only XHR based (via action-xhr attribute) submissions are support for POST requests

### ISSUE THREAD

**Issue by n0ne** [auth0/lock#1268]
I have this error, when I'm trying to login with e-mail or register new user
Facebook and Google login are working normally, without any problem

auth0-lock: 11.2.3
Browser: Chrome & Firefox
OS: Linux Mint 18.3

![error](https://user-images.githubusercontent.com/783906/36302731-3545c934-1312-11e8-9826-9d117504775c.png)

**Comment by luisrudge** [comment]
are you running this as an AMP page?

**Comment by n0ne** [comment]
Damn...yes. I've remooved `<style amp-boilerplate>` and `cdn.ampproject.org/v0.js`

Now only one error - the last, GET... )))-:

**Comment by luisrudge** [comment]
Click the link and see what error is being returned. Probably a configuration issue.

**Comment by n0ne** [comment]
I've clicked...
error=access_denied
error_description=Unknown or invalid login ticket

I can't understand, what and when  I did wrong....

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by n0ne** [comment]
Thank you very much!
