### ISSUE TITLE
Home Realm Discovery not working using OpenIDConnect

### ISSUE THREAD

**Issue by niksw7** [auth0/lock#1270]
SetUp: 
We had setup 2 tenants, one a  global tenant and other normal tenant following the instructions said here
[https://auth0.com/docs/connections/social/auth0-oidc](https://auth0.com/docs/connections/social/auth0-oidc)
What worked in Auth0 9.2.2:- The moment I enter a email with @particular-domain, the password button will be disabled, and the submit button will have href to global auth0 authentication page, which when clicked you will see the global tennant's auth0 Page.

This feature does not work in Auth0 11.2.3.

[My analysis]- The v9.2.2 has the following code
`OptionsManager.prototype._isEnterpriseConnection = function (email, output) {
  var client = this.$client;
  var domain = this._extractEmailDomain(email);
  var conn = this._filterConnections(domain, client.strategies, {userAndPass: undefined});

  if (conn && output) {
    output.domain = conn.domain;
  }

  return !!conn;
};`
If i look at strategies, i can see both the connection names here.

[v11.2.3] -However in this version, I see there are groupings as database, social,etc. However the auth0-oidc strategy comes under unknown connection.
![screen shot 2018-02-20 at 12 17 11 pm](https://user-images.githubusercontent.com/2026034/36410703-2d47fc9c-1638-11e8-8caa-68c8c8c06e3c.png)

Or please let me know if I am not doing the right way

**Comment by luisrudge** [comment]
when you say `Auth0 9.2.2`, you mean Lock@9.2.2?

**Comment by niksw7** [comment]
Yes I meant auth0 lock

**Comment by luisrudge** [comment]
Thanks for the heads up. I fixed this in #1275 and will publish a patch version in the next few days
