### ISSUE TITLE
Allow connectionResolver to resolve to AD and other enterprise connections

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1272]
Lock v9 provided the `options` and `context` parameters in the events that allowed some interesting magic to happen. In particular, by analyzing the `context` and changing the `options`, you could decide that the target connection for the authentication was an AD/LDAP connection. One interesting use, for instance, was using the default DB connection if an email was entered in the first field, or switch to a specific AD connection if a username was used instead (no `@`).

While Lock 10/11 don't allow changing options dynamically, it seems that this use case would be better served by the `connectionResolver`, except that it currently only supports database connection. Ideally, `connectionResolver` should also support using AD/LDAP connections and other types of enterprise connections that support "active" authentication (like ADFS and Azure AD depending on configuration).

To support this use case, there should be some way of configuring the username/email text field to allow it to freely type either usernames or emails (this might also be desirable even when switching between different database connections, as some might support username while others don't).

**Comment by nicosabena** [comment]
Related https://github.com/auth0/lock/issues/1194, because currently the resolver apparently validates that the returned connection is in the list of available connections for the client (up to 50 returned).

**Comment by cocojoe** [comment]
@nicosabena this has been added to an internal discussion regarding the improvement of the connectionResolver in general.  Thanks for raising.

**Comment by kjk129** [comment]
In our case, we have significant number of customers used to using the AD/LDAP connections with Lock 9 where they can just enter just their User Name ( minus the @domain.com suffix ).  In Lock 11, it would be nice to be able to preserve this behavior to avoid the need for users to enter the fully qualified UserName@domain.com.   We typically have both an AD/LDAP & Azure AD connection bound to a each Client, so there remains a need for Lock to resolve the correct connection at run-time based on what the user types.  In other words, we can't just initialize Lock with a specific Connection.

**Comment by luisrudge** [comment]
@kjk129 lock already supports that out of the box.

**Comment by kjk129** [comment]
Luis – Could you explain how to achieve this behavior?

Kurtis Kyle
Sr. Software Developer
Blue Mountain Quality Resources, Inc.
814-234-2417 x 189 | KJKyle@coolblue.com
www.coolblue.com<http://www.coolblue.com/> | Connect with us!<https://www.linkedin.com/company/blue-mountain-quality-resources-inc-?trk=biz-companies-cym>

[cid:BMQR_logo_RGB-e1478549506901_53e55b27-f7c5-4f69-bce3-00b2b4c04a32.png]

**Comment by kjk129** [comment]
Luis – Could you explain how to achieve this behavior?

**Comment by luisrudge** [comment]
Sorry, I should've be more clear: If you have less than 50 connections in total, it handles OOTB. Otherwise, we fall into this issue that we're typing

**Comment by kjk129** [comment]
Per Client, we only have 2 Connections configured total.  One AD/LDAP and one AzureAD.
I'm not sure what OOTB means ?

**Comment by luisrudge** [comment]
`out of the box`. If you have only two, lock will initiate the HRD (home realm discovery) automatically when the username domain matches your connection domain.

**Comment by luisrudge** [comment]
https://auth0.com/docs/libraries/lock/v11/selecting-the-connection-for-multiple-logins

**Comment by kjk129** [comment]
Yes, this is indeed how Lock 11 is behaving.  It is just different than Lock 9 behavior where in that case the user could simply enter the UserName only and a Password and then proceed with the authentication in one click.  Somehow the Lock 9 widget determined to use the AD/LDAP connection (even without the domain entered) and to authenticate using the legacy /ro endpoint.

**Comment by luisrudge** [comment]
ah, sorry. I misread your comment. You're saying that v9 did HRD without the user typing the domain name, right? Did you add any configuration to make that happen? I have no familiarity with v9 at all, so I'm not sure how would that be possible, considering you have two connections to chose from

**Comment by kjk129** [comment]
Correct.  Below was the specific configuration we used in Lock 9.   With UsernameStyle set to 'username', you wouldn't think that Azure AD or SAML connections would necessarily work with username@domain.com entered, but the Lock 9 would still resolve the correct connection for those user names as well.

                    popup: true,
                    sso: false,
                    rememberLastLogin: false,
                    disableSignupAction: true,
                    disableResetAction: true,
                    usernameStyle: 'username',
                    socialBigButtons: false,
                    focusInput: true,
                    icon: '/images/Logo.jpg',
                    defaultADUsernameFromEmailPrefix: true,

**Comment by sdanbury** [comment]
Also interested in the logic @nicosabena was talking about with being able to pick an enterprise connection based on what is entered into the username box.

I would like to do some enterprise connection selection logic based on username suffix like so:

```
connectionResolver: function (username, context, cb) {
  var suffix = username.endsWith('_blahblah');
  if (suffix) {
    cb({ type: 'enterprise', name: 'ldap-connection' });
  } else {
    // Use the default approach to figure it out the connection
    cb(null);
  }
}
```

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
