### ISSUE TITLE
lock 10->lock 11 Second login not trigger the redirectUrl

### ISSUE THREAD

**Issue by jiaxiangl** [auth0/lock#1276]
I am updating auth0 from lock10 to lock 11 and I followed this article :  https://auth0.com/docs/libraries/lock/v11/migration-v10-v11  after setup, the first time username and password login *works fine* and the second time when I log out and log back in, it shows something like this below
![image](https://user-images.githubusercontent.com/22890806/36690150-074d2dbe-1af7-11e8-9bf9-bad93998e308.png)
Then when I click the gray button, if just shows 
![image](https://user-images.githubusercontent.com/22890806/36690175-139b94b6-1af7-11e8-9649-d5e5b51e3a6d.png) and it's not triggered the callback url, which means that picture just stay there and won't go to the callback page.

**Comment by jiaxiangl** [comment]
after I click the gray button it does submit a request 
![image](https://user-images.githubusercontent.com/22890806/36690423-e27131f6-1af7-11e8-8a94-898352268b31.png)

**Comment by luisrudge** [comment]
That’s by design. The quick session call uses the new response mode “web_message”, which doesn’t do a redirect. It does trigger the authenticated event though, so you can use that instead.
