### ISSUE TITLE
Different placeholders for signup and signin

### ISSUE THREAD

**Issue by danjohansson** [auth0/lock#1284]
The placeholder for password in signup and signin tabs are controlled by the passwordInputPlaceholder data field in the language dictionary.
To make it clear to the user that they are setting a **new** password in the signup tab as oppose to writing an already known password in the signin tab. A different placeholder datafield would be good to have, with a text like "Pick a password".

Using v11.2

**Comment by luisrudge** [comment]
Do you want to send a PR with that? Make sure to set the default as the current placeholder so we don't break anyone
