### ISSUE TITLE
cb() never called! during npm install

### ISSUE THREAD

**Issue by MaxCCC** [auth0/lock#1287]
Thank you for using Lock! Please read the following before creating a new issue.

- [x] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [X] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [X] Lock version: 11.3.1
- [X] Browser & OS: Locally on Windows, On Unix (ArchLinux on Jenkins2)

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.
I tried this to resolve the issue (read it online):
```
λ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
```
install:
npm: 5.6.0
node: 9.4.0
```
λ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by lvthillo** [comment]
Maybe related to https://github.com/ubirak/gulp-uglifycss/issues/15

**Comment by luisrudge** [comment]
are you cloning this repo or trying to install it in your app?

**Comment by MaxCCC** [comment]
@luisrudge I'm cloning the repo and performing an npm install in it.

**Comment by luisrudge** [comment]
probably an issue with npm itself: https://github.com/npm/npm/search?q=cb+never+called&type=Issues&utf8=%E2%9C%93
