### ISSUE TITLE
Silently refreshing access token

### ISSUE THREAD

**Issue by catamphetamine** [auth0/lock#1293]
I was reading through Auth0 docs and saw a feature of calling `auth0.checkSession()` to silently refresh access token on a timeout.
https://auth0.com/docs/quickstart/spa/react/05-token-renewal
But we're not using Auth0 directly, we're using Lock.
Then I saw some people using `lock.checkSession()` in issues but I didn't find `.checkSession()` method in the Lock API reference.
https://auth0.com/docs/libraries/lock/v11/api
Is there a way to both use Lock and use `auth0.checkSession()` feature?
Or does it have to be either one or another?

**Comment by catamphetamine** [comment]
Oh, I see, so they can be used together:
https://auth0.com/docs/libraries/lock/v11/auth0js
Closing then.

**Comment by luisrudge** [comment]
you can also call `lock.checkSession`. It's not documented yet, but it's already available: https://github.com/auth0/lock/blob/2d88aa7c241e7f4c14a06fd95c6c8f192d77cb79/src/core.js#L183

**Comment by luisrudge** [comment]
I also created the PR to document this: https://github.com/auth0/docs/pull/5886 Thanks for the heads up! 🎉
