### ISSUE TITLE
Safari not working with Auth0 11.4.0

### ISSUE THREAD

**Issue by krokhale** [auth0/lock#1299]
I am using it in a single page react app, which uses localstorage as has been described in the docs, using Safari 11.0.3 on a mac and the login seems to be crashing out at the point when the localstorage in safari comes into play. The user is not able to login.

Auth0 lock seems to be working on all other browsers like Chrome, opera, firefox just fine using the code in the docs.

**Comment by luisrudge** [comment]
do you have a repro? or just a simple lock.show() will cause the error? are you seeing anything in the console?

**Comment by krokhale** [comment]
Just researched it a bit, looked at the logs in dashboard:

 "error": {
      "message": "Unable to configure verification page.",
      "oauthError": "server_error",
      "type": "oauth-authorization"
    }


https://community.auth0.com/t/unable-to-configure-verification-page-error-on-hosted-login/9214

I just don't get what changed suddenly. Would paying for a custom domain resolve this issue?

**Comment by luisrudge** [comment]
did you follow https://auth0.com/docs/cross-origin-authentication#create-a-cross-origin-verification-page?

**Comment by krokhale** [comment]
Never mind, just paid and set up a custom domain, works now. I kind of like the look of a custom domain instead of a auth0 in the URL.

Thanks for your help. quick question: on this page:

https://auth0.com/docs/custom-domains#step-3-complete-feature-specific-setup

It says:

The CDN URL varies by region. For regions outside of the US, use https://cdn.{region}.auth0.com.

What's the region? What are links?

**Comment by luisrudge** [comment]
this is only for the `configurationBaseUrl` option inside lock. You can use the same as your tenant's location. Available regions: `https://cdn.auth0.com`, `https://cdn.eu.auth0.com` and `https://cdn.au.auth0.com`;
Thanks 🎉

**Comment by chauhanvishaal** [comment]
Hi,

I am fighting this error since a while now.
I have implemented custom domain and callback-cross-auth.html pages.
Do not have cookies blocked in IE v11 even then cant get rid of the problem.
Below are the options I pass to Auth0Lock before calling
this.lock.show({ allowSignUp: false });

These options work in IE if I set redirect: false but with that MFA authentication doesnt work which is why I am now using default redirect: true which has problems with IE.

Please help..

oprtions = {
configurationBaseUrl: 'https://cdn.eu.auth0.com',
auth: {

            redirectUrl: window.location.origin,
            autoParseHash: true,
            responseType: 'token id_token',
            params: {
                scope: 'openid email profile name picture user_metadata app_metadata user_id',
                state: JSON.stringify({

                })
            }
        },
        allowSignUp: false,
        allowForgotPassword: true,
        theme:  {
            logo: this.logo,
            primaryColor: '#0a355c'
        },
        avatar: null,
        closable: true,
        rememberLastLogin: false,
        container: "login-container",
        languageDictionary: {
            success: {
                logIn: ''
            }
        },
    };

**Comment by chauhanvishaal** [comment]
Hi Luis. Yes It works.

**Comment by luisrudge** [comment]
Then it's likely a configuration issue. Please reach out to our amazing support team at https://support.auth0.com

**Comment by chauhanvishaal** [comment]
My issue apparently seems to be only in my local environment. Later in the day I thought of checking the same build on a proper integration environment, which seemed to work.
So I will close the issue, though my local env still doesnt work. I have even tried following below steps at the end of this link: https://auth0.com/docs/custom-domains

Go to Internet Options > Security.
Select the Local Intranet Zone tab and go to Sites > Advanced. Add your domain.
Return to the Security tab, and make sure the proper zone has been selected.
Click Custom Level and look for Access data sources across domains under the Miscellaneous section. Check the radio button next to Enable..

**Comment by luisrudge** [comment]
@chauhanvishaal Are you running on localhost?

**Comment by Sbphillips19** [comment]
@luisrudge I just started running into the same problem on safari in localhost.   Is there anyway around this?  I am using auth0.js library instead, but it appears to be the same issue.  We use custom domains so have no issues in other environments.  I can deploy and test in safari, but I can't develop in safari
