### ISSUE TITLE
Issue with HRD on Sign Up if database connection has requires username enabled

### ISSUE THREAD

**Issue by jmangelo** [auth0/lock#1301]
Originally reported at: https://community.auth0.com/t/auth-bug-saml-required-username-database-connections/10257

---

If you configure a client application to have a database connection with _Requires Username_ **enabled** and a SAML enterprise connection with an associated email domain of `contoso.com` then if you perform the following steps in Lock 11.4.0:

1. Show Lock.
1. Select the _Sign Up_ section.
1. Input an email like `user@contoso.com` in the email field.

then Lock should detect that the email is associated with an enterprise connection and display the SSO enabled option. **However, Lock won't show SSO enabled even though the email domain matches an enterprise connection**.

As additional information, if you then enter `user@contoso.com` also as the username value Lock does show the SSO enabled option so it seems that when requires username option is available Lock gets the username instead of the email for the purposes of checking for SSO against enabled enterprise connections, however, it should always pick from the email field as HRD is based on email addresses.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/pull/1278
