### ISSUE TITLE
iphone 6 : get message : "we're sorry, something went wrong when attempting to log in." when try to sing in "

### ISSUE THREAD

**Issue by ArielBar** [auth0/lock#1302]
when i am using my app (with embedded  auth0 lock) and trying to sign in with iPhone 6 - I keep getting the message  : "we're sorry, something went wrong when attempting to log in.".
this error is not shown when I am using iPhone 7 or other android device.

- angular 5 code snippet : 
lock = new Auth0Lock(this.configService.getConfiguration().auth0ClientID, this.configService.getConfiguration().auth0Domain, {
    oidcConformant: true,
    autofocus: true,
    autoclose: true,
    container: 'auth-container',
    rememberLastLogin: false,
    avatar: null,
    allowedConnections: ['Username-Password-Authentication'],
    auth: {
      redirectUrl: window.location.origin + '/home',
      responseType: 'id_token token',
      audience: this.configService.getConfiguration().auth0ClientAudience,
      redirect: false,
      sso: true,
      params: {
        scope: 'openid profile'
      }
    },
    languageDictionary: {
      title: "Please Login"
    },
    theme: {
      primaryColor: "#ceb202",
      authButtons: {
        "Username-Password-Authentication": {
          foregroundColor: "#000000"
        }
      }
    }
  });
- [ ] 
![printscreen](https://user-images.githubusercontent.com/29005175/37716146-7b9952ba-2d26-11e8-8623-f4003c977a8b.jpeg)

- [ ] 11.1.3
- [ ] safari/chrome & IOS 9.2.1

please help me!

**Comment by luisrudge** [comment]
Can you inspect the console and see the error?

**Comment by ArielBar** [comment]
i check it in I phone, how could i do inspect?

**Comment by luisrudge** [comment]
https://stackoverflow.com/questions/4478271/remote-console-log-on-ios-devices?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by ArielBar** [comment]
thank you!
i need mac for this or it work with PC?

**Comment by luisrudge** [comment]
only a mac can do that

**Comment by ArielBar** [comment]
:(  - unfortunately i don't have one. 
It worked before I upgraded to "auth0-lock": "^11.1.3"
can i return to "auth0-lock": "^10.21.1"?

**Comment by luisrudge** [comment]
Unfortunately, you can't. the v11 is a security update and everyone should migrate to that version before April 1st. I just tried with an iPhone 6s and it works without any issues. Can I test with your website/configuration?

**Comment by ArielBar** [comment]
yes!
can i send it by mail?

**Comment by luisrudge** [comment]
yeah, luis.rudge@auth0.com

**Comment by ArielBar** [comment]
check your mail
thank you!

**Comment by luisrudge** [comment]
![image](https://user-images.githubusercontent.com/941075/37725131-ffbcf620-2d10-11e8-8c7a-739e1386789d.png)

Did you read https://auth0.com/docs/cross-origin-authentication?
Also, the best and most secure way to handle authenticate is using our universal login page, did you try using that?

**Comment by luisrudge** [comment]
via email:
```
Hey, this web site does not allow http,
You got this message because of that.
Can you try with https?
```

Let's keep the conversation here:

I just tested with https://mymalcatest.azurewebsites.net/ and it worked just fine on an iphone 6s. Did you implement https://auth0.com/docs/cross-origin-authentication#create-a-cross-origin-verification-page? If that doesn't work, I suggest you use the universal login page.

**Comment by luisrudge** [comment]
I'm seeing this in the request:
![image](https://user-images.githubusercontent.com/941075/37730225-ea67ab82-2d1d-11e8-9ed0-eb1f63f44d17.png)

Do you have any rules enabled?

**Comment by ArielBar** [comment]
hey Luis,
i tried to set the  Cross-Origin Verification Fallback
but i got Forbidden
what i need to do?


2018-03-21 20:38 GMT+02:00 Luís Rudge <notifications@github.com>:

**Comment by luisrudge** [comment]
I still get the "Cannot read property 'toLowerCase' of undefined". Do you have any rules enabled in your tenant?

**Comment by ArielBar** [comment]
No, I just search this in my code- I saw this function in Auth0.js maybe it came form your code?

נשלח מה-iPhone שלי

‫ב-22 במרץ 2018, בשעה 16:14, ‏‏Luís Rudge ‏<notifications@github.com> כתב/ה:‬

**Comment by ArielBar** [comment]
sorry my fault, it came from another js code.
not from yours.
Anyway-about that:
i tried to set the  Cross-Origin Verification Fallback
but i got Forbidden
what i need to do?


2018-03-22 17:57 GMT+02:00 <relbr87@gmail.com>:

**Comment by luisrudge** [comment]
I'm still getting the same error. I don't get forbidden, I get a bad request.

**Comment by ArielBar** [comment]
I got the forbidden in Auth0 dashboard

נשלח מה-iPhone שלי

‫ב-22 במרץ 2018, בשעה 18:41, ‏‏Luís Rudge ‏<notifications@github.com> כתב/ה:‬

**Comment by luisrudge** [comment]
I can't see the cross auth fallback configured for this client: PtqUbVbFoqk4oIbLz6scfOzP06kr85e6 Are you sure it's all set up? Can you send me a print screen of the configuration?

**Comment by ArielBar** [comment]
I’m sure you cannot see the configuration because I cannot set it, I tried to do this

But I getting forbidden message!
נשלח מה-iPhone שלי

‫ב-22 במרץ 2018, בשעה 20:03, ‏‏Luís Rudge ‏<notifications@github.com> כתב/ה:‬

**Comment by luisrudge** [comment]
Ah, you get the forbidden message inside the dashboard. Sorry :) I have no idea what's going on. Try to logout and login again. Otherwise, reach out to our amazing suppor team at https://support.auth0.com

**Comment by ArielBar** [comment]
hey Luis,
I finally succeeded set the configuration of fallback page - but when i got
to the page -  i got :

can you help me please?

2018-03-22 20:32 GMT+02:00 Luís Rudge <notifications@github.com>:

**Comment by ArielBar** [comment]
the exception happens here:
                    t.source.postMessage({
                        type: "co_verifier_response",
                        response: {
                            verifier: r
                        }
                    }, t.origin)

2018-03-27 11:06 GMT+03:00 אריאל בר <relbr87@gmail.com>:

**Comment by luisrudge** [comment]
What error are you getting?

**Comment by ArielBar** [comment]
נשלח מה-iPhone שלי

‫ב-27 במרץ 2018, בשעה 15:33, ‏‏Luís Rudge ‏<notifications@github.com> כתב/ה:‬

**Comment by luisrudge** [comment]
There's nothing in your message

**Comment by ArielBar** [comment]
see image attchment

2018-03-27 16:13 GMT+03:00 Luís Rudge <notifications@github.com>:

**Comment by luisrudge** [comment]
There is no image.

**Comment by ArielBar** [comment]
cross-origin-authentication.js:127 Uncaught DOMException: Failed to execute
'postMessage' on 'Window': Invalid target origin 'undefined' in a call to
'postMessage'.
    at r.callback (https://cdn.auth0.com/js/auth0/9.0.0/auth0.min.js:9:14964
)
    at r.crossOriginVerification (https://cdn.auth0.com/js/
auth0/9.0.0/auth0.min.js:12:307)
    at https://mymalcatest.azurewebsites.net/callback-cross-auth.html:12:11

2018-03-27 16:50 GMT+03:00 Luís Rudge <notifications@github.com>:

**Comment by luisrudge** [comment]
Can you update auth0.js to the latest version (9.4.1) and see if it works?

**Comment by luisrudge** [comment]
did you change the password from the 'test' user? I can't login anymore:
![image](https://user-images.githubusercontent.com/941075/38036741-c2701d98-327d-11e8-99ca-61f66e4f7607.png)

**Comment by ArielBar** [comment]
no,
i loged in know with this user
test
test123

2018-03-28 17:47 GMT+03:00 Luís Rudge <notifications@github.com>:
