### ISSUE TITLE
Lock 11 and ie11 Failed cross origin authentication

### ISSUE THREAD

**Issue by jamesaa7** [auth0/lock#1305]
We recently upgraded to lock 11 (11.3.1), and while many of our users could log in ok, we did have a fairly large subset who could not.

The log errors were..
Type: Failed cross origin authentication
Description: Origin header required.

We have used Lock 10 for auth seamlessly for the last year, so we had to wind back to Lock 10 to get people accessing the site again, which obviously worked, no other changes needed. Am very conscious that Lock 10 is deprecated in a few days.

Full details of the error below - All users experiencing the error were using the same user agent.

{
"date": "2018-03-20T09:44:14.358Z",
"type": "fcoa",
"description": "Origin header required.",
"connection_id": "",
"ip": "***",
"user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko",
"details": {
"body": {
"client_id": "****",
"username": "****",
"password": "*****",
"realm": "Username-Password-Authentication",
"credential_type": "http://auth0.com/oauth/grant-type/password-realm"
},
"qs": {},
"connection": null,
"error": {
"message": "Origin header required.",
"oauthError": "Origin header required.",
"type": "invalid_request",
"uri": null
}
},
"hostname": "***.auth0.com",
"auth0_client": {
"name": "lock.js",
"version": "11.3.1",
"lib_version": "9.3.0"
},
"log_id": "***"
}

We were wondering if as it was CORS related if setting up the new custom domain feature would help, but on trying it seems that delegation is not support by it.

We are currently trying to replace using the delegation endpoint (for firebase) so we can get custom domains working and live to test, but given there is no proof either way ( https://community.auth0.com/t/origin-header-required-lock-11/10136/4 ) 

So i guess it can either be fixed by custom domains, or its a bug. Given the time frame to deprecation, i wanted to raise it while also trying out the custom domains update.

It obviously goes without saying that ie11 is still a huge browser especially in the enterprise, so is deprecating Lock10 in a few days wise?

Many thanks

**Comment by luisrudge** [comment]
Hi, the problem with IE11 and the "Safe Zones" configuration. There's more context here: https://stackoverflow.com/a/22450633
CNAMES solves this issue because the you don't need CORS anymore. I'll ping the docs team to add a section about this in the [docs](https://auth0.com/docs/cross-origin-authentication) page and the migration guide.

**Comment by jamesaa7** [comment]
Thank you so much for your quick response. We will push lock 11 back out tomorrow with custom domains running. Cheers

**Comment by jamesaa7** [comment]
Hmmmm we have updated to custom domains with lock 11 and those same users cannot log in again - back to Lock 10... any thoughts?

{
  "date": "2018-03-25T07:54:55.458Z",
  "type": "fcoa",
  "description": "Origin header required.",
  "connection_id": "",
  "ip": "*****",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko",
  "details": {
    "body": {
      "client_id": "*****",
      "username": "*****",
      "password": "*****",
      "realm": "Username-Password-Authentication",
      "credential_type": "http://auth0.com/oauth/grant-type/password-realm"
    },
    "qs": {},
    "connection": null,
    "error": {
      "message": "Origin header required.",
      "oauthError": "Origin header required.",
      "type": "invalid_request",
      "uri": null
    }
  },
  "hostname": "auth.mydomain.com",
  "auth0_client": {
    "name": "lock.js",
    "version": "11.4.0",
    "lib_version": "9.3.3"
  },
  "log_id": "****"
}

**Comment by luisrudge** [comment]
HI, I already contacted the backend team internally. Can you please create a new ticket and copy the ticket number? You can reference this issue in the ticket. Thanks!

**Comment by jamesaa7** [comment]
Thanks, yeah raised another ticket, no responses to either yet.
Cheers

**Comment by luisrudge** [comment]
Can you give me the ticket number?

**Comment by jamesaa7** [comment]
Yeah sure, here you go

#37862 – first one
#38110 – follow up

Thanks very much,
James

**Comment by luisrudge** [comment]
I just escalated this ticket internally.
