### ISSUE TITLE
Remember the last used passwordless email address / phone number

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1306]
Lock Passwordless used to provide the last used email address as the default value when doing a new authentication, but this is no longer present in Lock.
It would be convenient to have that feature available again in Lock, as most users will probably reuse the last email address/phone number.

**Comment by luisrudge** [comment]
We already have the `rememberLastLogin` option in the [ui customization section](https://github.com/auth0/lock#ui-options). This will show the "Last time you logged in with" screen. We're not storing the previous used email/phone number on localstorage.
