### ISSUE TITLE
Default password reset titles not displayed properly

### ISSUE THREAD

**Issue by yveswehrli** [auth0/lock#1315]
Lock version: 11.4.0
Browser: Safari 11.0.1 & Chrome 64.0.3282.119

Default password reset titles aren't displayed properly. I observed this behavior for German, French and Italien (maybe effects more languages). Before I upgrade to 11.4.0, I used version 10.24.2, there it worked fine.

Here some screenshots of the demo auth0 lock:
<img width="303" alt="bildschirmfoto 2018-03-26 um 09 20 08" src="https://user-images.githubusercontent.com/20794608/37892388-fe31e02a-30d7-11e8-8488-3ed7e722a9d3.png">
<img width="302" alt="bildschirmfoto 2018-03-26 um 09 20 23" src="https://user-images.githubusercontent.com/20794608/37892391-0203f346-30d8-11e8-970e-b91bba85b9ca.png">
<img width="301" alt="bildschirmfoto 2018-03-26 um 09 26 51" src="https://user-images.githubusercontent.com/20794608/37892398-0636ec16-30d8-11e8-95c1-5754d4fc96fa.png">

**Comment by luisrudge** [comment]
Are you talking about the ellipsis (...)?

**Comment by yveswehrli** [comment]
Yeah, it's cutting of the titles :/

**Comment by luisrudge** [comment]
I'll talk with the design team

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/pull/1728
