### ISSUE TITLE
Sign up failed event

### ISSUE THREAD

**Issue by yveswehrli** [auth0/lock#1316]
I need to track if a sign up failed, unfortunatly I only found the sign up submitted event. But that could be a successful or a failed sign up. Is there a way to distinguish between successful and failed sign ups? For login tracking I used `authorization_error`, but this event doesn't emit for registrations errors...

**Comment by luisrudge** [comment]
Do you want to send a PR with that? Here's where the code needs to be: https://github.com/auth0/lock/blob/master/src/connection/database/actions.js#L119

**Comment by yveswehrli** [comment]
I'll open a pull request

**Comment by luisrudge** [comment]
🎉

**Comment by yveswehrli** [comment]
Would you prefer a new event or emitting `authorization_error`?

**Comment by luisrudge** [comment]
a new event, since it's not an auth request yet

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/pull/1317

**Comment by yveswehrli** [comment]
@luisrudge Can you bump the version?

**Comment by luisrudge** [comment]
There's a few fixes I want to add. Release is probably happening today or tomorrow
