### ISSUE TITLE
Lock 10 to 11 upgrade - “generated token is too large”

### ISSUE THREAD

**Issue by zachguo** [auth0/lock#1318]
> richard.dowinton (Auth0 Employee)
> "I had a further look into it, and there is actually a problem that was introduced in Lock 11 that can result in the token being too large. Lock 11 performs a call to get SSO data that uses the scopes `openid profile email`."
https://community.auth0.com/t/lock-10-to-11-upgrade-generated-token-is-too-large/9778/6

It seems that it hasn't been fixed yet. So I repost it here.

**Comment by luisrudge** [comment]
Hi, this is a limitation in the backend, not a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com, create a ticket and send me the ticket number so I can escalate it internally.

**Comment by luisrudge** [comment]
Oh, sorry. You already created the community post. I'll ping the backend team.

**Comment by zachguo** [comment]
@luisrudge  Thank you. That post was created by another person, but I have the exactly same issue.
