### ISSUE TITLE
Safari login is not working

### ISSUE THREAD

**Issue by catamphetamine** [auth0/lock#1319]
Auth0 lock login works in Chrome, for instance, but doesn't work in Safari.
E.g. Safari 11.0.1.
The error appears in the console as soon as the "Login" button is clicked.

The errored URL is:

> https://[DOMAIN].auth0.com/authorize?client_id=8ByEbGpPAG0Kne2GPmaN6GACEdNajB5a&response_type=token&redirect_uri=http%3A%2F%2F192.168.1.103%3A3000%2Fauth0-callback&state=FXuXyiCLA93dPBRMudYMNfyoVe~op8U2&scope=openid%20email%20app_metadata&realm=Username-Password-Authentication&login_ticket=1px-A3dPB8iE96wcgDreXNsvqE-XMx8J&response_mode=web_message&prompt=none&auth0Client=eyJuYW1lIjoibG9jay5qcyIsInZlcnNpb24iOiIxMS40LjAiLCJsaWJfdmVyc2lvbiI6IjkuMy4zIn0%3D

The reason is:

> Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400)

The 400 code explanation is:

> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server could not understand the request due to invalid syntax.

The `/authorize` URL is being GET and the response is HTML for some reason (perhaps Safari doesn't send something like "'Content-Type': 'application/json'"? Or something like that, and Auth0 server decides to reply with HTML instead of JSON (or even does a completely different thing, like it used to do when `responseType` was not explicitly set to `token`).

Here are two screnshots.
First one is the indication of HTML response type:

<img width="1920" alt="2018-03-25 11 32 16" src="https://user-images.githubusercontent.com/477167/37977642-d9e19dee-31ec-11e8-8bad-980747432bcf.png">

The second one is the contents of the HTML response from `/authorize` endpoint:

<img width="1920" alt="2018-03-25 11 35 12" src="https://user-images.githubusercontent.com/477167/37977673-e529a886-31ec-11e8-98c5-34e5992b4c76.png">

Our lock config:

```js
{
  autoclose: true,
  theme: {
    logo: 'https://dliov3t26vp8o.cloudfront.net/cc-logo-trans.png',
    primaryColor: '#1DB64A'
  },
  languageDictionary: {
    emailInputPlaceholder: 'you@college.edu',
    title: 'College Consortium'
  },
  auth: {
    params: { scope: 'openid email app_metadata' },
    responseType: 'token',
    redirect: false,
    redirectUrl: typeof window === 'undefined' ? undefined : `${window.location.origin}/auth0-callback`
  }
};
```

**Comment by catamphetamine** [comment]
I can't find a way to view HTTP request headers in Safari dev tools: they're so different from Chrome ones.
But here's what "Copy cURL" gives:

> curl 'https://college-consortium-students-develop.auth0.com/authorize?client_id=8ByEbGpPAG0Kne2GPmaN6GACEdNajB5a&response_type=token&redirect_uri=http%3A%2F%2F192.168.1.103%3A3000%2Fauth0-callback&state=64vinzM-f_6yA93o3L7sGVtXJpcY~HGU&scope=openid%20email%20app_metadata&realm=Username-Password-Authentication&login_ticket=JHFYZLkePWMSIbjFhKCELZk7_O1Wh3yB&response_mode=web_message&prompt=none&auth0Client=eyJuYW1lIjoibG9jay5qcyIsInZlcnNpb24iOiIxMS40LjAiLCJsaWJfdmVyc2lvbiI6IjkuMy4zIn0%3D' \
-XGET \
-H 'Accept-Encoding: br, gzip, deflate' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5' \
-H 'Host: college-consortium-students-develop.auth0.com' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Connection: keep-alive' \
-H 'Accept-Language: ru' \
-H 'Referer: http://192.168.1.103:3000/'

If that's all headers then Content-Type is definitely not in the list, and I guess it should be.

**Comment by catamphetamine** [comment]
So yeah, compared to another XHR on the same page, the `/authorize` one doesn't set `Content-Type` header. I guess that could be the issue.

The another XHR, for comparison:
> 
curl 'https://ht9h1jpye0.execute-api.us-east-1.amazonaws.com/master/institutions/28' \
-XGET \
-H 'Referer: https://www.collegeconsortium.org/' \
-H *'Content-Type: application/json' \*
-H 'Origin: https://www.collegeconsortium.org' \
-H 'Host: ht9h1jpye0.execute-api.us-east-1.amazonaws.com' \
-H 'Accept: */*' \
-H 'Connection: keep-alive' \
-H 'Accept-Language: ru' \
-H 'Accept-Encoding: br, gzip, deflate' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5'

**Comment by catamphetamine** [comment]
Funny thing: when in Safari Dev Tools I was looking at that HTTP request with status 400 and clicked "Open in New Tab" on it - then I saw the error page HTML (which is expected), and after that the next login attempts no longer fail.
I don't know what's the deal here - seems like opening this `/authorize` URL in a new tab instead of an XHR request somehow does some kind of a magic trick and the bug is no longer reproducible.

So I had the website deployed in 2 different places and I checked 2 times: yes, the trick works for both deployments.
Which still doesn't resolve the issue.
And it kinda strips one from the ability of debugging it further.

Dunno.

**Comment by luisrudge** [comment]
did you add your origin to the allowed web origins?

**Comment by catamphetamine** [comment]
It was there from the start.

**Comment by catamphetamine** [comment]
So, does this library use `auth0` internally and should I create an issue in their repo?
I mean, it wouldn't hurt to set `Content-Type` for that `/authorize` request, would it?

**Comment by catamphetamine** [comment]
Seems like we're unable to reproduce this bug as of now, due to the "Open in New Tab" magic trick.
Not sure if I should leave this issue open.
Perhaps let it calm down, let the session expire, etc.
And then we'll see if it resurfaces.

**Comment by luisrudge** [comment]
that specific request (with `response_mode=web_message`) expects an html back, so that's not the issue. I'm investigating.

**Comment by catamphetamine** [comment]
I see.
Well, the only weird thing here is the 400 Response code I guess.
If someone could track it to where the Auth0 backend responds with 400 then there would be clues.
If it logged somehow on the server more details about what exactly didn't it like and what exactly was "bad" in that request.
Ok, won't be distracting you.

**Comment by luisrudge** [comment]
I find a log but I think it's not related to your error. When I tried to access your URL, the `login_ticket` was already used, so my error was `Unknown login ticket`, which is expected.

**Comment by luisrudge** [comment]
I just ran our [example page](https://github.com/auth0/lock/blob/master/support/index.html#L115) adding your configuration and it works fine on safari.

```js
const defaultOptions = {
      allowShowPassword: true,
      usernameStyle: 'email',
      defaultDatabaseConnection: 'acme',
      prefill: {
        email: 'johnfoo@gmail.com'
      },
      passwordlessMethod: 'code',
      allowedConnections: ['email', 'acme', 'twitter'],
      auth: {
          params: { scope: 'openid email app_metadata' },
          responseType: 'token',
          redirect: false,
          redirectUrl: `${window.location.origin}/support/`
      }
    };
```

Let me know if this happens again.

**Comment by catamphetamine** [comment]
Ok, thx
