### ISSUE TITLE
Confusing button name

### ISSUE THREAD

**Issue by mbeckenbach** [auth0/lock#132]
The button text "all" is confusing for some users. 

When you were already logged in before and see the "Last time you signed in using..." screen it should not say "Show all". Instead something like "Use another account to log in" would be better at this screen.

German translation would be "Mit einem anderen Account anmelden".

**Comment by felixinx** [comment]
Try to make a pull request in the https://github.com/auth0/lock/blob/master/i18n/en.json file. You can also make another pull request for german.
I recommand ```Use another social provider to log in```.

**Comment by cristiandouce** [comment]
How about

1. `Show all providers`
2. `See all providers`
3. `Use a different provider`
4. `Use other account`

Let's play to get it shorter in text and as meaninful as possible! :dancers:

**Comment by felixinx** [comment]
`Use a different provider` sounds good!

I recommend `Utuliser un autre service` for `fr-FR`.

**Comment by mbeckenbach** [comment]
Use a different provider sounds very technical. I think more end users will understand use a different account.

**Comment by jfromaniello** [comment]
I agree with @mbeckenbach , "provider" is too technical.

Maybe 4, or "Use a different account"

**Comment by cristiandouce** [comment]
So we agreed on `account` over `provider`. Not the contest is between 4. and 5. Or another good option! :grinning:

**Comment by mbeckenbach** [comment]
5 makes it more clear that you log in as another person in my opinion
