### ISSUE TITLE
Introduce a hidden custom field

### ISSUE THREAD

**Issue by DimitriLubenski** [auth0/lock#1324]
Due to the fact that rules are not executed during sign up but it is often required to add some additional user_metadata fields to control e.g. email translation or other post sign up processes there should be support for hidden sign up fields which can be initialized with e.g. browser language our other data available in the browser. Alternatively there could be an event processed before sending the data to the backend which can help to add some additional metadata.

Here some details on a similar request: https://community.auth0.com/t/can-i-add-a-fixed-value-to-user-metadata-when-a-user-does-self-sign-up/7901 

Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ ] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [11.5.1] Lock version
- [ ] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by luisrudge** [comment]
I can see this being useful. Do you want to send a PR with that?

**Comment by DimitriLubenski** [comment]
Would you like me to put it here as a use story? Or there is another place for feature requests?

**Comment by luisrudge** [comment]
I'm going to be honest with you: if you send us a pull request with the implementation, I can review the pull request and help you get this done. If you just want to submit a feature request, I'll add this to our backlog but it can take a while before we even consider start working on this, because we have a lot of other priorities right now.

**Comment by DimitriLubenski** [comment]
Unfortunately, JS is not my native tongue 😊. I am more Java-savvy..

Let me though explain the use case, so might be you have an idea for a workaround:
1.	The user performs a sign-up
2.	The user’s browser language is added to the user_metadata using e.g. a hidden field or using an event like 'signup submit' which offers the submit model for a modification before submitting it to the backend. 
3.	User gets the welcome e-mail in the right language (this part works now using the tamplate language)

The feature can be added in the “custom_input.js” (type='hidden'). The available prefill paraemter is sufficient to set the inital value.
https://github.com/auth0/lock/blob/master/src/field/custom_input.jsx

Is there any other option to assure the user to get mails in a right language?

**Comment by luisrudge** [comment]
No problem! I'll add this to our backlog. There is no ETA for this. For now, you can use a regular text field and use css to hide the field.

**Comment by camel113** [comment]
I use the _Hosted Pages_ with Auth0Lock and it could be very useful to have a input type hidden to send the user language without asking the user to choose.
It is very tricky to hide a field with CSS when you use _Hosted Pages_.

**Comment by DimitriLubenski** [comment]
The CSS is actually not a big deal. For a custom field language the css is:

```
/* hide the language field */
.auth0-lock-input-language {
    display: none;
}

```
Though for sure a hidden field would be more straight forward
