### ISSUE TITLE
Not able to make a select field non mandatory

### ISSUE THREAD

**Issue by RaghavendraJha** [auth0/lock#1327]
I am not able to make country code non mandatory.Even by using validator property:
{
      type: "select",
      name: "countrycode",
      placeholder: "Country Code",
      options: [
		{value:"+213", label: "Algeria (+213)"},
		{value:"+376", label: "Andorra (+376)"}
      ],
	  validator: function(countrycode) {
        return {
          valid: true
        };
      }
}

![image](https://user-images.githubusercontent.com/26899761/38170217-c493378c-359c-11e8-83c2-60158cadf84c.png)

**Comment by luisrudge** [comment]
Select custom fields can't have validator functions, since we assume all options are valid: https://github.com/auth0/lock/blob/master/src/connection/database/index.js#L153

The behavior you mentioned is fairly consistent with the regular input:

```js
var options = {
  additionalSignUpFields: [{
    name: "address",
    placeholder: "enter your address",
    validator: () => { valid: true }
  }, {
    type: "select",
    name: "countrycode",
    placeholder: "Country Code",
    options: [
      { value: "+213", label: "Algeria (+213)" },
      { value: "+376", label: "Andorra (+376)" }
    ]
  }]
};
```

**Comment by irving017** [comment]
how can i obtain the info selected in the input so i can use it to validate another textfield?
