### ISSUE TITLE
Auth0 Lock v11.0.2 prevents login on Safari in Polymer app

### ISSUE THREAD

**Issue by esonmez** [auth0/lock#1335]
Browser: Safari 11.0.2
OS: Mac OS X 10.13.2
Lock Version: 11.4.0

Upgrading to Lock 11.4.0 from 10.24.3 broke our login on Safari. We use Auth0 Lock within our Polymer app. When attempting to login from Safari, we get the following error:
```
TypeError: undefined is not an object (evaluating 's.get')
```

This causes the “login” button on the lock widget to keep spinning, preventing our users from logging in on Safari.

We investigated this issue by first running Auth0 Lock in a separate HTML file and confirmed that the lock widget works properly on Safari when not loaded within a Polymer app:
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Login</title>
  <base href="/">
  <script src="https://cdn.auth0.com/js/lock/11.5.2/lock.min.js"></script>
</head>
<body>
  <script>
    var lock = new Auth0Lock(
      'CLIENT_ID',
      'DOMAIN',
      {
        auth: {
          responseType: 'token id_token',
          audience: 'AUDIENT',
          redirectUrl: 'REDIRECT_URI',
        },
      }
    );

    lock.show();
  </script>
</body>
</html>
```
Running the lock widget within our Polymer app throws the TypeError and prevents login (loading spinner spins indefinitely):

![screen shot 2018-04-06 at 3 56 28 pm](https://user-images.githubusercontent.com/5974930/38447698-e5c966ae-39b3-11e8-8e44-da78493b2fbb.JPG)

**Comment by luisrudge** [comment]
Did you find where this is failing inside the app? Like a stack trace or something? Otherwise, please build a simple project using lock inside a polymer app with clear steps to run it so we can investigate.

**Comment by esonmez** [comment]
![screen shot 2018-04-06 at 7 49 13 pm](https://user-images.githubusercontent.com/5974930/38450561-dcffc79a-39d4-11e8-9eb6-6f84b621965d.JPG)

**Comment by luisrudge** [comment]
Yeah.. unfortunately, there's not a single Lock line in there. Can you please create a simple repro project so I can take a look?
