### ISSUE TITLE
Errors in Chrome console when typing the e-mail during lock.show()

### ISSUE THREAD

**Issue by danielmcardoso** [auth0/lock#1340]
I am testing lock with angular. Very simple setup:
`lock: Auth0Lock = new Auth0Lock(environment.auth0.clientId, environment.auth0.domain, {});`   

After running `lock.show()`, in the login screen, while I'm typing an e-mail, error messages like the following are shown in Chrome console and the avatar is not shown nor loaded.
`GET https://secure.gravatar.com/avatar/0156da3d04c78052781a8a4069cee2e6?d=404&s=160 404 ()`
`GET https://secure.gravatar.com/0156da3d04c78052781a8a4069cee2e6.json?callback=__jp0 net::ERR_ABORTED`

Am I missing something?
Using lock 11.5.2 (current version).

**Comment by luisrudge** [comment]
We try to match the login to available gravatars. This is made with HTTP requests to the gravatar service. They return 404 if the image is not available. You can disable this with `avatar: null` or use your own avatar provider: https://github.com/auth0/lock#avatar-provider

**Comment by danielmcardoso** [comment]
@luisrudge, sorry, but I am still unsure about this behavior. From what I could understand, lock generates a gravatar url from the e-mail, right? The auth0 User has a read-only `picture` attribute  and its content is a gravatar url as well. If I get this url in the `user.picture` and directly / manually access it using Chrome, the avatar is downloaded and shown as expected. Shouldn't I expect that lock will use / generate this same url if I haven't chosen to use my own avatar provider? Why is lock generating / using a different (and invalid) link that gravatar does not recognize if auth0 could generate a valid gravatar url (`user.picture`)?

**Comment by luisrudge** [comment]
Because we try to fetch that on every key press (debounced and only when it's a valid email): https://github.com/auth0/lock/blob/1424ce0409f64346951836570aa33e2b2a56dcca/src/field/email/email_pane.jsx#L21

So you might see this:
luis.rudge@test.co > send request
luis.rudge@test.com.b > send request
luis.rudge@test.com.br > send request

**Comment by danielmcardoso** [comment]
Sorry. I missed explaining that the error still occurs when I type the full matching email address. This can be verified by starting with an empty email field and pasting the matching email from the clipboard. I get the same two error messages and no avatar is displayed. Am I missing something?

**Comment by luisrudge** [comment]
what email?

**Comment by danielmcardoso** [comment]
Let's say johnfoo@gmail.com is a valid User `email`. Copy johnfoo@gmail.com to clipboard, open the lock login window (`lock.show()`), paste the email from clipboard in the email field. The error messages will appear in the console and no avatar will be shown (even though the email matches `user.email`).

**Comment by luisrudge** [comment]
johnfoo@gmail.com does not have a picture in the gravatar service, that's why you get the error. if you try with luis.rudge@auth0.com, you'll see the gravatar. 
![image](https://user-images.githubusercontent.com/941075/38581448-4e83f97a-3ce3-11e8-99c7-592ab07fab27.png)

**Comment by danielmcardoso** [comment]
oh, I see! I was expecting lock to behave the same as the autogenerated gravatar url in `user.picture`, with the initials when there is no picture (for example, https://i1.wp.com/cdn.auth0.com/avatars/jf.png), but it would also mean that it would need to know that the email is a valid user email for the app. Ok. Got it! Thank you for your patience.

**Comment by Kipriz** [comment]
@luisrudge is there any way not to throw an error, but just info message that avatar is not available?
Most of users have no gravatar and all of them see these 2 js errors. The users (and the product owners) worries about the error in browser's console.
I'd like to keep gravatar look up, but remove the errors from the console.

**Comment by luisrudge** [comment]
@Kipriz they're not javascript errors, they're HTTP request errors. Gravatar returns a 404 when there's no gravatar available for that e-mail. There's not much we can do. You can either disable avatar or ignore those errors.
