### ISSUE TITLE
Different auth result object for RS256 vs HS256

### ISSUE THREAD

**Issue by murphyke** [auth0/lock#1343]
Why is `idTokenPayload` undefined in the result object when JWTs are signed using RS256? It *is* included when JWTs are signed with HS256. I'm using embedded Lock 11.5.2. I realize this is probably not a Lock phenomenon per se, but that's what I'm using. Thanks!

**Comment by murphyke** [comment]
```
{
      responseType: 'token',
      redirectUri: window.location.protocol + '//' + window.location.host + '/login',
      sso: true,
      params: {
        scope: 'openid email name'
      }
}
```

Results:

HS256 - idToken and idTokenPayload populated
RS256, non-OIDC-conformant - idToken and idTokenPayload populated
RS256, OIDC-conformant - idToken and idTokenPayload `null`

Hmm, now that I'm looking at it, I notice that `responseType` doesn't include `id_token`. I think I was misled by the fact that `id_token` wasn't necessary to get an HS256 token.

If `id_token` is included in `responseType`, the idToken and idTokenPayload are populated, as expected.

- - -

One other funny thing is that there are a lot more properties on the `idTokenPayload` for HS256 tokens. E.g. `given_name`, etc only occur on HS256 tokens, not RS256 tokens (whether OIDC-conformant or not). It seems odd for a signature algorithm to be associated with such feature differences.

**Comment by luisrudge** [comment]
non-oidc applications always send id_tokens and they can be HS256 or RS256. oidc applications will only use RS256. oidc applications will also follow the oidc spec with regards to scope and returned properties in the /userinfo call or id_token. There's a lot of information about the differences between non-oidc and oidc applications here: https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

**Comment by murphyke** [comment]
Thanks; I will adapt to this. Naively I would expect non-OIDC RS256 tokens to work the same as (non-OIDC) HS256 tokens, but it's no big deal.
