### ISSUE TITLE
no loading indicator after clicking remembered login

### ISSUE THREAD

**Issue by zachguo** [auth0/lock#1345]
Lock v11.3.0 - v11.5.2.
Latest Chrome.

Repro sandbox: https://codesandbox.io/s/n9lv0781wp (v11.5.2)

Steps:
- login once (there is a loading indicator/spinner after clicking login button)
- refresh page
- click remembered login (no loading indicator/spinner)

**Comment by luisrudge** [comment]
That's expected. You can subscribe to the 'authenticated' event and get the renewed tokens

**Comment by zachguo** [comment]
Isn't it bad UX? It usually takes ~2 seconds before the popup auto-closes.
![](http://g.recordit.co/5E4n2lAUQw.gif)

**Comment by luisrudge** [comment]
Absolutely! I just did a quick read and thought you were talking about the lack of redirect. But you're right, we should add the loading indicator there.
