### ISSUE TITLE
Long passwordless authentication timeout - token expires after one day instead of timeout set in Auth0 config

### ISSUE THREAD

**Issue by de-code** [auth0/lock#1347]
Hi,

I am trying to keep the password less session valid for 30 days.
I set the timeout on the _Authentication API_ and the Application's _JWT_ to 30 days (2592000 seconds). The access token times out within a day though. Which is confirmed by the _expiresIn_ field on the authentication result being _86400_.

The docs for an older version make reference to the [refresh token](https://auth0.com/docs/libraries/lock/v9/using-a-refresh-token). Which seem to be discouraged and not mentioned in the new version.

Expected behaviour:
Access token should expire after _2592000_ seconds (as per timeout set in Authentication API configuration).

I am using _11.5.2_ of _auth0-lock_.

The code looks more or less like:

```javascript
const lock = new Auth0LockPasswordless(
  client_id, domain, {
    passwordlessMethod: "link"
  }
);

// when showing login
lock.show();

// after initial login and resuming using stored access token (to get the email)
lock.getUserInfo(access_token, callback);
```

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Token expiration is managed entirely by the server. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by de-code** [comment]
Well, I would think it touches the SDK as the first entry point because it mentioned the refresh token which is longer there. Could you please clarify that refresh tokens should no longer be used with the Lock API?

**Comment by luisrudge** [comment]
You can use `checkSession` to get new tokens: https://github.com/auth0/lock#checksessionparams-callback
