### ISSUE TITLE
Unexpected "Sign Up" title in v11.4

### ISSUE THREAD

**Issue by tazmaniax** [auth0/lock#1349]
Updating the Lock version from v11.3 to v11.4 causes an additional "Sign Up" title to appear when switching from the "Log In" tab to the "Sign Up" tab. In our situation we've overridden the languageDictionary.title to be a blank string so not expecting any title to appear. This feels like a bug has been introduced, which is why I'm raising here, but maybe not? I'm not sure why a tab focus would impact the main title. This could be related to the fix for #1286 . 

<img width="319" alt="screenshot 2018-04-17 19 09 59" src="https://user-images.githubusercontent.com/1079943/38888922-f5bf9f50-4274-11e8-95b3-0f65ef5bb292.png">

<img width="317" alt="screenshot 2018-04-17 19 09 50" src="https://user-images.githubusercontent.com/1079943/38888948-0af78568-4275-11e8-9c1c-d03aafa55ba5.png">

**Comment by luisrudge** [comment]
You'll need to override the `signupTitle` dictionary entry to be a blank screen as well. We have only 4 screen titles if you want to override all of them:

`forgotPasswordTitle`, `signupTitle`, `mfaLoginTitle`, `title`
