### ISSUE TITLE
Can show title in lock fr-FR

### ISSUE THREAD

**Issue by felixinx** [auth0/lock#135]
Using WP Extension and Lock 7.1.5.

In the english form, default, we have the `title` option return and show up. In another language (if we configure with `dict`), is `NULL` and this cannot be change (if we change, we will get `NULL`). So we get `Connexion`(fr-FR) or `Iniciar sesión` (es) but not the our choice. The WP extension only show the div.  This should be fix.
*Edit - Screenshot*
In `fr-FR`;
![auth0 fr-fr](https://cloud.githubusercontent.com/assets/8009156/6491001/53fa9adc-c278-11e4-960d-f32d4691c03e.png)
In `es`;
![auth0 es](https://cloud.githubusercontent.com/assets/8009156/6491000/53f98f8e-c278-11e4-9a92-34317fe7ce1e.png)
And finally in default (`en`);
![auth0 en](https://cloud.githubusercontent.com/assets/8009156/6490999/53f95b0e-c278-11e4-9f3a-482b7f49b0b1.png)

**Comment by cristiandouce** [comment]
Could you confirm what version of the plugin are you using?

Also if you could print how you are initializing the lock, that would be helpful too!

Thanks!

**Comment by felixinx** [comment]
I use the latest WordPress Plugin from the WP store https://wordpress.org/plugins/auth0/ (todays version) and CDN 7.1.5

**Comment by felixinx** [comment]
I just edit the issue with screenshot.

**Comment by cristiandouce** [comment]
Closing in favor of auth0/lock#102

**Comment by felixinx** [comment]
Ok, Thanks
