### ISSUE TITLE
Lock fetches Gravatar images on option avatar set to null

### ISSUE THREAD

**Issue by citricacid-pl** [auth0/lock#1351]
I would like that Lock is not fetching and displaying avatar icons from Gravatar. Thus I have set `avatar: null` in lock options as [said in documentation](https://auth0.com/docs/libraries/lock/v11/configuration#avatar-object-). 

However Lock is still trying to get avatars from Gravatar.

![](https://user-images.githubusercontent.com/745572/38985942-2b5806fa-43cb-11e8-81fc-0ac5ff01a480.png)

Code snippet of the configuration:

```
        lock.show({
          initialScreen: this.data.initialScreen || 'signUp',
          language:      getAuth0Language(this.language),
          avatar:        null,

          // ...
        });
```

- Lock version: 11.5.1
- Browser & OS: Chrome, OSX

**Comment by luisrudge** [comment]
`avatar` can't be overwritten in the `show` method. You have to set that in the constructor.

**Comment by citricacid-pl** [comment]
🤦‍♂️ True indeed. Thank you and sorry.
