### ISSUE TITLE
Convert to Components

### ISSUE THREAD

**Issue by jshado1** [auth0/lock#1353]
There should be a set of React components instead of a own do-it-yourself application with its own Redux store, which Redux explicitly denounces. Integrating this into a react application is a nightmare that requires violating countless best practices.

```jsx
// …
import { LockLogin } from 'auth0lock';

import logo from '…';

const Login = ({
    audience,
    // …
    ...rest,
}) => (
    {/* … */}

        <LockLogin
            allowShowPassword
            logo={logo}
            socialButtonSize="small"
            {...lockConfig}
        />

    {/* … */}
);
```
```jsx
// …
import { LockSignup } from 'auth0lock';

import logo from '…';

const Singup = ({
    audience,
    // …
    ...rest,
}) => (
    {/* … */}

        <LockSignup
            allowShowPassword
            logo={logo}
            socialButtonSize="small"
            {...lockConfig}
        />

    {/* … */}
);
```

Items like `avatar` and `title` should be excluded when not specified, as is the react best/standard practice.

Ideally, it would also allow the implementer to provide fields for Lock to use.

**Comment by luisrudge** [comment]
That might be something we pursue at some point, but there's no plans to do that at this time. Why do you think it's a nightmare to integrate Lock with a react app? Our samples do it and looks pretty straight forward: https://github.com/auth0-samples/auth0-react-samples/blob/embedded-login/01-Embedded-Login/src/Auth/Auth.js

It's important to understand that we don't pitch auth0-lock as being a react component for Auth0 integration. auth0-lock is an all-inclusive widget that integrates with Auth0 and its features. It just happens that we built it with react, but we could've used preact, angular, vue or vanilla js instead.
