### ISSUE TITLE
Double checkbox for Terms & Conditions

### ISSUE THREAD

**Issue by sun2rise** [auth0/lock#1358]
Thank you for using Lock! Please read the following before creating a new issue.

- [x] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Is there a way to have a double checkbox to check for terms & conditions? I am asking this because in Italy we need to have a checkbox for general terms and conditions and another one for other typs of terms.
The second checkbox should be just like the first and it should contain a link, again, like the first one

Thanks

**Comment by luisrudge** [comment]
No. We only support one checkbox.
