### ISSUE TITLE
Lock returning app_metadata field 

### ISSUE THREAD

**Issue by tyvdh** [auth0/lock#1359]
- [x] Code snippet or sample project that reproduces the bug
- [x] Lock version `https://cdn.auth0.com/js/lock/11.6.0/lock.min.js`
- [x] Browser & OS `Version 65.0.3325.181 (Official Build) (64-bit) & mac OS High Sierra Version 10.13.4`

```js
var lock = new Auth0LockPasswordless(
  'Dm0zXin0aDaSV2pTGGHmFdJCXakF2rFf',
  'colorglyph.auth0.com',
  {
    passwordlessMethod: 'code',
    auth: {
      redirectUrl: 'http://localhost:8000',
      responseType: 'token id_token',
      params: {
        scope: 'openid profile email picture user_metadata'
      }
    }
  }
);
```

I'm not requesting the app_metadata scope and yet when I authenticate the request that field is returned along with all the data inside it from the `authResult.idTokenPayload` which I don't want sent. Seems weird to me and I'm unsure how to resolve it. Why is the id_token returning more than I'm asking for?

**Comment by luisrudge** [comment]
It depends on the type of client you have (OIDC or NON-OIDC). This doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your questions.
