### ISSUE TITLE
Authenticated user is returning app_metadata fields concatenated in root object

### ISSUE THREAD

**Issue by tyvdh** [auth0/lock#1360]
- [x] Code snippet or sample project that reproduces the bug
- [x] Lock version `https://cdn.auth0.com/js/lock/11.6.0/lock.min.js`
- [x] Browser & OS `Version 65.0.3325.181 (Official Build) (64-bit) & mac OS High Sierra Version 10.13.4`

When returning the `app_metadata` field it would seem that attributes inside it are being concatenated to the root user object. This means if I removing something from the `app_metadata` field via a Rule the attribute will still show up in the user object.

```js
var lock = new Auth0LockPasswordless(
  'Dm0zXin0aDaSV2pTGGHmFdJCXakF2rFf',
  'colorglyph.auth0.com',
  {
    passwordlessMethod: 'code',
    auth: {
      redirectUrl: 'http://localhost:8000',
      responseType: 'token id_token',
      params: {
        scope: 'openid profile email picture user_metadata app_metadata'
      }
    }
  }
);
```

```js
// Some arbitrary Rule
function(user, context, callback) {
  delete user.app_metadata.secret;
  callback(null, user, context);
}
```

```json
// Response on client
{
  ...
  "app_metadata": {
    "fine_value": "hello",
    "other_value": "nice"
  },
  "secret": "why-is-this-here",
  ...
}
```

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK, since we don't have control on what the server sends back from the authentication request. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
