### ISSUE TITLE
JS Console Error - 'unable to get property 'protocol' of undefined or null reference' on Win8-IE10 and Win 8.1-IE11

### ISSUE THREAD

**Issue by Saurabh-vs** [auth0/lock#1361]
Hey.
We are getting a JS error 'unable to get property 'protocol' of undefined or null reference'

Browser - IE 10 (Win 8) and IE 11 (Win 8.1)

This happened on upgrading Auth0 Lock from 10.9.1 to 11.3.0 and Auth0 from 8.0.4 to 9.3.3!

![screen shot 2018-03-22 at 8 34 24 pm](https://user-images.githubusercontent.com/16660669/39465081-040f31cc-4d3f-11e8-9655-ac06bce91391.png)

On using debugger we found that Line no. 4171 in lock.min.js is the cause. Following code snippet suggests the same, where e is undefined:

`function d(t) {
        if(t) {
                var e = g(t), n = e.protocol + "//" + e.hostname;
                return e.port && (n += ":" + e.port) , n;
        }
 }`

Also I am attaching lock.min.js (renamed as lock.min.txt here) copied from Win 8.1 IE 11 browser debugger. 
[lock.min.txt](https://github.com/auth0/lock/files/1963225/lock.min.txt)

This is how we have included the libraries.
<script src="https://cdn.auth0.com/js/lock/11.3.0/lock.min.js"></script>
<script src="https://cdn.auth0.com/js/auth0/9.3.3/auth0.min.js"></script>

**Comment by luisrudge** [comment]
Try with this files instead:

https://cdn.auth0.com/js/lock/11.6/lock.js
https://cdn.auth0.com/js/auth0/9.5/auth0.js

If it works, just swap those files for the minified files:
https://cdn.auth0.com/js/lock/11.6/lock.min.js
https://cdn.auth0.com/js/auth0/9.5/auth0.min.js

If it doesn't work, the stacktrace will be more helpful with the unminified files, so please paste the code snippet which is failing.

**Comment by Saurabh-vs** [comment]
Hey @luisrudge, thanks for the reply.

I followed your suggestion and used lock.js version 11.6 and auth0.js version 9.5. It doesn't work. Here is the code snippet that fails.

`function getOriginFromUrl(url) {
  if (!url) {
    return undefined;
  }
  var parsed = getLocationFromUrl(url);
  var origin = parsed.protocol + '//' + parsed.hostname;
  if (parsed.port) {
    origin += ':' + parsed.port;
  }
  return origin;
}`

Code at line no. 7438 of lock.js breaks. Here parsed is null.
`var origin = parsed.protocol + '//' + parsed.hostname;`

Also please find attached the screenshot showing call stack and exact position of js error:

![js-error-lock-11 6](https://user-images.githubusercontent.com/16660669/39621528-b4922a58-4fac-11e8-86c2-229eed692fe7.png)

**Comment by luisrudge** [comment]
Thanks, that was very helpful. Can you do one more test? [This](https://github.com/auth0/auth0.js/blob/b93797fea60cd270f81bad66cc67c4265fcef73b/src/helper/object.js#L120) is the function that is failing. Can you paste the browser url when this method fails? Also, please run this inside your console and show me the result:

```
var match = href.match(
    /^(https?:)\/\/(([^:/?#]*)(?::([0-9]+))?)([/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/
  );
console.log(match);
```

**Comment by luisrudge** [comment]
how are you instantiating lock? I mean, what options are you using? The issue here is the `redirectUri` option.

**Comment by Saurabh-vs** [comment]
@luisrudge 
This is how we are instantiating lock. But this fails just on Win 8.1 - IE 11 and Win 8 - IE 10.
` var lockOptions = {
            container : 'auth0-popup-container',
            avatar: null,
            allowLogin: false,
            allowSignup: false,
            initialScreen: 'forgotPassword',
            theme : {
                logo: HYFY_ICON,
                primaryColor : "#e91e63"
            },
            languageDictionary : {
                title: 'Reset Password'
            }
        };
var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, lockOptions);`

**Comment by luisrudge** [comment]
Thanks for your patience and help finding this issue. I just submitted a fix which will be available in the next version. While this isn't released, you can just set the `auth.redirectUrl` yourself and it will work just fine 🎉

**Comment by Saurabh-vs** [comment]
Thanks @luisrudge for all your help. Will try setting `auth.redirectUrl` as per your suggestion and would let you know.
