### ISSUE TITLE
`container` option does not support shadowDom

### ISSUE THREAD

**Issue by bennypowers** [auth0/lock#1369]
Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [x] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Lock does not allow passing a container element which is obscured behind a shadowDom boundary.

```js
const show = () => {
  const lock = new Auth0LockPasswordless(clientID, domain, { auth, theme });
  lock.show(clientID, domain, {
    container: document.getElementById('app').shadowRoot.getElementById('login')
  });
};
```

Instead, it only accepts a string for id in the light dom.

https://github.com/auth0/lock/blob/b66b79917d66b76184e835fa760c80f40ee4aebb/src/ui/box.js#L8

This property should check the type passed, and if it's an element, accept it as is.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by bennypowers** [comment]
From a very cursory test it looks like it's working

https://glitch.com/edit/#!/useful-direction?path=script.js:20:4

**Comment by luisrudge** [comment]
I don't think so. container is a property that you have to pass in the constructor: https://glitch.com/~magical-polo

**Comment by bennypowers** [comment]
Confirmed this bug still exists
