### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by KayHS** [auth0/lock#1371]
I upgraded my application from Angular 5 to Angular 6 and now im getting the following error.

- [X] Code snippet or sample project that reproduces the bug

> uncaught ReferenceError: global is not defined
>     at Object../node_modules/auth0-lock/lib/utils/cdn_utils.js (cdn_utils.js:13)

- [X] Lock version
```
"angular2-jwt": "^0.2.3",
"auth0-js": "^9.5.1",
"auth0-lock": "^11.6.1",
```
- [X] Browser & OS
Chrome / Firefox / Linux

**Comment by luisrudge** [comment]
Hi. This is an angular issue. More context: https://github.com/auth0/auth0.js/issues/753
