### ISSUE TITLE
getSSOData of undefined

### ISSUE THREAD

**Issue by Atiqullah-Naemi** [auth0/lock#1372]
I am upgrading from lock v7 to lock v11 in angular js application and getting this error in the console:
                 AuthCtrl.js:192 Uncaught TypeError: Cannot read property 'getSSOData' of undefined
is there any replacement for getSSOData in v11?
any solutions? how can I fix it?

Thanks

**Comment by luisrudge** [comment]
lock doesn't have the `getSSOData` method. [auth0.js does](https://auth0.github.io/auth0.js/global.html#getSSOData)
