### ISSUE TITLE
Setting rememberLastLogin to false still shows the "Last time you logged in as..." dialogue

### ISSUE THREAD

**Issue by oneillsp96** [auth0/lock#1378]
Using Lock V11....when user logs out, they are presented with "Last time you logged in as..." dialogue, and don't have to re-enter email and password.  This seems like a pretty serious security issue. Setting rememberLastLogin to false in the hosted page does not prevent this behavior.

**Comment by oneillsp96** [comment]
Possibl

**Comment by luisrudge** [comment]
how are you logging out?

**Comment by oneillsp96** [comment]
Closed as I found out this was a mistake on my part.  I didn't realize that rememberLastLogin  was set to !prompt by default when a new hosted login page is created.  So I was assigning it to false, and it was being reassigned to !prompt farther down in the Lock code.
