### ISSUE TITLE
Update all submits through auth0.js client

### ISSUE THREAD

**Issue by cristiandouce** [auth0/lock#138]
... to something like this:

```js
var req = widget.$auth0.changePassword(options, onresetpassword);

this.widget.once('hidden', cancelrequest);
function cancelrequest() {
 req.cancel(); 
}

function onresetpassword(err) {
  // same content as before
  this.widget.off('hidden', cancelrequest);
}
```

so we avoid calling the callbacks when the widget has been force to be hidden or removed from DOM manually.

This is a safety check, and it requires auth0/auth0.js#68 to work

**Comment by hzalaz** [comment]
Closes in favor of auth0/auth0.js#68
