### ISSUE TITLE
GDPR Requirement: Make `mustAcceptTerms` work on social logins

### ISSUE THREAD

**Issue by gebrits** [auth0/lock#1380]
This is an exact featureRequest-replica of #903 

The social-login flow does not allow setting 'mustAcceptTerms'. 

In light of GDPR where users are required to explicitly opt-in of having understood T&C, this is a pretty severe issue. 

Please make this work ASAP.

**Comment by luisrudge** [comment]
@gebrits do you have to accept terms on every log in?

**Comment by gebrits** [comment]
@luisrudge no. However, as it stands (afaik) a user can do a social login without doing a social signup. Thereby requiring us to have the requested functionality on the login-screen as well.

**Comment by gebrits** [comment]
@luisrudge as a completely different solution: inform users that attempt to do a social login, without having done a social signup first, to do just that, would be more than acceptable. 

In fact it would make a lot of sense imho: even if technically a social sign-up and social login are the same, it's definitely not from a user point of view.

**Comment by luisrudge** [comment]
> @luisrudge no. However, as it stands (afaik) a user can do a social login without doing a social signup. Thereby requiring us to have the requested functionality on the login-screen as well.

Yes, there's nothing we can do about that. It's just how it works today. If you use a federated connection (twitter/facebook etc), there's no concept of signing up and signing in.

I'll close this issue becase, as of now, this is the correct behavior for Lock. I'll ping our GDPR compliance team and see what they think about this.

**Comment by gebrits** [comment]
@luisrudge hmm ok. So any more official channel I could make this incompliance known. We're a paid customer, and simply closing an issue, because 'it's just how it works' will not do.

**Comment by luisrudge** [comment]
I talked with our GDPR team and they said you should contact your lawyer about your specific use case - we can't provide you with legal advice.

From our own perspective, we don't see GDPR as requiring this level of process for obtaining data-subject consents to processing (but you will need to confirm your own approach with your lawyer).

Other organizations also feel comfortable with this approach. For example, https://www.thetrainline.com/my-account/register has only a text saying that the user accepts the terms and a link to the privacy policy, no checkbox, and no lock-out.

**Comment by tomakehurst** [comment]
There's a lot of advice out there saying that explicit opt-in is the right way to comply with GDPR. Although not all orgs necessarily need to do this, it'd be nice if this was an option in the lock widget (and Auth0 generally).
