### ISSUE TITLE
Customize Auth0-lock flash message dynamically

### ISSUE THREAD

**Issue by Sachin1678** [auth0/lock#1383]
I am using Auth0-lock v11.6.1. I want to customize flash message. I am using below code but its not working.
`lock.on('authorization_error', function(error) {
  console.log(error);
  lock.show({
    flashMessage: {
      type: 'error',
      text: 'SOME CUSTOM TEXT MESSAGE'
    }
  });
});`

It is showing the console log but not overriding the message.

Auth0-lock Version: v11.6.1
React: 16.2.0

**Comment by luisrudge** [comment]
is lock already in the screen? lock.show doesn't override the previous lock.show call. 

Works fine if it's the first time:

![image](https://user-images.githubusercontent.com/941075/40629106-963c9074-629f-11e8-8f7c-a18fcf4efc20.png)
