### ISSUE TITLE
Verify if we can remove "plain bonzo" calls

### ISSUE THREAD

**Issue by tehsis** [auth0/lock#139]
We are using a [wrapper around bonzo](https://github.com/auth0/lock/blob/master/lib/bonzo-augmented/index.js) but we are still using the original library on some cases:

https://github.com/auth0/lock/blob/master/index.js#L11
https://github.com/auth0/lock/blob/master/index.js#L14

We need to check if we can just remove the "bonzo duplication"

**Comment by cristiandouce** [comment]
:+1:

**Comment by hzalaz** [comment]
Not longer used in v10
