### ISSUE TITLE
Guardian not working properly with push notifications

### ISSUE THREAD

**Issue by truelet** [auth0/lock#1391]
Hello,
I am using auth0 lock and I am using Guardian as 2FA. But it is not working properly for the purpose of security.

**Settings for Auth0**
1. I have enabled push notification from ***Multifactor Auth*** section and put below code for enabling 2FA when user login from other IP or location:
```javascript
function (user, context, callback) {

  var deviceFingerPrint = getDeviceFingerPrint();
  user.app_metadata = user.app_metadata || {};
    
  if (user.app_metadata.lastLoginDeviceFingerPrint !== deviceFingerPrint) {

    user.app_metadata.lastLoginDeviceFingerPrint = deviceFingerPrint;

    context.multifactor = {
      allowRememberBrowser: false,
      provider: 'guardian'
    };
    
    auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
    .then( function() {
      callback(null, user, context);
    })
    .catch( function(err) {
      callback(err);
    }); 
  } else {
    callback(null, user, context);
  }

  function getDeviceFingerPrint() {

    var shasum = crypto.createHash('sha1');
    shasum.update(context.request.userAgent);
    shasum.update(context.request.ip);
    return shasum.digest('hex');

  }
}
```
2. I have installed Guardian app on my mobile.

**Use Case**
1. I tried to log in with a user with email and password.
2. It shows 2FA authentication window with 2 options for download the Guardian app.
3. Now I clicked on the back button and retry to log in with the same user.
4. And I have logged in without 2FA authentication. That should not happen.
5. And after log out and re-login again for the same user, then it also not showing the 2FA option.

***Lock version: 10.23.1***
***Browser & OS: Mozilla Chrome Windows 7 |8  & Linux Ubuntu 16.04***

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in Lock itself. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
