### ISSUE TITLE
Lock doesn't autoclose if closable set to false

### ISSUE THREAD

**Issue by gorbypark** [auth0/lock#1396]
I'm not sure if this is the intended behaviour, but it seems like a bug to me.  

- Versions
11.7.0, Latest chrome and firefox for macOS.

- What's happening 
If lock is set to `closable: false` and `autoclose: true`, a screen that says "Thanks for logging in." shows up with no way to close it.

- Intended behavior   
I was hoping that setting `closable: false` would get rid of the "x" icon/button, and `autoclose: true` would auto close lock after a successful login.

- Code   
```
      this.lock = new Auth0Lock(clientId, domain, {
        closable: false,
        autoclose: true,
        avatar: null,
        rememberLastLogin: false,
        auth: {
          responseType: 'token id_token',
          audience: 'redacted', 
          redirect: false
        },
        theme: {
          logo: 'https://redacted.com/assets/img/icon.png',
          primaryColor: '#2366d1'
        },
        mustAcceptTerms: true,
        languageDictionary: {
          emailInputPlaceholder: 'you@redacted.com',
          title: 'redacted',
          signUpTerms: "redacted",
        }
      })
```
Sorry if this is the intended behaviour and not a bug, it just seems like a common use scenario would be to not allow lock to be closed with the "x" button but autoclose after successful login.

**Comment by luisrudge** [comment]
it's documented here: https://github.com/auth0/lock#ui-options

> autoclose {Boolean}: Determines whether or not the Lock will be closed automatically after a successful sign in. If the Lock is not closable it won't be closed even if this option is set to true. Defaults to false.
