### ISSUE TITLE
Lock's SSO transformation triggers LastPass Chrome extension to autofill repeatedly

### ISSUE THREAD

**Issue by ethanyoung** [auth0/lock#1397]
Lock version: 10
Browser: Chrome (tested on Firefox, the issue does not happen on Firefox)
OS: MacOS

When SSO is enabled, Lock will transform to hide the password field when the user-type email matches a domain configured in Auth0. In addition, It will transform to show the password field again when the user starts deleting characters from the email field (domain becomes not matched).

The problem is, if the user installed LassPass Chrome extension, which autofills the email, every time the user updates the email, Lock's transformation triggers LastPass extension to autofill the email field repeatedly. This causes the user cannot update the email field at all, unless the user hit delete furiously.

Here is an example:

![screen shot 2018-06-07 at 12 09 59 pm](https://user-images.githubusercontent.com/6742999/41075034-1d28bf9e-6a4e-11e8-8d24-428c43749fed.png)

LastPass autofills the email, and the domain is matched. The password field is hidden.

![screen shot 2018-06-07 at 12 25 51 pm](https://user-images.githubusercontent.com/6742999/41075036-1f20198c-6a4e-11e8-82f8-40d3083939ff.png)

If the user hit `delete`, Lock should transform to show the password field as shown in the second image. However, the email is autofilled again. Lock immediately becomes back to the first image.

**Comment by luisrudge** [comment]
Can you record a video of this? I don't understand what's happening.

**Comment by ethanyoung** [comment]
A small screen recording can be downloaded [here](https://drive.google.com/open?id=1bRoZI79VGSPlccJ51Oyv5wXDrNkrycIw) (15MB).

**Comment by luisrudge** [comment]
Password managers are weeeeeird :) I just submitted a fix, which should be out in the next release. Thanks for reporting it

**Comment by ethanyoung** [comment]
Thanks!

May I ask when the next release will be? So that we can arrange our release to apply the fix.

**Comment by luisrudge** [comment]
I'm trying to narrow a few extra SSO issues and I to ship everything on Thursday. As always, things might go wrong and dates can change, but those this is the plan right now 😬

**Comment by luisrudge** [comment]
I just opened the last pr for the SSO issues. I'll cut a new release once both are merged! Thanks for your patience.

**Comment by ethanyoung** [comment]
Looks like this fix is not in _11.17.2_. Just want to ask approximately when will 11.17.3 be release, please?

**Comment by luisrudge** [comment]
Sorry to keep you waiting. The next release is scheduled to happen this week.
