### ISSUE TITLE
Lock 11 for web is removing URL Parameters

### ISSUE THREAD

**Issue by Wayneio** [auth0/lock#1405]
Say we have an app at www.myapp.com/app.html?food=cheese

and we go through Lock V11 for web authentication, when it successfully authenticates, the page it loads is just www.myapp.com/app.html without the URL parameter. (Note if you press the ‘previously logged in as’ button, it will keep the parameters).

This occurs on at least Chrome and Safari and has been tested in 11.2.2 and 11.7.2

**Comment by luisrudge** [comment]
That's expected. We set the default `redirectUrl` without any query string or hash parameters: https://github.com/auth0/lock/blob/master/src/core/index.js#L276
