### ISSUE TITLE
allowAutocomplete for password

### ISSUE THREAD

**Issue by jshado1** [auth0/lock#1406]
Setting `allowAutocomplete: true` does not enable autocomplete for the password field, as the name suggests—the property name is not specific, so it should apply to all fields (the [documentation](https://auth0.com/docs/libraries/lock/v11/configuration#allowautocomplete-boolean-) does specify the limitation, which is confusing). Most browsers now ignore this obnoxious attribute, but a few stragglers are behind the times.

[Lock is currently hard-coded](https://github.com/auth0/lock/blob/master/src/ui/input/password_input.jsx#L69) to set `autocomplete="off"`.

Some mobile browsers fail to ignore that attribute, which interferes with password managers.

**Comment by luisrudge** [comment]
It's turned off by default. If someone is going to set that flag to `true`, hopefully, they already read the [docs](https://auth0.com/docs/libraries/lock/v11/configuration#allowautocomplete-boolean-) which state that this is only for username and login.

We can't change the behavior of the flag because that would be a breaking change. What's wrong with having autocomplete=off for the password input?

**Comment by jshado1** [comment]
>What's wrong with having autocomplete=off for the password input?

@luisrudge please see the end of my original post:

>interferes with password managers

[A cursory look through Google](https://www.google.fr/search?q=password+autocomplete) shows the litany of issues with it.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#Allowing_autocomplete), for example:

>Note that some software ignores this value, since it's typically harmful to users' ability to maintain safe password practices.

**Comment by luisrudge** [comment]
I saw your post, I'm asking what happens? Do the password managers fail to fill the inputs? Do they fill username but not password? I recently tested all browsers and a few password managers for this very specific reason and, with the exception of IE/Edge, all browsers asked to save username/password. LastPass and 1Password also worked as expected.

**Comment by jshado1** [comment]
Chrome for iOS; I believe the user was using the built-in password manager.

I have to ask: Why were you verifying that a feature you specifically try to break still works?

**Comment by luisrudge** [comment]
There was some reports that Lock wasn't working with password managers, so I verified that the built-in password managers shipped in browsers (desktop chrome, firefox and safari) work with Lock. I don't know why we have autocomplete=off in the password input, but I can't remove it right now without releasing a breaking change.

**Comment by jshado1** [comment]
Wellllll, +1 to the reports that Lock isn't working with password managers.

You could add an interim configuration property `allowPasswordAutocomplete`, which is a non-breaking change, and then reconcile/combine them later as the breaking change.

**Comment by luisrudge** [comment]
What specific issue are you having with password managers? Can you record a video and show what's happening?

**Comment by jshado1** [comment]
The bug was reported by an end-user. The first thing I checked during my initial investigation was autocomplete, which is well documented and very well known for causing problems, so I didn't need to investigate further.

**Comment by luisrudge** [comment]
And what was the issue? What was the browser? os version? I want to help, but there's not enough information in this issue to start investigating.

**Comment by Chris-Nicol** [comment]
@luisrudge 

Here's the steps:

1) Store a email/password for chimp.net in Chrome
2) Go to Chrome, on iOS 11
3) Navigate to chimp.net/users/login
4) Tap/Click the email field 
4.1) Password will fill, but email will not
4.2) Email field does not have focus
5) Tap/Click email field again
5.1) Password will go away 
6) Use Chrome’s password manager to fill email/password
6.1) Nothing fills
7) Type into email field
7.1) Password manager will suggest password
7.2) Tap password suggestion
7.3) Nothing fills

**Comment by jshado1** [comment]
I got some of that info from the user: iOS 11 using the latest Chrome.

The investigation is that you're forcing `autocomplete="off"`, which is well known and well documented to cause this exact issue.

**Comment by luisrudge** [comment]
Does it work in iOS safari? Can you send a PR that conditionally adds the autocomplete flag like the other inputs ([example](https://github.com/auth0/lock/blob/1424ce0409f64346951836570aa33e2b2a56dcca/src/field/email/email_pane.jsx#L46))? In the meanwhile, I'll ask our product and security teams if that's ok to move forward with this.

**Comment by Chris-Nicol** [comment]
Yes it does work in iOS Safari

**Comment by jshado1** [comment]
Yes, I can. I can get to it next week.

**Comment by luisrudge** [comment]
@jshado1 Thanks 🎉

**Comment by jshado1** [comment]
@luisrudge I have the updates ready, but your project set up will not let me commit due to unrelated/preexisting linting errors for files I did not touch.
