### ISSUE TITLE
Database connection with username and HRD 

### ISSUE THREAD

**Issue by cocojoe** [auth0/lock#1409]
Lock: 11.7.2

**Environment:** 
_Connections:_
A database connection with requires username and sign up options enabled.
An AD / LDAP connection with an associated email domain.

**Scenario 1**: Resetting a password after trying to login

_Steps to reproduce:_
1. Start lock with empty username/email and password
2. Try to login with incorrect username and password (this does not clear the inputs)
3. Go to remember your password section
4. Input an email associated with an enterprise connection

_Expected behavior:_ The error message due to the email being associated to enterprise connection.
_Actual behavior:_ No error message.

**Scenario 3**: Start a log in, but them move to Sign up

_Steps to reproduce:_
1. Start lock with empty username/email and password
2. Start to input a username (for example, user)
3. Conclude you may not have an account so move to Sign Up (without clearing the input)
4. In the Sign Up screen realize that username has been automatically filled in, but don't clear it as you actually want that username
5. In the email field input an email associated with an enterprise connection

_Expected behavior:_ SSO indication
_Actual behavior:_ No SSO indication

**The above seems to be caused by two main issues:**

- inputs and their values are available even if not shown on screen so an invisible value may impact the current screen when it should not
- only fall backing to email when username is empty still has issues because switching screens does not reset input values so a screen can start with a username already filled

**Comment by luisrudge** [comment]
scenario 2 was moved to https://github.com/auth0/lock/issues/1416
