### ISSUE TITLE
 "wrong password" message stays on Signup screen

### ISSUE THREAD

**Issue by rogozind** [auth0/lock#141]
1. Put wrong email/password and click SignIn
2. Widget displays "Wrong email or password" error message.
3. Click SignUp button. The message is still there but it does not make sense on that screen. It should be hidden on Signup page.

**Comment by cristiandouce** [comment]
True! Will fix that soon. Thanks!

**Comment by rogozind** [comment]
Any ETA on this fix?

**Comment by cristiandouce** [comment]
soon :grinning:

**Comment by cristiandouce** [comment]
@rogozind A fix for this was released with the latest `7.2.0` version of __Lock__. Let us know how it goes!

Thanks again for reporting!
