### ISSUE TITLE
Bug: button style display block 

### ISSUE THREAD

**Issue by iorrah** [auth0/lock#1412]
This is an awesome project, guys.

I'm starting this thread since we're having an issue that might be related to [this work](https://github.com/auth0/lock/pull/1394), where customized locks gets unintentionally affected by inline style rules.

I appreciate that this is a PR that aims to fix an IE-related bug but it would be nice we could find a solution that does not affect live apps.

- [x] Code snippet or sample project that reproduces the bug

Our app in production: https://app.bunch.ai/login

- [x] Screenshots when appropriate

### The issue:

Because the `.auth0-lock-submit` now received `display: block;` as **inline** style, it's hard for users to override this definition with `display: inline-block`.

<img width="1487" alt="image-1" src="https://user-images.githubusercontent.com/15240251/41529975-04728120-72ef-11e8-9899-196821c5b77d.png">

### How it should look like:

<img width="1603" alt="image-3" src="https://user-images.githubusercontent.com/15240251/41529550-db914076-72ed-11e8-85be-9cbcd1d9123b.png">

### Suggested solution:

Any chance we can revise the `display: block;` rule so that it could be defined under the `.auth0-lock-submit` class name? - in that case, it could be more easily overridden:

```
.auth0-lock-submit {
  ...
  display: block;
  ...
}
```

- [x] Lock version

```
  "dependencies": {
    "auth0-js": "9.6.1",
    "auth0-lock": "11.7.2",
  }
```

- [x] Browser & OS

- Google Chrome Version 67.0.3396.87 
- Firefox Version 60.0.2 
- Safari Version 11.1
- Opera Version 53.0.2907.68
- macOS High Sierra Version 10.13.4

**Comment by luisrudge** [comment]
We don't officially support custom styles, but I'll review a PR to fix this if you send one. You can also just use `!important`, since it will override the inline style.
