### ISSUE TITLE
Remove theme logo container.

### ISSUE THREAD

**Issue by Sachin1678** [auth0/lock#1414]
I want to remove theme logo container. My purpose is to remove the theme logo animation but as mentioned in https://github.com/auth0/lock/issues/1410 that it is not possible so now I want to show a custom header. is there any way to remove that container?

![screenshot-2018-6-19 sign in with auth0](https://user-images.githubusercontent.com/6849105/41578488-460b07a8-73b0-11e8-9d02-e05c390a49c6.png)

I want to remove the "Red-boxed" container with logo.

Auth0-lock - v11.7.1
React: 16.2.0

**Comment by skunde** [comment]
Take a look at this: https://auth0.com/docs/libraries/lock/v11/configuration#logo-string-

That should do what you want.

**Comment by luisrudge** [comment]
You can change the logo image we use with [this options](https://auth0.com/docs/libraries/lock/v11/configuration#logo-string-), but you can't remove the header. You can try overriding the css if you absolutely must do that, but that's not something we support and css classes might change without a new breaking change release.
