### ISSUE TITLE
Auth0 Lock stays on Loading screen

### ISSUE THREAD

**Issue by BrianSHenderson** [auth0/lock#1418]
When running locally on http://localhost:3000 it runs fine but when deployed there is just the loading screen despite having added the Allowed Callback URLs and Allowed Web Origins.

I'm using v11.7.2 of lock with React v16.4.

**Comment by luisrudge** [comment]
This happens because you're getting an error when trying to fetch your current session. Use dev tools to inspect the request and see what the error is.

**Comment by BrianSHenderson** [comment]
![screen shot 2018-06-20 at 16 30 30](https://user-images.githubusercontent.com/2174330/41668465-4b3b31c4-74a7-11e8-946b-6f078c76bee7.png)
Unfortunately the message doesn't give any clues as to the problem.

**Comment by luisrudge** [comment]
Where are you deploying?

**Comment by BrianSHenderson** [comment]
Its deployed to CloudFront here:
https://d20l9171dak5u8.cloudfront.net/

**Comment by luisrudge** [comment]
@BrianSHenderson did you change something in your client? it's not fetching the initial client data anymore

![image](https://user-images.githubusercontent.com/941075/41718224-be725ee8-7532-11e8-9d2d-f64330fa9f6f.png)

**Comment by BrianSHenderson** [comment]
I removed the old Application and created a new one but the error above still points to the old id even though it has been deleted?

**Comment by luisrudge** [comment]
Yeah, you have to change the client_id inside your webapp
