### ISSUE TITLE
User_blocked message not showing.

### ISSUE THREAD

**Issue by shehanf** [auth0/lock#1420]
Hi, 
I'm currently using the lock v11.3,  And i need to display the error message when a user is blocked. i did from what i could find from documentation and from readings. But nothing worked, below is  my current configuration.

![lcok code](https://user-images.githubusercontent.com/40231012/41832160-73a890e2-7868-11e8-8fa6-c17dd57d32c5.PNG)

can someone tell me where have i gone wrong or is this a bug in the lock ?

Thanks in advance.

**Comment by luisrudge** [comment]
I already answered you here: https://github.com/auth0/lock/issues/1413#issuecomment-398417661

This is not a bug in the sdk. Please reach out to support so they can assist with your project. https://support.auth0.com
