### ISSUE TITLE
Terms and Privacy checkbox not available with Passwordless mode of Lock 

### ISSUE THREAD

**Issue by raisedadead** [auth0/lock#1421]
**Issue:**

Currently when using passwordless signup we aren't able to get a checkbox with the `signUpTerms` text and the `mustAcceptTerms` keys set.

This is limited only to the `Auth0LockPasswordless` where as it seems to be working fine when using the database with username-password version of the lock.

We would like to be able to ensure this checkbox/notice display to be in compliance with GDPR and other privacy standards.

- [x] Code snippet or sample project that reproduces the bug

```js
  var clientID = "XXXXXXXXXXXXXXXXXXXX";
  var domain = "freecodecamp.auth0.com";

  var options = {
    languageDictionary: {
      title : "freeCodeCamp.org",
      signUpTerms: "By choosing to continue you confirm that you have read and agreed to..."
    },
    mustAcceptTerms: true,
    theme: {
      ...
    },
    ...
    socialBigButtons : true,
    passwordlessMethod: 'link',
    auth: {
      redirectUrl: 'http://localhost:3000/',
      responseType: 'token id_token',
      params: {
        scope: 'openid profile email'
      }
    },
    allowedConnections: [
      "email", "google-oauth2", "facebook", "github"
    ],
  };

  var lock = new Auth0LockPasswordless(clientID, domain, options);
  lock.show();
```

- [x] Screenshots when appropriate

![image](https://user-images.githubusercontent.com/1884376/41974178-d7c3b1ce-7a34-11e8-8904-6b4496721a0a.png)

- [x] Lock version

```
11.7.2
```

- [x] Browser & OS

```
Not relevant
```

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by raisedadead** [comment]
That should be totally handled by the client logic, that is :

```js

if (/* Someone clicked on SignUp button */){
	options.showTermsPasswordless = true // defaults to false
	var lock = new Auth0LockPasswordless(clientID, domain, options);
    lock.show();
} else {
	var lock = new Auth0LockPasswordless(clientID, domain, options);
    lock.show();
}

```

or in case of hosted pages, a config param can be passed.

I agree its not the responsibility of the Lock to know if its a sign up or sign in. It simply is yet another param that would be used to render the checkbox, and the text.

**Comment by luisrudge** [comment]
Yeah.. I agree. I added the box in the PR, I just need to write the tests and finish the PR.

**Comment by andreasvirkus** [comment]
Any progress on this @luisrudge ?

**Comment by luisrudge** [comment]
@andreasvirkus this will probably land next week 🎉

**Comment by andreasvirkus** [comment]
Awesome, we're really looking forward to this ^_^

**Comment by andreasvirkus** [comment]
Ping 🤞

**Comment by luisrudge** [comment]
@andreasvirkus I'm so sorry 😓 I got sidetracked into another project. I have the PR ready since foreeeever, but I still need to write the tests 😬 https://github.com/auth0/lock/pull/1424 - I'll try to get back to it this week. Thanks for the patience.

**Comment by mantagen** [comment]
@luisrudge fantastic! Looking forward to this also :D

**Comment by andreasvirkus** [comment]
Hey no biggie. Knew there'd be a valid reason : )

Any way anyone could help out? Should the tests go to this file?
https://github.com/auth0/lock/blob/master/test/sign_up_terms_agreement.ui.test.js

**Comment by luisrudge** [comment]
One test here:

https://github.com/auth0/lock/blob/master/src/__tests__/connection/passwordless/passwordless.actions.test.js

The other tests should have new test files for `src/connection/passwordless/index.js`, `src/engine/passwordless/social_or_email_login_screen.jsx` and `src/engine/passwordless/social_or_phone_number_login_screen.jsx`. Feel free to give it a shot if you want. Unfortunately, the tests/state management are super hard to understand 😞 so, don't feel bad if you don't grasp everything in the first read. Let me know if I can help 🎉
