### ISSUE TITLE
Verification message is not showing

### ISSUE THREAD

**Issue by Sachin1678** [auth0/lock#1423]
The new version of auth0-lock is not showing verification message **"A verification email has been sent to your inbox. Please verify your email before logging in."** as the flash message, Though all others message like "wrong email/password" etc. are displaying properly.

I also tried with

```
handleAuthentication() {
    // Add callback Lock's `authenticated` event
    this.lock.on('authenticated', this.handleAuth.bind(this));

    // Add callback for Lock's `authorization_error` event
    this.lock.on('authorization_error', (error) => {
      console.log(error); // here it is consoled
      this.lock.show({
        flashMessage: {
          type: 'error',
          text: error.errorDescription // Also tried with hardcoded text
        }
      });
    });
  }
```
Seems It just re-render the widget but dont display the flash message. But I want a way to show it by default like all other flash messages.

Auth0-lock: v11.7.2
Auth0-js: 9.6.1
React: 16.2

**Comment by luisrudge** [comment]
Where does this message come from?

**Comment by Sachin1678** [comment]
We have enabled the "verification email" status in which user has to verify the account. This message comes in the query string.

**Comment by luisrudge** [comment]
Sorry, can you provide more details? Are you migrating from a previous version? How are you forcing users to have the email verified? Is it through a rule? If that's the case, please share the rule code.

Also, if Lock is already being shown in the screen, you can't call `show` again, which looks like what you're trying to do.
