### ISSUE TITLE
big emails in the forgot password page break out of lock

### ISSUE THREAD

**Issue by luisrudge** [auth0/lock#1427]
![image](https://user-images.githubusercontent.com/941075/42348951-82292e76-8081-11e8-97d1-6c6c6348a58e.png)

**Comment by Rishabh570** [comment]
I would like to work on this issue...

**Comment by luisrudge** [comment]
@Rishabh570 unfortunately, the Change Password widget is not open source. I opened this issue here so we can track it and the community can see that we have under our radar.

**Comment by Rishabh570** [comment]
No worries, I'll look for another one :)

**Comment by depombo** [comment]
This is also true when displaying error messages

<img width="420" alt="Screen Shot 2019-03-13 at 2 14 41 AM" src="https://user-images.githubusercontent.com/2381303/54261681-64054f00-453a-11e9-85ae-6068546690c5.png">

**Comment by luisrudge** [comment]
error messages were fixed. change password widget is another repo.
