### ISSUE TITLE
Incorrect error message when fetching SSO data

### ISSUE THREAD

**Issue by KevinGrandon** [auth0/lock#1428]
- Lock version: 11.7.2
- Browser & OS: Firefox, MacOSX

For a new account and setup, I'm seeing the following error logged in the browser console:

> There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "http://localhost:8080" to the "Allowed Web Origins" list in the Auth0 dashboard:

My tenant settings definitely have the http://localhost:8080 CORS origin. Eventually the UI shows an error message like `We're sorry, something went wrong when attempting to log in.`.

It's quite frustrating seeing this incorrect error message with no guidance about how to properly resolve it. It would be nice if we can make the error message accurate. It's possibly around using a deprecated API/setting, but I'm not sure which one?

**Comment by luisrudge** [comment]
Are you talking about the allowed Cors origin or the allowed web origins in the dashboard? They’re different settings. Can you send a print screen of your configuration?

**Comment by KevinGrandon** [comment]
Thanks for chiming in! Both of my fields in the auth0 have the correct origins listed. I think really the error message here is just incorrect in my case. Ideally it would give some actionable advice to debug, because right now it's just confusing. 

There is:
* No cors error logged before the warning.
* No issue with my local network.

So it seems something else can go wrong when fetching SSO data that is not listed in the error message.

**Comment by luisrudge** [comment]
Because the page is loaded in an iframe, there's no way for the library to actually catch the specific error. Can you inspect the http request (via dev tools, for example) and tell me what the actual error is?

**Comment by KevinGrandon** [comment]
The problem is that I can't see any identifiable/actionable information in the console. The widget needs to surface more information around what went wrong. It seems this manifests as a bug in #1429, so we'll try to add more details to that issue.

**Comment by luisrudge** [comment]
It doesn't surface more information because the widget has no info at all because the error is thrown inside the iframe'd url, making the actual error impossible to retrieve. Normally, the most common error in this case is the CORS error, that's why we added the instructions to check the allowed web origins field. If you inspect the http error and find another error, we can add this to the message as well.
