### ISSUE TITLE
Username/password auth stops working without error message

### ISSUE THREAD

**Issue by KevinGrandon** [auth0/lock#1429]
- Lock version: 11.7.2
- Browser & OS: OSX, latest Firefox

We are attempting to disable the "Legacy Lock API" on a website which currently uses lock 11+ and auth0.js 9+. I believe that this should be supported according to docs, but when we do disable the legacy lock APIs in the Auth0 UI, our existing username/password auth stops working.

When we do login with a username/password we first see a spinning indicator which looks like:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/122602/42423510-54d60454-82b0-11e8-984a-1b09b93bbc50.png">

Eventually an error is displayed:
> We're sorry, something went wrong when attempting to log in.

I'm expecting that this would continue to work, and if not, analyze the current configuration/environment to provide an actionable error message as to why it doesn't work.

**Comment by luisrudge** [comment]
Can you please share a snippet or a demo that I can test myself? Thanks
