### ISSUE TITLE
Hitting multiple request for authorize

### ISSUE THREAD

**Issue by Sachin1678** [auth0/lock#1431]
I have added "force verification rule" in which user will receive verification email each time he/she login with an unverified email address. It was working fine in v10. But after updating to v11 user is receiving two emails. After exploring I found that after trying login with the unverified account user is receiving the email even if we refresh the page. So I think the reason behind two emails to log in is:

1. For authentication, flow redirect to "any_domain.auth0.com" and from there It sends email as the normal flow, this is the 1 email.
2. Now when the flow comes back to my login page from  "any_domain.auth0.com" it renders again the auth0 widget and sends another email as it is sending email even on refreshing the page.

So the actual reason might be it is hitting authorize request every time widget renders (after trying login with the unverified account).

React version: 16.2
Auth0-lock: 11.7.1

**Comment by luisrudge** [comment]
Yeah. To build the `Last time you logged in` screen, we do a `/authorize?prompt=none` to the server (to see if the user has a session). This happens when the widget is loaded. If you want to disable this, set the option `rememberLastLogin` to `false`.
