### ISSUE TITLE
Chrome autofill (prefilled) fields breaks the username validation when switching from login to sign up forms

### ISSUE THREAD

**Issue by jwallet** [auth0/lock#1432]
Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Lock version: cloud version
- [x] Browser & OS : Chrome  67.0.3396.99 x64

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

- in the login page, use chrome autofill to fill the form, make sure your username is an email  (has an @)
- switch tab to sign up page
- [first issue] the email entered is placed in the wrong field, I don't know if you can detect the difference between an username and an email and paste the value in the right field
- [second issue] if you make sure your form is valid (without touching the email pasted) and submit, it will throw an error 400 "something went wrong" but if you look at the network, the message says "no @ in the username", touching the username field will actually show the tooltip "Invalid" as expected.
- [workaround/third issue] I set autocomplete to false to solve temporary this issue, but in the sign up page the email field is still using autocomplete on.

**Comment by luisrudge** [comment]
Can you specify which lock version are you running? The default hosted page template?

**Comment by jwallet** [comment]
yes the default hosted page template

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
