### ISSUE TITLE
Custom connection does not show up when other connections are enabled.

### ISSUE THREAD

**Issue by NullVoxPopuli** [auth0/lock#1436]
- [ ] Code snippet or sample project that reproduces the bug
configuration:
![image](https://user-images.githubusercontent.com/199018/42899429-fc0f6194-8a93-11e8-90a6-5879d5a4ddfd.png)

- [ ] Screenshots when appropriate
![image](https://user-images.githubusercontent.com/199018/42899417-f376a59c-8a93-11e8-8bce-6b3790bcf163.png)

- [ ] Lock version
```
$ yarn why auth0-lock
yarn why v1.7.0
[1/4] Why do we have the module "auth0-lock"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "auth0-lock@11.7.2"
```

- [ ] Browser & OS
Ubuntu 18.04 - Chrome 67.0.whatever

So, only the database connection and social auth shows up.
But, if I comment out the database and social auth, then the custom idp shows up:
![image](https://user-images.githubusercontent.com/199018/42899518-4e07746e-8a94-11e8-999b-27b5eb26735f.png)

could something be wrong with lock? here is my whole config:

![image](https://user-images.githubusercontent.com/199018/42899533-60ae504c-8a94-11e8-937a-08549a3a4e5f.png)

**Comment by luisrudge** [comment]
Hi, what type of connection is the SIL-IdP-Hub? I tried reproducing this by creating a new oauth2 custom connection (using our extensions), but it's working for me:

```
const defaultOptions = {
  allowedConnections: ['spotify', 'twitter', 'acme']
};
```

![image](https://user-images.githubusercontent.com/941075/43281646-a78c714a-90ea-11e8-9e71-51ef80a5efa3.png)

**Comment by NullVoxPopuli** [comment]
@luisrudge it's a SAMLP Identity Provider

**Comment by luisrudge** [comment]
@NullVoxPopuli did you create that as an enterprise connection or via the extension to add custom social connections?

**Comment by NullVoxPopuli** [comment]
It's an Enterprise connection

**Comment by luisrudge** [comment]
@NullVoxPopuli Ah, yeah. I thought you were asking about the "Custom Social Connection". The "Quick Auth" enterprise connection screen is only shown when you have only that connection available (or when you force that connection via `allowedConnections`). If you have multiple connections (Enterprise + DB, or Enterprise + DB + SOcial etc), then Lock will use the enterprise connection when the email domain matches the enterprise domain, enabling this screen:

![image](https://user-images.githubusercontent.com/941075/43336465-62554e68-91a7-11e8-952b-ee302e7fda6c.png)

**Comment by luisrudge** [comment]
The connection is enabled, you just don't have a button to click.

my config: 

```js
const defaultOptions = {
  allowedConnections: ['my-db-connection', 'my-saml-connection']
};
```

This will show only the email/password input, but if you type the email and the email's domain matches your saml domain, then it will show the screen I sent in my previous answer, which will allow you to login with your saml provider.
