### ISSUE TITLE
Auto zoom in iOS have functional consequences when adding accept terms

### ISSUE THREAD

**Issue by Ronnie-J** [auth0/lock#1437]
Hi guys.

We are using the hosted page at Auth0 and have done some standard configuration of the widget. 
The version we are running is the new version `11.7.2` (didn't work on `11.2` that we used earlier).

When using an iOS device the input field gets zoom when the font size is under 16px (https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone). The current size is set to 13px and we cannot change this font size. This zoom causes the checkbox for accepting terms to move out of screen and there is no easy way for the enduser to understand how to mark the checkbox.

<img width="307" alt="screen shot 2018-07-19 at 10 41 54" src="https://user-images.githubusercontent.com/7793111/42931597-6a0c84ea-8b40-11e8-80da-0d51651eaed3.png">

![billede 17-07-2018 13 44 01](https://user-images.githubusercontent.com/7793111/42930474-61bda70e-8b3d-11e8-84cb-222357569bf3.png)

**Comment by Ronnie-J** [comment]
Hi @luisrudge 

How would I do that? I was under the assumption that you could not/should not override CSS when using the lock widget.

**Comment by luisrudge** [comment]
You can just do a regular css override:

```css
/* or any other class you want to override */
.auth0-lock {
  font-size: 16px;
}
```

If this fixes your issue, I'll talk with our design team to investigate a permanent fix.

**Comment by aggeren** [comment]
I've added the suggested <style> to auth0->hosted-pages->Login Page within <head>, but it's seems like auth0 are overriding this setting with its own from within lock.show() when it's called.
Can you describe where in the config page to insert the suggested override code?

**Comment by luisrudge** [comment]
it's in the place you mentioned. You probably need to add a !important to make it work:

```css
.auth0-lock {
  font-size: 16px !important;
}
```

**Comment by aggeren** [comment]
We implemented the above code and it fixed the autozoom issue, which are now not triggered on iOS devices. The increase of font-size might cause some related issues on the number of characters possible to enter in fields.

**Comment by luisrudge** [comment]
Ok, I'm talking with the design team about this. Thanks for the feedback!

**Comment by shayneoneill** [comment]
Did you talk to your design team. This still seems like its a thing.

**Comment by remotealex** [comment]
I've add `maximum-scale=1` to my viewport meta (`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`) from https://stackoverflow.com/a/46254706 and it stopped zooming in.

**Comment by shayneoneill** [comment]
Yeah that <meta> tag thing brought the magic.
