### ISSUE TITLE
Fail when re-enable MFA

### ISSUE THREAD

**Issue by andoanwkm** [auth0/lock#1440]
I use `Multifactor with Google Authenticator` rule to setup MFA for my client.
1. When user request disable it, I set `use_mfa` in `app_metadata` to `false` in my backend
2. When user request enable it again, I re-set `usa_mfa` to `true`
3. User login using lock

- Expect: MFA registration form & QR code will display for user
- Reality: This image below

<img width="668" alt="screen shot 2018-07-23 at 3 11 46 pm" src="https://user-images.githubusercontent.com/29110569/43065250-7875d344-8e8b-11e8-8026-5e7821ebde6b.png">

- Lock version: 11.7.2
- Browser & OS: MacOS Sierra 10.12.6, Chrome 67.0.3396.99 & Safari 11.1.2 & Firefox 61.0.1

Please help us soon because some users have complained about this situation.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
