### ISSUE TITLE
Lock including ES7+ dependencies breaks testing

### ISSUE THREAD

**Issue by franciscop-invast** [auth0/lock#1449]
Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [x] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [x] Screenshots when appropriate
- [x] Lock version: 11.7.2
- [x] Browser & OS: Jest test runner - Ubuntu 18.04

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

***

Hi, by using Create-React-App I am able to include Lock and build the bundle properly. However, for testing with Jest I encounter this issue:

![auth0](https://user-images.githubusercontent.com/36914428/43239479-57133662-90cd-11e8-9c31-7ff9db58f60c.png)

While the `auth0-lock` package is transpiled, it seems it is requiring the raw `auth0-js` package:

```js
// auth0-lock - src/core/web_api.js
import auth0 from 'auth0-js';
```

```js
// auth0-lock - lib/core/web_api.js
var _auth0Js = require('auth0-js');
```

The `main` field in `auth0-js` is pointing to the ES7+ version:

```js
// auth0.js - src/index.js
import Authentication from './authentication';   // This is the bit throwing
```

Lock is transpiled but includes ES7+ dependencies, so from a conceptual point of view I think it is an Auth0 Lock issue. What is the point of transpiling Lock if it's going to include ES7? I'd recommend one of these 3 fixes:

1. Lock to import the transpiled `auth0.js` library manually like `import auth0 from 'auth0-js/build/auth0.js';`.
2. `auth0-js` to point to the minified version in `package.json` like `"main": "build/auth0.min.js"`.
3. Lock to transpile the whole thing into a single bundle and include that with the npm package, similar to `https://cdn.auth0.com/js/lock/11.8.0/lock.min.js` as that is properly using UMD.

(1) and (2) should be fairly easy, and (3) also not so hard. I could try to do a PR if either of those is wanted.

From a practical point of view and since this is only a testing issue, I can work around this with ugly hacks:

- Manually copy/pasting the CDN file into a `lock.min.js` in my code and import that. However this loses the benefits of versioning and bugfixes, which is critical for an auth library.
- Use a `require()` instead of `import` within my testing and mock it out with jest.
- Compile the module manually somehow for testing.

However I think it'd benefit developers using Auth0's Lock in the future if this was fixed at the library level.

> Note: I'm properly using babel-jest so all my tests are using `import`, however jest won't transpile node_modules.

**Comment by luisrudge** [comment]
11.8.0 has a fix for this. sorry for the trouble!

**Comment by franciscop-invast** [comment]
That is amazing and I just missed it for a couple of days, thanks for the update! I tested it and it does indeed fix this :+1:
