### ISSUE TITLE
languageDictionary title property only displays on "login" tab

### ISSUE THREAD

**Issue by Jack000** [auth0/lock#1453]
in lock 11.8.0 the customized title only appears for "login", it doesn't seem to change for the "signup" tab.

I've made a minimal page to reproduce the issue at https://app.brandmark.io/v2/lock-test.html
the title says "Sign Up" instead of "my custom title" until you click the login tab.

tested on osx/chrome.

edit: lock 10 had the correct behavior

```
<html>
<head>
<title>test</title>
</head>
<body>
<div id="auth0"></div>

<script src="https://cdn.auth0.com/js/lock/11.8.0/lock.min.js"></script>
<script>
window.lock = new Auth0Lock('2yt-Sc9Cv425g3KjjAu89GHbMsym9uqi', 'brandmark.auth0.com', {
container: 'auth0',
auth: {
  redirect: false,
  responseType: 'token',
  redirectUrl: 'https://app.brandmark.io/v2/callback.php',
  params: {
    scope: 'openid profile email'
  }
}
});
window.onload = function(){
    window.lock.show({
      initialScreen: 'signUp',
      languageDictionary: {
        title: "my custom title"
      }
    });
}
</script>
</body>
</html>
```

**Comment by luisrudge** [comment]
Hi! We fixed the behavior of how the title is shown because it was super inconsistent. There's a great explanation here: https://github.com/auth0/lock/issues/1286

**Comment by luisrudge** [comment]
Oh, wow. That's terrible. It sucks that we can't fix this without a breaking change. I'll patch it up so you can use both signupTitle and signUpTitle
