### ISSUE TITLE
v11.8.0 warning regarding autoComplete (possibly React only)

### ISSUE THREAD

**Issue by mcrawshaw** [auth0/lock#1454]
Lock: v11.8.0
Browser: Chrome Latest

Console message when login dialog shown:
```Warning: Received `false` for a non-boolean attribute `autoComplete`.
If you want to write it to the DOM, pass a string instead: autoComplete="false" or autoComplete={value.toString()}.
If you used to conditionally omit it with autoComplete={condition && value}, pass autoComplete={condition ? value : undefined} instead.
    in input (created by PasswordInput)
    in div (created by InputWrap)
    in div (created by InputWrap)
    in InputWrap (created by PasswordInput)
    in PasswordInput (created by PasswordPane)
    in div (created by PasswordPane)
    in PasswordPane (created by LoginPane)
    in div (created by LoginPane)
    in LoginPane (created by Component)
    in div (created by Component)
    in Component (created by Chrome)
    in div (created by Chrome)
    in div (created by Chrome)
    in div (created by Chrome)
    in div (created by Chrome)
    in div (created by Chrome)
    in div (created by Child)
    in div (created by Child)
    in Child (created by Slider)
    in span (created by Slider)
    in Slider (created by Chrome)
    in div (created by Chrome)
    in div (created by Chrome)
    in Chrome (created by Container)
    in div (created by Container)
    in form (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container```

I can confirm the issue was introduced with v11.8.0.  I would say this PR is the likely suspect:
https://github.com/auth0/lock/pull/1419

I won't try to create a PR myself, until I let you have a go at it @jshado1.

Mark.

**Comment by luisrudge** [comment]
I'll submit a patch fix this week. This warning only happens when you're using the dev version of react, so it's not super critical.

**Comment by luisrudge** [comment]
fixed in #1456

**Comment by mcrawshaw** [comment]
Retested and can confirm fixed in v11.8.1.
