### ISSUE TITLE
Error with util library

### ISSUE THREAD

**Issue by timgivois** [auth0/lock#1462]
Thank you for using Lock! Please read the following before creating a new issue:
Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ ] Code snippet or sample project that reproduces the bug
When importing auth0-lock, I receive:
`Module not found: Can't resolve 'util' in './node_modules/auth0-lock/lib'`

- [ ] Lock version
`11.8.1`

**Comment by luisrudge** [comment]
please provide a snippet/config on how you're using lock.

**Comment by mivanyna** [comment]
@luisrudge https://github.com/miki995/test-auth0-lock-angular12
