### ISSUE TITLE
Validator function for checkbox is not working

### ISSUE THREAD

**Issue by sun2rise** [auth0/lock#1463]
Hi I am using Lock from the auth0 pages here https://manage.auth0.com/#/login_page
as hosted page

```js
additionalSignUpFields: [
  {
    type: 'checkbox',
    name: 'terms',
    prefill: 'false',
    placeholder: 'some term for the app',
    validator: function(terms) {
      return {
        valid: terms === true,
        hint: 'You have to accept'
      };
    }
  }
];
```

even if i use the validator function the condition won't be verified and the form is stuck.

I am doing something wrong or what?

**Comment by luisrudge** [comment]
Checkbox doesn't accept a validator. If you want to add custom terms, look for the `mustAcceptTerms` option [here](https://github.com/auth0/lock#database-options).

**Comment by sun2rise** [comment]
Thanks @luisrudge I already use it, the fact is that I need 2 mandatory acceptation for the registration.
But already told me that you won't add a second checkbox to the mustAcceptTerms.. so I hoped that I could find a workaround with it
