### ISSUE TITLE
Additional property text outside user_metadata

### ISSUE THREAD

**Issue by sun2rise** [auth0/lock#1464]
Hi I am using Lock from the auth0 pages here https://manage.auth0.com/#/login_page
as hosted page

When using a username-password login how can i get an additional property like `name` and have it outside `user_metadata` object in the root of the user profile?

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
