### ISSUE TITLE
Tapping the email text box immediately jumps the focus to the password text box on some phones

### ISSUE THREAD

**Issue by lorenh** [auth0/lock#1466]
We have a Xamarin app that uses the Lock component in a customized hosted login page. When we open the login screen on some mobile phones and tap the “Email” box, the focus immediately goes to the password box.

We tried this with Lock versions 11.4.0 and 11.8.1. This is repeatable 100% of the time on an iPhone 7 running iOS 11.4 but we also see it sporadically on an iPhone 6s+ on 11.4 and Pixel running Android 8.1 and 9. We were not able to reproduce this on many of our other test phones.

**Comment by luisrudge** [comment]
Does this happen without customizing the page?

**Comment by lorenh** [comment]
Not sure.  Our system is heavily dependent on the branding done in the customized login page, and we can't remove the customization very easily.  (Luis, is it common practice to close issues right away?)

**Comment by luisrudge** [comment]
I'm closing new issues until we have a repro.

Can you please try this with the default page (or even a customized page but using the default template we provide) and see if you have the same issues?

**Comment by lorenh** [comment]
Well, the good news is we went back to the non-customized login page, as well as the default "lock" template, and neither of them exhibited this behavior.  So it is something we're doing in our customization.  Through a process of elimination we'll try and narrow it down.  Thanks for the suggestion to try that experiment.

**Comment by luisrudge** [comment]
Perfect. let me know if you need more help with this!

**Comment by lorenh** [comment]
To circle back on this for others who might be seeing something similar. (offset caret focus on customized lock screen on iOS)

We seem to have been fighting a known Safari bug (https://bugs.webkit.org/show_bug.cgi?id=176896 ) related to position:fixed that MUCH has been written on (see: https://gist.github.com/avesus/957889b4941239490c6c441adbe32398 )

That led me to this stackoverflow article (https://stackoverflow.com/questions/29001977/safari-in-ios8-is-scrolling-screen-when-fixed-elements-get-focus ) where the first answer suggests inserting some CSS as a workaround. Inserting some CSS inspired by that SO solution seems to have fixed it.
