### ISSUE TITLE
Support Electron

### ISSUE THREAD

**Issue by jeaye** [auth0/lock#1467]
As discussed in https://github.com/auth0/lock/issues/1217, lock@11 doesn't support Electron. Since that issue has been closed, this issue specifically focuses on supporting Electron.

Will you please provide an estimate for when this will happen, as well as a suggestion for what users, and paying users, should do in the meantime?

**Comment by luisrudge** [comment]
Electron apps will have to use the Universal Login Page or PKCE. As of version 11, Lock only works with implicit flow. I'll provide an estimate on the guidance on the other thread (https://github.com/auth0/lock/issues/1217) when I have one.

**Comment by uotw** [comment]
I've got electron working with PKCE using a massaged version of @adeperio 's git.  I'll put together some sample code using the newest electron quickstart if anyone is interested in seeing my version.

**Comment by jeaye** [comment]
Having a complete sample would be pretty darn helpful, @uotw. Thank you for offering!

**Comment by uotw** [comment]
https://github.com/uotw/auth0-PKCE-for-electron-quickstart

**Comment by adeperio** [comment]
Nice work @uotw beat me to it :)
