### ISSUE TITLE
"Service not found" error has an (unexpected) error code of "invalid_user_password"

### ISSUE THREAD

**Issue by lkgarrison** [auth0/lock#1470]
- [ ] Lock version: 11.4.4
- [ ] Browser & OS: Chrome 68, Mac
- [ ] Code snippet or sample project that reproduces the bug
        Using Auth0 :

Initialization of Auth0Lock:
```
      const lock = new Auth0Lock(clientId, authDomain, {
        auth: {
          ...
          responseType: 'token',
          audience: 'api identifier that does NOT exist in my auth0 tenant (i.e. misspelling, forgot to create the API in my Auth0 tenant, etc)'
        },
      );
```

Catching and displaying authorization errors:
```
lock.on('authorization_error', (error) => {
  console.log(error);
}
```

The problem here is that the error that I get (which I am logging in the above code snippet) when the auth.audience option is an api identifier that doesn't exist on my auth0 tenant looks like the following:

```
{
  code: "invalid_user_password",
  error: "invalid_user_password",
  description: "Service not found: api identifier that does NOT exist in my auth0 tenant (i.e. misspelling, forgot to create the API in my Auth0 tenant, etc)"
}
```

This error looks almost identical to a login error, except for the description property:
```
{
  code: "invalid_user_password",
  error: "invalid_user_password",
  description: "Wrong email or password."
}
```

Ultimately, the "Service not found" error should not have a "code" of "invalid_user_password". The fact that the "Service not found" error has this code is pretty confusing and makes it difficult for me to distinguish between an auth0 configuration issue and an "error" caused by the user entering the wrong email/password.

In reproducing this error, note that the best way to get the "service not found" error is to specify a "responseType" or "token" and an "audience" as an API identifier that does **not** exist on the Auth0 tenant.

It may be worth checking if other configuration issues like this result in error codes of "invalid_user_password"

**Comment by luisrudge** [comment]
If you're outside of the Universal Login Page, every `access_denied` error gets mapped to `invalid_user_password` because that's the most common scenario for this error code. I understand your frustration in finding this error, but, given the limited error codes the spec allows us to use, that's the best decision for real life production usage. It might make the setup/configuration a bit confusing if you make a configuration mistake or a typo, but makes everyone's life easier in the long run.

**Comment by luisrudge** [comment]
@lkgarrison you want the official version? 😬

Official: Don't rely on the `description` strings as we might change them anytime without releasing a changelog or breaking change announcement.

Unofficially: Don't rely on them for the critical parts of your app. It's unlikely, but if they change, make sure your app fails silently and everything still works.
