### ISSUE TITLE
wont close if focus isn't in some input

### ISSUE THREAD

**Issue by cristiandouce** [auth0/lock#148]
`'keyup'` event on `'#a0-lock'` wont trigger if focus is in overlay.

**Comment by cristiandouce** [comment]
We need to bind the event `keypress` to the `body.a0-lock-open` and unbind it on each `lock.hide()`.

And also use another variable named `escapable` just like `component/dialog`: https://github.com/component/dialog#dialogescapable

**Comment by hzalaz** [comment]
Already fixed
