### ISSUE TITLE
Sign-Up Terms & Conditions are empty by default

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/lock#1482]
Lock widget is missing a default value for the sign-up _Terms & Conditions_ which causes the container to be hidden. **I think it's important to be straightforward on what the user is signing up to.**

[This line](https://github.com/auth0/lock/blob/7178d6223f02a990889cd44b957abdb6b51b29d5/src/i18n/en.js#L106) should have a text like:

```
By signing up, you agree to our terms of service and privacy policy
```

In the mobile SDKs we also link to the policies (which are customizable, see below). By default, we could display plain text or link to the Auth0 ones: https://auth0.com/privacy and https://auth0.com/terms.

**iOS:** https://github.com/auth0/Lock.swift/blob/master/Lock/Base.lproj/Lock.strings
**Android:** https://github.com/auth0/Lock.Android/blob/master/lib/src/main/res/values/strings.xml

![image](https://user-images.githubusercontent.com/3900123/45500045-1313ca00-b754-11e8-9c89-f568af1b8d4d.png)

**Comment by andreasvirkus** [comment]
Would just like to raise 1 point: issue there is that certain regions (EU for example) demands that the user actually has to manually opt-in for any consent and displaying a message as such could get a user into legal troubles. Whilst not displaying anything at all indicates that the user is giving no consent.

**Comment by luisrudge** [comment]
@andreasvirkus there's an option to add a checkbox to accept the terms: https://auth0.com/docs/libraries/lock/v11/configuration#mustacceptterms-boolean-

**Comment by luisrudge** [comment]
this is not the case anymore
