### ISSUE TITLE
Returned profile is always empty

### ISSUE THREAD

**Issue by casper1149** [auth0/lock#1483]
Hello,

I am using the Auth0Lock v11.9.1 in my React application, and the getUserInfo method always returns an empty({}) "profile". Also, the "authResult.scope" is null.
Following the documentation and other resources where a similar question has been asked I am setting the "auth.params.scope" property to "profile".

Here is my code snippet
```
import React from "react";
import {AUTH_CONFIG} from "../auth/auth0-variables";
import {Auth0Lock} from "auth0-lock";

class Login extends React.Component {
    constructor(props) {
        super(props);

        this.lock = new Auth0Lock(AUTH_CONFIG.clientId, AUTH_CONFIG.domain, {
            auth: {
                responseType: 'token',
                redirect: false,
                params: {
                    scope: "profile"
                }
            },
            autoclose: true,
            allowAutocomplete: true,
            allowForgotPassword: false,
            allowSignUp: false,
            theme: {
                logo: AUTH_CONFIG.logo
            },
            languageDictionary: {
                title: ""
            }
        });
    }

    componentDidMount() {
        if (!this.props.auth.isAuthenticated()) {
            this.lock.show();
            this.lock.on('authenticated', this.auth.bind(this));
        }
    }

    auth(authResult) {
        this.lock.getUserInfo(authResult.accessToken, (error, profile) => {
            if (error) {
                // Handle error
                console.log('error');
                return;
            }

            this.props.auth.login(authResult, profile); // save values to the localStorage
            this.props.history.push('/private');
        });
    }

    render() {
        return <div />;
    }
}

export default Login;
```

Can you please take a look and let me know what I am doing wrong or there is a bug in the version of the widget I am using.

**Comment by luisrudge** [comment]
Can you remove the scope param and see if it works? This way, Lock will use the default params: https://github.com/auth0/lock/blob/6abc70f6ddcd7c4bf656ec928daca7716785fa02/README.md#authentication-options

**Comment by casper1149** [comment]
Yes, it works now, thank you. But why it does not work when I specify this values explicitly?

**Comment by luisrudge** [comment]
I think you missed the `openid` scope as well. You can try adding `openid profile` only and it will work as well (you won't get the email though)
