### ISSUE TITLE
Warning: Failed prop type: Invalid prop `children` supplied to `CSSTransition`. in IE

### ISSUE THREAD

**Issue by yasa83-jsm** [auth0/lock#1490]
lock.show() function giving the following error on IE 11. It works fine on Chrome.

When I compare work flow with chrome. There is not child elements created in div class="auth0-lock-container" id="auth0-lock-container-1" /div

Following are the console error log,

Warning: Failed prop type: Invalid prop `children` supplied to `CSSTransition`.
    in CSSTransition (created by Chrome)
    in Chrome (created by Container)
    in div (created by Container)
    in form (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container
Warning: Failed prop type: Invalid prop `children` supplied to `TransitionGroup`, expected a ReactNode.
    in TransitionGroup (created by Chrome)
    in Chrome (created by Container)
    in div (created by Container)
    in form (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container
Warning: Failed prop type: Invalid prop `children` supplied to `Slider`, expected a ReactNode.
    in Slider (created by Chrome)
    in Chrome (created by Container)
    in div (created by Container)
    in form (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
bundle.js (81934,5)
SCRIPT5007: Unable to get property '__reactInternalInstance$fjg81iaqyopb' of undefined or null reference
1.chunk.js (21399,3)
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
bundle.js (81934,5)
SCRIPT5007: Unable to get property '__reactInternalInstance$fjg81iaqyopb' of undefined or null reference
1.chunk.js (21399,3)
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
bundle.js (81934,5)
SCRIPT5007: Unable to get property '__reactInternalInstance$fjg81iaqyopb' of undefined or null reference
1.chunk.js (21399,3)
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
bundle.js (81934,5)
SCRIPT5007: Unable to get property '__reactInternalInstance$fjg81iaqyopb' of undefined or null reference
1.chunk.js (21399,3)
SCRIPT5007: Unable to get property 'forEach' of undefined or null reference
1.chunk.js (14014,5)
SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
bundle.js (81934,5)
There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "http://localhost:3002" to the "Allowed Web Origins" list in the Auth0 dashboard: https://manage.auth0.com/#/applications//settings
SCRIPT5007: Unable to get property '__reactInternalInstance$fjg81iaqyopb' of undefined or null reference
1.chunk.js (21399,3)

**Comment by luisrudge** [comment]
do you have a code snippet? does it work if you use our cdn version?
