### ISSUE TITLE
IE 11 fails on Lock loading: minLength seems to not be configured in password policy

### ISSUE THREAD

**Issue by romainPellerin** [auth0/lock#1502]
It seems that Lock (auth0-lock@^11.1.2: version "11.10.0") is not compatible with IE11.

In fact it fails on a one of the library it imports:
password-sheriff/lib/rules/length.js : 33

```
if (!_.isNumber(options.minLength) || _.isNaN(options.minLength)) {
      throw new Error('length expects minLength to be a non-zero number');
}
```

Here are the screenshots of the console outputs:

<img width="1089" alt="screen shot 2018-10-08 at 2 31 55 pm" src="https://user-images.githubusercontent.com/591564/46638545-fa19f100-cb26-11e8-994e-052d90e67f4d.png">

<img width="770" alt="screen shot 2018-10-08 at 2 32 24 pm" src="https://user-images.githubusercontent.com/591564/46638549-fedea500-cb26-11e8-87ee-7ae6f7608081.png">

For now we have disabled the support of IE within eminent.ly website, but that's obviously not a good way to fix the issue... so we will need your help here.

I think this error is caused by a password_policy (that we cannot access or configure ourselves, since it's set by auth0 automatically) that does not contains ```minLength```.

**Comment by luisrudge** [comment]
does it work in other browsers?

**Comment by romainPellerin** [comment]
You just have to go to https://eminent.ly and register then sign in if you want to verify, but here the snippet anyway:

<img width="534" alt="screen shot 2018-10-08 at 9 58 22 pm" src="https://user-images.githubusercontent.com/591564/46644309-60ae0780-cb45-11e8-900e-e93ab45afc08.png">

We have the max security set on the database connection:

<img width="854" alt="screen shot 2018-10-08 at 10 01 42 pm" src="https://user-images.githubusercontent.com/591564/46644448-e467f400-cb45-11e8-9ec3-1131dd529afe.png">

**Comment by luisrudge** [comment]
I see you have the default `Username-Password-Authentication` enabled as well. Are you using this connection? If not, can you remove it and see if this fixes the issue?
[image](https://user-images.githubusercontent.com/941075/46665790-2e2ef980-cb9b-11e8-9dcd-8112df56f254.png)

**Comment by romainPellerin** [comment]
I did try. It does not think the issue. If you have IE11 on your side, you can try I temporarily disabled the anti-IE protection.

**Comment by romainPellerin** [comment]
@luisrudge are your tech team going to deep dive in this issue?

**Comment by luisrudge** [comment]
I will, yes.

**Comment by luisrudge** [comment]
We did a few changes in how we handle password policy since this issue was opened and I think this was fixed in the process. I just tested this on my IE11 browser with the same config as yours and it worked. If you're seeing the same behavior, please let me know so I can reopen the issue 🎉
