### ISSUE TITLE
Standard Lock auth button for google is not compliant with Google Sign-In Branding Guidelines

### ISSUE THREAD

**Issue by alexander-ignatow** [auth0/lock#1510]
Default Google sign in button (as of v 11.10.0):

![image](https://user-images.githubusercontent.com/1983879/47093049-fece5b80-d230-11e8-9dd4-cdbefec791f8.png)

That look is not compliant with [Google's Sign In Branding Guidelines](https://developers.google.com/identity/branding-guidelines#top_of_page)

That issue caused our app to become "Not verified by Google"

As a temporary workaround I have added following CSS to fix the issue:

```
<style>
    .auth0-lock-social-button[data-provider^=google] .auth0-lock-social-button-icon {
      background-image: url("https://developers.google.com/identity/images/g-logo.png");
    }
    .auth0-lock.auth0-lock .auth0-lock-social-button.auth0-lock-social-big-button[data-provider^=google] .auth0-lock-social-button-icon,
    .auth0-lock.auth0-lock .auth0-lock-social-button.auth0-lock-social-big-button[data-provider^=google]:hover .auth0-lock-social-button-icon{
      background-color: white;
      border: 1px #4285f4 solid;
      border-radius: 3px 0px 0px 3px;
      height: 38px;
    }
  </style>
```

**Comment by luisrudge** [comment]
@alexander-ignatow can you send a print screen with the end result?

**Comment by alexander-ignatow** [comment]
The result of implementing my fix:
![image](https://user-images.githubusercontent.com/1983879/47093923-d5aeca80-d232-11e8-80fc-0de51b5510e5.png)


What Google expect:
![image](https://user-images.githubusercontent.com/1983879/47093950-e8290400-d232-11e8-94be-e67e74d24259.png)


However Google has not responded anything on my fixed app yet, so I cannot be 100% sure that the fix works for them.
For instance the button text uses default font (Google want Roboto) and comes in all caps

**Comment by luisrudge** [comment]
Ok, let me talk with the design team. I'll get back to you on this.
