### ISSUE TITLE
Auth0 Lock uses callbackUrl instead of responseType token

### ISSUE THREAD

**Issue by sprockow** [auth0/lock#152]
```js
      var auth0Options = {
        responseType: 'token',
        popup: true
      };
       var auth0LockInstance = self.get('auth0Lock').show(auth0Options,
        function(err, profile, token) {
            //handle failure/success logic here....
      });
```

This works as expected most of the time, and does not try to redirect my SPA to a callback url. However, if I switch from a social media provider, logout, and then switch to username-password user, I can pretty regularly get a redirect callback from the auth0Lock, which will break my SPA login flow.

Am I doing something wrong? Should I ever a expect auth0Lock to redirect my app with the above options?

I've updated to the latest 7.3 release, and am still experiencing the issue.

**Comment by sprockow** [comment]
Ok, so I have some new insight. And this is going to sound like I'm a crazy person.

I run this file through uglify.js as part of my ember-cli build pipeline. After minifying the file, the token response behavior breaks, and I get a callback url in my SPA. 

When I disable minification, the behavior works, and my popup communicates with the main window properly.

My resolution has been to import the cdn file directly in my index.html, and avoid building the file in my minification pipeline.

Is there anything in the code that might break due to minification?

**Comment by jfromaniello** [comment]
What version are you using?

**Comment by sprockow** [comment]
I'm using version 7.3.0

**Comment by jfromaniello** [comment]
@sprockow can you try adding `sso: false`:

```javascript
var auth0Options = {
  responseType: 'token',
  popup: true  
  sso: false
};
```

Thanks

**Comment by ddbaron** [comment]
@sprockow Thanks for raising this, I've been banging my head for half a day. 

I recently added an uglify pipeline and suddenly my auth0-lock v9.2.2 had the exact same problem for auth0 database users. On Android and iOS the callbackURL is changed. On android it's: file:///android_asset/www/index.html

removing auth0-lock from my pipeline fixed the problem. I haven't tried this with v10 lock yet because it doesn't work with angular 1.x

**Comment by hzalaz** [comment]
Fixed in Lock v10

**Comment by sprockow** [comment]
Awesome! thanks so much!
