### ISSUE TITLE
Unclear which languageDictionary options are available for Passwordless

### ISSUE THREAD

**Issue by mantagen** [auth0/lock#1535]
### Description

It is not clear which of the  [languageDictionary options](https://github.com/auth0/lock/blob/master/src/i18n/en.js) are available when using Lock's Passwordless feature.

It would be helpful for there to be a definitive list of the languageDictionary options available when using Passwordless, as some seem to have been lost in the migration from the [Lock Passwordless](https://github.com/auth0/lock-passwordless)
(e.g. footerText)

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: v11
* Browser version: N/A
* OS: N/A
* Additional extensions/libraries that might be affecting your instance: N/A

### Reproduction
N/A

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by mantagen** [comment]
Not currently on that project, but I think this was a problem around documentation rather than a bug report.
