### ISSUE TITLE
Add "footerText" option Auth0LockPasswordless 

### ISSUE THREAD

**Issue by mantagen** [auth0/lock#1536]
### Description

In the deprecated [Lock Passwordless](https://github.com/auth0/lock-passwordless#dict-specification), there was a [dict option](https://github.com/auth0/lock-passwordless#dict-specification) to add "footerText" to either email or the code section.

This is nowhere to be seen in Lock v11, and would be awesome to have that flexibility back.

Many thanks

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: v11
* Browser version: N/A
* OS: N/A
* Additional extensions/libraries that might be affecting your instance: N/A

### Reproduction

N/A

**Comment by mantagen** [comment]
Thanks for the quick response!

![image](https://user-images.githubusercontent.com/12934669/47727290-11468d00-dc54-11e8-8679-42b87e4bf7c9.png)

**Comment by luisrudge** [comment]
https://github.com/auth0/lock#example-7

You can use `signUpTerms`. This *might* not work until this gets finished: https://github.com/auth0/lock/pull/1424
