### ISSUE TITLE
Lock 11.4 prevents sign in for custom db usernames including a space

### ISSUE THREAD

**Issue by mmaddex** [auth0/lock#1537]
Starting with 11.4 typing a space character in the username input box was disabled. However it's possible to have a Custom DB with usernames containing spaces. Newer versions of Lock should support this use case.

**Comment by luisrudge** [comment]
ref: https://github.com/auth0/lock/pull/1280

Are you saying that you can't **end** a string with a space or you can't even type a space in between two words?

**Comment by mmaddex** [comment]
Sorry I should have included more detailed repro steps. I am saying that I cannot type a space between two words.
