### ISSUE TITLE
Using icons from Auth0 styleguide in Lock custom fields

### ISSUE THREAD

**Issue by arvinsim** [auth0/lock#1538]
Is there a way to use the icons in the [Auth0 styleguide](https://styleguide.auth0.com) in Lock's custom fields?

**Comment by luisrudge** [comment]
That's not supported :(

**Comment by askrzypczak** [comment]
any update on this? running into the problem of adding the root name field to the signup form, and it would make my job here a lot easier if i could just use one of these icons
