### ISSUE TITLE
Several syntax issues with IE9

### ISSUE THREAD

**Issue by mildfuzz** [auth0/lock#155]
IE9 is listed as supported, but I am seeing lots of breaking errors when loading auth0lock via bower and script tag:

```<script src="/bower_components/auth0-lock/build/auth0-lock.js"></script>```

![image](https://cloud.githubusercontent.com/assets/196705/6821577/f3a77c64-d2cf-11e4-93f8-acf411100eec.png)

**Comment by cristiandouce** [comment]
@mildfuzz Do you ge the same using the CDN url? or just from the bower package?

Please try: https://cdn.auth0.com/js/lock-7.1.1.js

I tested on IE9 recently and I don't find those errors.

**Comment by mildfuzz** [comment]
Same

![image](https://cloud.githubusercontent.com/assets/196705/6822273/5e978a7c-d2d6-11e4-9238-9fcae20444e1.png)

**Comment by jfromaniello** [comment]
Is your page loading in IE9 as in IE9 mode as shown in this picture?

![](http://support.microsoft.com/library/images/2665906.png)
