### ISSUE TITLE
Better email validation on signup

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1554]
When typing a very long email address on a signup, the server returns a `400` error with the following payload:

```
{"error":"invalid email address"}
```

but Lock shows the following error message:

> WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO SIGN UP.

We should preemptively check that the email matches the server validation, or better handle the error message to tell the user that the email is invalid.

Among other things, the server checks that the name part is up to 64 characters, and the domain is up to 255 characters.

**Comment by luisrudge** [comment]
we'll have better validation using json schema for emails/usernames etc
