### ISSUE TITLE
When setting `languageBaseUrl`, Lock does not fetch the english translations

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1555]
When setting the `languageBaseUrl` to a location different than the CDN, Lock does not attempt to fetch the English translation (`en.js`), even if `language` is set to `'en'`. 
This is an issue for users who are putting custom text in their own server and want Lock to grab the custom translations (even for English).

To repro:

```
var options = {
  languageBaseUrl : 'https://mytranslations.com',
  language: 'en' // makes no difference if this is removed
};
// instantiate Lock
```

Check the network requests, Lock will not reach out to `https://mytranslations.com/.../en.js` to grab the custom translation.

On a quick discussion with @luisrudge , this seemed like a bug. I'm not completely convinced that all users will want Lock to automatically fetch the English translation, though. Some users use `languageBaseUrl` to circumvent firewall restrictions but are mirroring the exact contents of our CDN. In those cases, fetching the English translation from the server will be a wasted request, since the English translation included in the Lock distribution will be exactly the same.

Maybe an option to force getting the English translations externally when `languageBaseUrl` is set?

In the meantime, a workaround is to do the following:

```
    // this will remove the default English dictionary included,
    // forcing Lock to fetch one from the configured location
    Auth0.registerLanguageDictionary('en',null);

    var lock = ...
```

**Comment by luisrudge** [comment]
duplicated: https://github.com/auth0/lock/issues/1234
