### ISSUE TITLE
Non-compliant passwords for signups or password resets should not make requests to Auth0

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#156]
This is the behavior when attempting to log in with an invalid email address (no requests to Auth0 are made):

![image](https://cloud.githubusercontent.com/assets/829698/6871225/eada4178-d47f-11e4-9651-a9446a01b6cc.png)

This is the behavior when attempting to sign up with a password that doesn't comply with the password policy (a request to Auth0 is made, which is unnecessary):

![image](https://cloud.githubusercontent.com/assets/829698/6871254/1a077330-d480-11e4-8683-dfa342da0c66.png)

Same when attempting to reset a non-compliant password:

![image](https://cloud.githubusercontent.com/assets/829698/6871280/435b78d0-d480-11e4-8a3b-17d9f13c1da1.png)

**Comment by jfromaniello** [comment]
I think this has been implemented on newer versions.

@pose?

**Comment by rolodato** [comment]
I just tried this on `lock-7`, same behavior.

**Comment by jfromaniello** [comment]
@rolodato weird, according to #79 you should also see a popup with the password rules.

What Password Strength level are you using?

![](https://dl.dropbox.com/s/tdz745l0jwk86fy/ss-2015-03-27T14-37-57.png?dl=0)

**Comment by rolodato** [comment]
I'm seeing the popup when typing the password, but it doesn't prevent me from submitting. I was using `excellent` as the policy but it's the same for any policy.

**Comment by jfromaniello** [comment]
@rolodato oh great.. yes that sounds like a bug definitely.

**Comment by hzalaz** [comment]
Fixed in Lock v10
