### ISSUE TITLE
Allow validation on dropdown fields

### ISSUE THREAD

**Issue by shib71** [auth0/lock#1562]
Currently it is not possible to have an optional dropdown field. The workaround is to have a "no value" option as the default. However since the UI only has placeholders on fields (not separate labels), we have to choose between an option label that makes sense as a list option _or_ as a field label.

The approach that seems to fit with the rest of the library is a validation function.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
