### ISSUE TITLE
initialScreen=signUp and rememberLastLogin

### ISSUE THREAD

**Issue by alexstrat** [auth0/lock#1563]
Make `initialScreen=signUp` and  `rememberLastLogin=true` compatible.
### Description

I'd like to show the `signUp` as the initial screen because that's the most common usage of my login page. However, if the user was previously logged, I'd like to present them the quick-login screen (`rememberLastLogin=true)`.

Is there a reason why `initialScreen=signUp` and  `rememberLastLogin=true` are not compatible to day?

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.3
* Browser version: not necessary 
* OS: not necessary
* Additional extensions/libraries that might be affecting your instance: no

**Comment by luisrudge** [comment]
Because the quick-**login** screen only kicks in when you're actually trying to open the **login** screen. It can't be activated from the signup screen. One alternative is to save a localStorage item when your user authenticates and then you can use `initialScreen: hasAuthenticatedBefore ? 'login' : 'signUp'`.

**Comment by alexstrat** [comment]
Thanks for your quick answer!

> Because the quick-login screen only kicks in when you're actually trying to open the login screen.

Ok, but is that something we can improve directly in auth0-lock or there is a conceptual reason why it's not acceptable.

For instance by adding an option `initialScreen='signUpIfNotQuickLogin'`?

**Comment by luisrudge** [comment]
The conceptual reason is that you specifically asked for the signup screen, so there's no point in showing the quick login screen 😬 

I think your best bet is to handle your specific use case directly into your app with the localStorage idea.
