### ISSUE TITLE
Add SMS authentication support

### ISSUE THREAD

**Issue by cristiandouce** [auth0/lock#157]
### Expected Flow

1. User is asked for a phone no.

      <img src="https://cloud.githubusercontent.com/assets/367429/6874909/bd245682-d499-11e4-8616-a5c31b7f3703.png" width="250">

2. Taping or clicking over the + 54 9 (shown before) should display a full list of countries to select.
Default could be browser’s locale.

      <img src="https://cloud.githubusercontent.com/assets/367429/6874921/d0567e4c-d499-11e4-9d32-44d3af42cf58.png" width="250">

3. User is asked to input the received code. Alternatively could ask to re-send (that should be displayed with a timeout)

      <img src="https://cloud.githubusercontent.com/assets/367429/6874935/e3552084-d499-11e4-8d17-0007f0288cbf.png" width="250">

### Usage

```javascript
var lock = new Auth0Lock(‘clientID’, ‘auth0Domain’);

lock.show({
  connections: ['sms'],
  apiToken: 'jwtAccessToken'
})
```

The SMS authentication does not allow a combination to
`apiToken` is a JWT generated from https://auth0.com/docs/apiv2 with access to `create:users` only.

### Notes

This will trigger the send code for SMS authentication. 

```
POST /api/v2/users
Header "Authorizarion : Beared {JWT}"
{
  "phone_number": "phoneNumber",
  "connection": "sms",
  "email_verified": false
}
```
> Notice that `{JWT}` is the `apiToken`.

When users receive the SMS Passcode and submit it, then:

```
POST /oauth/ro
{
  "username": "<PHONE NUMBER>",
  "password": "<SMS PASSCODE>",
  "grant_type": "password",
  "client_id": "<CLIENT_ID>",
  "connection": "sms"
}
```
> Notice that phone number must have the international code in it. For example `+549<phoneno>`

**Comment by hzalaz** [comment]
Done in passwordless widget
