### ISSUE TITLE
This resource is no longer available under v1 APIs

### ISSUE THREAD

**Issue by webmobiles** [auth0/lock#1581]
I've just installed last version of lock, and i get this message:

This resource is no longer available under v1 APIs

after I try login with linkedin. This is sure it's a bug from lock and auth0, because my apps in linkedin are from today 31 december, and my app on auth0 same.

someone is getting this too ? I can't use auth0 for this reason, please i need an answer about that.
We can't reproduce a bug that we are having with auth0

**Comment by luisrudge** [comment]
Can you send a print screen? It’s unlikely this is a bug with lock itself.
