### ISSUE TITLE
callback does not work if user is already logged

### ISSUE THREAD

**Issue by webmobiles** [auth0/lock#1584]
* Lock version:  11.12.1
* Browser version: chrome
* OS: mac

Callback is not working when the user is already logged , and on lock, just confirm my email, then i get a windows 'thanks for logginig'. But this is not correact because all the login must to redirect to the callback, in another cases for login errors or when you enter your user and password (eg. auth0 for linkedin)

### Reproduction
<img width="319" alt="screen shot 2019-01-07 at 16 44 12" src="https://user-images.githubusercontent.com/21120559/50777377-b2c50d00-129b-11e9-8233-eccbee6dcfa5.png">

<img width="324" alt="screen shot 2019-01-07 at 16 40 27" src="https://user-images.githubusercontent.com/21120559/50777179-2fa3b700-129b-11e9-80d8-db183c4c83c7.png">

**Comment by luisrudge** [comment]
The "quick auth" screen (the one you're mentioning) doesn't do a full redirect. You have to subscribe to the `authenticated` event and react to that event:


```js
lock.on("authenticated", function(authResult) {
  console.log(authResult);
});
```
