### ISSUE TITLE
Footer logo displayed even for paid account

### ISSUE THREAD

**Issue by Maxim-Filimonov** [auth0/lock#159]
I have social+ and startup plans on my account and I still see auth0 logo footer. As far as I understand it should only appear on dev plan

**Comment by rolodato** [comment]
Try enabling and disabling any connection, it should refresh the client data retrieved by Lock and not show the logo anymore.

**Comment by Maxim-Filimonov** [comment]
Enable/Disable doesn't work as I can't disable anything in dashboard. When i flip the switch -> refresh the page it comes enabled again. No errors in console

**Comment by cristiandouce** [comment]
Could you share your initialization setup? (+clientId+domain)

Thanks!

**Comment by Maxim-Filimonov** [comment]
Fixed by @rolodato. Startup account needed manual fix.

**Comment by cristiandouce** [comment]
Awesome!
