### ISSUE TITLE
Broken vertical alignment in 11.13.0

### ISSUE THREAD

**Issue by hedlund** [auth0/lock#1591]
### Description

The latest release of Lock (11.13.0) changed the behaviour of the vertical alignment of the Lock widget: 

   https://github.com/auth0/lock/pull/1566/files

The fix is to make it possible to scroll the Lock widget when it is vertically larger than the viewport, but it also means that if a Lock widget is opened on a page that has been scrolled down, the widget may be opened (partially) outside the current viewport, as it now seems to be aligned with the top of the window.

This fix shouldn't have been introduced as a minor release, as it is quite a big change in behaviour, and it should also be configurable.

### Environment

Please provide the following:

* Lock version: 11.13.0
* Browser version: Chrome 71.0.3578.98
* OS: MacOS
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

1. Add Lock to a page that i vertically longer than the current viewport.
2. Scroll down the page
3. Open the Lock widget
4. See that the widget is displayed (partially) outside the current viewport.

![lock11-13](https://user-images.githubusercontent.com/826034/51532645-f47bb900-1e40-11e9-91f2-8cee9a22a6b3.png)

**Comment by luisrudge** [comment]
@hedlund do you have a test website that I can look at? or maybe a simple html/css example that shows the issue?

**Comment by hedlund** [comment]
@luisrudge Take the official Webpack example here:

   https://github.com/auth0/lock/tree/master/examples/bundling/webpack

Make sure you bump the `auth0-lock` dependency to `11.13.0` in `package.json`.

Then we need to make sure the Lock widget is opened in a document that is higher than the window. A simple hackish way to do so is to _replace_ `lock.show();` on line 31 in [index.js](https://github.com/auth0/lock/blob/master/examples/bundling/webpack/index.js#L31) with:

```
const btn = document.createElement('button');
btn.appendChild(document.createTextNode('Login'));
btn.style['margin-top'] = '2000px';
btn.addEventListener('click', () => lock.show());
document.body.appendChild(btn); 
```

This is a hack just to illustrate the point, but basically just add a button to the body, with a lot of margin to make sure you need to scroll the window to reach it. Then open the Lock dialog, and it will be outside the current viewport. Also, in case you have a large monitor, make sure you use a smaller browser window (so that you need to scroll to reach the button).

**Comment by luisrudge** [comment]
@hedlund ahhh, gotcha. I'm investigating this right now.

**Comment by hedlund** [comment]
@luisrudge Great; thanks! :)

**Comment by luisrudge** [comment]
@hedlund Can you test to see if this works for you? (I'll submit a patch release later)

```css
.auth0-lock.auth0-lock {
 position: fixed !important;
}
```

**Comment by hedlund** [comment]
@luisrudge Yeah, that does seem to do the trick! 👍
