### ISSUE TITLE
avatar is getting cropped

### ISSUE THREAD

**Issue by luisrudge** [auth0/lock#1600]
![image](https://user-images.githubusercontent.com/941075/52277487-f7e06b80-293b-11e9-93f6-5c280fc488db.png)

**Comment by jonnenauha** [comment]
I'm also getting this. Traced it to `v11.13.2` breaking it.

Probably this overflow add here or the above static position change:
https://github.com/auth0/lock/compare/v11.13.1...v11.13.2#diff-6e75cf9db4a3c7d943f8603dc182c0e9R125

**Comment by luisrudge** [comment]
@jonnenauha yup, that's the reason. But this overflow fixed a firefox issue, so we had to take a step back to fix both issues (and another one we found on mobile) at the same time. This will be fixed in the next release.
