### ISSUE TITLE
Issue with loading auth0-lock in WebView in a react-native app

### ISSUE THREAD

**Issue by atalebagha** [auth0/lock#1601]
### Description

When viewing a react web app with auth0-lock within React-Native WebView to login/signup the fields/body of the login dialog is blank.

![screen shot 2019-02-06 at 10 07 53 pm](https://user-images.githubusercontent.com/9886105/52393980-97e1e600-2a5d-11e9-8eb5-e48f064c16d5.png)

### Environment

* Lock version: v11
* Browser version: https://github.com/react-native-community/react-native-webview v5.0.5
* OS: iOS 12.1 (simulator on OS X Mojave)
* React-Native version 0.57.7
* React app with Auth0-Lock is React 16.4.1
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

- In a React app (web app) add auth lock signup and run on localhost
- Create a react-native app with a Webview pointing to localhost (127.0.0.1) web app with auth0-lock
- Using iOS simulator go to the Webview that displays the react app and start the auth0 login/signup process

**Comment by luisrudge** [comment]
Can you please create a repro project on github so I can take a look? Do you see any console errors?
