### ISSUE TITLE
Misleading error for `404` on user/ssodata

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1604]
When Lock fails to obtain the SSO data, it logs the following warning in the console:

> There was an error fetching the SSO data. This is expected (and not a problem) if "Enable Seamless SSO" is enabled for your tenant. If "Seamless SSO" is disabled, this could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "${origin}" to the "Allowed Web Origins" list in the Auth0 dashboard: ${appSettingsUrl}

This is very helpful when Lock is embedded in an app. However, it is misleading in a scenario that's now very common: Lock used in the hosted login page, where the tenant has "Seamless SSO" enabled (either by manual choice or because it's a new tenant that has it enabled by default). In this case, `/user/ssodata` will return 404 and it's the expected behavior. 

Ideally, Lock should detect this case (`404` for `/user/ssodata`) and log instead something to this effect:

> There was an error fetching the SSO data. This is expected - and not a problem - if the tenant has Seamless SSO enabled.

**Comment by luisrudge** [comment]
fixed in #1663
