### ISSUE TITLE
request: logout of federated/SSO

### ISSUE THREAD

**Issue by trusktr** [auth0/lock#1607]
### Description

There doesn't seem to be a way to log out of federated/SSO. The docs say to use auth0.WebAuth to do it from code.

I was hoping there was a way to do it from the login screen provided by Auth0Lock.

When I log out, if `sso` is false, then I am able to type my email address, and then it will log me in without a password.

If `sso` is `true` then I will have a convenient button that has my email address in it, and I can click it to log back in without my password.

I want to require my password, so I want to sign out of federated/SSO.

But there's no way to do this in the UI.

Having a button for it would be great, so that just like when I sign out of Google it signs me out of all Google sites in that browser. I'd like the same thing.

I'm in Electron though, and don't want to make my users go to the login provider to log out. I just want them to hit the button on the login screen.

### Prerequisites

* [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.14
* Browser version:
* OS:
* Additional extensions/libraries that might be affecting your instance:

**Comment by luisrudge** [comment]
Sorry, not sure why you'd want to show a logout button inside a login widget 😬 
If you want don't want to show the 'last time you logged in with' screen, just use `rememberLastLogin:false` as an option. Of course, this doesn't *actually* logs you out, just prevents the screen from showing up, but if you call `lock.checkSession`, you'll get a logged in user. If you want to actually logout, then Auth0.js is the recommended way of doing it.
