### ISSUE TITLE
Lock gets hidden by iPad keyboard (landscape)

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/lock#1609]
### Description

Using Lock in hosted login page:

Attempting to type in input fields in landscape mode opens the iPad on-screen keyboard. This blocks the input fields, making it hard for users to see what they are typing. If user tries to scroll up to see the Lock widget more clearly, this will fail to scroll. The only way users can see their input is by closing the keyboard.

### Environment

* Lock version: 11.10
* Browser version: Chrome v72.0.3
* OS: iOS 12.1 (iPad, 6th gen)

### Reproduction

- Set up hosted login page using Lock (any version).
- Call /authorize endpoint, will redirect to hosted login page.
- Tap on email input, on-screen keyboard will appear, blocking Lock input fields.
- Attempting to scroll up to make these visible will fail.

Screen recording:

![screenrecording](https://user-images.githubusercontent.com/6582826/53370035-7cf5f800-39b1-11e9-9538-2793e49ed3be.gif)

**Comment by luisrudge** [comment]
Can you please try this with latest? We did a few improvements in how lock is positioned and this might be fixed as a side effect.
