### ISSUE TITLE
Signup password field not working for third-party clients

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#1612]
When using Lock with a third-party client (`__useTenantInfo: true`), when trying to type a password in the signup form a JS error is thrown:

```
password.js:8 Uncaught TypeError: e.toJS is not a function
    at r (password.js:8)
    at o (index.js:25)
    at r (index.js:10)
    at o (password.js:12)
    at index.js:27
    at St (immutable.js:1973)
    at St (immutable.js:1982)
    at St (immutable.js:1982)
    at pt.updateIn (immutable.js:1280)
    at a (index.js:27)
```

This is the line where the error is raised: https://github.com/auth0/lock/blob/9446a37bab6d2a9e74fab468b9b4a05dfce940f4/src/field/password.js#L8

At that moment, the `policy` parameter is a string with a value of `none`.

Not sure if it's relevant, but the processing of the tenant information assigns a `"none"` value as default:

https://github.com/auth0/lock/blob/8cebda3497724f01b21efaee45288d6c41543200/src/core/tenant/index.js#L83

whereas the client information processor uses instead a default value of `passwordPolicies['none']` (an object from `auth0-password-policies`):

https://github.com/auth0/lock/blob/10b68db110b60dd739b5151b88a6922bc501bed2/src/core/client/index.js#L117

**Comment by AdvinRoz** [comment]
@luisrudge Is there a work-around to this issue? we re using third-party clients, and we would like to upgrade to the latest version

**Comment by luisrudge** [comment]
@AdvinRoz not yet. We recently cleaned up old issues, so the issue list you're seeing is our current backlog. If you want to dig into this and send a PR, I'll review it and merge it ASAP though.
