### ISSUE TITLE
MFA in popup mode

### ISSUE THREAD

**Issue by dpraul** [auth0/lock#1613]
[The docs](https://auth0.com/docs/libraries/lock/v11/authentication-modes#popup-mode) report that when Lock is in popup mode (i.e. `redirect: false`) that multifactor authentication is not supported. Is there any reason for this? Would this be changed in the future?

Our site is a SPA, so using popup mode affords us a lot of benefits that we can't get while using redirect mode. In particular it removes our reliance on user storage, since cookies, localStorage, and sessionStorage are not needed to store the `state` and `nonce` and we can keep the token in memory when none of those are available for long-term storage (popup mode also gives us faster login times since the app does not need to be re-instantiated again after login).

That said, MFA is essential to a lot of our clients. Is there any reason that MFA can't work in popup mode, or is it just that more development is required to make it work?

Thanks!

**Comment by luisrudge** [comment]
Sorry, we'll clarify in the docs that MFA is not supported when using Lock in embedded mode + popup mode (this scenario is unlikely to be supported in the future).

MFA will work fine if you use Auth0.js + popup mode though (we'll load the Universal Login Page in a popup).
