### ISSUE TITLE
Error message hidden with overflow

### ISSUE THREAD

**Issue by Sytten** [auth0/lock#1625]
### Description

Like #986, #912 and #1002, I have a problem with login. The overflow is auto and causing the error to be hidden. Removing it works, but it seems like a regression to me.

### Environment

* Lock version: 11.14.1
* Browser version: Chrome 73.0.3683.86
* OS: Windows

### Screenshots
![image (1)](https://user-images.githubusercontent.com/2366731/55192516-09dfcd00-517b-11e9-87e0-e77c1fbd6c02.png)
![image](https://user-images.githubusercontent.com/2366731/55192525-0e0bea80-517b-11e9-8a15-ad66d136578a.png)

**Comment by arvinsim** [comment]
Yep, I also get this problem.
