### ISSUE TITLE
setTimeout loaded state resolution throws error

### ISSUE THREAD

**Issue by barneycarroll** [auth0/lock#163]
The options manager's [asynch 'loaded' resolution](https://github.com/auth0/lock/blob/master/lib/options-manager/index.js#L170) allows for the widget to be destroyed between then and resolution, causing an error when the DOM components [attempt to initialise on elements that are no longer there](https://github.com/auth0/lock/blob/master/lib/header/index.js#L68).

Could this be done some other way to avoid the race condition?

**Comment by cristiandouce** [comment]
The `ready` async event __should__ actually stop the execution of every DOM rendering as shown in [this line](https://github.com/auth0/lock/blob/master/index.js#L545).

If you follow the call stack, this `ready` event, calls initialize, which calls the `HeaderView` initialization. In that order.

@barneycarroll Could you provide some repro steps?

It could be possible that this occurs if you call `.hide()` before the initialization has finished. I'll dig a little more about this, yet your repro example would be really appreciated! :grinning:

**Comment by barneycarroll** [comment]
> It could be possible that this occurs if you call .hide() before the initialization has finished

@cristiandouce spot on – my component's 'unload' behaviour was deferred until after the next component had loaded. Moving from distinct login to submit pages caused things to screw up. My mistake, thanks for the insight!

**Comment by cristiandouce** [comment]
Awesome. Yet, we should prevent that or fail with a better message I think.

I'll keep this open for the time being until I find the time to dig into this.

Thanks!

**Comment by hzalaz** [comment]
No longer applies in Lock v10
