### ISSUE TITLE
Using ' in an application name [Mariam's World -> Mariam&#39;s World ]

### ISSUE THREAD

**Issue by dchahla** [auth0/lock#1632]
![Messages Image(587866671)](https://user-images.githubusercontent.com/2994164/56085848-9b546d80-5e10-11e9-9627-5d57cdab6728.png)
![image](https://user-images.githubusercontent.com/2994164/56085852-a9a28980-5e10-11e9-8f44-07756a6bfa1c.png)

**Comment by luisrudge** [comment]
This is not an issue with lock itself, but with the way lock is rendered in the Universal Login Page. I'll report to the appropriate team.
