### ISSUE TITLE
auth-lock-content-wrapper css does not overflow when an error pops up it can't overflow and gets cut off

### ISSUE THREAD

**Issue by ewoess** [auth0/lock#1636]
**Thank you for using Lock!**

In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

The password strength fade in gets cut off because the main content container is not allowing overflow

### Environment

Please provide the following:

* Lock version:11.15.0
* Browser version: Chrome 73.0.3683.103
* OS: Windows 10
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

1) Go to sign up.
2) click on password 
3) type a single character

At this point the hint should appear showing the password requirements. If there are a log of requirements the hint gets cut off.

Please include:

![image](https://user-images.githubusercontent.com/48554167/56395979-13000f00-61fa-11e9-9fe7-6def3e6e8454.png)

![image](https://user-images.githubusercontent.com/48554167/56396030-522e6000-61fa-11e9-9212-9c99d21c605c.png)

**Comment by ewoess** [comment]
For the second screenshot I didn't attach the correct one. Lets try this.
![image](https://user-images.githubusercontent.com/48554167/56396126-af2a1600-61fa-11e9-8bff-b8263e89a61d.png)

**Comment by shaheen-karodia** [comment]
Having the same issue. It does not occur when there is more space between the header and the password field, as is the case when you have some form of social login
![image](https://user-images.githubusercontent.com/29511241/57010074-049ef380-6bfb-11e9-92f8-c030fd48703a.png)

**Comment by shaheen-karodia** [comment]
Hi has any progress been made on this issue?

**Comment by luisrudge** [comment]
@shaheen-karodia not yet. We have higher priorities, but I plan to start on this and other lock issues next week.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/pull/1728
