### ISSUE TITLE
Allow file protocol for default redirectUrl 

### ISSUE THREAD

**Issue by mmaddex** [auth0/lock#1638]
https://github.com/auth0/lock/blob/bbf35cdf40856c724f23caf270e4217565d692e9/src/utils/url_utils.js#L2-L8
Is there a reason we shouldn't allow a default redirectUrl for the `file` protocol in Lock like we do in Auth0.js? 

https://github.com/auth0/auth0.js/blob/master/src/helper/object.js#L126-L128

---

#### Implications of this logic

This lead to a very confusing `Cannot read property 'protocol' of null` error that took quite a bit of debugging to arrive at this as the root. When not providing a `redirectUrl` lock sets the default here
https://github.com/auth0/lock/blob/adfc8a8dbc253e3e1fae2503084f74baac17cd0d/src/core/index.js#L282
if the location is `file://path/to/file` that line sets the `redirectUrl` to `"null/path/to/file"`.

This ultimately makes it's way to Auth0.js

```javascript
function getLocationFromUrl(href) {
  var match = href.match(
    /^(https?:|file:)\/\/(([^:/?#]*)(?::([0-9]+))?)([/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/
  );
  return (
    match && {
      href: href,
      protocol: match[1],
      host: match[2],
...
```
https://github.com/auth0/auth0.js/blob/master/src/helper/object.js#L125-L141

which returns `null`

```javascript
function getOriginFromUrl(url) {
  if (!url) {
    return undefined;
  }
  var parsed = getLocationFromUrl(url); //null since lock set redirectUrl to "null/path/to/file"
  var origin = parsed.protocol + '//' + parsed.hostname; // throws `Cannot read property 'protocol' of null`
...
```
https://github.com/auth0/auth0.js/blob/master/src/helper/object.js#L148

Which throws the `Cannot read property 'protocol' of null` error.

**Comment by trusktr** [comment]
@mmaddex Thanks for reporting this. The workaround we found is to explicitly always provide a `redirectUrl` setting in the Lock constructor options, which causes it to bypass the auto-detection. 

We've got `file://` vs `http://localhost` URLs for our Electron application depending on prod vs dev mode, respectively, so we just have to detect the most and supply the correct URL for the workaround.

**Comment by luisrudge** [comment]
Lock is only supported in SPAs. Electron apps should use Code+PKCE flow instead.
