### ISSUE TITLE
Wiki improvement: mention how to use refresh tokens in popup mode

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#164]
https://github.com/auth0/lock/wiki/Using-a-Refresh-Token doesn't specify how to access the refresh token in the popup callback.

**Comment by ni-hil** [comment]
Is it possible to use the refresh token in popup mode? How can I get back the refresh_token in the callback?

**Comment by rolodato** [comment]
Yes, it's possible. Add the following parameters to the callback function:

```js
function callback(err, profile, id_token, access_token, state, refresh_token)
```

`refresh_token` should be present when sending `offline_access` as part of the scopes.

**Comment by rolodato** [comment]
Added here to wiki: https://github.com/auth0/lock/wiki/Using-a-Refresh-Token/963b892b4a6d2c88a1e82347779592cee08ffcd6
