### ISSUE TITLE
IE display bug for login form

### ISSUE THREAD

**Issue by nickerzb** [auth0/lock#1640]
**Thank you for using Lock!**

In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

- Lock renders unnecessarily tall (height) on hosted login page.
- Lock v11.14.1

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

* Lock version: 11.14.1 
* Browser version: IE 11.437.17763.0
* OS: Windows 10
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippet or sample project that reproduces the bug
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

![image](https://user-images.githubusercontent.com/19597570/56906962-edc89780-6a68-11e9-92d2-95352530e738.png)

![image](https://user-images.githubusercontent.com/19597570/56907008-05a01b80-6a69-11e9-9124-4b9aabfcffb6.png)

It looks like the following styles are being applied to auth0-lock-content-wrapper that are the cuprit:

```
_:-ms-fullscreen, :root .auth0-lock.auth0-lock .auth0-lock-content-wrapper {
    -ms-flex-preferred-size: 50vh !important;
    flex-basis: 50vh !important;
}
```

**Comment by luisrudge** [comment]
Can you send a print screen that shows the entire page? Also, send a print screen of other browser as well. Thanks!

**Comment by nickerzb** [comment]
![image](https://user-images.githubusercontent.com/19597570/56911764-5c125780-6a73-11e9-97ca-d30d584fcb1a.png)
![image](https://user-images.githubusercontent.com/19597570/56911777-6af90a00-6a73-11e9-872f-5dc11a3c4f51.png)

Second image is Chrome V73.0.3683.103

**Comment by nickerzb** [comment]
This works as expected in Lock V11.14.0, so this was introduced in Lock V11.14.1

**Comment by luisrudge** [comment]
Thanks for reporting. It will be fixed in the next patch release
