### ISSUE TITLE
Focus is lost when there's a "remembered" session available

### ISSUE THREAD

**Issue by catamphetamine** [auth0/lock#1642]
If Auth0 "lock" widget is shown when there's no "previous session" available for "quick login" then the focus is on the input field.
But if there's a "previous session" available for "quick login" then it doesn't focus on anything.

**Comment by luisrudge** [comment]
Thanks for opening the issue. In order to effectively review and triage issues, please make sure to fill the entire issue template so we have as much information as possible.
