### ISSUE TITLE
Throw error when calling resumeAuth and autoParseHash is true

### ISSUE THREAD

**Issue by luisrudge** [auth0/lock#1643]
### Description

Customers might use `resumeAuth` without setting `autoParseHash` to false, which would cause the `Invalid token - \`state\` does not match` error. It'd be good to strictly enforce this when you're calling `resumeAuth`.

**Comment by luisrudge** [comment]
related:
- https://github.com/auth0/docs/pull/7569
- https://github.com/auth0/auth0.js/issues/655#issuecomment-488091877

**Comment by trusktr** [comment]
Also, just a thought, but maybe if the hash is already parsed, can you just re-use that state instead of parsing again (or no-op, or similar)?

**Comment by luisrudge** [comment]
but it's kinda misleading that you're calling 'hey, lock, please parse the hash' and we return a result without actually parsing the hash. I rather fail the execution with a more descriptive method than rely on something funky that might break in the future

**Comment by luisrudge** [comment]
We'll stick with the docs that were added in https://github.com/auth0/docs/pull/7569 for now.
