### ISSUE TITLE
Doesn't refocus when re-showing the widget

### ISSUE THREAD

**Issue by catamphetamine** [auth0/lock#1646]
In our application we have this code:

```js
function getAuth0Lock(clientId, domain) {
  // Checks that there isn't already an "Auth0 lock" being shown.
  // Without this check it would stack "Auth0 lock" modals.
  // But when reusing the "Auth0 lock" widget it won't focus the input field.
  if (!window.CCAuth0lock) {
    window.CCAuth0lock = new Auth0Lock(clientId, domain, AUTH0_LOCK_OPTIONS);
  }
  return window.CCAuth0lock;
}
```

But the widget only autofocuses on the input field only when it opens initially.
When the widget is later shown without re-creating it it doesn't autofocus on the input field upon being shown.

**Comment by luisrudge** [comment]
Can't repro:

![focus](https://user-images.githubusercontent.com/941075/58223391-ca9fa980-7cef-11e9-8637-374617e9bac6.gif)


Can you provide more information?
