### ISSUE TITLE
rememberLastLogin not working with 11.16.0

### ISSUE THREAD

**Issue by DinakaranS** [auth0/lock#1651]
### Environment

Please provide the following:

* Lock version:11.16.0
* Browser version: Chrome 74.0.3729.157
* OS: macOS Mojave

### Reproduction

Below is the lock option i am using 
{
    auth: {
        responseType: "id_token token",
        params: {
            state: window.location.pathname + window.location.search,
            scope: "openid email app_metadata"
        }
    },
    autoclose: true,
    closable: false,
    avatar: null,
    languageDictionary: {
        title: "Log me in"
    },
    theme: {
        primaryColor: '#4285f4'// 40DF7D
    }
}

Working fine in my localhost, once after publishing it to server the lock widget is keep on loading.

If i set **rememberLastLogin: false**, then the widget is showing and allowing the user to login.
With below error.
<img width="733" alt="Screenshot 2019-05-20 at 3 35 20 PM" src="https://user-images.githubusercontent.com/8424594/58013758-ee5ac800-7b14-11e9-832d-aaf1ecb53b20.png">

**Comment by luisrudge** [comment]
is your app running on a web browser?

**Comment by luisrudge** [comment]
Works fine here: 
![image](https://user-images.githubusercontent.com/941075/58030994-ef303180-7af5-11e9-9bed-f550e3bf3b31.png)

This is probably an integration issue. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

If you have a repro project with one our support scenarios, feel free to reopen this issue with a link to the repro.
