### ISSUE TITLE
TransitionGroup Error with React/Gatsby

### ISSUE THREAD

**Issue by mvbooth** [auth0/lock#1673]
### Description
Using the current Auth0-js and Auth0-Lock packages, I was receiving an error in TransitionGroup.js that's being used from the Auth0-Lock dependency: react-transition-group ("react-transition-group": "^2.2.1"). 

My app is built in React (16.8.6) with Gatsby (2.3.31).

I fixed the issue so I no longer have the exact line of code, but basically "this.state.children" did not exist so TransitionGroup.js would cause an error which prevented the entire page from rendering.

### Environment

Please provide the following:

* Lock version: 11.16.2
* Browser version: Chrome 74.0.3729.169
* OS: Windows 10
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

As this is a project that can't be viewed by the public yet, I can't link to my repo, but I was able to fix the problem by removing the 'react-transition-group' from the Auth0 dependencies. I used the same method for fixing the errors between React versions from the Auth0 dependencies:

 
"resolutions": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-transition-group": "^4.1.1"
  }

**Comment by luisrudge** [comment]
you removed it or upgraded it?

**Comment by mvbooth** [comment]
@luisrudge - so I added that resolution to my package.json file, then I installed the most recent transition group package as a dependency to my project.

I realize this might be quite a bit of an edge case for users with current versions of React/Gatsby.

If it helps, I can put together a repo that I can share publicly to give more specific details. I was hoping this log might help anyone in the future if they are trying to use Auth0 with React/Gatsby. I appreciate you previous work in getting React16 working with the resolutions!

**Comment by luisrudge** [comment]
Thanks! I'll close this but it's amazing that you added this info. It will certainly help future users that have the same issue. 🎉

**Comment by demonmovch** [comment]
I have the same issue. I followed the instructions but that did not solve the issue. Can anybody help me? I have attached my package.json file. I also attached package-lock.json just in case. Please let me know what else infowmation you need.

[files.zip](https://github.com/auth0/lock/files/4722962/files.zip)

**Comment by mvbooth** [comment]
> I have the same issue. I followed the instructions but that did not solve the issue. Can anybody help me? I have attached my package.json file. I also have attached package-lock.json just in case. Please let me know what else information you need.
> 
> [files.zip](https://github.com/auth0/lock/files/4722962/files.zip)

I'm unable to extract your package files from the zip - getting an unspecified error.

**Comment by demonmovch** [comment]
It is weird. I was able to extract the package files from the zip. 
Ok. I attached my package files with .txt extension. Could you please look at it.

[package-lock.json.txt](https://github.com/auth0/lock/files/4727975/package-lock.json.txt)
[package.json.txt](https://github.com/auth0/lock/files/4727976/package.json.txt)

**Comment by demonmovch** [comment]
It is weird. I was able to extract the package files from the zip.
Ok. I have attached the package files as txt files. Could you please look at it&
[package-lock.json.txt](https://github.com/auth0/lock/files/4728101/package-lock.json.txt)
[package.json.txt](https://github.com/auth0/lock/files/4728102/package.json.txt)

**Comment by GreenOn** [comment]
For NPM users having the same issue, please note that resolutions is not an NPM feature. You will have to use something like [https://www.npmjs.com/package/npm-force-resolutions](url). We learned about this after spending hours :-(.

**Comment by GreenOn** [comment]
I tried the above solution adding `resolutions` along with the `preinstall` script from `npm-force-resolutions`. 
Resolutions did the job. 

However, `gatsby develop` gives me this error:

```
The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App ....
```
Problem is React& React-Dom versions are applied to the entire package.json and not just to the Auth0, which is not good. Dear Auth0 team, please give us a solution for this. If you can update your package to the latest React versions which match the ones with Gatsby, I think the problem would be solved with no hacks.

**Comment by GreenOn** [comment]
An update to the above post... I went with the yarn route and got rid of all the problems I was having with npm.

**Comment by lucasdellabella** [comment]
@luisrudge I'm still having this issue in 2021 - is there a reason we can't bump this dependency? The breaking releases seem like they shouldn't be much of an issue, but can't say with certainty otherwise I'd make the PR.

https://github.com/reactjs/react-transition-group/releases/tag/v3.0.0
https://github.com/reactjs/react-transition-group/releases/tag/v4.0.0
