### ISSUE TITLE
TypeError: this.updater.enqueueCallback is not a function in react 16

### ISSUE THREAD

**Issue by marcelorl** [auth0/lock#1679]
### Description

 - Running auth0-lock in react 16, I have another component which is a modal that must popup anytime but it just breakes instead, with the error:

`ReactBaseClasses.js:68 Uncaught TypeError: this.updater.enqueueCallback is not a function
    at Transition.push../node_modules/react-transition-group/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState`

I went through auth0-lock dependencies and noticed it requires react 15.6.2 and react-transition-group 2.2.1.

Not sure, but, shouldnt it be react 16?

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.16.3
* Browser version: Chrome Version 74.0.3729.169
* OS: MacOS Mojave
* Additional extensions/libraries that might be affecting your instance: reactstrap

### Reproduction

I do have an open repository with it:
https://github.com/marcelorl/todo-geru/tree/feature/auth0

Run `yarn && npm run dev`, after init, click the green button at the top, the error must show up.

**Comment by luisrudge** [comment]
You have to use resolutions to make sure you're using 16.x. More context here: https://github.com/auth0/lock/issues/1148
