### ISSUE TITLE
Signup page headerText is inadequate / useless

### ISSUE THREAD

**Issue by barneycarroll** [auth0/lock#169]
The `signup:headerText` is "Please enter your email and password". This text is more suited to the signin context – users don't yet have a password, and besides they need to choose a username. I personally believe it should be removed completely – the title and the inputs themselves are fully self-evident.

**Comment by cristiandouce** [comment]
You can now override it by setting:

```js
lock.show({
  dict: _.merge(lock.$dicts.en, {
    "signup:headerText": ""
  })
})
```
