### ISSUE TITLE
Nonce does not match error in v11.17.0

### ISSUE THREAD

**Issue by DinakaranS** [auth0/lock#1699]
After upgrading to v11.17.0. The lock is not working authentication failed. Invalid_token, nonce does not match error. 

* Lock version: v11.17.0
* Browser version: All
* OS: All

Below is my configuration
{
    auth: {
        responseType: 'id_token token',
        params: {
            state: window.location.pathname + window.location.search,
            scope: 'openid email app_metadata',
        }
    },
    autoclose: true,
    closable: false,
    avatar: null,
    languageDictionary: {
        title: 'Log me in'
    },
    theme: {
        primaryColor: '#4285f4'
    },
}

**Comment by DinakaranS** [comment]
After the error once again if you refresh the page. The lock is resuming and working fine. But for the first time login i am facing the authentication failed error.

<img width="583" alt="Screenshot 2019-07-19 at 8 55 33 AM" src="https://user-images.githubusercontent.com/8424594/61507345-02cb1c00-aa03-11e9-8a1f-4bf203d4f052.png">

**Comment by luisrudge** [comment]
Do you see that every time you log in for the first time?

**Comment by DinakaranS** [comment]
Yes. Every time.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
