### ISSUE TITLE
Password requirements popup gets cut off 

### ISSUE THREAD

**Issue by meguna** [auth0/lock#1705]
The password requirements popup is covered by the title div. 

### Environment

* Lock version: 11.16.3
* Browser version: chrome 75
* OS: macos

### Reproduction
<img width="403" alt="Screen Shot 2019-07-21 at 12 10 34" src="https://user-images.githubusercontent.com/17038508/61586496-b7ef0700-abb0-11e9-87ac-96836a9e7b89.png">

**Comment by frsc** [comment]
Same problem here
