### ISSUE TITLE
Add custom image button

### ISSUE THREAD

**Issue by AnanasPie** [auth0/lock#1707]
Hi,

I want to add a custom social button to the lock screen.
The button will redirect the user to another site and call be to **my** server back (and not to the auth0).
Is this possible ?

**Comment by luisrudge** [comment]
You can, but this is not supported. You can use javascript to add a button inside our button list etc. 
You can also use Auth0 to add custom OAuth0 services via https://auth0.com/docs/connections/social/oauth2.

**Comment by AnanasPie** [comment]
Can you give me an example of such JS code or reference to the documention about that. I couldn't find any dynamic buttons list.

**Comment by luisrudge** [comment]
There's no docs about this because it's not officially supported (it might even break in the future), so we can't recommend it. But you can do it, knowing the risks. Here's a great tutorial on how to do it: https://www.tutorialrepublic.com/faq/how-to-add-element-to-dom-in-jquery.php
