### ISSUE TITLE
Option to move signUpTerms above social sign up buttons?

### ISSUE THREAD

**Issue by daniel-VGW** [auth0/lock#1710]
### Description

I've set mustAcceptTerms to true and the social sign up buttons are grayed out until the user accepts the terms. 

This is fine, but as the terms are at the bottom of the form users may not see them.

I found this exact issue in the auth0 community but a ticket was never raised. https://community.auth0.com/t/can-we-move-the-signup-terms-to-above-the-social-signup-buttons/7943.

Would be very nice to have an option to move this above the social sign up buttons, but it's just a suggestion.

### Environment

Please provide the following:

* Lock version: 11.4.2
* Browser version: Not relevant
### Reproduction

Open a lock with signUpTerms set and mustAcceptTerms set.

**Comment by luisrudge** [comment]
Thanks for the suggestion! I added this to our backlog so we can discuss it in the future.
