### ISSUE TITLE
Gatsby runtime errors related to environment variables

### ISSUE THREAD

**Issue by kmcaloon** [auth0/lock#1711]
So I looked all over and can't find a solution here. I have the latest Gatsby and lock packages installed, along with making sure process.env.NODE_ENV is available during runtime.  For some reason simply importing auth0-lock into the application is causing Gatsby to run a function that I believe itself is causing the error. Here is the function that is being called in Gatsby:

```
/**
 * Save `namespaces`.
 *
 * @param {String} namespaces
 * @api private
 */

function save(namespaces) {
  if (null == namespaces) {
    // If you set a process.env field to null or undefined, it gets cast to the
    // string 'null' or 'undefined'. Just delete instead.
    delete {}.DEBUG;
  } else {
    {}.DEBUG = namespaces;
  }
}
```

This looks to be directly related to env variables, so I'm guessing the lock is trying to access an undefined variable.  The thing is when I build the app without importing lock and console process.env.NODE_ENV it is outputting correctly. I'm assuming I'll probably have to submit an issue over there, but wanted to first check to see if anyone here might have any ideas since it is directly related to importing the lock.

**Comment by luisrudge** [comment]
Lock itself doesn't access any env variables. We do use react internally and that uses env variables, but I doubt Gatsby has any issues running react 😬 Let us know if you find the reason for this as others might face the same issue in the future.
