### ISSUE TITLE
Support `lock.on('cancel', ...)`

### ISSUE THREAD

**Issue by cdosborn** [auth0/lock#1713]
Right now there is no way to know if the user cancelled the lock, short of waiting an arbitrary amount of time and guessing.

**Comment by luisrudge** [comment]
https://github.com/auth0/lock#onevent-callback

`lock.on('hide', () => {
  console.log('user closed lock');
})`

**Comment by cdosborn** [comment]
`hide` is firing me when the auth is successful.

**Comment by luisrudge** [comment]
You can check inside hide if the user is authenticated or not.

**Comment by cdosborn** [comment]
Something like?
```
lock.on('hide', lock.on("authenticate", ...)
```

Doesn't seem great, but that will work for me, thanks.

**Comment by luisrudge** [comment]
```
var accessToken;
lock.on("authenticated", function(authResult) {
 accessToken = authResult.accessToken;
});
lock.on("hide", function() {
  if (!accessToken) {
     console.log('user probably cancelled');
  }
});
```

**Comment by cdosborn** [comment]
There is no guarantee that that code works. Sometime after "hide", "authenticated" triggers. If its the next tick or more after "hide", then `accessToken` won't exist.

**Comment by cdosborn** [comment]
This ticket was to propose an api that I think is reasonable, can you explain why it should be closed?

**Comment by luisrudge** [comment]
I just checked in the codebase, and the code won't actually work. We emit 'hide' before 'authenticated' 😬 I'll leave this as a feature request. If you want to send a PR with this, I'll review it and ship it. Thanks! 🎉

**Comment by cdosborn** [comment]
Sure

**Comment by cdosborn** [comment]
I don't have the time to make this change (and the doc updates). There's the simple fix of just changing the order, but I think that's the wrong fix. It's okay that hide comes before authenticate, but there should really be a separate event only fired when a user closes pre auth.

I have autoClose set, and am using popup mode. When a user successfully auths, the modal closes, and then a second or so later the authorize event occurs, so waiting some amount of time is a no go. By manually closing, I can work around this.
