### ISSUE TITLE
CONTRIBUTING to lock

### ISSUE THREAD

**Issue by thisis-Shitanshu** [auth0/lock#1716]
Hey @luisrudge , there are a couple of design issues, like the  #1709, #1636, #1315. If not inconvenient to you and if you're still working on them, I was looking forward to contributing to this project. If you like me to, please just let me know.

**Comment by luisrudge** [comment]
@thisis-Shitanshu Thanks for the interest! If you want to start contributing to lock, those seem like a good place to start. Let me know if you need any help. 🎉
