### ISSUE TITLE
`password_expired` error during login is not being mapped to `password_change_required`

### ISSUE THREAD

**Issue by xiananfan** [auth0/lock#1719]
**Thank you for using Lock!**

In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

Hi Auth0 team,

We are using AD connector on a windows server to talk to our Active Directory. And we have a 90 days password expired policy. When a user's password is expired, the lock widget displays an unclear message: "We're sorry, something went wrong when attempting to log in."

After looking into the code [here](https://github.com/auth0/lock/blob/fb4948c38808e8ef900deb393840f76090ff4864/src/i18n/en.js#L13), it seems like the lock is using the message for "lock.fallback", it probably should be displaying the message for "password_change_required".

When looking at this [method](https://github.com/auth0/lock/blob/master/src/core/index.js#L497), it does not map any message for "password expired", as a result, it will display "lock.fallback" message. Please check for password expired error as well, and display the correct message.

Thanks,
Xianan

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.16.0
* Browser version: Chrome 76.0.3809.100 
* OS: MacOS 10.14.6
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippet or sample project that reproduces the bug
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

log in AD connector showing password expired:
![password expired log](https://user-images.githubusercontent.com/26611670/63554229-bf783780-c4f1-11e9-87e9-16bb9516935a.png)

log in auth0 appliance:
![password expired auth0 appliance log](https://user-images.githubusercontent.com/26611670/63554264-dae34280-c4f1-11e9-9ac9-a1c75ad754e1.png)

message displayed on lock widget:
![password expired message](https://user-images.githubusercontent.com/26611670/63554241-ce5eea00-c4f1-11e9-8c8e-9fa5b68da0e2.png)

**Comment by xiananfan** [comment]
@luisrudge we are using lock.js inside the universal login page.

**Comment by xiananfan** [comment]
@luisrudge How do you test this lib against Auth0's AD connector? Can you use the setup on your side to verify the behavior? I can't easily change my company's password policy to reproduce this. I am only aware of this due to our customer reporting this.

**Comment by luisrudge** [comment]
@xiananfan I already pinged your support agent so we can work together and spin up a test environment for this. I'll keep you posted.

**Comment by xiananfan** [comment]
@luisrudge, I was able to find one password expired account, and reproduce it. I attached the har file in the Auth0 ticket: https://support.auth0.com/tickets/00435936

![Screen Shot 2019-09-04 at 10 39 22 AM](https://user-images.githubusercontent.com/26611670/64277940-69978c80-cf00-11e9-8952-6c137712a673.png)

**Comment by luisrudge** [comment]
@xiananfan ok, so the behavior is expected. We need translation strings for that code specifically. You can extend the dictionary to add that string:

```js
lock.show({
    languageDictionary: {
        error: {
            login: {
                password_expired: 'your string here'
            }
        }
    }
});
```

**Comment by xiananfan** [comment]
@luisrudge can you explain more on why this is expected? The auth0 documentation does not mention there are certain errors that the developer needs to override in order to work.

Also, the default hosted login code provided in Auth0 admin dashboard doesn't override any error message.

Is that an indication that for most errors, there should be a default set?

**Comment by luisrudge** [comment]
Sorry, I meant that this is expected based on the code we have in the repo today, not in the general experience that we want customers to have. I renamed the issue to add this translation string in the future. The snippet I provided is a workaround while we don't ship this update.

The `password_change_required` is used for when you have to change your password because it's your first login and it's not meant to be used for expired passwords.

**Comment by xiananfan** [comment]
@luisrudge , if you read the message mapped to `password_change_required`, it's `You need to update your password because this is the first time you are logging in, or because your password has expired.` I think it's meant for expired password as well.

**Comment by luisrudge** [comment]
HA! I was betrayed by my screen size 😝 

![image](https://user-images.githubusercontent.com/941075/64302154-a8046a00-cf47-11e9-95de-ab01d085cdcc.png)

I guess that facilitates things. We can certainly map the expired error to that message instead of creating a new 'translation key' for this error. I'll rename the issue again.

**Comment by xiananfan** [comment]
@luisrudge I think the `password_change_required` right now is only mapped to the error when the user's password has never been set. I think if you revise the message, and remove the `, or because your password has expired.`, it would be clearer. Then you can to create another message dedicated to 'password_expired', and each message will be shorter and clearer.

**Comment by luisrudge** [comment]
We'll think about that, yes. I'm on vacation for the next two weeks, but I already pinged our product manager about this so he can figure it out what's the best way to move forward with this (single message for both or individual messages for each error).

In the meantime, you can use the snippet I sent you to provide a better UX for your customers 🎉
