### ISSUE TITLE
index.js:405 There was an error fetching the SSO data. This is expected - and not a problem - if the tenant has Seamless SSO enabled. If the tenant doesn't have Seamless SSO enabled, this could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "https://dev-787979.auth0.com" to the "Allowed Web Origins" list in the Auth0 dashboard: https://manage.auth0.com/#/applications/S5ssEikA1dpZUNOzyIcC5JokK0yuGk/settings.  auth0.min.esm.js:8 Following parameters are not allowed on the `/authorize` endpoint: [sso]

### ISSUE THREAD

**Issue by aisamuel** [auth0/lock#1724]
**Thank you for using Lock!**

In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version:
* Browser version:
* OS:
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippet or sample project that reproduces the bug
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by luisrudge** [comment]
The warning is self-explanatory.

**Comment by aisamuel** [comment]
Yes. I'm working on an using django rest api and angular as my frontend. I can route my guarded page after logging in but I'm not getting data from my backend.

**Comment by aisamuel** [comment]
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
client:52 [WDS] Live Reloading enabled.
core.js:6014 **ERROR HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: "http://localhost/api/task/", ok: false, …}**

**Comment by aisamuel** [comment]
got that error after loggin in

**Comment by aisamuel** [comment]
https://auth0.com/blog/angular-2-authentication/
i followed the instruction there. my django rest api is working perfecting well after using the test token provided on the auth0 dashboard. but my frontend seems not to be sending the accesstoken to my backend even though i can route into my secured pages after logging in

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.
