### ISSUE TITLE
Cannot Override 'Can't be blank' error message in Auth0

### ISSUE THREAD

**Issue by ganeshshirsath123** [auth0/lock#1727]
Hi 
We are using Auth0 and we have successfully overridden error messages.
For Blank username and Password we are not able to override the error message. it always appeared as "Can't be blank" message.

We have used following properties 
 invalidErrorHint: "Please enter valid input.",
 blankErrorHint: "Please enter valid input."

Please help me out to resolve this point

**Comment by stevehobbsdev** [comment]
Hi @ganeshshirsath123, have you got some sample code you can share to show how you're overriding these properties?

**Comment by stevehobbsdev** [comment]
@ganeshshirsath123 Looking into this further, I've successfully managed to override `blankErrorHint` as follows:

```js
var options = {
    languageDictionary: {
        blankErrorHint: 'The field is blank!'
    }
}
```

Which results in this being displayed:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/766403/67682982-695bc080-f988-11e9-9699-c4811e13d4ac.png">

If you're still having trouble getting this to work, please feel free to continue the conversation.
