### ISSUE TITLE
Using PT language file results in unknow key errors

### ISSUE THREAD

**Issue by Jelle-vz** [auth0/lock#1729]
**Thank you for using Lock!**

### Description

When trying to get the Portugese language using `pt` as the language option, the language doesn't load and the console will fill with warnings:

- language does not have property success
- language does not have property blankErrorHint
- language does not have property codeInputPlaceholder
- Etc.

![Screenshot 2019-09-23 at 13 36 38](https://user-images.githubusercontent.com/18547621/65423159-ae7c5800-de08-11e9-83fd-0e82910d576f.png)

I see that the `pt` version is not listed on https://auth0.com/docs/libraries/lock/v11/i18n, but when i check the git repo, the file is available (https://github.com/auth0/lock/blob/master/src/i18n/pt.js).

### Environment
* Lock version: 11.17.2
* Browser version: Chrome 76
* OS: Mac OS 10.14.6

### Reproduction
Reproducable by requestion `pt` language in local setup or will be happy to share test environment privately

**Comment by Jelle-vz** [comment]
I see that the issue has been fixed! Please accept PR https://github.com/auth0/lock/pulls

**Comment by luisrudge** [comment]
fixed by https://github.com/auth0/lock/pull/1726
