### ISSUE TITLE
_enableIdPInitiatedLogin doesn't work with redirect: false

### ISSUE THREAD

**Issue by dgilling** [auth0/lock#1731]
When _enableIdPInitiatedLogin is set to true, and auth.redirect is set to false. The identity initiated login doesn't work. Yet setting auth.redirect to true is a horrible experience for single page apps. Looks like parseHash is not called?

**Thank you for using Lock!**

In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

* [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [ ] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [ ] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version:
    "auth0": "^2.20.0",
    "auth0-js": "9.11.3",
    "auth0-lock": "11.17.2",
* Browser version:
* OS:
* Additional extensions/libraries that might be affecting your instance:

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code snippet or sample project that reproduces the bug
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by stevehobbsdev** [comment]
@dgilling Thanks for your patience.

> The identity initiated login doesn't work

Can I have some more detail around this? What's the expected vs. current behaviour? Are you getting any errors either in the browser developer console or the Auth0 log dashboard?

**Comment by dgilling** [comment]
I want to have an IdP initiated login, yet when we set _enableIdPInitiatedLogin to true, it doesn't work. We are using embedded lock and have redirect set to false (as we are a single page app we don't want a real redirect). Seems like _enableIdPInitiatedLogin doesn't work when no redirect takes place.

**Comment by dgilling** [comment]
Haven’t heard back a resolution.

**Comment by stevehobbsdev** [comment]
I'm trying to get an answer for this now, sorry it's taken so long. Part of the problem is I don't have an easy way to test and validate this, so please bear with me a little longer while I do that.

**Comment by dgilling** [comment]
OK, thanks!

**Comment by stevehobbsdev** [comment]
@dgilling 👋  Again, apologies for the length of time this has taken.

I'm afraid you might be out of luck combining these two options.

Using `redirect: false` here causes the login dialog to be displayed in a popup window, which is the desired effect. In this mode, however, it's no longer looking at the URL fragment for the authentication result, and is instead expecting a response through `postMessage`.

Now this would normally be fine, except combining this with `__enableIdpInitiatedLogin` causes this not to work, as in this mode the authentication result is **only** delivered through regular redirect-based modes (query or fragment), or when using the `form_post` response type. The IdP simply cannot use `postMessage` in this configuration using an IdP-initiated flow.

The recommendation is:

* Do not use `redirect: false` when using an IdP-initiated flow; use a different callback for when the login should be IdP initiated with the appropriate Lock configuration, or
* Do not use IdP-initiated mode for OIDC. Instead, use a flow where the party that wishes to initiate login for a client uses the client’s “initiate login uri”. The client will start an authorization process with the IdP itself while not compromising its capability to use state/nonce for CSRF protection

Apologies if that's no longer useful to you after all this time but unfortunately those are the recommendations. Will close for now but feel free to continue the conversation if need be.
