### ISSUE TITLE
ConnectionResolver wipes out email address/username and gives validation error first time....

### ISSUE THREAD

**Issue by clechner77** [auth0/lock#1732]
### Description

Using lock.js v11.17.2 – I have two database connections and am using connectionResolver to swap them based on if an email is entered or a username.

Connection A = EMAIL ADDRESS is used to log in
Connection B = USERNAME is used to log in. Connection B is set as DEFAULT

If I put an email address in (and password) and hit submit, it wipes out the email address and gives me a validation error that it can’t be blank. If I put the email address back in again and submit, it authenticates just fine.  Additional troubleshooting note, if I put in the wrong password, then change from email to username and hit submit, I get a validation error about it not being in email format.   Seems like this is validation getting in the way here......

Nothing special in code, pretty much identical to your sample…

connectionResolver: function (username, context, cb) {
var isEmail = username.indexOf(’@’) !== -1;
connection = isEmail ? ‘ConnectionA’: ‘ConnectionB’
cb({ type: ‘database’, name: connection });
}

--------------------------------
Here's the full code...... I stripped most anything non-vanilla out and it still happens....

    var connection = null, config = {
      allowWindowsAuth: false,
      clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
      auth0Domain: "xxx.auth0.com",
      options: {
        container: "auth0-lock-widget-container",
        auth: {
          responseType: 'token id_token',
          params: {
            state: getParameterByName('Source'),
            protocol: 'wsfed',
            scope: 'openid email user_metadata'
          }
        },
        defaultDatabaseConnection: 'Connection B',
        connectionResolver: function (username, context, cb) {
          var isEmail = username.indexOf('@') !== -1;
          connection = isEmail ? 'Connection A': 'Connection B'
          localStorage.setItem("connection", connection);
          console.log("setting connection: " + connection);
          cb({ type: 'database', name: connection });
        },
      }
    };

    var lock = new Auth0Lock(config.clientID, config.auth0Domain, config.options);

      window.onload = function () {
        console.log("onload...");
        if (config.allowWindowsAuth) {
          document.getElementById("windowsauthblock").style = '';
          document.getElementById("windowsauthbutton").href = '/_windows/default.aspx?ReturnUrl=' + getParameterByName('ReturnUrl') + '&Source=' + getParameterByName('Source');
        }
        document.getElementById("auth0-lock-container").style = '';
        lock.show();
      }

### Environment
* Lock version: 11.17.2
* Browser version: Multiple browsers, Chrome, Firefox, Edge Chromium verified
* OS:  Win10
* Additional extensions/libraries that might be affecting your instance: NA

**Comment by clechner77** [comment]
Might as well re-open this since it's still an issue.  I would think the above should be simple enough.  Two database connections.  User enters an email, it chooses connection A.  User does not enter an email, connection B is used.

**Comment by danwoda** [comment]
Tested this and can confirm. I couldn't find a way around it, since the resolver runs on submit. Here's a screen cap I took to confirm the issue.


![connectionResolverIssue](https://user-images.githubusercontent.com/49003466/90663623-bdc57a80-e1fe-11ea-9d79-d306282e6d20.gif)

**Comment by clechner77** [comment]
This is baffling to me as I know people actively use connection resolver.  I don't mean it negatively, I just can't believe more haven't raised this issue.  Note, I saw that connection resolve was originally working onblur of the username input, which is where I'd expect it to be.  

That coincides with my biggest nitpick about lock, the lack of built-in access to add functionality to various events.  That said, it's the safe approach and probably works for 90%+ of your consumers, so it's probably the smartest decision.

**Comment by danwoda** [comment]
I was surprised to not find more requests for a way to have a username connection and an email connection play nicely together. I couldn't find many people requesting it, but it is somewhat unique of a scenario.

Regardless, I went through it with @stevehobbsdev and its on our radar.

Thanks for your patience, I know this issue was reported some time ago.

**Comment by clechner77** [comment]
Me too.  One of the most frequent issues/requests I deal with is the conversion from some sort of non-email username over to email.  Nobody originally planned on email addresses as a unique identifier and now that's just how it is.  Appreciate you guys working on it.  Hopefully there are a few more requests and the time will be worthwhile.
