### ISSUE TITLE
Chrome SameSite attribute warning

### ISSUE THREAD

**Issue by robertedjones** [auth0/lock#1734]
### Description

Google Chrome now shows the following warning: 
A cookie associated with a cross-site resource at http://auth0.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

### Reproduction

Use lock.js

### Environment

SPA eact app using auth0-lock 11.7.2 & auth0-js 9.11.2

**Comment by ramirs** [comment]
Found this on Auth-0's community site, they're aware of the issue

https://community.auth0.com/t/chrome-warning-message-samesite-cookie/31752

**Comment by stevehobbsdev** [comment]
@robertedjones Thanks for raising the issue. As @ramirs pointed out, we're aware:

> It is a change to Chrome’s cookie protocol, scheduled to go live with Chrome 80 in Feb 2020. We are aware of the change in policy and are prepared for the Feb release.

**Comment by Serfenia** [comment]
@stevehobbsdev We're still seeing this error with the following versions:
- auth0-lock: 11.21.1
- auth0-js: 9.12.2

When will this get fixed in the lock library? It's already february.

**Comment by stevehobbsdev** [comment]
Hi @Serfenia, could you let me know which cookie it's complaining about?

The warning is really more to do with Auth0 server than with Lock or our other JavaScript SDKs. There's nothing that can be done in the SDK itself. We have already made the changes on the server and you should find that the cookie is being set with `samesite=None` (you can inspect this in the network or application tabs).

The warning is probably coming from the `auth0_compat` compatibility cookie that we set for browsers that don't support the `sameSite=None` attribute. If so, it's nothing to worry about. You can read all about [the changes Auth0 are making for samesite here](https://auth0.com/docs/sessions/concepts/cookie-attributes). The thing to check for is that the `auth0` cookie in the `Set-Cookie` header on the `/authorize` request when you sign in has `sameSite=None`.

**Comment by Serfenia** [comment]
Hi Steve,

The compat cookie is indeed set. Somehow we're experiencing an /authorize call resulting in a 403, which includes cookies that do not have SameSite + Secure.

However, we're not doing anything other than initializing the Auth0lock and  using the `show`, `getUserInfo` and `hide`.

Our config:
```javascript
{
    theme: { logo: '/path-to-logo.png', primaryColor: '#ccc' },
    disableSignupAction: true,
    rememberLastLogin: true,
    languageDictionary: {
        title: 'Title'
    },
    auth: { redirect: false, responseType: 'token' },
    allowedConnections: ['google-oauth2']
}
```

Any ideas?

**Comment by stevehobbsdev** [comment]
@Serfenia Are there any clues either in the response body of that 403 or in your application logs as to what the error is?

**Comment by Serfenia** [comment]
Ah nevermind, the 403 root cause is something on our end due to being on the wrong page for checking the SSO data in the background by Auth0. However, on the correct page when `/authroize` returns a 200, we're still experiencing warning logs when on the correct page to various endpoints:

<img width="1263" alt="Schermafbeelding 2020-02-04 om 15 10 02" src="https://user-images.githubusercontent.com/2427370/73752095-99251c00-4760-11ea-98f5-8d49ccff189e.png">

At least 1 is the `auth0_compat` for the `getUserInfo` call, but the others we cannot explain directly.
