### ISSUE TITLE
Options in Additional Sign Up filed

### ISSUE THREAD

**Issue by Bini-Saju** [auth0/lock#1738]
![sample_form](https://user-images.githubusercontent.com/37089639/66445927-306cb200-ea94-11e9-84ab-35b9a07b2baf.PNG)
![select_type](https://user-images.githubusercontent.com/37089639/66445928-306cb200-ea94-11e9-9f09-b4bb40cd1c10.PNG)

Attached are the images of how options appear in Sign Up Form.
Code:
{
    type: "select",
    name : "location",
    placeholder: "choose your location",
      options: [
           {value: "us", label: "United States"},
	   {value: "fr", label: "France"},
           {value: "ar", label: "Argentina"}
	 ],
 prefill: "us"
}

So can I have that options come below the field, similar to a drop down.

**Comment by luisrudge** [comment]
Hi there 👋  I didn't understand your request. Are you saying that you want the select options to behave like a standard `<select>` element?

**Comment by Bini-Saju** [comment]
Yes

**Comment by luisrudge** [comment]
Ok, thanks for clarifying that. I'll mark this as a feature request but, at this time, there's no plans to modify the behavior of the `select` additional signup field.
