### ISSUE TITLE
move react and react-dom to devDependencies or peerDependencies

### ISSUE THREAD

**Issue by veeramarni** [auth0/lock#1743]
### Description

We noticed that due to this package, we get older `react` downloaded even when we have the latest `react` in our `package.json`. We figure out later that this packages have direct dependency on `react` instead of as `peerDependency` or `devDependency`. 

What is the ration of using direct dependency? Can `react` and `react-dom` moved as `devDependency`? 

Noticed a few other similar issues a few months ago. Any ETA when this package uses the latest react 16?

https://github.com/auth0/lock/issues/1722

**Comment by stevehobbsdev** [comment]
Hey @veeramarni, the issue you've linked to and the resources that are linked from there are still relevant to our position today; we can't upgrade to React 16 without releasing a new major, and we have no ETA on releasing a new major currently.

Those links do have a couple of workarounds that should get you moving: [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) or by using the CDN package.

**Comment by stevehobbsdev** [comment]
👋🏻 We now have a v12 beta version that includes an upgrade to React 18 - please see [this issue](https://github.com/auth0/lock/issues/2224) and let us know what you think, or if you encounter any problems!
