### ISSUE TITLE
User is unable to login in first attempt

### ISSUE THREAD

**Issue by Nishantn4u** [auth0/lock#1747]
Hi,

We are existing customer of Auth 0.

We found the issue that even first time user input correct password, system again ask for the login and when second time user input password, user get login but it show message as “Last time you logged in with” and again user need to click on it’s user name and after that finally user redirect to success login screen.

I like to add that we have migrated lock V11.7.2.

Can some one please advise how we can fix above issue so simply user can login in first attempt. 

Thanks in Advance,
Nishant Joshi

**Comment by stevehobbsdev** [comment]
@Nishantn4u The latest version of Lock is [11.18.1](https://github.com/auth0/lock/releases/tag/v11.18.1), are you able to confirm whether or not the problem goes away when using the latest version?

**Comment by stevehobbsdev** [comment]
Closing this for now, please feel free to continue the discussion if you have anything further.
