### ISSUE TITLE
Allow signup submit to make async requests before completing sign up

### ISSUE THREAD

**Issue by bstaley** [auth0/lock#1748]
### Describe the problem you'd like to have solved

> I would like to control when or if the `signup submit` continues

### Describe the ideal solution

> Ideally if you subscribe to `signup submit` using `on` the function would expect you to return a promise or an observable. That way i could perform some functions or requests and if they fail then stop the processing of the signup.

## Alternatives and current work-arounds

> Not sure of any ATM

### Additional context

> I am trying to add database generated info to the `user_metadata` before Auth0 processes the signup request. This information is then turned into a claim.

**Comment by bstaley** [comment]
i have forked lock and committed a work around which emits 'signup success'. this will allow me sign up(auto log in disabled) -> get a notification from success -> make my calls -> have the user sign in with their newly created account with the correct claims. fyi, https://github.com/bstaley/lock

**Comment by stevehobbsdev** [comment]
@bstaley Apologies for the time it has taken to pick this up. For the workaround, please feel free to submit your PR and we can look at getting it integrated. Thanks!

**Comment by bstaley** [comment]
Looks like you guys were able to merge in some changes in late Nov. that included signup success. I have made a small change and submitted a PR for it. Let me know if you see any issues.
