### ISSUE TITLE
Custom domains is not working for Lock 11

### ISSUE THREAD

**Issue by Skrpk** [auth0/lock#1751]
### Description

I use Lock login form in my app but it's not working in safari mobile because of third-part cookies.

I know, that custom domains can help to solve this issue. I have custom domain created and already use it in emails. And now i want to make Lock request not auth0.com, but my custom domain.

As i found, i need to add `configurationBaseUrl: 'https://cdn.eu.auth0.com'` to my  Lock form options and i did it.

But nothing changed, lock sends requests to the same domain and i can't find any additional info about this.

Probably i miss something?

**Comment by zangab** [comment]
@Skrpk 
hey, do you have a solution for this?
i am also running into this issue, configurationBaseUrl is set but still doesn't work. 😞

**Comment by Skrpk** [comment]
@zangab aah, i solved it, but i don't remember how :)
Did you try to pass your custom domain as second argument when creating `Lock` instance?
Just like 
`
new Lock(
      clientId,
      customDomain, // <=== here
      options
    );
`

**Comment by zangab** [comment]
nooooooooo 😱 😭 
yeah i already do that, have been looking into several issues and stack-overflow posts but haven't found the solution yet. gotta keep searching in this case 🤓
