### ISSUE TITLE
Auth0 Lock in mobile 

### ISSUE THREAD

**Issue by Bini-Saju** [auth0/lock#1755]
Hi,

I am using auth0 lock version 11.17.3 which works perfectly in desktop, but lock screens looks small/unreadable in mobile.

It would be great if you could help me with this.

FYI Screenshots – Mobile IOS Emulator and also appears the same on real device iPhone 8 Plus

![image](https://user-images.githubusercontent.com/37089639/69502671-e5383100-0f65-11ea-902e-595232d5c8da.png)

![image](https://user-images.githubusercontent.com/37089639/69502675-f123f300-0f65-11ea-90d5-ae5feafd8974.png)

**Comment by stevehobbsdev** [comment]
@Bini-Saju This is most likely down to a missing viewport meta tag in the `head` tag of your page. The one we define in the template for the hosted one is:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

Can you try adding this and see if it solves your problem?
