### ISSUE TITLE
Why does the password policy box cuts in lock 11.18.1 

### ISSUE THREAD

**Issue by Bini-Saju** [auth0/lock#1756]
Hi,

I have upgraded my system to use lock version 11.18.1 from 11.17.3, But the password policy cuts as in the image:

![image](https://user-images.githubusercontent.com/37089639/69596060-776b3280-1055-11ea-9ae8-37003b1d85a0.png)

Note: This issue was fixed in 11.7.3 but now it is still happening. Below is the link to the same issue.
(Why does the password policy box cuts in lock?)

**Comment by Bini-Saju** [comment]
FYI-   overflow-x: auto; was removed in version 11.17.3

But following is the content in css/index.styl for version 11.18.1

 .auth0-lock-content-wrapper
    flex-grow: 1
    flex-shrink: 1
    flex-basis: auto;
    -webkit-overflow-scrolling touch;
    overflow-x: auto;

Hopefully removing   overflow-x: auto; will fix the issue

**Comment by stevehobbsdev** [comment]
@Bini-Saju Can you confirm if it works in 11.18.0?

**Comment by stevehobbsdev** [comment]
@Bini-Saju Not to worry, I've found the issue. It is because of the `overflow-x: auto` but we need to keep that to fix a different issue with the submit button on mobile views (see the associated PR). I've put in a media query to fix it for desktop.

**Comment by stevehobbsdev** [comment]
@Bini-Saju Also, thanks for raising this!

**Comment by Bini-Saju** [comment]
Hi, 

FYI- I know the issue on mobile views

So password policy doesn't works on 11.18.0, tried it.

It works perfectly on 11.17.3 but the lock  breaks on mobile views. So upgraded to 11.18.x works good on mobile but password cut fails.

**Comment by stevehobbsdev** [comment]
That's fine. Initially I thought the problem only came in 11.18.1, but it was actually there in 11.18.0. So the PR should fix it fine.
