### ISSUE TITLE
Email address not trimmed/lowercased using new universal login experience 

### ISSUE THREAD

**Issue by jpagand** [auth0/lock#1757]
Using the universal login with the new experience and the default login page, I noticed a high number of `Failed Login (invalid email/username)` errors in the logs.
From the logs I can see that the `user_name` value got a trailing space in most of the case.
I cannot find a way to enforce trim on my side. I looked at the rules but it seems they are applied after the authentication

Edit: After further tests, I confirm `user_name` is not trimmed nor lowercased for **sign in** but it is for **sign up**

_I'm not sure it's the right place for this issue but it's the best place I could have found_

**Comment by stevehobbsdev** [comment]
@jpagand No unfortunately this isn't the right place. This SDK is only concerned with the old "classic" Lock experience whereas the new Universal Login Page is something different.

Can I ask you to redirect this issue to the [community forums](https://community.auth0.com)?
