### ISSUE TITLE
Xcode signing error for ionic apps

### ISSUE THREAD

**Issue by hzalaz** [auth0/lock#176]
When submitting an ionic app for AppStore review, the validation process fails due to the presence of the `bin` directory and its contents which are expected to be signed by the Apple Developer. 
This is clearly an Xcode bug, but until its solved by Apple we should at least rename that folder to avoid this annoyance.

**Comment by cristiandouce** [comment]
@hzalaz would it work the ignore of the directory from bower and npm?

**Comment by hzalaz** [comment]
@pose already fixed this in 8baa4a5022a512c138b779875f08803162e26859
