### ISSUE TITLE
Display Enterprise Connections Buttons

### ISSUE THREAD

**Issue by mario-moura-silva** [auth0/lock#1763]
### Describe the problem you'd like to have solved

When is created an Enterprise Connection is not displayed on the Lock.js widget.

### Describe the ideal solution

Add the possibility to allow display Enterprise Connection.

## Alternatives and current work-arounds

Manipulating/changing the DOM

### Additional context

N/A

**Comment by stevehobbsdev** [comment]
Sorry for the lack of comms around this issue. Lock can and does display enterprise connections, but cannot display them at the same time as other social connections if you have them enabled. You can only use one or the other.
