### ISSUE TITLE
Configurable Signup tab HRD support for Lock

### ISSUE THREAD

**Issue by Cody-Mansfield** [auth0/lock#1768]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> Lock handles HRD in login and forgot password, some customers desire a configurable HRD support for sign up tab. UX is not consistent.

### Describe the ideal solution

> A way to toggle hrd support for signup so customers can choose to handle enterprise domain signups as they see fit and improve UX (i.e. blocking un/pw signup for those domains). The way forgot password throws a "contact your admin" message and disables the submit button could be a configurable option for signup.

## Alternatives and current work-arounds

> Right now it seems we can only change the sso-enabled languageDictionary, UX is not consistent.

### Additional context

> Having this be a supported configuration is desirable, customers customizing UX based on events/triggers may encounter breaking changes in the future.

**Comment by stevehobbsdev** [comment]
Reopening, this should be investigated

**Comment by stevehobbsdev** [comment]
Apologies that the stalebot has gotten involved here thanks to a lack of activity on our part.

This is not on our roadmap to implement, so I will close the issue for now.
