### ISSUE TITLE
Ability to link to privacy policy and terms of service

### ISSUE THREAD

**Issue by sholladay** [auth0/lock#1782]
### Describe the problem you'd like to have solved

When a user signs up in my application (using the hosted login page), they see the "By signing up, you agree to our terms..." text. It's nice, but the user has _no idea_ what the terms of service or privacy policy _actually say_. They have no way to access them from the login page. That makes the text feel rather ominous and frustrating.

How do I set up links to the ToS and privacy policy?

### Describe the ideal solution

> A clear and concise description of what you want to happen.

Perhaps a couple of new options, such as `privacyPolicyUrl` and `termsOfServiceUrl`, should be added to Lock. But I don't know how this would play nice with `languageDictionary`. Maybe they would be used by default if the text was not overridden.

Alternatively, some sort of templating system for `languageDictionary` would work. Perhaps the template could contain markers for where the `<a>` HTML tags would go. Or some sort of limited support for [markdown](https://daringfireball.net/projects/markdown/) could be added.

## Alternatives and current work-arounds

None that I am aware of, beyond customizing the login page source code and using some hacky JavaScript.

### Additional context

<img width="373" alt="Screen Shot 2020-01-16 at 5 54 00 PM" src="https://user-images.githubusercontent.com/3674950/72569780-350de700-3889-11ea-993c-c9d0b411ead8.png">

**Comment by MarcMagdi** [comment]
You can add signUpTerms to languageDictionary with what ever HTML you need:
https://github.com/auth0/lock/blob/master/src/i18n/en.js

Ex: 
```javascript
languageDictionary = {
          signUpTerms:
            "By signing up, you agree to our <a href='domain.com/terms/' target='_blank'>Terms of Service</a> and <a href='domain.com/privacy-policy/' target='_blank'>Privacy Policy</a>."
        }
```

**Comment by sholladay** [comment]
Ah, I was under the impression that `languageDictionary` did not support HTML. It would be nice to explicitly mention that in the docs.

**Comment by jasonbarry** [comment]
@MarcMagdi I agree with @sholladay – arrived here looking for the same thing.

**Comment by tihuan** [comment]
Hi there! Sorry for reviving an old thread 🙏 Is it possible to add `signupTerms` to "Sign In" page too? Something similar to:

<img width="379" alt="Screen Shot 2020-10-22 at 2 54 14 PM" src="https://user-images.githubusercontent.com/6309723/96934157-9ac17c00-1476-11eb-8483-abc9ee281952.png">

The mock above is done via:

```ts
const content = document.getElementsByClassName("auth0-lock-content")[0];
const span = document.createElement("span");

span.innerHTML =
  "<small class='auth0-lock-terms'>By continuing, you agree to cellxgene's <a href='https://cellxgene.cziscience.com/static/cellxgene/deploy/tos.html' target='_blank' rel='noopener'>terms of service</a> and <a href='https://cellxgene.cziscience.com/static/cellxgene/deploy/privacy.html' target='_blank' rel='noopener'>privacy policy</a>.</small>";

content.appendChild(span);
```

But there doesn't seem to be an event to hook into when the "Sign In" form is rendered, so currently is done using the `lock.on("show", () => { ... })` callback, which the DOM elements get deleted after Sign In form is rendered 🤔 

Thank you!
