### ISSUE TITLE
Uncaught can't find relay frame

### ISSUE THREAD

**Issue by robertedjones** [auth0/lock#1786]
### Description

Using a SAML Enterprise connection with Salesforce as the identity provider does not work on a mobile device that has the Salesforce mobile app installed. The authentication looks like it happens but it hangs on the login/callback?connection=xxxxx page. The console has this error: Uncaught can't find relay frame.

### Reproduction

Set up a SAML Enterprise connection with Salesforce as the identity provider. Install the Salesforce mobile app on an Android device. Try to sign in using SAML username.

### Environment

auth0-lock = ^11.20.3
reactjs
firebase hosting

**Comment by stevehobbsdev** [comment]
Thanks for raising @robertedjones. Have you managed to reproduce this in any simpler cases? We also have #1725 which sounds like it might be a similar thing.

**Comment by robertedjones** [comment]
@stevehobbsdev  as of yet I have been unable to.

**Comment by stevehobbsdev** [comment]
This is something that we have not been able to reproduce, so I will close the issue for now. Please feel free to raise another issue if some more reproducible steps can be defined.
