### ISSUE TITLE
Auth0 Chrome SameSite issue

### ISSUE THREAD

**Issue by gmrao** [auth0/lock#1797]
Chrome console is showing warning for Chrome restriction for cross site cookies. We are using auth0 lock 11 sdk. Is auth0 lock releasing any fix for the below issue?

A cookie associated with a cross-site resource at http://auth0.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by Sieabah** [comment]
On the topic of cookies, why does the extension create a new cookie on every page load and not clean up after itself? This created an issue where we had some 100 nonce cookies that we clear on page load

```
Object.keys(Cookies.get())
    .filter(c => c.trim().match(/^com\.auth0\.auth/))
    .forEach(c => Cookies.remove(c));
```

**Comment by stevehobbsdev** [comment]
@gmrao Please see [this community issue](https://community.auth0.com/t/auth0-chrome-samesite-issue/37614/2) which should hopefully explain what you're seeing.

@Sieabah This is unrelated - please can you raise a new issue?
