### ISSUE TITLE
Email input is rendering with type="text"

### ISSUE THREAD

**Issue by otaviobps** [auth0/lock#1798]
### Description

Basically I implemented lock and the email input field type attribute is rendering like "text" instead of "email". 

`<input type="text" id="1-email" inputmode="email" name="email" class="auth0-lock-input" placeholder="yours@example.com" autocomplete="off" autocapitalize="off" aria-label="Email" aria-invalid="false" value="">`

This causes troubles in mobile devices.

I'm using React and I'm rendering the `Lock` component like this:

```
const lock = new Auth0Lock(AUTH_CONFIG.clientId, AUTH_CONFIG.domain, {
        auth: {
            responseType: "token id_token",
            params: {
                scope: "openid email profile",
                audience: "..."
            },
            sso: false
        },
        container: AUTH_CONFIG.container,
        theme: {
            primaryColor: "#3a99d8"
        },
        language: i18n.language === "en-US" ? "en" : i18n.language
    });

return <div id={AUTH_CONFIG.container} />
```

I don't have access to the `input` element, and I couldn't find a way to override the `input type` attribute.

Is there any option to pass to lock that changes this behavior?

### Environment

> Please provide the following:

- **Version of this library used:** 11.20.3
- **Version of the platform or framework used, if applicable:** React 16.12.0
- **Other relevant versions (language, server software, OS, browser):** Firefox and Chrome
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@otaviobps There is no option you can pass in I'm afraid. Could you tell me more about the issues this causes on mobile?

**Comment by otaviobps** [comment]
Hi @stevehobbsdev, the problem is that in some phones when typing the e-mail the autocorrection tool understands that this field is a text field and correct the e-mail to text, i.e., while typing this e-mail: firstname.lastname@gmail.com, the autocorrection tool transforms it to Firstname. Lastname@gmail. Com

Setting the field to `type=email` would make the autocorrection understand this is an e-mail field and disable the correction

**Comment by stevehobbsdev** [comment]
@otaviobps Thanks for that!

**Comment by stevehobbsdev** [comment]
@otaviobps I'm looking into this now. Can you let me know of any specific devices you're seeing this issue with? I'm testing with a few virtual devices but they don't exhibit this problem; just want to make sure I can reproduce and subsequently fix it.

**Comment by otaviobps** [comment]
Hey @stevehobbsdev, nice to know you are into this issue. I have an Android phone, OnePlus 7+, using Firefox. Phone and browser updated to the latest version. Here is the screenshot:

![image](https://user-images.githubusercontent.com/28715087/74537678-58c05d80-4f19-11ea-8661-52bfb7464a69.png)

I noticed that this doesn't happen on my girlfriend's phone, which is an iPhone 7+, using Safari.

So yes, it may be specific to some browsers. But I guess that changing the html input type attribute should solve the issue.

**Comment by stevehobbsdev** [comment]
Great! I've managed to reproduce it now and the associated PR appears to fix it. Thanks for raising this!
