### ISSUE TITLE
Broken scrolling (started with v11.19.0)

### ISSUE THREAD

**Issue by robbiehanson** [auth0/lock#1800]
### Description

We support a lot of different login providers, and this normally works fine with Auth0:

![Screenshot](https://resources.storm4.cloud/bugReports/auth0_lock_good.png)

But starting with v11.19.0, the UI no longer displays the options properly:

![Screenshot](https://resources.storm4.cloud/bugReports/auth0_lock_bad.png)

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

- Configure an auth0 app that has a lot of login options.
- Create a react app using something like `npx create-react-app test`
- Add auth0: `npm install auth0-lock`
- Configure & show the auth0 lock window
- Notice that scrolling is broken in all versions from current, back to and including v11.19.0
- Downgrade to v11.18.1: `npm install auth0-lock@11.18.1`
- Notice that scrolling is working perfectly

### Environment

> Please provide the following:

- **Version of this library used:** v11.19.0
- **Version of the platform or framework used, if applicable:** create-react-app
- **Other relevant versions (language, server software, OS, browser):** macOS 10.15.3, Brave v1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Sounds like the same issue as #1783. Let me raise a PR which should fix this.

**Comment by stevehobbsdev** [comment]
@robbiehanson I've raised a PR which fixes the broken container but there are tradeoffs with the scrollbars - please contribute to the PR discussion if there are blocking concerns.
