### ISSUE TITLE
Example for third-party cookies misleading

### ISSUE THREAD

**Issue by highway900** [auth0/lock#1806]
### Description

reassignment of `auth0` in example 
https://github.com/auth0/lock/blob/e6a0dbd53d29215317c83fa1da65948a1c319418/support/callback-cross-auth.html#L7

https://github.com/auth0/lock/blob/e6a0dbd53d29215317c83fa1da65948a1c319418/support/callback-cross-auth.html#L12 

`auth0` is reassigned and misleading what should be used to call `crossOriginVerification()`

Which object do I call the function from?

### Reproduction

Nothing to reproduce the code is not erroneous but that is javascript for you.  

### Environment

https://github.com/auth0/lock/blob/e6a0dbd53d29215317c83fa1da65948a1c319418/support/callback-cross-auth.html#L12

**Comment by stevehobbsdev** [comment]
Thanks for this @highway900!
