### ISSUE TITLE
Any plans to upgrade React?

### ISSUE THREAD

**Issue by inssein** [auth0/lock#1814]
### Describe the problem you'd like to have solved
Any recent React project (> 16) that uses `auth0-lock` has to live with two versions of react being included in their application. This adds quite a bit to the bundle size.

### Describe the ideal solution

For `auth0-lock` to use version 16 of React.

## Alternatives and current work-arounds

Do nothing, live with a large bundle size.

**Comment by stevehobbsdev** [comment]
@inssein Unfortunately upgrading the version of React would require a new major version of Lock to be released. As we have no plans to release a new major version, we cannot at this time upgrade the version of React.

There is more info and some possible workarounds for you [in this issue](https://github.com/auth0/lock/issues/1761).

**Comment by stevehobbsdev** [comment]
👋🏻 We now have a v12 beta version that includes an upgrade to React 18 - please see [this issue](https://github.com/auth0/lock/issues/2224) and let us know what you think, or if you encounter any problems!
