### ISSUE TITLE
v11.22.4 does not contain a "build" directory

### ISSUE THREAD

**Issue by stanimoto** [auth0/lock#1823]
### Description

The released package of the version [v11.22.4](https://github.com/auth0/lock/releases/tag/v11.22.4) does not seem to contain a `build` directory at all while the previous versions do. I was not able to find a related change to the release process. Is this an intentional change?

Best,

**Comment by stevehobbsdev** [comment]
@stanimoto What is your requirement for having the build directory available? This should not be used at runtime.

**Comment by stanimoto** [comment]
Hi @stevehobbsdev ,

We have been generating a concatenated file from `build/lock.min.js` and our own code and other libraries in the build process.

Thanks!

**Comment by stevehobbsdev** [comment]
@stanimoto We actively exclude that folder from git and from the npm package. Is there a chance that the build step was manually invoked after installation in the past and that folder has been hanging around?

Also, can you let me have a specific version number where the build folder is included?

Either way, this isn't really a scenario we encourage nor support.

**Comment by stevehobbsdev** [comment]
Closing this for now but feel free to continue the discussion if you need to.
