### ISSUE TITLE
Authenticate users secondary account for account linking without overriding the currently logged in (primary) account

### ISSUE THREAD

**Issue by 814k31** [auth0/lock#1824]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> I would like to be able to authenticate a secondary account without it affecting my current accounts status
> I'm really only needing the sub from a secondary user account, although I'm struggling to get that without it overriding the initial logged in account.
> A solution without use of the management api would be ideal...

### Describe the ideal solution

>- User logs in with primary account `lock.show()`
>- User Initiates Account Linking on secondary account `lock.show({ remember: false })`
>- User Authenticates with secondary account 
>- User fetches primary user profile `lock.getUserInfo()`
>- User triggers linking on primary user profile with secondary `linkAccount(authResult.idToken, authResult.idTokenPayload.sub);`

## Alternatives and current work-arounds

> Saving the user_id into local storage and fetching the primary user profile using the management api

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by 814k31** [comment]
My use case has changed a little as my understanding of auth0 has developed

I want to be able to authenticate an account that doesn't get triggered in the checkSession method...
is that possible?

```jsx
lock.show(); // authenticate primary
// page refreshes and gets routed to callback link
lock.show({ remember: false }) // authenticate secondary
// page refreshes and gets routed to callback link
lock.checkSession(); // get the session of the primary because the secondary was a one time authentication
lock.getUserInfo(accessToken); // gets the user info of the primary
```

My current work around is
```jsx
lock.show(); // authenticate primary
// page refreshes and gets routed to callback link
localstorage.set('accessToken', accessToken);
lock.show(); // authenticate secondary to get sub
// page refreshes and gets routed to callback link
localstorage.get('accessToken', accessToken);
lock.getUserInfo(accessToken); // gets the user info of the primary
// Link accounts
link(accessToken, secondarySub);
lock.checkSession(); // return the session of the primary
```

**Comment by 814k31** [comment]
Is that supposed to be the use case for defaultDatabaseConnection?

https://auth0.com/docs/libraries/lock/v11/configuration#defaultdatabaseconnection-string-

I gave it a go but didn't seem to work...

**Comment by stevehobbsdev** [comment]
@814k31 Please correct me if I'm wrong, but it sounds like you're trying to authenticate two different accounts in the same browser session, do I have that right?

> Is that supposed to be the use case for defaultDatabaseConnection?

With Auth0 you can set up multiple user databases in addition to the default one that we create for you; this setting allows you to control which database you hit when you log in. If my first assumption is correct then I don't think this setting is relevant for you.

**Comment by 814k31** [comment]
@stevehobbsdev yes thats correct!

I'm trying to find a nice approach to the user initiated account linking. Where our use case uses auth0 to link for data although not to be used for logging in.

I currently have it working using the above flow

although if the link function breaks for whatever reason I am forced to log the user out which means there's a chance for a really poor ux experience

**Comment by stevehobbsdev** [comment]
@814k31 Does anything in [this guide](https://auth0.com/docs/users/references/link-accounts-user-initiated-scenario) help you at all?

**Comment by 814k31** [comment]
@stevehobbsdev the guide helped me get my current work around though it wasn't completely appropriate for my flow of authentication

Mainly it was the reloadProfile part was the hardest to get working

Though I was trying to avoid using the management api to reload the profile so I can maintain my current app loading flow and also due to restrictions on my backend I had to retrieve the primary user profile beforehand to check if it's okay to link

I'm satisfied with the current workaround though so feel free to close the issue if it's not something that is in the pipeline :)
