### ISSUE TITLE
Lock shows select connection popup when there is only one available connection

### ISSUE THREAD

**Issue by 814k31** [auth0/lock#1825]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Using auth0-js you can provide `connection: 'service'` as an option and it will automatically go to the services authentication page.

### Reproduction

> lock.show({ allowedConnections: ['google-oauth2'] });
> Should not provide a popup?
![Screen Shot 2020-03-10 at 4 16 46 pm](https://user-images.githubusercontent.com/9160551/76292644-8f0bb580-62ea-11ea-8f68-1379f534ccfc.png)

### Environment

> Please provide the following:

- **Version of this library used:** `11.22.4`
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** `[english, NA, Mac, Chrome]`
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@814k31 To confirm, is the expected behaviour to automatically select the one login option if there is only one? (Google in this case).

**Comment by 814k31** [comment]
@stevehobbsdev sorry for the delay

Yeah that sounds right! Or at least thats what happens when I used auth0-js
Do you know if there's a configuration option I missed?

**Comment by stevehobbsdev** [comment]
@814k31 Sorry for the delay too! We don't have this feature in Lock currently. Yes, you can do this with Auth0.js but all you're really doing there is passing the `connection` param to Auth0 server, which is doing all the magic in terms of redirecting you to the social IdP.

With Lock, there is no interaction with the server until you click a login link, but we don't have the facility to redirect you there automatically.
