### ISSUE TITLE
Issues with version 11.22.4 - "build" folder is missing

### ISSUE THREAD

**Issue by Nemanja-Milojevic** [auth0/lock#1831]
Hi, I may be missing something but I'm getting an error with the latest version (11.22.4)

> Failed to instantiate module auth0.lock due to: Error: Auth0Lock must be loaded.

but if I downgrade to version 11.22.3 it works fine. As far as I can tell, the build folder is missing from the latest version which is causing my app to not work. 

I already saw this issue https://github.com/auth0/lock/issues/1823 where you guys said that you have been excluding the build folder for a long time, but in version 11.22.3 it is available. So I'm not sure if this is causing the issue or something else. I'm using angular js
Thanks in advance

**Comment by Nemanja-Milojevic** [comment]
@stevehobbsdev here's the full error that I'm getting
https://imgur.com/CJtCiCF

I'm using bower to install the library so I'm expecting it to be in `bower_components/auth0-lock`. The only change I made is I updated auth0-lock version in bower.json from 11.22.3 to 11.22.4 and the app is not working anymore. From what I can tell the only difference is that the build folder is missing (not sure why it is needed or if it is that that is actually causing the error).

11.22.3 version
https://imgur.com/X1fCbep

11.22.4 version
https://imgur.com/cScAe5v

I'm using "auth0.js": "^9.12.2", "angular": "~1.5.8" and bower 1.8.8

**Comment by stevehobbsdev** [comment]
@Nemanja-Milojevic Thanks for the extra context here - let me take a look

**Comment by stevehobbsdev** [comment]
I've confirmed the behaviour but can't see anything in the codebase that has changed [in between v11.22.3 and v11.22.4](https://github.com/auth0/lock/compare/v11.22.3...v11.22.4) that would have caused this. Let me have a look into our build script.

**Comment by stevehobbsdev** [comment]
@Nemanja-Milojevic We've identified the issue as being down to a build failing on our internal Jenkins build, which takes care of creating the GitHub tag and pushing the release to NPM, amongst other things. As such, the latest release was tagged with an archive that unknowingly did not include the build folder. Had the Jenkins build passed, this would have been included.

The only way to fix this is to release a new version, which will be happening very shortly.

**Comment by adamjmcgrath** [comment]
Hi @Nemanja-Milojevic 

We've release [11.22.5](https://github.com/auth0/lock/releases/tag/v11.22.5) which has the [build folder](https://github.com/auth0/lock/tree/v11.22.5/build)

Can you check if this version works for you?

**Comment by stevehobbsdev** [comment]
Closing this for now as the new release has the build folder available in the release archive. @Nemanja-Milojevic if you're still having problems, please feel free to continue the discussion.
