### ISSUE TITLE
Password requirements popup gets cut off (regression)

### ISSUE THREAD

**Issue by crab-apple** [auth0/lock#1832]
This issue has already popped up (no pun intended) a few times:

https://github.com/auth0/lock/issues/1705
https://github.com/auth0/lock/issues/1636

I can't reproduce the issue in v11.21. However, as of v11.22, it's happening again.

## Description

The password strength fade in gets cut off because the main content container is not allowing overflow

## Reproduction

    Go to sign up.
    click on password
    type a single character

At this point the hint should appear showing the password requirements. If there are a log of requirements the hint gets cut off.

## Environment
    Lock version: 11.22.4
    Browser version: Firefox 74.0 (64-bit)
    OS: Ubuntu 16.04

**Comment by crab-apple** [comment]
The other times this issue has appeared, it seems to have to do with the styling for the selector `.auth0-lock.auth0-lock .auth0-lock-content-wrapper`, and specifically the rules for overflow.

The PR https://github.com/auth0/lock/issues/1832 changed such rules for 11.22.0, so I guess that may be the cause.

**Comment by stevehobbsdev** [comment]
@crab-apple Thanks for raising this. Yes we noticed the regression and are working towards a fix. The problem is as you rightly point out, an issue with the overflow setting. It's necessary for the layout to work on mobile but when we change it for desktop it breaks other things. We're in a position where fixing this breaks something else, so that's what we're trying to figure out.

Actively working on this, will keep you posted.

**Comment by jacobedawson** [comment]
@stevehobbsdev If the issue is with desktop vs mobile, could you just set an @media rule that adds / removes the overflow based on screen-width?

**Comment by stevehobbsdev** [comment]
> @stevehobbsdev If the issue is with desktop vs mobile, could you just set an @media rule that adds / removes the overflow based on screen-width?

Yes and is what we do now. However, doing this breaks another element of the layout where the content breaks out of the container when the height is reduced. We thought we’d fixed this by specifying the `overflow-y` rule but this resulted in the regression we see here with the password strength UI.
