### ISSUE TITLE
phone_number_input has no validation hint/msg

### ISSUE THREAD

**Issue by blankg** [auth0/lock#1836]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using passwordless login with phone_number_input, if user enters illegal chars (for example +444-5555) there is a client side validation using a numbers only regex. The only indication user has is a red line under the input. We got feedbacks from users they could not understand what is wrong.
A simple invalidhint string with something like "invalid phone number. only numbers are allowed" would make a big difference.

### Reproduction

In a passwordless login screen just enter a phone number with invalid chars like +5874-4444 or similar
### Environment

"auth0-lock": "11.22.2"

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks @blankg, let's talk about this on the PR.
