### ISSUE TITLE
loginAfterSignup === true can fail silently

### ISSUE THREAD

**Issue by heskew** [auth0/lock#184]
This happens pretty consistently in a Chrome Incognito window. The sign up process seems to go well but the auto-login fails with the popup closed check indefinitely stuck checking.

![auto-login](https://cloud.githubusercontent.com/assets/132403/8320146/fc5de620-19cb-11e5-84c8-d2c067649b66.png)

**Comment by hzalaz** [comment]
Can't be reproduced in latest version. Please reopen if needed
