### ISSUE TITLE
Getting these issues after "expo start" in terminal 

### ISSUE THREAD

**Issue by mortezahaidari** [auth0/lock#1840]
Hi,

I keep getting this issues, 
the app loads, but log in button does not lead anywhere, and the given error below is printed.
What can i do, i have already tried auto linking, but still the same!
Thanks beforehand!

Missing NativeModule. React Native versions 0.60 and up perform auto-linking. Please see https://github.com/react-native-community/cli/blob/master/docs/autolinking.md.
- node_modules/react-native-auth0/src/webauth/agent.js:34:23 in Agent#newTransaction
- node_modules/react-native-auth0/src/webauth/index.js:58:43 in WebAuth#authorize
* App.js:43:15 in _onLogin
- node_modules/react-native/Libraries/Components/Touchable/TouchableOpacity.js:264:45 in createReactClass$argument_0.touchableHandlePress
* [native code]:null in touchableHandlePress
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:880:34 in TouchableMixin._performSideEffectsForTransition
* [native code]:null in _performSideEffectsForTransition
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:779:44 in TouchableMixin._receiveSignal
* [native code]:null in _receiveSignal
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:490:24 in TouchableMixin.touchableHandleResponderRelease
* [native code]:null in touchableHandleResponderRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:555:30 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:722:42 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:744:20 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:907:29 in executeDispatchesAndRelease
* [native code]:null in forEach
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:887:16 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:932:21 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1096:19 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2796:6 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18791:14 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2870:28 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
![Screenshot 2020-04-02 at 03 36 11](https://user-images.githubusercontent.com/20289413/78201902-1afca180-7493-11ea-819b-3d1ef14c9864.png)

**Comment by stevehobbsdev** [comment]
Hi @mortezahaidari, please can you raise this on the [`react-native-auth0`](https://github.com/auth0/react-native-auth0) repository? Include as much detail as you can, including the SDK version and the version of React Native you are using.

I would urge you to not delete the GitHub issue template content as it asks for all this information that would help us to help you. Please take that into consideration when creating your new issue.
