### ISSUE TITLE
In popup mode the popup does not close in IE11

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/lock#185]
When using the Lock with Popup mode in IE11 the popup does not close when it reaches /login/callback (the end of the login flow). This is caused by IE11 protected mode.

**Comment by sandrinodimattia** [comment]
We've made a few improvements on the server side (add a P3P header) to improve IE support when running in protected mode (default behaviour).

Even with this change you might still see some issues when:

 - Running an application on localhost
 - Not using HTTPS

So this means that local development might be broken, while actual production deployments will be working fine.

To improve the local development experience you can manually disable protected mode by going to Tools, Security, Disable Protected Mode.

**Comment by pose** [comment]
@sandrinodimattia do you think we can add a note with this information in docs.auth0.com ? Thanks in advance

**Comment by sandrinodimattia** [comment]
Yes. Where do you think we can put it?

**Comment by cristiandouce** [comment]
@sandrinodimattia We need something like Lock FAQ or SOS or Troubleshoot. What do you think?

**Comment by sandrinodimattia** [comment]
Yes @pose @cristiandouce a Troubleshooting section makes sense

**Comment by cristiandouce** [comment]
:heart:

**Comment by nicosabena** [comment]
Was this ever documented?

I'm finding the exact opposite behavior: the popup window is not closed (fails) when Protected Mode is **disabled**.
The "Local Intranet" zone (the one IE uses when browsing `localhost`, and possible internal sites in a corporate environment) has Protected Mode **disabled** by default. When enabling it, it works ok.

This is the default:
![Imgur](http://i.imgur.com/dL5IW2z.png)

A fix in the Lock/WinChan code is impossible, right?

**Comment by jeffijoe** [comment]
@nicosabena me too, enabling protected mode seems to fix it for me, too.

Damn you IE, making our lives miserable since 1996.
