### ISSUE TITLE
Update the Salesforce Logo and Styling

### ISSUE THREAD

**Issue by TehNrd** [auth0/lock#1850]
### Describe the problem you'd like to have solved

The current Salesforce styling and logo is very out of date, probably 10+ years old, for the out of the box universal login page. I'd like to update this to align with the new logo and style of Salesforce. 

This is the current very outdated logo and color scheme.

<img width="336" alt="Screen Shot 2020-04-20 at 11 08 49 AM" src="https://user-images.githubusercontent.com/1007085/79769632-6075f700-82fa-11ea-8524-96ce583eebfb.png">

### Describe the ideal solution

Update the logo and colors. Salesforce does not currently have any design guidelines for a "Login with" button but here are some potential designs:

![sfdclogo](https://user-images.githubusercontent.com/1007085/79777679-98366c00-8305-11ea-9b58-5189c94f3047.jpeg)

The first matches the blue from their standard login page, https://login.salesforce.com. The other two use their primary logo color.

I'm leaning towards the first option as it matches their login page and similar logins else where, https://trailblazer.me/TrailblazerLogin. It is also the smallest change to the existing CSS.

I can submit a simple PR to tweak this but wanted to get feedback on which option is preferred first.

## Alternatives and current work-arounds

Create your own custom login page or override the CSS.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @TehNrd - let me discuss internally with the design team and get back to you.

**Comment by stevehobbsdev** [comment]
@TehNrd We've been discussing this internally and we'd welcome a PR to tweak the design. Let's go with the middle option (with the lighter blue) as it also matches the colours we use on the dashboard and our new ULP.

Thanks for raising this!

**Comment by stevehobbsdev** [comment]
Closing this for now, will keep an eye out for the PR, if one is incoming.
