### ISSUE TITLE
"Wrong email or password" message when attempting login to a connection that only uses usernames

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#186]
For example, AD uses only usernames (as prompted by the "Username" field) but the message shows "Wrong email or password". It should show "Wrong **username** or password":

![screen shot 2015-06-24 at 2 15 21 pm](https://cloud.githubusercontent.com/assets/829698/8336587/f535860e-1a7b-11e5-8042-f441ae455408.png)

**Comment by sandrinodimattia** [comment]
Same thing should happen when a database connection has been enabled for usernames.

**Comment by rolodato** [comment]
Yes, in that case the error message should correspond to whether the user entered a username or an email. "Wrong email/username or password" doesn't look too good :smile:

**Comment by hzalaz** [comment]
Already fixed in latest version of Lock (v10)
