### ISSUE TITLE
Race condition with auth0lock cookies and quick user logout

### ISSUE THREAD

**Issue by Jazzepi** [auth0/lock#1860]
### Description

Auth0Lock creates cookies and does not clean them up when calling .logout() creating a race condition if the user quickly logs out after logging in. I was able to replicate this consistently on a local machine connected to Auth0 production with little difficulty.

### Reproduction

1. A user enters credentials and clicks the login button on the Auth0Lock.
2. Immediately a user receives a nonce cookie on the domain of the website being secured by the Auth0Lock (NOT THE AUTH0 DOMAIN). I believe this happens before the HTTPS request to authenticate has been made to the auth0 domain.
This cookie begins with the com.auth0.auth. namespace.
3. The HTTPS request to the auth0 domain “authorize” endpoint succeeds and returns a 302.
4. The browser loads the new webpage with the url returned in step 3.
5. When the Auth0Lock is instantiated by Javascript it looks at the URL, cuts out the hash, stores the token, changes the URL to delete the hash, and then deletes the nonce.

Critically, in step 5 before the nonce cookie is deleted I can log myself out of my application. In this logout procedure I call logout() on the Auth0Lock object, delete our copy of the access token credentials being stored in localstorage, and then refresh the browser.

At this point the user should have had both the local application session invalidated (by deleting what was stored in local storage) and the Auth0 session, but they’re still presented with the Last time you logged in with pane. This is the core of my problem. Users should not see that screen, and they should not be able to immediately log back in.

I’m not sure what the logic is inside of the Auth0Lock to decide when to display the “login again”, but if either the auth0.ssodata or com.auth0.auth cookies are deleted the login again screen will not display which is the behavior that I expect.

So I think the fix to this is that Auth0Lock should delete the cookies that it created when .logout() is called on it instead of me having to delete those cookies for it. That way even if I logout before the nonce cookie is deleted, Auth0Lock won’t get confused and present the user with the wrong prompt.

### Workaround

As a work around I’m using this code in my logout method.

    const cookies: string[] = document.cookie.split('; ');
          cookies.forEach((cookie: string) => {
            if (cookie.startsWith('auth0.ssodata') || cookie.startsWith('com.auth0.auth')) {
              console.log(`Handling cookie ${cookie}`);
              const d = window.location.hostname.split('.');
              while (d.length > 0) {
                const cookieBase = encodeURIComponent(cookie.split(';')[0].split('=')[0]) + '=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain=' + d.join('.') + ' ;path=';
                const p = location.pathname.split('/');
                console.log(`Clearing potential cookie at ${cookieBase + '/'}`);
                document.cookie = cookieBase + '/';
                while (p.length > 0) {
                  console.log(`Clearing potential cookie at ${cookieBase + p.join('/')}`);
                  document.cookie = cookieBase + p.join('/');
                  p.pop();
                }
                d.shift();
              }
            }
          });

### Environment

- **Version of this library used:**
    "auth0-js": "^9.13.2",
    "auth0-lock": "11.21.1",

- **Other relevant versions (language, server software, OS, browser):**
chrome, javascript, windows

- **Other modules/plugins/libraries that might be involved:**
None

**Comment by stevehobbsdev** [comment]
Thanks for raising this @Jazzepi, leave it with us for some investigation.

**Comment by stevehobbsdev** [comment]
@Jazzepi Apologies for the radio silence here. This is proving difficult for me to reproduce. Are you able to reproduce what you're seeing on the latest version (v11.24.4)?

**Comment by Jazzepi** [comment]
I can try this weekend. If you're having trouble reproducing artificially slowing down the network may help.

**Comment by stevehobbsdev** [comment]
Unfortunately we are still not able to reproduce this. If you are able to provide a reliable, reproducible sample then I'm very happy to take another look and reopen the issue.
