### ISSUE TITLE
close button is missing

### ISSUE THREAD

**Issue by guosheng19** [auth0/lock#1863]
I updated auth0-lock from version 11.17 to 11.24.0, then the close button on the top-right corner is gone.

**Comment by stevehobbsdev** [comment]
Thanks for raising - this looks like it might be related to https://github.com/auth0/lock/pull/1846

**Comment by griffinmartin** [comment]
I'm experiencing the same issue as well. 
The  `remember-me` appears to be broken as well.
Downgrading to `11.23.0` resolved these issues for me.

**Comment by adamjmcgrath** [comment]
>  then the close button on the top-right corner is gone.

The header is further down in the DOM than the close button and they have matching `z-index` values so the header is winning

https://github.com/auth0/lock/blob/master/css/index.styl#L178
https://github.com/auth0/lock/blob/master/css/index.styl#L204

close button z-index should be > header z-index
