### ISSUE TITLE
Login Issue: The 'q' parameter is available only if you specify 'search_engine=v3'

### ISSUE THREAD

**Issue by sinedsem** [auth0/lock#1864]
### Description

My login form which worked for 2 years broke today. I got the following error message:

`{error: "access_denied", errorDescription: "{"statusCode":400,"error":"Bad Request","message":"The 'q' parameter is available only if you specify 'search_engine=v3'.","errorCode":"invalid_query_string"}", state: "D4jJISoA8Ov147RuXgEdXPslFeLF9IrR"}`

error description is actually url-encoded, I decoded for the simplicity

### Reproduction

```
  lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, {
    auth: {
      redirectUrl: AUTH_CONFIG.callbackURL,
      audience: AUTH_CONFIG.audience,
      responseType: 'token id_token',
      params: {
        scope: this.requestedScopes
      }
    },
    container: 'hiw-login-container',
    avatar: null
  });
```

### Environment

- **Version of this library used:**     "auth0-js": "^9.13.2",    "auth0-lock": "^11.24.0",
- **Version of the platform or framework used, if applicable:** "@angular/core": "^4.0.0",

**Comment by stevehobbsdev** [comment]
@sinedsem Thanks for raising - can you confirm if the problem exists on the previous version of Lock, v11.23.1?

**Comment by sinedsem** [comment]
@stevehobbsdev actually, my application worked on the versions
```
    "auth0-js": "^9.10.0",
    "auth0-lock": "^11.14.0",
```
and broke today. I have updated to the lastest versions - but this didn't help.

**Comment by sinedsem** [comment]
Seems like it was a bug in Auth0, issue has gone away after a few days with nothing changed on my side.
