### ISSUE TITLE
App is Not installed in below iOS 13 version

### ISSUE THREAD

**Issue by sakthinath** [auth0/lock#1873]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description
unable to load login and signup screen in iOS 13 below version 
It is showing only black screen and above iOS 13 it is working fine. 
can you please help me is there any OS restriction.
### Reproduction

Install Below iOS 13 version devices. It showing black screen

### Environment

iOS 12.4  and iOS 12.4.5

In these OS version is app loading as black screen

**Comment by stevehobbsdev** [comment]
@sakthinath I have tested this in an iOS 12 simulator but can show that it does not show a black screen there. Unfortunately we do not have real devices to hand on which to test this for you.

Closing for now as we are unable to reproduce, but if you manage to find the root cause of the issue, please feel free to report back and reopen.
