### ISSUE TITLE
Improve CSP, use only HTTPS cdns

### ISSUE THREAD

**Issue by bstaley** [auth0/lock#1881]
### Description

To improve CSP, by forcing all images to use https, can you update all cdn urls for lock to use https?

### Reproduction

Force CSP to use https only

### Environment

> Please provide the following:

- lock 11.24.2
- ng latest
- chrome latest

**Comment by bstaley** [comment]
The following url is fetched after lock is loaded into the DOM:

http://cdn.auth0.com/styleguide/components/1.0.8/media/logos/img/badge.png

I've checked and there is an https version of it. Can you use that instead?

**Comment by stevehobbsdev** [comment]
Thanks for reporting this @bstaley. As you've pointed out, the request does take on the protocol you're using at the time, so if you're on an HTTPS origin, the image will be requested using that same protocol.

We will take this on board as a low-priority item to fix. In the meantime, we really appreciate you raising it as a concern.
