### ISSUE TITLE
Universal login is not working, after third party cookie block in IE11 browser

### ISSUE THREAD

**Issue by nikunj-drupal** [auth0/lock#1883]
### Description

I was using an Auth0 embedded login in my site from the past many years. But because of some browsers updates, some of my users getting issues for login. The reason, they are getting disabled 3rd party cookies with their latest browser.

For the solution, we have decided to replace our login with the Universal login system. We have implemented it.

During testing, we have found that It is working in all browsers and test users are able to log in too. But not for IE11(Internet Explorer) Browser. **For IE11 I am getting the issue to get(render) a form on an Auth0 domain URL with 3rd party cookie disabled**. If we are enabling 3rd party cookie support in IE11, then it is working fine. The form is rendering and the test user is able to log in when 3rd party cookie support is enabled from the browser.

Also, if I am seeing in the network area from developer tools, then I can see **'lock.bundle.min.js' is giving 307.**

Please see attached screenshot.

<img width="528" alt="Screenshot 2020-06-12 at 3 26 49 AM" src="https://user-images.githubusercontent.com/57451301/84443894-2a9c2180-ac5e-11ea-9771-e66420b4d59e.png">

### Environment

- **Version of this library used:** 11.14
- **Version of the platform or framework used, if applicable:** Drupal
- **Other relevant versions (language, server software, OS, browser):** IE11
- **Other modules/plugins/libraries that might be involved:** N/A

This is a blocker for me, Need help or guidance to fix this.

**Comment by adamjmcgrath** [comment]
Hi @nikunj-drupal - from the screenshot you've provided it looks like the Lock SDK is not being loaded on the page.

> Also, if I am seeing in the network area from developer tools, then I can see 'lock.bundle.min.js' is giving 307.

This usually means that you're trying to get the file using HTTP and the browser is being redirect to HTTPS.

Can you verify that you are requiring the lock SDK file with the https protocol, eg for 11.14 your url should be: `https://cdn.auth0.com/js/lock/11.14/lock.min.js`

If that doesn't help, can you provide a link to your app so we can investigate further?

**Comment by stevehobbsdev** [comment]
Closing for now due to inactivity, but please feel free to reopen if you are able to identify where the issue lies.
