### ISSUE TITLE
auth0 lock package size is suspiciously large

### ISSUE THREAD

**Issue by bencao** [auth0/lock#1884]
### Description

Base on the report by https://github.com/danvk/source-map-explorer, I noticed the auth0-lock took almost 578kb alone which is a significant amount of the whole application(21.9%).

<img width="857" alt="Screen Shot 2020-06-12 at 1 17 35 AM" src="https://user-images.githubusercontent.com/666516/84467603-aa1ff580-ac4a-11ea-8231-f8254259ac7e.png">

### Reproduction

1. Setup a repo that uses Auth0 lock
2. Follow https://create-react-app.dev/docs/analyzing-the-bundle-size/ to show the source analyze

### Environment

> Please provide the following:

- **Version of this library used:** 11.23.0
- **Version of the platform or framework used, if applicable:** create-react-app
- **Other relevant versions (language, server software, OS, browser):** N/A
- **Other modules/plugins/libraries that might be involved:** webpack

**Comment by adamjmcgrath** [comment]
Hi @bencao - thanks for your report

Yep Lock is around 600kb (which should GZip to around 200kb) - it's a fairly complex application that uses some libraries like react and core.js (which make up about 50% of the final binary). 

So, it's fairly large, but not suspiciously so :)

Looking at that Tree Map that you've provided, it looks like we might be able to use corejs a little more judiciously, which may save a few bytes - so I'll raise something internally about that

You could also build your own binary and share the version of react with your application's version, target only modern browsers and do some other optimizations specific to your use cases that would greatly reduce the bundle size - but beware the Lock library may not work as expected if you built it differently.

Closing this for now, but feel free to reopen if you want to continue the conversation

**Comment by qortex** [comment]
I second that. Using Angular, it seems really weird to me to have to include react in addition. And it's actually a showstopper :(

**Comment by geosigno** [comment]
Should we not re-open this issue to have a progress on what is being done to reduce the size?
