### ISSUE TITLE
Header height calculation is broken when title is empty

### ISSUE THREAD

**Issue by awzietal** [auth0/lock#1886]
### Description

PR #1859 broke header height calculation when the title is empty.

### Reproduction

Reset the Universal Login login page to the default Lock template. Change the title to be empty (line 39 in the current template):
languageDictionary = { title: '' };

Initiate login. The login form will look ok.

Switch to the Sign Up tab. There will be extra white space between the header and the tabs.

Switch back to the Log In tab. The white space between the header and the tabs will completely disappear.

![image](https://user-images.githubusercontent.com/57819310/84659436-509c1d00-af0f-11ea-8d55-6fb087761528.png)

**Comment by stevehobbsdev** [comment]
Thanks @awzietal. We reworked how the calculation was being done since #1859 but looks like there are still issues. Let me investigate and get back to you.
