### ISSUE TITLE
Password hint tooltip is blank

### ISSUE THREAD

**Issue by sentilesdal** [auth0/lock#1903]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

The password tooltip appears to be blank in the latest (11.25.1) version.  We reverted to 11.24.0 and the problem was fixed.  However, the tooltip also appears seems to get clipped due to an overflow issue.

![image](https://user-images.githubusercontent.com/9002261/88206683-8665ad00-cc03-11ea-9eb5-80099ab3df58.png)

### What was the expected behavior?

A tooltip with hints about the password

### Environment

> Please provide the following:

- **Version of Lock used:**
11.25.1 exhibits the problem, 11.24.0 solves it
- **Which browsers have you tested in?**
Chrome 84
- **Other modules/plugins/libraries that might be involved:**
none

**Comment by stevehobbsdev** [comment]
Thanks for raising. I'm not able to reproduce this using the latest version on Chrome - 

- Can you tell me anything else about your configuration, such as your password requirement settings?
- Do you have a public login page I can access that demonstrates the issue?
- Are you able to repro this using the [built-in playground app](https://github.com/auth0/lock/blob/master/DEVELOPMENT.md#the-sdk-playground)?

![image](https://user-images.githubusercontent.com/766403/88269648-4fa79980-cccc-11ea-99a3-18d670323f43.png)

**Comment by sentilesdal** [comment]
@stevehobbsdev thanks for replying and sorry this fell off my radar.  Turns out the issue was on our end, closing this issue.  Thanks!
