### ISSUE TITLE
Invalid chars in email address

### ISSUE THREAD

**Issue by joelmeiller** [auth0/lock#1919]
# Problem

We use the auth0 redirect page with the custom login page and the Lock widget v11 for the signup of a new user. During the testing the email address _test00990@test009kökölköl90.ch_ (yes, we are from the german speaking world ;) passed the validation and led to errors in our own application as such an email is not allowed by our validation. 

Check also the following topic: [https://community.auth0.com/t/invalid-chars-in-email-on-signup/49227/4](https://community.auth0.com/t/invalid-chars-in-email-on-signup/49227/4)

# Expected behaviour

Special chars in the email, primarily german (ö, ä, ü) , french (é, à, è, ...) and spanisch ones (ç) should not be allowed and blocked by the Lock widget and the user cannot processed with the signup.

# Reproduction

1. Signup with email with special chars: test@testööö.ch
2. Check Management Dashboard if user has been created

# Environment

- Version of Lock used: 11.20
- Which browsers have you tested in? Chrome
- Other modules/plugins/libraries that might be involved: Authorisation token is used with Meteor.js authorisation mechanism and user validation

**Comment by stevehobbsdev** [comment]
Thanks for raising @joelmeiller - let me validate this internally and report back here.

**Comment by saltukalakus** [comment]
https://github.com/auth0/lock/pull/1921 should fix this issue.

**Comment by stevehobbsdev** [comment]
@saltukalakus would the customer have to specify `signUpFieldsStrictValidation` in order for this problem to be fixed? Or would this case be fixed by default? (I'm presuming the former, just wanted to confirm).

**Comment by stevehobbsdev** [comment]
@joelmeiller We have now released a new feature in v11.27.0 that allows you to specify `signUpFieldsStrictValidation`, which could fix this. Could you please try it out and let us know?

**Comment by saltukalakus** [comment]
@stevehobbsdev sorry I just noticed your message. Yes, `signUpFieldsStrictValidation` should be set `true` in order to validation to apply.

**Comment by joelmeiller** [comment]
@stevehobbsdev I am gonna try it and let you know. thanks.

**Comment by joelmeiller** [comment]
@stevehobbsdev Sorry again. Where exactly in my lock options do I have to specify to option?
Like this it did not work
```
const lockOptions = {
      auth: {
        redirectUrl: options.redirectUrl,
        params: {
          state: OAuth._stateParam('redirect', options.credentialToken, options.callbackUrl),
        },
      },
      autoParseHash: false,
      allowedConnections:
        options.lock.connections || (isSignup && ['Username-Password-Authentication']) || null,
      rememberLastLogin: true,
      languageDictionary: options.lock.languageDictionary,
      theme: {
        logo: options.lock.logo,
        primaryColor: options.lock.primaryColor,
      },
      closable: true,
      container: options.lock.containerId,
      allowLogin: isLogin,
      allowSignUp: isSignup,
      sso: true,
      signUpFieldsStrictValidation: true, // From email validation issue: https://github.com/auth0/lock/issues/1919
    }
```

**Comment by stevehobbsdev** [comment]
Yes that looks correct, did you also upgrade the Lock version to the latest one?

cc: @saltukalakus

**Comment by joelmeiller** [comment]
Finally I managed to find time to look at your solution, but it seems that the flag `signUpFieldsStrictValidation`  did not yet led to the wanted effect. The user was still created with an invalid email:
<img width="507" alt="Screenshot 2020-09-29 at 22 17 52" src="https://user-images.githubusercontent.com/11474224/94617611-c7340f00-02a1-11eb-8980-84b50f5a4385.png">

Npm auth0-lock package version is: v11.27.0

**Comment by joelmeiller** [comment]
The log shows me the following:
![Uploading Screenshot 2020-09-29 at 22.21.08.png…]()

**Comment by saltukalakus** [comment]
Hi @joelmeiller sorry, the changes with the previously shared commit makes the verification inline with Auth0 server checks. Our backend already accepts your sample email as a valid one and with the new universal login option without Lock it also works. So, I don't think that we can fix this (if it is an issue) from Lock widget.

**Comment by stevehobbsdev** [comment]
@joelmeiller as @saltukalakus mentioned, this will be difficult to fix from this component's standpoint as we reflect the validation logic as allowed by the server.

As this is a testing phase, in reality will you have users who have such an email address? In the case of spam and to prevent the user being created, you could use a [pre-registration hook](https://auth0.com/docs/hooks/extensibility-points/pre-user-registration) to write some custom validation logic to prevent the actual user record from being created, and return an error. Does this help?

**Comment by stevehobbsdev** [comment]
Closing this for now but feel free to raise any further questions you might have.
