### ISSUE TITLE
"Go Back to App" Button within Container in Auth0 Login/Signup Screens

### ISSUE THREAD

**Issue by arpavlic03** [auth0/lock#1925]
## Describe the problem you'd like to have solved

> I am working on an Auth0 login screens where the user is forced to use the back button on the browser or mobile phone to go back to the screen...I wish there was a way to try to use the login-redirect urls to go back to the app if the user accidentally clicks on Login/Signup buttons/links in the actual app/site. Unfortunately, the login screen I am designing (with the Classic Experience) uses a container where the closable feature in the Lock.js config options is always false.

### Describe the ideal solution

> I would like to see a close button similar to the button you find when the user clicks the "Forgot Password" link that allows the user to go back to the app using the login redirectTo auth parameter.

**Comment by stevehobbsdev** [comment]
Thanks for raising @arpavlic03. Unfortunately we're not in a position where we can action feature requests at the moment, so I will close. However, I've kept a note internally to revisit this later.
