### ISSUE TITLE
Auth0LockPasswordless does not consider the `showTerms` option

### ISSUE THREAD

**Issue by jmangelo** [auth0/lock#1927]
### The problem

The `showTerms` option (https://auth0.com/docs/libraries/lock/lock-configuration#showterms-boolean-) is not respected for `Auth0LockPasswordless` although the reference documentation does not mention anything that would suggest that this option would not apply to passwordless as well. Given passwordless also displays the terms it seem relevant that it should respect that option.

### What was the expected behavior?

If you set `showTerms: false` the signup terms should not be displayed for `Auth0LockPasswordless`.

### Reproduction

1. configure universal login to use `Auth0LockPasswordless` and pass `showTerms: false` in the options.
1. trigger a login through universal login and observe that terms are shown.

### Environment

- **Version of Lock used:** 11.27
- **Which browsers have you tested in?** Chrome
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by stevehobbsdev** [comment]
Keeping this open; we have an open PR for this, will triage today.
