### ISSUE TITLE
Add extra information to login screen

### ISSUE THREAD

**Issue by mbj36** [auth0/lock#1928]
I want to add couple of links just below `Don't remember your password ?` just like `signUpTerms` field in login screen, is there any way to do it ?

<img width="342" alt="Screenshot 2020-09-23 at 3 22 21 PM" src="https://user-images.githubusercontent.com/9936881/93997180-b9b5eb00-fdb0-11ea-9082-f32bc1b3ee13.png">

**Comment by stevehobbsdev** [comment]
Hi @mbj36, unfortunately not - this is currently not supported.
