### ISSUE TITLE
Lock vs Auth0: Already logged in users

### ISSUE THREAD

**Issue by pythonmobile** [auth0/lock#1929]
I have a web application, where I have "Sign in with Google button" implemented using Lock and Auth0 (Classic Universal login screen). I am looking for a behavior when a user is already logged into his/her Google account, they automatically bypass the Classic Universal login screen, and don't have to click the "Sign in with Google button". How do I do this using Lock/Auth0 - was not sure where to ask this, so am asking here?

**Comment by stevehobbsdev** [comment]
👋  This should work provided you have [Seamless SSO turned on](https://auth0.com/docs/get-started/dashboard/enable-sso-for-legacy-tenants) for your Auth0 tenant, so if your user is already logged in they should not see a log in page.

However, there's a caveat that this does not work on `localhost`, but will if your app was published to something other than localhost.

**Comment by stevehobbsdev** [comment]
Closing for now but feel free to raise any more questions you might have.

**Comment by pythonmobile** [comment]
@stevehobbsdev Thanks for the help. I do not see "Seamless SSO turned on" Setting that is described in that document in my account. Perhaps "Seamless SSO turned on" link needs to be updated with what users are looking at? 

In my case: https://images.ctfassets.net/cdy7uua7fh8z/6gosFazm005xCkb1uyo6h/16e1448625889dc1f1e8c36999a5dcf4/tenant-settings-advanced-login-session-management.png

does not have "Enable Seamless SSO" toggle at all.  "Log In Session Management" section starts with "Inactivity timeout".

**Comment by stevehobbsdev** [comment]
Hey @pythonmobile,

It was the "Enable Seamless SSO" setting I was referring to, sorry if that wasn't clear. If you click that setting in your dashboard, it should become enabled.

I can see from the screenshot that you have this setting but it is currently turned off. If you enable it by clicking on the toggle on the right, do you get the desired effect of the user not having to see the login screen again if they're already logged in?

**Comment by pythonmobile** [comment]
> Hey @pythonmobile,
> 
> It was the "Enable Seamless SSO" setting I was referring to, sorry if that wasn't clear. If you click that setting in your dashboard, it should become enabled.
> 
> I can see from the screenshot that you have this setting but it is currently turned off. If you enable it by clicking on the toggle on the right, do you get the desired effect of the user not having to see the login screen again if they're already logged in?

Hi @stevehobbsdev : Thanks for the help. In my actual login screen - there is No "Enable Seamless SSO". The one I linked was from a documentation - that seems out of date.  "Enable Seamless SSO" seems to have been removed from at least my settings. Not sure about others.
