### ISSUE TITLE
Unwanted padding between error message and lock header

### ISSUE THREAD

**Issue by buren** [auth0/lock#1933]
### Describe the problem

Upgrading from v11.20 to v11.27 there is a regression where there are unwanted padding between the lock header and the lock content wrapper (seen attached screenshots).

After some trial and error it seems like the bug was introduced in lock v11.24 (works as intended in v11.23).

### What was the expected behavior?

No whitespace/margin between the error/feedback component and the header component.

### Reproduction

- Setup Universal login with lock v11.24 (or v11.27, however v11.24 seems to have introduced it)
- Goto login screen
- Either input a wrong password for existing account OR submit a forgot password request
- The UI regression should be visible (see screenshots below)

The error is NOT present in version v11.20.

__Before (v11.23, v11.20)__
<img width="322" alt="Screenshot 2020-10-05 at 21 25 34" src="https://user-images.githubusercontent.com/922411/95123244-ef17ec80-0751-11eb-81ab-439000ef36ce.png">
<img width="318" alt="Screenshot 2020-10-05 at 21 08 54" src="https://user-images.githubusercontent.com/922411/95123258-f3dca080-0751-11eb-8a6b-ba730d1d5451.png">

__After (v11.27, v11.24)__
<img width="310" alt="Screenshot 2020-10-05 at 21 25 11" src="https://user-images.githubusercontent.com/922411/95123279-fd660880-0751-11eb-80a6-6d03104f2f5b.png">
<img width="339" alt="Screenshot 2020-10-05 at 21 08 44" src="https://user-images.githubusercontent.com/922411/95123287-0060f900-0752-11eb-9849-42888a2e09b4.png">

### Environment

> Please provide the following:

- **Version of Lock used:**
	+ Bug present in v11.27, v11.24
    + Bug not present in v11.20, v11.23
- **Which browsers have you tested in?** Chrome 85, Safari 13, Firefox 80.

**Comment by stevehobbsdev** [comment]
Thanks for raising @buren - I've attached a PR.

**Comment by buren** [comment]
Thanks @stevehobbsdev! 👍
