### ISSUE TITLE
Scrollbar appears during initial animation

### ISSUE THREAD

**Issue by awzietal** [auth0/lock#1934]
### Describe the problem

A scrollbar appears during initial animation.

### What was the expected behavior?

The scrollbar doesn't appear during initial animation.

### Reproduction

On every page load.

Lock v. 11.17.3 (the last working version; 11.18.0 was broken)

![no-scrollbar](https://user-images.githubusercontent.com/57819310/95481411-e22f0f00-0984-11eb-8ead-d06950a52e98.gif)

Lock v. 11.27.0

![scrollbar](https://user-images.githubusercontent.com/57819310/95481404-e0fde200-0984-11eb-97e7-0630230a8197.gif)

### Environment

Example from Chrome. Also tested in FireFox

**Comment by stevehobbsdev** [comment]
@awzietal The version you're using is somewhat out of date (we're up to 11.27 now) and we have done some work in this area. Could you please see if you can reproduce the problem in a more up-to-date version?

**Comment by awzietal** [comment]
@stevehobbsdev The second gif is from a Universal Login page configured with the default Lock template using Lock 11.27. Just checked it again and the problem is still there.

**Comment by stevehobbsdev** [comment]
Unfortunately the UI here has a long history of fixes that cause anomalies like this one. It's not ideal, I agree, but it's also not something that's a priority. Having said that, I have kept an internal note to revisit.
