### ISSUE TITLE
Not showing multiple connection in the universal page

### ISSUE THREAD

**Issue by manish-kumar9a9** [auth0/lock#1937]
I have configured multiple enterprise connection, which is not get displayed. But when I try it out from the Auth0 dashboard it shows all the buttons. I have turned off the customize page switch in Auth0 dashboard.

**Comment by manish-kumar9a9** [comment]
I want anew universal login page, instead of a classic login page

**Comment by stevehobbsdev** [comment]
@manish-kumar9a9 You are able to use the new universal login page by selecting it in [the dashboard](https://manage.auth0.com) under **Universal Login**, as shown here:

![image](https://user-images.githubusercontent.com/766403/96262323-8afaf100-0fb9-11eb-92a6-0e09329b281b.png)

Does this help?

**Comment by manish-kumar9a9** [comment]
@stevehobbsdev 
It's already there.
![Uploading Screen Shot 2020-10-16 at 6.48.36 PM.png…]()

**Comment by stevehobbsdev** [comment]
You are able to customize the pages of the new Universal Login using [Custom Templates](https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates) and on that page I showed above there is a small amount of customization you can apply, such as logo and theme color.

However, I should point out that template customization is only available if you're also using Custom Domains, which is a paid feature.

**Comment by stevehobbsdev** [comment]
Closing for now, but if you have further questions feel free to raise them.
