### ISSUE TITLE
types don't include the passwordless constructor

### ISSUE THREAD

**Issue by andrewthamcc** [auth0/lock#1946]
`Auth0LockPasswordless` is not an export for `auth0-lock` as per the docs. The `passwordlessMethod` option does not exist in the typings and can't be configured in the options.

Current work around is with a custom typing file to extend the `Auth0LockConstructorOptions` but unable to confirm at this moment it works correctly or as expected.

> declare module 'auth0-lock' {
>   interface Auth0LockPasswordlessConstructorOptions
>     extends Auth0LockConstructorOptions {
>     passwordlessMethod: 'link'
>   }
> 
>   export type Auth0LockPasswordlessStatic = Auth0LockStatic & {
>     new (
>       clientId: string,
>       domain: string,
>       options?: Auth0LockPasswordlessConstructorOptions
>     ): Auth0LockStatic
>   }
> 
>   export const Auth0LockPasswordless: Auth0LockPasswordlessStatic
> }

**Comment by stevehobbsdev** [comment]
@andrewthamcc could you link to which typings you're referring to? It's not entirely clear from your post.

**Comment by andrewthamcc** [comment]
@stevehobbsdev for clarity:
Attempting to import per the docs as: `import { Auth0LockPasswordless } from 'auth0-lock` generates a typing error with: `Module '"auth0-lock"' has no exported member 'Auth0LockPasswordless'.`

Inspecting the type definition for auth0-lock and there's no export for `Auth0LockPassswordless` and the only typing is for `Auth0LockStatic`.

The `Auth0LockConstructorOptions` in the typings does not include the option for `passwordlessMethod` as listed in the [docs](https://auth0.com/docs/libraries/lock/lock-configuration#passwordlessmethod-string-).

**Comment by stevehobbsdev** [comment]
Thanks @andrewthamcc.

> Inspecting the type definition for auth0-lock

We don't export any typings from the library and it's not built in TypeScript; I'm asking which typings you're referring to.

**Comment by stevehobbsdev** [comment]
Checking the source, we do export `AuthLockPasswordless` as a named export from `index.js`, so that should work. If you're using some typings on top of that, I would suggest the typings you're using are incorrect but we don't export those typings from the library.

https://github.com/auth0/lock/blob/master/src/index.js

**Comment by stevehobbsdev** [comment]
There's also a lot of information we ask for on the default issue template, one of the most important things is the version of Lock that you're using. Could you please supply that information if you still believe there to be an issue?

**Comment by andrewthamcc** [comment]
@stevehobbsdev closing this issue. I apologize for the confusion!
