### ISSUE TITLE
Regression - SSO login "email can't be blank" by default

### ISSUE THREAD

**Issue by RLRabinowitz** [auth0/lock#1952]
### Describe the problem you'd like to have solved

There seems to be a minor regression introduced in version 11.27.0:
When displaying a lock where the `allowedConnections` are simply multiple different Enterprise SAML connections, the email field automatically has the flash error "Email can't be blank", even though the user didn't yet type anything.
On version 11.26.3, flash errors on the email field only appear after the user have typed into that field
![Screen Shot 2020-12-21 at 14 07 09](https://user-images.githubusercontent.com/30493345/102776451-6b0bf300-4397-11eb-8f81-db936c4380fb.png)

### Describe the ideal solution

The "Email can't be blank" flash error should only appear if the user has started typing into that field

## Alternatives and current work-arounds

We do not currently have a work-around for this issue, other than not upgrading Auth0 lock version to 11.27.0.
We do not want our users to receive this flash message each time pick their email to login via SSO

### Additional information, if any

**Comment by stevehobbsdev** [comment]
Thanks for the report @RLRabinowitz, let me look into this and see what I can find.

**Comment by stevehobbsdev** [comment]
We've found an issue that was introduced with [this PR](https://github.com/auth0/lock/pull/1921), so we'll be patching this for the next release - thanks again for raising it!
