### ISSUE TITLE
How to add user_metadata while signup ?

### ISSUE THREAD

**Issue by dellwatson** [auth0/lock#1957]
I tried to place it in addtionalSignUp but it's not working,
```

componentDidMount() {
    // Avoid showing Lock when hash is parsed.
    if (!/access_token|id_token|error/.test(this.props.location.hash)) {
      this.lock.show({
        user_metadata: { logged_in_as: 'admin' },
        additionalSignUpFields: [
          {
            logged_in_as: 'name',
            user_metadata: { logged_in_as: 'admin' },
            storage: 'root',
          },
        ],
      });
    }
```

also this:

```
 lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, {
    auth: {
      responseType: 'token id_token',
      sso: false,
    },
    additionalSignUpFields: [
      {
        logged_in_as: 'name',
        user_metadata: { logged_in_as: 'admin' },
        storage: 'root',
      },
    ],
    container: AUTH_CONFIG.container,
    theme: {
      logo: '/logo192.png',
      primaryColor: 'lightblue',
    },
  });
```

docs said : 
> If you want to save the value of the attribute in the root of your profile, use storage: 'root'. Only a subset of values can be stored this way. The list of attributes that can be added to your root profile is here. By default, every additional sign up field is stored inside the user_metadata object.

what did i do wrong ?

**Comment by stevehobbsdev** [comment]
Thanks for raising this @dellwatson. `additionalSignUpFields` adds extra UI elements to the Lock page that allow the user to input additional custom data, and accept certain properties to make that happen. I suspect you're trying to add custom data in the form of static properties on the object, which will not work.

Here's a full description of how `additionalSignUpFields` works on our readme page: https://github.com/auth0/lock#additional-sign-up-fields

If that's not ultimately what you're looking to do, please let us know your use case and I'll try to help.

**Comment by dellwatson** [comment]
@stevehobbsdev yup im trying to add static properties like what i did on auth0 api  `/dbconnections/signup` ,
```
{ 
    "clientID": "xxx",
    "connection": "Username-Password-Authentication", 
    "email": "xx@dellwatson.com", 
    "password": "@Secret1234",
    "user_metadata": { "logged_in_as": "admin"}
}
```
is it possible with lock ?
because i need some tweaking with auth0-rules on first encounter of signup

**Comment by stevehobbsdev** [comment]
You can send custom parameters through to the signup endpoint by setting some [custom properties](https://github.com/auth0/lock#authentication-options) on the `auth.params` object. An example:

```js
var options = {
  auth: {
   params: {
    param1: "value1",
    scope: "openid profile email"
   },
  }
};
```

You would then be able to pick these up in a custom rule and tweak what you need. Does this help?

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
