### ISSUE TITLE
Module not found: Error: Can't resolve 'auth0-js/dist/cordova-auth0-plugin.min.js' in '/myapp/node_modules/auth0-lock/lib/core/web_api'

### ISSUE THREAD

**Issue by szTheory** [auth0/lock#1958]
Running `auth0-lock` in a TypeScript application, I get this error while trying to compile with webpack:

```
ERROR in ./node_modules/auth0-lock/lib/core/web_api/p2_api.js
Module not found: Error: Can't resolve 'auth0-js/dist/cordova-auth0-plugin.min.js' in '/myapp/node_modules/auth0-lock/lib/core/web_api'
resolve 'auth0-js/dist/cordova-auth0-plugin.min.js' in '/myapp/node_modules/auth0-lock/lib/core/web_api'
  Parsed request is a module
  using description file: /myapp/node_modules/auth0-lock/package.json (relative path: ./lib/core/web_api)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /myapp/app/javascript
        using description file: /myapp/package.json (relative path: ./app/javascript)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /myapp/package.json (relative path: ./app/javascript/auth0-js/dist/cordova-auth0-plugin.min.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /myapp/app/javascript/auth0-js/dist/cordova-auth0-plugin.min.js doesn't exist
            .mjs
```

This is the import:

```typescript
import { Auth0Lock } from "auth0-lock";
```

This is in my package.json dependencies:

```json
"@types/auth0": "^2.20.13",
"@types/auth0-js": "^9.14.2",
"@types/auth0-lock": "^11.27.0",
"auth0-lock": "^11.27.0",
```

Please help, we are paying for auth0 but can't get it working.

**Comment by szTheory** [comment]
I had to downgrade to auth0-js 9.14.0. Looks like the latest release of auth0-js 9.14.1 removed a build dependency for auth0-lock, `auth0-js/dist/cordova-auth0-plugin.min.js`. Debugging that out was an unfortunate waste of a few hours.

@jakedolan Change your package.json to this line `"auth0-js": "9.14.0",`

**Comment by jakedolan** [comment]
Thank you @szTheory. That appears to have worked for me.

**Previously (fails with missing dependencies):**
package.json:
`"auth0-lock": "^11.28.0",`
```
yarn list --pattern=auth0
├─ auth0-js@9.14.1
├─ auth0-lock@11.28.0
└─ auth0-password-policies@1.0.2
```

**With the fix (succeeds in build)**
package.json:
`auth0-js": "9.14.0",
    "auth0-lock": "^11.28.0",`
    
```
yarn list --pattern=auth0
├─ auth0-js@9.14.0
├─ auth0-lock@11.28.0
│  └─ auth0-js@9.14.1
└─ auth0-password-policies@1.0.2
```

**Comment by stevehobbsdev** [comment]
Thanks for the report, we had an issue publishing `auth0-js` earlier which caused the package to be uploaded without its assets. `9.14.2` has now been published and the build issue looks to be resolved. Could you please try again ensuring that this new version is installed?

Context: https://github.com/auth0/auth0.js/issues/1148

Thanks

**Comment by stevehobbsdev** [comment]
Closing as this issue has now been resolved.
