### ISSUE TITLE
TypeError https://cdn.auth0.com/js/lock/11.27.1/lock.min.js

### ISSUE THREAD

**Issue by jakesorce** [auth0/lock#1959]
We use Sentry and this error fires off quite a bit. 

<img width="590" alt="Screen Shot 2021-01-21 at 1 29 02 PM" src="https://user-images.githubusercontent.com/801470/105408785-a4c95700-5bec-11eb-8848-e6b6c2005af3.png">

Looking for solutions. Thank you

**Comment by stevehobbsdev** [comment]
Hi @jakesorce, thanks for raising. I haven't come across that before, can you give me any more context around this? As right now it's a bit tricky to know where to start.

For example:

* When are you seeing this? Page load? Login? Sign up?
* Are you seeing it with any previous versions that might indicate a regression?
* Do you have a stack trace or a reproducible sample to share?

Thanks
