### ISSUE TITLE
How to UPDATE metadata with Lock getUserInfo

### ISSUE THREAD

**Issue by mattbloem007** [auth0/lock#1961]
How can one update user_metadata with Lock Library as stated in the documentation? It is said we can use getUserInfo.

I receive the profile object and I am able to manipulate it but it is manipulated locally and not updated to the auth0 backend where user information is stored. Is there a function or way with the Lock library to update user_metadata to the backend?

I am using Gatsby and React in frontend dev. It is headless, serverless

Thank you

**Comment by mattbloem007** [comment]
Please could I know why this was closed?

Is this a valid question to ask here?

**Comment by stevehobbsdev** [comment]
My apologies! I see that you have raised two very similar issues so I closed this ☝️ but when I closed it, the issue detail had not been filled out and so I had assumed that it was raised in error.

Let me reopen this one, close the other one and investigate this for you. Sorry about that!

**Comment by stevehobbsdev** [comment]
To answer your question, Lock itself does not provide an API to update user metatdata using the management API, but you can instead do this with [Auth0.js](https://github.com/auth0/auth0.js/#auth0management), which has a `patchUserMetadata` function you can use.

Hope that helps!

**Comment by mattbloem007** [comment]
I get this error: 

 Error: {"statusCode":403,"error":"Forbidden","message":"Insufficient scope, expected any of: update:users,update:users_app_metadata,update:current_user_metadata","errorCode":"insufficient_scope"} 

when i run this code:

`auth0Manage.patchUserMetadata(userID, {user_metadata: newObj} , function(error, prof) {

        if (!error) {
          console.log(prof)
        }
        else {
          console.log("Can't get profile", error)
        }
      })`

userID is my userId and the object I am passing is an object with key "user_metadata" and value is an object. This object is what I want to use to update user metadata

**Comment by stevehobbsdev** [comment]
@mattbloem007 you can specify the scope in the [authentication options](https://github.com/auth0/lock#authentication-options) when constructing the Lock object.

Specifying `update:current_user_metadata` as well as the default scopes here should get you a token that will allow you to update the user's metadata.

```js
var options = {
  auth: {
   params: {
    scope: "openid profile email update:current_user_metadata"
   }
  }
};
```

Then the user will have to go through the full interactive login flow (where they may need to consent to the additional scopes), after which you should be able to update the metadata. Please let me know if that works for you.

**Comment by mattbloem007** [comment]
This worked! Thank you kindly
Appreciate the help
