### ISSUE TITLE
How to UPDATE metadata with Lock getUserInfo

### ISSUE THREAD

**Issue by mattbloem007** [auth0/lock#1962]
Hello

How does one UPDATE metadata with lock library. It states in the documents that one can update the user metadata with lock.getUserInfo, however there are only examples that retrieve the information of a specific user.

Once I receive the profile object, I am able to manipulate it the way I want but there is no method or function to send it back to auth0 database to change the profile information that has been changed

**Comment by stevehobbsdev** [comment]
Closing this one as a duplicate
