### ISSUE TITLE
Enterprise connections support with the Passwordless Lock

### ISSUE THREAD

**Issue by naman1-gupta** [auth0/lock#1966]
### Describe the problem

Does Auth0LockPasswordless support HRD for enterprise connections? From what I've gathered, nothing in the docs explicitly mentions anything different for enterprise connections with passwordless yet I can't get the 'Single Sign on Enabled' banner and can't get it to initiate a saml connection flow. `connectionResolver` seemed like a nice trick but unfortunately it only works for database connections and not enterprise.

### What was the expected behavior?

Show a banner with the label `Single Sign on enabled` and allow the user to complete the authentication flow with their enterprise IdP.

### Reproduction

- Step 1: Create an instance of `Auth0LockPasswordless` with client Id which has saml connection enabled
- Step 2: try to login with saml connection

### Environment

- **Version of this library used:** 11.26.2
- **Which framework are you using, if applicable:** React
- **Other modules/plugins/libraries that might be involved:** NA
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Hi @naman1-gupta, thanks for your patience here - let me look into this and see what I can find.

**Comment by stevehobbsdev** [comment]
Unfortunately at this time, showing the "SSO Enabled" banner is only supported for non-Passwordless Lock, so it will not work in the scenario you have described.

If you'd like to provide product feedback about this, the best way to do this would be to make that request here https://auth0.com/feedback.

Closing for now, but happy to continue the discussion.
