### ISSUE TITLE
mustAcceptTerms not honoured on latest version of safari

### ISSUE THREAD

**Issue by stevorobs3** [auth0/lock#1967]
### Describe the problem

The passwordless login window does not honor the  "mustAcceptTerms" flag set to `true` on safari. A user is still able to hit the `return` key to send the magic link. (note that the `submit` button remains correctly disabled).

This issue is not present on the latest version of chrome, I haven't tested other browsers

### What was the expected behavior?

Hitting the `return` key does nothing unless the T&C's checkbox is checked.

### Reproduction
Create a minimal sample app with this extra config:
{"showTerms"             true
  "mustAcceptTerms" true}

### Environment

Tested on version: "11.28.0"

**Comment by adamjmcgrath** [comment]
Hi @stevorobs3 

Looks like we rely on the submit button being disabled to prevent a user from submitting the form when they hit Enter.

This works on Chrome and forms with more than one field (which is why it only effects Passwordless), but Safari has a rule that states: If you have one text input Safari will submit the form regardless of a disabled submit button. If you have two text inputs or more Safari will not submit the form if the submit button is dsiabled. (more info https://bugs.webkit.org/show_bug.cgi?id=9756 and https://bugs.webkit.org/show_bug.cgi?id=16886)

I think we can manually prevent the form from submitting by adding an additional check for `props.disableSubmitButton` here: https://github.com/auth0/lock/blob/master/src/ui/box/container.jsx#L102 - which should make the browsers behave the same.

I'll raise a PR shortly

**Comment by alexiaharal** [comment]
Hi @adamjmcgrath 

Thanks for your immediate action on this.

Is this PR going to be merged soon or shall we use the branch?

**Comment by adamjmcgrath** [comment]
Hi @alexiaharal - I'll do a patch release today

**Comment by adamjmcgrath** [comment]
@alexiaharal - This is released as 11.28.1

https://cdn.auth0.com/js/lock/11.28.1/lock.min.js
and
https://www.npmjs.com/package/auth0-lock/v/11.28.1

If you're using the Universal Login Page with Lock, you'll need to update the version on that to `11.28.1` for now

Let me know if you have any issues with it

**Comment by alexiaharal** [comment]
@adamjmcgrath thanks for the release - however, I've just tried with version `11.28.1` and I'm still able to login when hitting the `return` button. Please note that the button seems disabled but I still receive the email and I'm able to login.

**Comment by adamjmcgrath** [comment]
@alexiaharal - will investigate

**Comment by adamjmcgrath** [comment]
@alexiaharal - do you have a previw universal login page I can look at? Or some other preview page?

**Comment by alexiaharal** [comment]
https://drive.google.com/file/d/1K8shwy0VVrh6UAbsIhoLRzSA0L5zLAZh/view?usp=sharing

not sure if this screenshot can help

**Comment by adamjmcgrath** [comment]
Hi @alexiaharal - thanks for sharing that screenshot, unfortunately that doesn't really help

Can you share the preview url? Right click on the iframed preview in Chrome, select "View Frame Source", send the link (it's public) without the `view-source:` prefix

Also, can you reproduce the issue on [my preview url](https://previews.auth0users.com/previews/eu/mcgrath/login?client=yvlgZjLRaS8TXuQ1g3XmQMweakppf2wc) in safari?

**Comment by alexiaharal** [comment]
No I can't reproduce on your preview url, that seems to be working as expected.

How can I get a preview url in safari, since that's where the problem is?

**Comment by adamjmcgrath** [comment]
HI @alexiaharal - can you share your client id and tenant domain? Then I should be able to get a preview of your universal login page.

**Comment by alexiaharal** [comment]
client-id: 63xKH3LlkS40so8b8AKXSqh1kqT6Km6S
domain: previse-development.eu.auth0.com

**Comment by adamjmcgrath** [comment]
Hi @alexiaharal - it doesn't look like you're using the correct version of lock.

On the page that you shared the screen grab of, can you view the source and confirm that the version of lock you are using is `11.28.1` (you should have a script tag pointing to `https://cdn.auth0.com/js/lock/11.28.1/lock.min.js`)

If you don't, you need to manually update the the page, to change the script tag to use `11.28.1`.

**Comment by stevorobs3** [comment]
@adamjmcgrath  thanks very much for fixing this. we have now deployed the latest version and it's working as expected. I'll close this ticket.
