### ISSUE TITLE
Re-introduced: Unwanted padding between error message and lock header

### ISSUE THREAD

**Issue by buren** [auth0/lock#1970]
### Describe the problem

The fix ~for~ in #1949 re-introduced the unwanted padding between error messages and lock header (specifically [this lin in this commit](https://github.com/auth0/lock/commit/48eb8304d0f177d710255835b7a43a4344e872ca#diff-9c65b17af8444f32f1b18600dd00835656efb83f57d3843b280a8118f9b44901R186)), described in issue #1933. 

<img width="317" alt="auth0 regression" src="https://user-images.githubusercontent.com/922411/109655091-2c4aa400-7b63-11eb-9600-8243f9dcec91.png">

### What was the expected behavior?

No whitespace/margin between the error/feedback component and the header component.

### Reproduction

Use latest lock version.

1. Request new password
2. Click send
3. The alert box info has unwanted margin/padding (see attached screenshot above)

### Environment

- **Version of this library used:** Tested on v11.27.2 and v11.28.1.

**Comment by stevehobbsdev** [comment]
@buren Apologies for the oversight here, it was simply missed during our UI refactor to solve some deeper issues. I've raised a PR.
