### ISSUE TITLE
Spanish translation not rendering HTML in messages correctly

### ISSUE THREAD

**Issue by yinzara** [auth0/lock#1973]
### Describe the problem
When using the "es" locale for Lock, the messages contain HTML `<br/>`s that are being rendered escaped in the UI
![Screen Shot 2021-03-10 at 5 09 12 PM](https://user-images.githubusercontent.com/671855/110720451-6bac6c80-81c3-11eb-9dcf-458f8405112e.png)

**Comment by stevehobbsdev** [comment]
Thank @yinzara, I've raised a PR 👍
