### ISSUE TITLE
Hook into the onChange events of the additionalSignupFields

### ISSUE THREAD

**Issue by ricardo-quinones** [auth0/lock#1995]
### Describe the problem

This is more of a feature request, but it would be nice to hook into the `onChange` functionality of additional inputs so that we can contingently show or hide other additional fields and/or change their values.

### What was the expected behavior?
Be able to respond to the `onChange` events of the additional sign up fields.

### Environment

Using version [`auth0-lock@11.27.2`](https://github.com/auth0/lock/tree/v11.27.2).

**Comment by stevehobbsdev** [comment]
Thanks for the suggestion @ricardo-quinones. At the moment I don't have an ETA for if or when this will make it in - we have an internal board we use for feature requests, to which I have added your suggestion. We will circle back here once we know more.
