### ISSUE TITLE
connections parameter should override all other defaults

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#200]
Otherwise it's impossible to log in with an enterprise connection that doesn't have any email domains. For example:

```
lock.show({
  connections: ["some-saml-idp"]
});
```

If `some-saml-idp` has no email domains associated, trying to log in with a `@gmail.com` email address will try to log in with `google-oauth2` instead, which contradicts the `connection` parameter.

**Comment by cristiandouce** [comment]
@rolodato the `connection` property only exists in the scope of auth0.js.

In lock it would ve like:

```js
lock.show({
  connections: ['some-saml-idp']
});
```

that `lock.signin` is not even part of the Lock API...

**Comment by yvonnewilson** [comment]
This issue was filed in conjunction with this ticket.  Update the ticket once this is fixed.
https://auth0.zendesk.com/agent/tickets/1870

**Comment by hzalaz** [comment]
Fixed in Lock v10. If there is only one enterprise connection it will show only a button.
