### ISSUE TITLE
Move text input icons to right side for RTL languages

### ISSUE THREAD

**Issue by alirezagit** [auth0/lock#2002]
Issue:
Hi there,
When I choose farsi language as default, the icons on text fields(mail icon, google icon...) still remain on left side.
Also some brand names like Google and Facebook stay in english and mix up with farsi translation.
Could you please fix these issues?
Tnx

Image:
![Untitled](https://user-images.githubusercontent.com/47676068/120707175-3f0ca600-c4cf-11eb-83b1-e63aa260cf2a.jpg)

**Comment by stevehobbsdev** [comment]
Thanks for raising this @alirezagit. We want to be respectful of RTL languages and provide a good experience, so let me put some time into this later this week to see what we can do here.
