### ISSUE TITLE
Lock window does not hide after login

### ISSUE THREAD

**Issue by goloroden** [auth0/lock#201]
I'm using Lock [as described in the docs](https://auth0.com/docs/libraries/lock/types-of-applications#2), using popup mode with a SPA:

```javascript
var lock = new Auth0Lock('…', '<user>.auth0.com');

lock.show(function(err, profile, id_token) {
  if (err) {
    // …
  }

  // …
});
```

However, the login windows does not close after logging in. Instead I need to add a manual call to `lock.hide` in the callback:

```javascript
var lock = new Auth0Lock('…', '<user>.auth0.com');

lock.show(function(err, profile, id_token) {
  lock.hide();

  if (err) {
    // …
  }

  // …
});
```

Is this by design, or am I missing something?

**Comment by cristiandouce** [comment]
@goloroden I apologize for the late response. Do you still experiment this issue?
Do you happen to see any errors on your browser's Debug Tools console?

It should hide. If it doesn't then it's a bug.

Could you provide with a reproducible sample/repository were we could quickly check that odd behavior?

thanks!

**Comment by goloroden** [comment]
Thanks for your reply, and no problems that it took you a little while :-)

After updating from 7.7.1 to 7.8.1 I can not reproduce it anymore, so apparently it seems to be gone.

Hence I'm going to close this issue.
