### ISSUE TITLE
Email trailing period was considered valid

### ISSUE THREAD

**Issue by john-fk** [auth0/lock#2015]
### Describe the problem
Email address accepts something@somehing.

### What was the expected behavior?
Should not be processed if it ends with a trailing period.

Running on Auth0 11.30.3
https://cdn.auth0.com/js/lock/11.30.3/lock.min.js

**Comment by stevehobbsdev** [comment]
Thanks for the report @john-fk. Are you seeing this on the login pane or the sign-up pane?

**Comment by john-fk** [comment]
Hi! Both in Login & Sign up pane, (while typing invalid emails are still blocked before submitting).. also double @ symbol, but I think the trailing period is a more probable typo for a user to perform.

**Comment by stevehobbsdev** [comment]
Thanks. So Lock today employs either strict or loose validation on the signup page on the client. You can set `signUpFieldsStrictValidation: true` (it's `false` by default) and email addresses into the signup page will use [`validator`](https://www.npmjs.com/package/validator) to validate email addresses. When set to `false` or left as default, [a _much_ looser validation method](https://github.com/auth0/lock/blob/master/src/field/email.js#L19) is used.

I can see though that this option is missing from the readme, so let me raise a PR to correct that.

The login page does not have such an option, and always uses loose validation as there are a variety of dynamic scenarios where it would be better to validate on the server only.

However, in both cases (login and sign-up) the email address should be validated correctly on the server. It's not as nice, I agree; I'm just trying to clarify the current situation.
