### ISSUE TITLE
Callback does not get executed after signup

### ISSUE THREAD

**Issue by goloroden** [auth0/lock#202]
When using Lock [as described in the docs](https://auth0.com/docs/libraries/lock/types-of-applications#2), using popup mode with an SPA, the callback does not get executed when a new user signs up:

```javascript
var lock = new Auth0Lock('…', '<user>.auth0.com');

lock.show(function(err, profile, id_token) {
  // This is never called
});
```

The only thing that helps moving things forward is manually reloading the entire website.

Any idea what I'm missing?

**Comment by cristiandouce** [comment]
This seems to be a bug. It's not the expected behavior.

Could you try with the latest release of the lock and check if still occurs?

Thanks!

**Comment by goloroden** [comment]
Okay… I updated to 7.8.1, and the issue is still there.

It's due to a blocked pop-up in Chrome. If you allow the website to open pop-ups, everything works as expected.

Hence, I'm going to close this one.

**Comment by cristiandouce** [comment]
Yes, It's a know issue I'm attempting to solve at auth0/lock/pulls/213

**Comment by goloroden** [comment]
Great :-))

Von meinem iPhone gesendet

Am 04.09.2015 um 16:18 schrieb Cristian Douce <notifications@github.com<mailto:notifications@github.com>>:


Yes, It's a know issue I'm attempting to solve at auth0/lock/pulls/213

-
