### ISSUE TITLE
Backspace or Deleting text from the inputs not always work

### ISSUE THREAD

**Issue by spyderdsn** [auth0/lock#2026]
### Describe the problem

Unable to use Backspace or Delete the text entered in the inputs. I'm able to authenticate and get user details, log out. The only thing which does not work is Backspace.

### What was the expected behaviour?

I should be able to delete text.

### Example

https://notionsite.xyz
```

const config = {
    cid: [CLIENT_ID],
    domain: [CLIENT_DOMAIN],
    callbackUrl: [CLIENT_CALLBACK_URL],
}

const options = {
    oidcConformant: true,
    allowShowPassword: true,
    autofocus: true,
    autoParseHash: true,
    allowSignUp: false,
    closable: false,
    offlineAccess: false,
    allowForgotPassword: false,
    avatar: null,
    usernameStyle: "email",
    defaultDatabaseConnection: "Username-Password-Authentication",
    auth: {
        responseType: 'token id_token',
        redirectUrl: config.callbackUrl,
        scope: 'openid'
    },
    theme: {
        labeledSubmitButton: false
    },
    languageDictionary: {
        title: "Sign In"
    }
};

const lock = new Auth0Lock(config.cid, config.domain, options);

function checkAuthenticated() {
    lock.on("authenticated", function (authResult) {
        console.log(authResult);

        if (!authResult.accessToken) return;

        lock.getUserInfo(authResult.accessToken, function (error, profile) {
            console.log(profile);
        });
    });

    lock.on("authorization_error", function (error) {
        console.log("authorization_error", error);
    });
}

checkAuthenticated();
lock.show();
```

### Environment

Loaded inside Cloudflare Worker

```
  <script src="https://cdn.auth0.com/js/lock/11.30.4/lock.min.js"></script>
  <script type="text/javascript" async="" src="https://mydomain.com/lock-config.js"></script>
```

**Comment by stevehobbsdev** [comment]
@spyderdsn this sounds really odd. I can reproduce it on the page you linked, but I can't reproduce it in an instance of Lock outside your environment. Looks like there's a `keydown` handler being attached that is overriding the backspace key, do you know where it's coming from? Perhaps something in the included JavaScript from Notion?

Can you reproduce it in the [Lock SDK playground](https://github.com/auth0/lock/blob/master/DEVELOPMENT.md#the-sdk-playground)?

**Comment by spyderdsn** [comment]
@stevehobbsdev to reproduce this issue you need:

1. Notion (share your test page publically)
2. Cloudflare Account
3. Auth0
4. Fruition Setup (https://fruitionsite.com/)

I used Fruition to generate Cloudflare worker with my demo Notion page. Then I added the scripts above in the custom script section to generate Auth0 lock. I was unable to replicate the issue on my local without a Cloudflare worker.

**Comment by stevehobbsdev** [comment]
Unfortunately, like with every JavaScript library, we can't guarantee compatibility with other scripts and libraries that you are using together. It looks like something you are using with the Notion or Cloudflare ecosystem is capturing input on those login boxes and causing you problems. There might be a way to stop that from happening within the tools you are using.

If you can show that there is an issue with Lock itself through a very small repro that doesn't involve these other third parties, I'd be happy to take a look. Please let us know here if you manage to do that.
