### ISSUE TITLE
Update Microsoft Account logo and color

### ISSUE THREAD

**Issue by ntotten** [auth0/lock#204]
The current logo in lock does not reflect Microsoft's current branding. Microsoft is unifying all logos on their side to be the Microsoft logo rather than the Windows flag. Additionally, they are using a consistent light blue color. We should do the same in lock. Also, any text should be "Microsoft" or "Microsoft Account" rather than "Live ID"

https://auth0.slack.com/archives/design/p1439916105001030

**Comment by cristiandouce** [comment]
@ntotten just to be clear, you say the logo should be the flat one, right?

![image](https://cloud.githubusercontent.com/assets/367429/9647520/3f361024-51b4-11e5-8199-0629961aa284.png)

What is with the color?

**Comment by cristiandouce** [comment]
BTW, it already says Microsoft Account

**Comment by vctrfrnndz** [comment]
This has already been fixed, right @gnandretta? closing.

**Comment by gnandretta** [comment]
@vctrfrnndz yes, thanks!
