### ISSUE TITLE
SMS login: Country code undefined after reopening widget

### ISSUE THREAD

**Issue by hungweng** [auth0/lock#2047]
### Describe the problem

From my understanding, the only way to allow the user to choose between email/password login and passwordless sms login is having two buttons as suggested here: [https://community.auth0.com/t/lock-sms-or-email/6979](https://community.auth0.com/t/lock-sms-or-email/6979)

However, if I close the Lock dialog without logging in, and click the button again to show the login widget, the country code field displays ‘undefined undefined’. And if I attempt to click the country code dropdown, the console shows an error: Cannot read property ‘map’ of undefined.

### What was the expected behavior?

The country code field should show the selected country code after reopening the login widget. And the user should be able to select a different country code.

### Reproduction

With auth0-lock configured for sms login, open the Auth0LockPasswordless login widget, close and reopen it, you will see that the field country code is displayed as "undefined undefined" when users click on the select list the widget stop working.

### Environment

- **Version of this library used:** 11.30 from auth0 cdn: https://cdn.auth0.com/js/lock/11.30/lock.min.js

### Similar issues

https://github.com/auth0/lock/issues/1687
https://community.auth0.com/t/sms-login-country-code-undefined-after-reopening-widget/15859

**Comment by stevehobbsdev** [comment]
Hi @hungweng,

Are you able to reproduce this in the [Lock SDK Playground](https://github.com/auth0/lock/blob/master/DEVELOPMENT.md#the-sdk-playground)? I'm unable to reproduce it but you can let me know if I'm performing the steps wrong.

https://user-images.githubusercontent.com/766403/135848723-557c5022-0fba-45b8-9b5b-05f443c68ab5.mov

If you're unable to reproduce it there, can you supply a small repro sample that demonstrate the issue so that I may look into it? Also, the issues and community posts you've linked managed to find a solution to their issue, do any of these work for you?

**Comment by hungweng** [comment]
Thank you @stevehobbsdev 

In the SDK Playground, when you click the button it creates a new instance of Auth0LockPasswordless each time: `new Auth0LockPasswordless(clientId, domain, defaultOptions)`, this creates a new `div` in the body each time which isn't ideal..

You can reproduce the issue by using the same instance and just call the `show` method.

The author of that community post get around the issue by not allowing the user to close the login widget, that won't work in this case since we need to allow the user to "toggle" between email/password login and sms passwordless login.

**Comment by stevehobbsdev** [comment]
Ohh yep 😄  can definitely reproduce it now - thanks for the additional context.

**Comment by stevehobbsdev** [comment]
I've had a look at this and I can see what's happening - the country code widget relies on some field data that is being cleared when Lock closes, but then the way it's set up at the moment it doesn't rehydrate those when the same instance of Lock is re-opened, as it doesn't run all the pre-init hooks.

It's not just for passwordless though, there's other data in there that might mess up the experience unless we also rehydrate those.

This isn't going to be a quick fix, unfortunately. I've put something in our internal backlog to take a look at what we can do here when time allows. In the meantime, please use a new instance if you wish to re-open Lock on the page. I appreciate it's not the most desirable outcome for your case but at least it unblocks you.
