### ISSUE TITLE
Release v11.30.5 breaks ability to use in NextJS and other SSR contexts

### ISSUE THREAD

**Issue by zackdotcomputer** [auth0/lock#2051]
### Describe the problem

Release 11.30.5 included PR #2030. This did a project-wide find-replace, removing `global` and replacing it with `window`. In the context of running inside of a browser, this works fine. However, because this find-replace included references in code that is executed when the file itself is loaded (e.g. [here in browser.js](https://github.com/auth0/lock/pull/2030/files#diff-341f39e37a92244daaf4fd691a67fd2caa4f9237d92b296584f165b3c512d193)), this has broken the ability to use Auth0 Lock inside of NextJS projects.

The reason for this is that NextJS evaluates page templates both at runtime on the client as well as at request-time on the server and/or build-time on your machine. Because these latter contexts are not running in a browser, `window` is not defined and any attempt to access properties on it will fail.

This does not cause issues in all situations, as the end developer can usually guard against these errors by checking that `typeof window !== "undefined"` before instantiating a client-only piece of UI. However, if `window` is referenced at the top level of a file, such that it will be accessed **during import**, then you have a more serious issue. That is what is happening here - because #2030 adds references to `window`'s properties that are evaluated while the code is initially parsed, even just including `import { Auth0Lock } from "auth0-lock";` in your project will cause the following error during build:

```
> Build error occurred
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/zack/code/addition/web-app/node_modules/auth0-lock/lib/utils/cdn_utils.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/zack/code/addition/web-app/node_modules/auth0-lock/lib/i18n.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  type: 'ReferenceError'
}
```

### What was the expected behavior?

It would be expected that importing `auth0-lock` would not cause a build error.

This could be achieved in one of two ways:

1. Remove references to `window` that are evaluated at import-time, moving the logic into functions or classes that the end developer must invoke intentionally.
2. Guard references to `window` that happen at import-time with the `typeof window !== "undefined"` check before attempting to access any properties.

### Reproduction

[Repro Project](https://github.com/zackdotcomputer/auth0-lock-repro)

Repro steps were:
1. Create a new NextJS Project
2. Add a dependency to auth0-lock
3. Import auth0-lock in a page

Project now fails `npm run build`

### Environment

From `package.json`:
```
    "auth0-lock": "^11.30.6",
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
```

**Comment by stevehobbsdev** [comment]
We've tried to resolve this in [v11.31.1](https://github.com/auth0/lock/releases/tag/v11.31.1) - please try it out and let us know if this is now working for you.
