### ISSUE TITLE
Move React and React DOM to peer dependencies

### ISSUE THREAD

**Issue by zackdotcomputer** [auth0/lock#2052]
### Describe the problem

Because react and react-dom packages are added as direct dependencies with compatible versions, adding this project in a react17 context causes a second, older version of react to be installed specifically for this project.

### What was the expected behavior?

The expected behavior would be for this project to reference react and react-dom as peer dependencies (and use a more permissive versioning such as `"react-dom": ">=15.6.2"`). This way the package resolution should always use the project's top-level dependency on the react packages and throw a warning if an incompatible one is present, rather than duplicating the packages.

### Reproduction

This issue can be viewed in [this project's yarn.lock](https://github.com/zackdotcomputer/auth0-lock-repro/edit/develop/yarn.lock) where adding auth0-lock to a react17 NextJS project has caused two copies of react-dom and react each to be installed.

### Environment

From package.json:
```
    "auth0-lock": "^11.30.6",
    "react": "17.0.2",
    "react-dom": "17.0.2"
```

**Comment by stevehobbsdev** [comment]
👋🏻 We now have a v12 beta version that includes an upgrade to React 18 - please see [this issue](https://github.com/auth0/lock/issues/2224) and let us know what you think, or if you encounter any problems!
