### ISSUE TITLE
No 'id' attribute on password input or login button

### ISSUE THREAD

**Issue by shaneagibson** [auth0/lock#2067]
### Describe the problem

The Password input and Login button do not contain **id** attributes.

This attribute was previously added to the Email input in v11.12.0. It would be valuable to have the same added to the Password input and Login button.

Without this, SaaS cookie consent tooling such as OneTrust are unable to perform a login as they rely solely on the ID attribute.

### What was the expected behavior?

The password input should contain something like:

`id="{lockId}-password"`

The login button should contain something like:

`id="{lockId}-submit"`

### Reproduction

1. Render the login page
2. View the DOM
3. Inspect the password input and login button elements

### Environment

- **Version of this library used:** 11.31.1
- **Which framework are you using, if applicable:** N/A
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:** N/A

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @shaneagibson , I've raised #2072 to fix this.
