### ISSUE TITLE
Object null issue in sync.js file

### ISSUE THREAD

**Issue by nishantr4p** [auth0/lock#2070]
### Describe the problem
Please check the image attached for error

### Reproduction
![Capture](https://user-images.githubusercontent.com/81556432/144626029-dc23b1f2-b696-4977-b137-7b1953a5ec0a.PNG)

1. Login to Auth0 Lock on React 
2. Login successfully  but in console i see this error
3. in Production it does not break anything but in local the application breaks

### Environment

- **Version of this library used:** "auth0-lock": "^11.27.1",
- **Which framework are you using, if applicable:** REACT typescript
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Thanks for reporting. This is not something I'm able to reproduce with the instructions given. If you're able to supply a small reprodicable sample that demonstrates the error, I'll be happy to take a look.

**Comment by stevehobbsdev** [comment]
Closing this for now but if you manage to come up with a repro, please reply here and I'll take a look.
