### ISSUE TITLE
Can't log in in firefox.

### ISSUE THREAD

**Issue by JohnnyTMD** [auth0/lock#2074]
Hi, I have an angular 12 project which uses latest version of auth0 lock, everything works fine for other browsers except firefox. I'm using firefox 95.0.2.
I have noticed this event never gets triggered.
` this.lock.on('authenticated', (authResult) => { `
Because of that I can't log in.
Please investigate. Happens on all platforms, linux, mac, windows.

**Comment by stevehobbsdev** [comment]
Hi @JohnnyTMD,

If you're able to supply a small repro that demonstrates the issue I'd be happy to take a look. We haven't otherwise seen any specific issues with Lock + Firefox 95 thus far.

Cheers
