### ISSUE TITLE
Self hosted files

### ISSUE THREAD

**Issue by miguel-krasamo** [auth0/lock#2075]
Greetings,

If I host the language files can we add a string in the lang files to  localize an item added in `additionalSignUpFields` or what is the recommended way to achieve this if that new field has to be localized in different languages?

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @miguel-krasamo. Currently there is no built-in support for localization of the `additionalSignupFields` and any localizations would have to be given by you when specifying the fields in the config. I'm not sure we have a canonical way to achieve this that I can recommend, but you'd need to know the language you're interested in, and also access to the localised strings. That might mean keeping them separate from the uploaded language files, or being able to download the files at the time when you need them.
