### ISSUE TITLE
webpack build: Error: Cannot resolve module 'package.version' 

### ISSUE THREAD

**Issue by lapanoid** [auth0/lock#208]
I tried to build my project with webpack which import auth0-lock.
I get this error.

```
ERROR in ../~/auth0-lock/~/auth0-js/index.js
Module not found: Error: Cannot resolve module 'package.version' in ../auth0-lock/node_modules/auth0-js
 @ ../~/auth0-lock/~/auth0-js/index.js 166:16-42
```

How actually require('package.version') work?
I guess this is 
```
version = require('./package.json').version
```
more straightforward way.

**Comment by jfromaniello** [comment]
Not sure how webpack works, but I think your solution will add more junk to the bundle.

However, this has been requested in other issues so I think we should find a solution.

My intention with this module is that you either use it with npm and browserify , or you use the bundled version that we ship.

**Comment by lapanoid** [comment]
Just found out the solution https://github.com/auth0/lock/tree/master/examples/webpack#running-the-example. This is duplicate of https://github.com/auth0/lock/issues/54 so closing. 
I just think you should wrote something in readme for webpack users. I mean like you did with browserify, I just skipped examples section https://github.com/auth0/lock#examples, did not expect to find solution here.

**Comment by HotCustard** [comment]
![locl-error](https://cloud.githubusercontent.com/assets/3368688/10380365/58cb0062-6e0b-11e5-9831-e7d06e18c0a6.png)

I am getting the same error using the example, did i miss something?

**Comment by cdroulers** [comment]
I'm experiencing the same issue, and when I checkout the examples project and run `npm install; npm start` it crashes with the following:

```
> lock-webpack-example@1.0.0 start C:\dev\external\lock\examples\webpack
> webpack && webpack-dev-server --quiet --port 3000 --content-base public/

Hash: 9e38a041f8188bc25668
Version: webpack 1.12.2
Time: 1124ms
    Asset    Size  Chunks             Chunk Names
bundle.js  923 kB       0  [emitted]  main
   [0] ./src/app.js 1.64 kB {0} [built]
   [1] ./src/auth0-variables.js 117 bytes {0} [built]
    + 105 hidden modules

ERROR in ./~/auth0-lock/index.js
Module not found: Error: Cannot resolve module 'package.version' in C:\dev\external\lock\examples\webpack\node_modules\auth0-lock
 @ ./~/auth0-lock/index.js 114:20-46

ERROR in ./~/auth0-lock/lib/insert-css/index.js
Module not found: Error: Cannot resolve module 'fs' in C:\dev\external\lock\examples\webpack\node_modules\auth0-lock\lib\insert-css
 @ ./~/auth0-lock/lib/insert-css/index.js 5:9-22
http://localhost:3000/webpack-dev-server/
webpack result is served from /
content is served from C:\dev\external\lock\examples\webpack\public
```

**Comment by hiroshi** [comment]
@cdroulers Same here.

I'm not sure, but `npm install --save fs` seems to save us.

**Comment by llops** [comment]
Hi @cdroulers @hiroshi I had the exact same error on windows, and this code #300 solve it
