### ISSUE TITLE
Prefill the password box

### ISSUE THREAD

**Issue by Ewan-S** [auth0/lock#2080]
### Describe the problem

We would like a way to prefill the password as well as the username/email. We are logging guest users into our site, and we don't want them to sign up, so we create a temporary user using the Auth0 management API, and then want to automatically log that user in.

Prefill allows us to populate the email box, but we cant populate the password box. I've tried using javascript to populate the box, but it doesn't appear possible to alter the password box's value. The HTML is displayed as if the password box has a value set, but the value is not set in the DOM. I suspect this is due to some combination of blazor's and the lock.js event handling.

### What was the expected behavior?

In some way or another, to pre-fill the password box with a value. Ideally, using the prefill options in the lock initialisation, so that we don't have to use javascript. Hopefully the developer could be trusted to use that option wisely in situations such as this.

### Reproduction

Here is a redacted version of our lock.js initialisation. I'm using an event handler that fires when the lock is shown, and I'm trying to use that to populate the password box.
```
  var lock = new Auth0Lock(
        clientId,
        loginUrl,
        {
           **** removed for brevity ****
            prefill: {
                email: email,
              }
        });

    lock.on("signin ready", function() {
        setTimeout(function () {
            //1 second window so the lock is displayed properly
            document.getElementById("1-password").value = pass;
        }, 1000);
    });

    lock.show();
```
The images below show the outcome of that javascript. The password box is populated in the HTML, but has not set the value in the DOM, and when you click to log in, it returns an error saying the password can not be blank

![1](https://user-images.githubusercontent.com/5892482/148799147-d67b8790-8f13-405e-8c89-7221309a3e43.JPG)
![2](https://user-images.githubusercontent.com/5892482/148799152-e310f106-3d5f-4f66-b8f0-5a503b213214.jpg)

### Environment
- Lock version - 11.32
- .NET 6, C#, ASP.NET Core Blazor WASM

**Comment by stevehobbsdev** [comment]
👋🏻As you've deduced, Lock does not allow prefilling the password, and you're unable to set it using JavaScript - what's more likely getting in the way here is React. It won't be picking up changes to the DOM and incorporating that into its state management, so any changes you make are lost the next time the component redraws.

For this use case, I would look into using [auth0.js](https://github.com/auth0/auth0.js/#clientloginoptions-callback) and using `login` to log the user in using a username and password. This way you can remove the need for the UI entirely for your guest users.

Does this help?

**Comment by Ewan-S** [comment]
HI Steve, thanks for getting back to me so quickly!

That makes a lot of sense actually! And auth0.js sounds along the right lines, definitely given us something to think about. Thanks for your input! One thing I'd like to clarify:

"This will not initialize a SSO session at Auth0, hence can not be used along with silent authentication."

Does that mean that we wouldn't be able to silently renew access tokens? We only have one app that needs signing into, so SSO isn't required as such, but we would like to be able to keep that user signed in and renew their access tokens as needed. 
For example, currently we have a 30 day inactivity window to allow users to come back and continue using the site without having to authenticate again, would that not be possible for guests if we were to use this mechanism?

**Comment by stevehobbsdev** [comment]
Yes, unfortunately you're correct with that one. This may need some deeper thought as to how you want to allow this guest user to be allowed into your application. Is there a backend involved in this architecture somewhere? You could use the client credentials flow to gain new access tokens while keeping your users logged in using a normal cookie session. A common pattern for this (if it applies) is to then provide some kind of endpoint (protected by the cookie) that your frontend app can access to retrieve the token and/or access user profile data, whatever you need.

> Hopefully the developer could be trusted

This is the crux of the problem with allowing Lock to prefill the password. The scenario we're optimizing for is that the user types the password into the box. If we were to facilite the password being prefilled, it means that somewhere the user has been encouraged to enter their password elsewhere and places a BIG trust on developers to do the right thing concerning the handling of that password (storage, etc). Granted your scenario is not that exactly but is instead a big edge case.

Unfortunately prefilling the password is not something we can accomodate, so I'll close this for now but happy to continue the conversation as necessary. As for some ideas as to how to architect this type of scenario, it could be worth poseing this question on the [community forums](https://community.auth0.com) to see how other areas of the Auth0 product surface area can help.

**Comment by Ewan-S** [comment]
Thanks for your reply Steve!
Honestly, that is the outcome I expected from this line of thinking, but I thought I may as well ask. I completely understand the reasoning and it makes a lot of sense.

That's actually really reassuring though, since we've been busy knocking this together and essentially came up with the exact same architecture that you outlined in your first paragraph. So I'm really glad that we're along the same lines with the solution.

Lastly, thank you for your time & input on this, its been very helpful in getting us over the finish line with this use case!
