### ISSUE TITLE
Incompatible with vitejs

### ISSUE THREAD

**Issue by nichita-pasecinic** [auth0/lock#2107]
### Describe the problem

Using vitejs `"vite": "^2.8.6"` and auth0-lock latest and seems like auth0-lock is not yet compatible 
Error:
```
Uncaught TypeError: Super expression must either be null or a function, not undefined
```

The issue is here
```javascript
export default require("./node_modules/auth0-lock/lib/index.js");
```

### What was the expected behavior?
To work with vitejs as client side bundler (react environment)

**Comment by stevehobbsdev** [comment]
Hi, we don't have any plans to support Vite at this stage, but happy to review and accept a PR that adds this support if it's truly needed.

**Comment by schmidfelix** [comment]
Sorry for the ping, but did you manage to get it running in some other way?

**Comment by nichita-pasecinic** [comment]
@schmidfelix yeah, import it as cdn

**Comment by adamdehaven** [comment]
@stevehobbsdev any plans to support Vite now that it has been widely adopted?

**Comment by stevehobbsdev** [comment]
@adamdehaven No plans but I suspect we could do something to help support this. Could you please raise a new issue with a small repro for us to work with?

**Comment by adamdehaven** [comment]
@stevehobbsdev here's a Codesandbox: https://codesandbox.io/p/sandbox/withered-night-l4khnn?file=%2Fpackage.json%3A1%2C1

In the terminal, just run `yarn dev` and you'll see the `Super expression must either be null or a function` error

**Comment by dRAT3** [comment]
Anybdy have a polyfill for this?

**Comment by strimbob** [comment]
cdn worked for me, but do you have plans to support Vite ? It is ubiquitous now
