### ISSUE TITLE
Error: Can't find element with id auth0-lock-container-8

### ISSUE THREAD

**Issue by xinghengwang** [auth0/lock#2108]
### Describe the problem

Exception of can't find element with id auth0-lock-container-1 -> 2. 

The lock isn't even shown. This is after user already successfully logged in. 

<img width="1225" alt="Screen Shot 2022-03-24 at 5 40 42 PM" src="https://user-images.githubusercontent.com/6666687/160032752-8ac287ae-b872-43cc-8b9f-0c8aef67207d.png">

### Reproduction

Just randomly pops out while the user already logged in after a while. The lock isn't even shown. 

### Environment

- **Version of this library used:**:   "auth0-lock": "11.30.1",
- **Which framework are you using, if applicable:**: react

**Comment by stevehobbsdev** [comment]
Thanks for raising @xinghengwang. If you can provide me with a repro that demonstrates the issue, I'd be happy to take a look.

**Comment by stevehobbsdev** [comment]
Will close this for now but if you have a repro we can look at, please send it over.
