### ISSUE TITLE
Signup link does not appear to change the rendered signup link

### ISSUE THREAD

**Issue by vrmardare** [auth0/lock#2112]
Hi,
I'm using auth0-lock package within a hybrid application - angular/react. All good so far setting up the auth0 form, but our app routes use hash based routes, which seems to mess up the sign up link. Although I have set the option of `signupLink: "https://yoursite.com/signup"` the sign up `href` still points to `#`, which would trigger a page refresh (not a server side refresh), and I'd still get the login and not the sign up.

DOM screenshot
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/103669171/163434474-b5a85cd4-ecf6-417b-8f65-5e061b99f53a.png">

What happens is that if I click sign up, I'll get a refresh and another login form would pop over the existing one, and I never get to access the sign up part.

`forgotPasswordLink` is actually working, but sign up not.

**Comment by stevehobbsdev** [comment]
Hi @vrmardare,

Just purely looking at information you've supplied, you might have a typo. It's `signUpLink` (with a capital "U"), vs `signupLink` as you specified above. However, not sure if that's just a typo in the issue or that typo is actually in your code as well. Can you double check?

I've tested here (albeit not inside an Angular app) and I'm able to set a sign-up link correctly, and the code around this feature seems very simple and straightforward. If there is an issue even with the correct spelling, I'd suggest looking into how Angular or React can possibly get involved and cause an issue. Happy to look at a small repro if you're able to provide one.

**Comment by vrmardare** [comment]
Right, it was a typo. The initial issue was around the generated sign up link which pointed to a different route than the one currently in place, therefore causing a refresh which remounted the component and I was never able to get to the sign up view.
