### ISSUE TITLE
CAPTCHA displays above custom fields

### ISSUE THREAD

**Issue by CMLabay** [auth0/lock#2118]
### Describe the problem

When configuring the lock object for the New Universal login, if both the simple CAPTCHA and additionalSignupFields are enabled,  the CAPTCHA will display above the additionalSignupFields (but below the email and password fields). This is bad looking UI. If there are additional signup fields defined in the additionalSignupFields array, the CAPTCHA should be placed underneath these fields.

### What was the expected behavior?

The expected behavior is that the CAPTCHA would be displayed underneath ALL fields on the the signup screen.

### Reproduction

- Step 1..
- Step 2..
- ...
Enable simple CAPTCHA by navigating to Security > Attack Protection > Bot Detection.
In the Response section, select Enforce CAPTCHA - Always, and choose Simple CAPTCHA as the provider.
Save.

Navigate to Branding > Universal Login > Settings
Select New as the Universal Login Experience
In the Login tab next to Settings:
Update the html file by adding the additionalSignUpFields config item, and add at least one field to the array.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/18117126/170345187-70362a1c-2982-4d36-939a-6a69774c9a23.png">

Save Changes.
View the Signup screen:
![image](https://user-images.githubusercontent.com/18117126/170343741-484ff66b-7864-4227-89be-7222fccb7533.png)

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Thanks for raising @CMLabay. I do agree the UI looks a little off in this case. Let me raise a PR to fix it 👍🏻
