### ISSUE TITLE
Replicate Firebase behavior of prompting SSO association with account

### ISSUE THREAD

**Issue by janat08** [auth0/lock#2158]
### Describe the problem
When user tries to sign in under email that already has account using different SSO then you just let him in instead of prompting him to sign in with sso with which account was create after which the new SSO is associated with the account like in firebase auth.

### What was the expected behavior?
For any new SSO to be associated with other email based accounts.

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment
auth0 for web/server

**Comment by stevehobbsdev** [comment]
Thanks for raising @janat08. We don't link accounts automatically, but you're able to do this using our APIs. Please read [Account Linking](https://auth0.com/docs/manage-users/user-accounts/user-account-linking) for more details.

You can also submit this type of product feedback to our [feedback page](https://auth0.com/feedback).
