### ISSUE TITLE
Incorrect success message from auth-lock options displayed (`logIn` message shown instead of `signUp`)

### ISSUE THREAD

**Issue by ebasic** [auth0/lock#2159]
### Describe the problem

Auth lock options are set correctly according to this example on [github](https://github.com/auth0/lock/blob/master/src/i18n/en.js).
In `success` part, I have both `logIn` and `signUp` messages defined as stated above in example. On `signUp success`, message for `logIn success`  is shown.

### What was the expected behavior?

Correct message for `signUp success` is shown.

### Reproduction
1. Open logIn page
2. Swith to signUp page
3. Fill out email/pw and confirm 
4. Observe success message on signUp success

### Environment

react version:  17.0.2
auth0-lock version:  11.32.0

**Comment by stevehobbsdev** [comment]
👋🏻 Is the link to the example correct? I'm just getting one of the i18n translation files. Did you mean to link to a workable example?

**Comment by ebasic** [comment]
Link is correct, I posted example of i18n translation files which is part of `auth0lock` config under `languageDictionary` key and we use almost the same dictionary in our project. There is nothing more to do with this config, it is just passed to auth-lock instance according to documentation:

`const lock = new Auth0Lock(clientId, domain, options)`

And as mentioned, `options` object is:

`const options = {...options, languageDictionary: {} }`
