### ISSUE TITLE
Disable form translate/opacity animation

### ISSUE THREAD

**Issue by Klaasvaak** [auth0/lock#2162]
This is a feature request, https://community.auth0.com/ told me to open an issue on the corresponding GitHub repo.

### Describe the problem

The login form has a translate and opacity animation. This animation has a delay of 0.5s and the animation itself takes 0.6s. For our implementation of Lock we would like to be able to disable this animation to save 1.1s of loading time before we can click on login. A lot of people in our company are seeing this login form every day, and it would be a great improvement if we can disable this animation.

<img width="325" alt="Screenshot 2022-08-16 at 10 50 59" src="https://user-images.githubusercontent.com/1911045/184838668-6f07205f-b175-463a-b9dc-5f570b9461f1.png">

### What was the expected behavior?

Having an option to disable the form animation.

### Reproduction

- Go to the page to see the login form
- Observe the translate/opacity animation

### Environment

- **Version of this library used:** v11.16.3

**Comment by stevehobbsdev** [comment]
Thanks for raising @Klaasvaak.

Unfortunately we are no longer taking feature requests for this library. However, as we've realised, this isn't obvious when you come to the repo (but we mention it on [our library support page](https://auth0.com/docs/libraries#:~:text=Github-,Lock%20SDK%20Libraries,-Do%20you%20use)).

So I'm unable to accommodate this request. However, you should be able to solve this with some specific CSS overrides with your app, or a [custom Lock template](https://auth0.com/docs/customize/universal-login-pages/customization-classic) (if you're using Lock through [Universal Login](https://auth0.com/docs/authenticate/login/auth0-universal-login)).

In the meantime I'll raise a PR to make our level of support here more obvious.
