### ISSUE TITLE
getUserInfo not returning user_metadata

### ISSUE THREAD

**Issue by Commandtechno** [auth0/lock#2181]
:warning: **Note:** We are no longer supporting requests for new features. Only requests for bug fixes or security patches will be considered.

### Describe the problem

I added registration fields using additionalSignupFields, and the metadata shows up in the dashboard

![image](https://user-images.githubusercontent.com/68407783/194366209-2b937c88-6d77-456a-8775-b85ab1362741.png)

But calling getUserInfo returns no user_metadata field, and nor does the api response

![image](https://user-images.githubusercontent.com/68407783/194367309-b714cf4e-a3b4-4f79-bed4-57c7f5d1f78d.png)

![image](https://user-images.githubusercontent.com/68407783/194367577-4e0474ff-2d3a-467b-9ff8-bc7b71da930c.png)

### What was the expected behavior?

getUserInfo returns the user object with uesr_metadata

### Reproduction

```js
    const lock = new Auth0Lock("client id", "domain", {
      additionalSignUpFields: [
        { name: "location", placeholder: "Where do you live?" },
        { name: "games", placeholder: "What games do you play?" }
      ]
    });
    lock.show();
    lock.on("authenticated", s => {
      console.log("authenticated");
      lock.getUserInfo(s.accessToken, (e, u) => {
        console.log(u);
      });
    });
```

### Environment

- **Version of this library used:** 11.34.1
- **Which framework are you using, if applicable:** next.js
- **Other modules/plugins/libraries that might be involved:** @auth0/nextjs-auth0
- **Any other relevant information you think would be useful:** I'm only using lock because I thought the nextjs auth0 didn't support user_metadata, but both seem to be returning the same data

**Comment by stevehobbsdev** [comment]
So there is a very subtle thing in [the documentation](https://auth0.com/docs/manage-users/user-accounts/metadata#use-rules) that I'm suspecting you're missing when trying to access `user_metadata` from either Lock or NextJS Auth0:

> You can also use the `GET /userinfo`endpoint to get a user's `user_metadata`, however, you must first write a Rule to copy `user_metadata` properties to the ID token.

I could reproduce your issue, and creating a rule with the following content then allowed me to access `user_metadata` in the exact way you've described in your issue:

```js
function (user, context, callback) {
  context.idToken.user_metadata = user.user_metadata;
  return callback(null, user, context);
}
```

Hopefully that helps. For me that's very subtle and I'm going to reach out to our internal docs team to see if we can make those docs more clear.
