### ISSUE TITLE
RequireJS - Unclosed String at position: 780174 / Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by asim-blueprintprep** [auth0/lock#2185]
### Describe the problem

I have auth0 lock in magento, via requireJS. The way I have this working is by using the unminified version (as magento in production mode minifies it). I have been using lock v11.30.4. I have tried to use every lock.min.js file in the repo history (goes back to 11.30.6) and use PHPStorm to unminify, and then let magento minify as it compiles. However, every revision of the file in the repo (back to 11.30.6) has introduced a bug that magento crashes on (unclosed string at position: 780174)

requireJS:
`"auth0Lock": {
            exports: 'Auth0Lock'
        }`

### What was the expected behavior?

Unminified version compiles in magento.

`Unclosed String at position: 780174 `

If I use the minified version:

`Uncaught SyntaxError: missing ) after argument list (at auth0Lock.min.js:8:237294)
auth0embed.min.js:4 Uncaught TypeError: Auth0Lock is not a constructor`

### Reproduction

- Step 1. download copy of minified file
- Step 2. add to repo and unminify
- Step 3. make sure it is being added via requireJS
- Step4. run bin/magento setup:static-content:deploy 
- Step 5. error appears
- ...
- repeat above but don't minify for other error

### Environment

Magento 2.4.4-p2
RequireJS
PHP 8
lock > v11.30.4

## Side note

If I use the minified version, the error I get is:

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
