### ISSUE TITLE
Please hide the value of input type="password" in the Form form

### ISSUE THREAD

**Issue by mountain2016** [auth0/lock#2194]
### Describe the problem

Under normal circumstances, when input type="password", the value attribute of the input can not be seen in the browser console elements, but can be directly seen in the login and signup form

### What was the expected behavior?

I hope the value attribute can be hidden

<img width="584" alt="image" src="https://user-images.githubusercontent.com/17536946/200111658-8260150a-33b9-4574-ab97-6302fba263a5.png">

**Comment by mountain2016** [comment]
> Duplicate of # #2200 @gido3823

I upgraded lock to 11.34，but can still see the value on the console, will this problem be modified?

**Comment by stevehobbsdev** [comment]
@gido3823 I'm not sure the PR you reference is a duplicate of this, #2200 is just a dependency upgrade.

As the form field is controlled using React, whatever you type into any input field will be reflected in the `value` attribute. We don't believe this is an issue as you are only seeing the value you yourself have typed in.

Even if we changed this behaviour, there are other ways you can easily discover the value that was entered (JavaScript manipulation, change the `type` attribute to `text`, etc). A potential attacker would also need to have access to the machine on which the login form is being used.

Thanks for raising this concern but we don't believe it needs modification at this time. If you believe this to be a genuine security concern, please familiarise yourself with our [security policy](https://github.com/auth0/lock/security/policy) where you can find guidance on how to report a vulnerability.
