### ISSUE TITLE
Weird "last time you sign in with" account with linked accounts

### ISSUE THREAD

**Issue by solepano** [auth0/lock#220]
I have my google account linked to a username&password root account (sole@sole.com). I logged-in to my app using the google account and then logout. When I was about to login again I got this message on lock:

<img width="280" alt="lock-issue" src="https://cloud.githubusercontent.com/assets/1350396/10023480/39a180f0-6107-11e5-90f0-683ca0a48386.png">

So, it is saying I logged in with the G+ provider, which is fine, but it is using the root user email instead of the google account email.

Thanks,
Sole

**Comment by hzalaz** [comment]
More of an issue of how SSO data is returned. Will report to backend
