### ISSUE TITLE
FAQ link in Readme is incorrect

### ISSUE THREAD

**Issue by piwysocki** [auth0/lock#2202]
:warning: **Note:** We are no longer supporting requests for new features. Only requests for bug fixes or security patches will be considered.

### Describe the problem

in README.md:

`[FAQs](https://github.com/auth0/lock/blob/master/FAQ.md) - frequently asked questions about lock.`

this link goes to 404 page

### What was the expected behavior?

remove FAQ in readme or add correct link

### Environment

- **Version of this library used: latest**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by frederikprijck** [comment]
Thanks for reporting!
