### ISSUE TITLE
"The domain null has not been set up" with usernameStyle: 'username'

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#221]
Steps to reproduce:

1. Create an enterprise connection with no configured email domains
2. Set `usernameStyle: 'username'`
3. Try to log in with any username

Result:

![image](https://cloud.githubusercontent.com/assets/829698/10061456/5427343c-622f-11e5-9146-c41dc6061f8b.png)

Example playground code:

```
var domain = 'panchaea.auth0.com';
var cid = 'jGMow0KO3WDJELW8XIxolqb1XIitjkYL';

var widget = new Auth0Lock(cid, domain);

widget.show({
  usernameStyle: 'username',
  connections: ['test'],
  focusInput: false,
  popup: true,
}, function (err, profile, token) {
  alert(err);
});
```

**Comment by hzalaz** [comment]
No longer applies in Lock v10 since it just shows
 
<img width="411" alt="screenshot 2016-08-31 11 00 16" src="https://cloud.githubusercontent.com/assets/895992/18144468/34d65708-6f9d-11e6-9262-6d1a6e6e9a74.png">
