### ISSUE TITLE
replace LGTM with GitHub code scanning

### ISSUE THREAD

**Issue by piwysocki** [auth0/lock#2211]
:warning: **Note:** We are no longer supporting requests for new features. Only requests for bug fixes or security patches will be considered.

### Describe the problem

https://lgtm.com/

LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead.

### What was the expected behavior?

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by stevehobbsdev** [comment]
Thanks - we have a PR open, which I will be triaging this week.

https://github.com/auth0/lock/pull/2197
