### ISSUE TITLE
Conditionally Disable Social login with Passwordless 

### ISSUE THREAD

**Issue by daxiang28** [auth0/lock#2216]
### Describe the problem

Is there a way to dynamically disable social connections when using passwordless? I have a scenario where I am creating accounts via the API and sending links to users. Some users with gmail accounts are clicking on the Google social auth and getting errors this way. I would like to constrain them to using passwordless for the time being. 

### What was the expected behavior?

![image](https://user-images.githubusercontent.com/260903/206571577-088ef075-fff9-4882-a502-168454ff4c70.png)

A user would only see the email field to request their pin.

### Environment

I am using a custom universal login via the Auth0 branding UI dashboard

**Comment by stevehobbsdev** [comment]
@daxiang28 You should be able to use the `allowedConnections` configuration option to control this:

```js
new Auth0LockPasswordless('<client id>', '<domain>', {
  allowedConnections: ['email']
});
```

**Before**
![image](https://user-images.githubusercontent.com/766403/209167281-69fec314-0fb5-406b-aab6-16b6d1a39b10.png)

**After**
![image](https://user-images.githubusercontent.com/766403/209167410-1ba11aad-1b52-4ca1-8ca8-94fc90c7693e.png)

Hope that helps
