### ISSUE TITLE
is it any possible login once then across multiple subdomain in this library? 

### ISSUE THREAD

**Issue by amantiwari1** [auth0/lock#2228]
### Describe the problem
I am trying to add auth0-lock to the landing page and after login, it doesn't work due to missing cookies like state doesn't match
and I know it works in auth0-spa-js but so is it possible to change domains like app.example.com to .example.com in auth0-lock just like auth0-spa-js

### What was the expected behavior?
the state doesn't match after login from redirect landing subdomain to app sub domain
 

it should be working auth in app subdomain after login in landing subdomain

### Reproduction

- **Version of this library used:**
 11.35.0
- **Which framework are you using, if applicable:**
 Vuejs
- **Other modules/plugins/libraries that might be involved:**
 no
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @amantiwari1. Today this is not possible with the library; it's actually the underlying [auth0.js](https://github.com/auth0/auth0.js) that manages the cookie storage and we unfortunately don't provide any affordances to set the cookie domain value, which would allow it to work across subdomains.

Curious as to your usage of SPA JS (which uses our Universal Login product) vs downgrading to Lock - can you share what's driving that decision?

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
