### ISSUE TITLE
Emails with trailing spaces are considered invalid only in IE

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#223]
Steps to reproduce:

1. Using IE11, enter an email with a trailing space, such as `foo@example.com `
2. Enter any password, try to log in

Result:

![image](https://cloud.githubusercontent.com/assets/829698/10111052/81a745d6-63a7-11e5-9559-32d1a9a40f82.png)

In Chrome, Firefox and Safari this works as expected.

**Comment by cristiandouce** [comment]
No longer a problem since **Lock v10**
