### ISSUE TITLE
Android popup results in page reload after redirect completion.

### ISSUE THREAD

**Issue by Zoltu** [auth0/lock#224]
When using the Auth0 lock widget popup on Android in Chrome, the popup will cause the originating page to refresh after completion.  On a desktop browser once the pop-up is complete the page will not refresh.

This is causing problems for me because I do not store authentication information in local storage.  When the originating page refreshes (after authenticating), authentication information is lost and the user is prompted to login again once they try to perform some restricted action.  In short, my users can't authenticate with Auth0 on Android.

**Comment by hzalaz** [comment]
Hi, is this still an issue? can you provide a sample where we can test it?

**Comment by Zoltu** [comment]
I believe I worked around this problem last year when I ran into it in some way (I don't remember how).  That project hasn't been touched much for about 6 months so I don't have a repro case at this point and I don't use Auth0 for my newer projects because of this issue and the Auth0 Lock Widget size issue.  Sorry.  :/

**Comment by hzalaz** [comment]
No worries, thanks for answering
