### ISSUE TITLE
12.0.0 Dictionary File Link Returns 403

### ISSUE THREAD

**Issue by alexdobson** [auth0/lock#2247]
### Describe the problem
It appears that the dictionary file in 12.0.0 returns a 403: [https://cdn.auth0.com/js/lock/12.0.0/en.js]( https://cdn.auth0.com/js/lock/12.0.0/en.js)

### What was the expected behavior?
It should be able to load the dictionary file for the current version.

### Reproduction

- Step 1: Open Auth0 Lock
- Step 2: Observe console warning `index.js:509 https://cdn.auth0.com/js/lock/12.0.0/en.js could not be loaded. Falling back to default dictionary.`
### Environment

- **Version of this library used:** 12.0.0

**Comment by stevehobbsdev** [comment]
Thanks for raising @alexdobson - we're aware of an issue with CDN publishing currently and we're actively working to fix it. I'll report back once we've got it sorted.

**Comment by stevehobbsdev** [comment]
Just to confirm you're getting a warning at this stage, but it's not preventing Lock from being used?

**Comment by alexdobson** [comment]
Hi, thanks for the quick reply! Well, first it prints out a 403 error in the console (followed about 100 warnings). It doesn't seem to affect the functionality of the lock.

![image](https://user-images.githubusercontent.com/67032270/214327864-78180f53-7ca0-49d3-b316-6cc5528e8bce.png)

**Comment by stevehobbsdev** [comment]
Thanks for confirming!

**Comment by stevehobbsdev** [comment]
@alexdobson The issue we've had with our CDN publishing looks to be resolved now and the files have been republished, can you confirm that it's working for you now?

**Comment by alexdobson** [comment]
I can confirm that the issue is resolved. Appreciate your swift response on this!
