### ISSUE TITLE
Lock "last time you signed in with" broke after Passwordless

### ISSUE THREAD

**Issue by solepano** [auth0/lock#227]
I login on my domain (local sample app at http://localhost:3000) using Lock-Passwordless with an email connection.

Then I tried to login to same domain using Lock, but couldn't do it. The "Last time you signed in with" message was showed but with no options. And the **show all** link was broken.

Lock should display all connection options if it doesn't recognize the strategy of the last login.

<img width="1094" alt="locklastloginwithbug" src="https://cloud.githubusercontent.com/assets/1350396/10229396/6354d4bc-684e-11e5-81a6-2afce5249208.png">

**Comment by glena** [comment]
Should be fixed in the latest release.
