### ISSUE TITLE
Missing dependency of events (auth0-lock is dependent on Webpack dependencies?)

### ISSUE THREAD

**Issue by noyoliel-devocean** [auth0/lock#2290]
### Describe the problem

When using Vite, instead of Webpack, the dependency of the library "events" is missing, however it is used by "auth0-lock".
This causes an exception to be thrown at runtime.

### What was the expected behavior?

"events" will be part of the dependencies of auth0-lock and I won't need to add it manually to my package.json dependencies sections.

### Reproduction

* create a React project and use vite instead of webpack
* add auth0-lock to the project dependencies
* add an import "import Auth0Lock from "auth0-lock";" and make sure that it is used somewhere so that it won't be removed by optimizations
* run the application in the browser.
* an error should appear.

### Environment

Version: 2.0.1
Frameworks: Vite, React
Other related libraries and plugins: Webpack, events

Additional information:

By adding "events" lib to my package.json dependencies, issue was resolved.
the functionality of auth0-lock worked fine, until we replaced Webpack with Vite, which removed the events library that comes with Webpack

**Comment by stevehobbsdev** [comment]
Thanks for raising this, looks like we should be including it as a dependency ourselves. I'll raise a PR 👍🏻
