### ISSUE TITLE
Redirect: true will disable the event of authenticated

### ISSUE THREAD

**Issue by qixiaojian310** [auth0/lock#2299]
I know that you advise the user use the redirect:true for lock. But I face some problem

When I use redirect:true it will redirect to the redirect page and will not trigger the authenticated event. I find that I can use redirect: false it will trigger that when I login as google or github account. but when I login with email, it will send a warning in the console as #1672 mention 
"WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.. The console shows this: auth0.min.esm.js:8 Consent Required. Consent can't be skipped on localhost"

so I want to know, if I use redirect:true, how can I trigger the authenticated event like the redirect:false or you can tell me how to require the consent

**Comment by qixiaojian310** [comment]
btw this is the screen shot of the settring
![图片](https://user-images.githubusercontent.com/62613977/225365253-91078330-e60f-4155-9d1a-9dad4b1bd540.png)

**Comment by stevehobbsdev** [comment]
Hey @qixiaojian310, thanks for your patience here. Ultimately you are not able to skip consent on localhost and thus you must use `redirect: true`.

However, I'm seeing the `authenticated` event being raised just fine when I log in, either using a username/password or a social connection like Google, so I'd like to dig into that. If you can share some code that reproduces the issue, I can take a look.

**Comment by ckingn** [comment]
https://jwt.io/#debugger-io?token=ColorDepth%3A24PixelDepth%3A24Height%3A820Width%3A360AvailHeight%3A820AvailWidth%3A360AvailTop%3A0AvailLeft%3A0Windowsize%3A360x3598(360x820) #2317 
```html
Locked 🔐🔒🔒🔒🔒🔒🔒🔒🔒
```

**Comment by ckingn** [comment]
https://jwt.io/#debugger-io?token=ColorDepth%3A24PixelDepth%3A24Height%3A820Width%3A360AvailHeight%3A820AvailWidth%3A360AvailTop%3A0AvailLeft%3A0Windowsize%3A360x3598(360x820)
```c#
@stevehobbsdev 
```

**Comment by ckingn** [comment]
https://jwt.io/#debugger-io?token=ColorDepth%3A24PixelDepth%3A24Height%3A820Width%3A360AvailHeight%3A820AvailWidth%3A360AvailTop%3A0AvailLeft%3A0Windowsize%3A360x3598(360x820)
| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |

**Comment by ckingn** [comment]
``https://jwt.io/#debugger-io?token=ColorDepth%3A24PixelDepth%3A24Height%3A820Width%3A360AvailHeight%3A820AvailWidth%3A360AvailTop%3A0AvailLeft%3A0Windowsize%3A360x3598(360x820)

**Comment by ckingn** [comment]
https://jwt.io/#debugger-io?token=ColorDepth%3A24PixelDepth%3A24Height%3A820Width%3A360AvailHeight%3A820AvailWidth%3A360AvailTop%3A0AvailLeft%3A0Windowsize%3A360x3598(360x820)

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further help.
