### ISSUE TITLE
Emoji characters should not be allowed in input fields

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#231]
We should ensure that only ASCII characters can be used for username, email and password fields.

**Comment by LegNeato** [comment]
Why shouldn't usernames have emoji?

**Comment by rolodato** [comment]
@LegNeato Because they aren't supported at the API level, and likely won't ever be supported.

**Comment by taion** [comment]
@rolodato Does that mean you don't support Unicode at all for user names? Otherwise how are emoji special?

**Comment by rolodato** [comment]
@taion Only alphanumeric characters and `_` are allowed for usernames at the API level, but in some cases this validation fails with Lock. See https://github.com/auth0/lock/issues/243 for example. Usernames should be used as machine-friendly identifiers, for anything else `app_metadata` or `user_metadata` should be used.

**Comment by taion** [comment]
Ah, okay - that makes sense, thanks!

**Comment by luisrudge** [comment]
This is being validated:
![screen shot 2017-01-31 at 17 32 17](https://cloud.githubusercontent.com/assets/941075/22481138/42b37da4-e7db-11e6-9fc6-73de59c12edb.png)
