### ISSUE TITLE
Support custom error messages from custom DB scripts

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#234]
For example, `/dbconnections/signup` returns an error like this when returning `new ValidationError('invalid_user', 'error message')` from a signup script:

```
{
  "message": "error message",
  "code": "invalid_user",
  "description": "error message",
  "fromSandbox": true
}
```

Currently Lock just shows "There was an error when processing the signup".

**Comment by jmb-oliveira** [comment]
I'm running on same issue from lock and from API calls (/dbconnections/signup) who returns HTTP ERROR 400 - BAD REQUEST

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!

**Comment by roku6185** [comment]
Could you please reopen this ticket?  I currently have a custom database script that throws ValidationError in some cases, e.g. callback(new ValidationError('user-not-active', 'You must accept the invitation from us before proceeding')). This scripts runs on "Get User", which is trigged when a user submits a new password via a password reset link. However, the error message is not propagated back to the client. We're using Auth0 Lock for web and the error message to the client is a generic one: "We're sorry, something went wrong when requesting the password change".

**Comment by luisrudge** [comment]
@roku6185 this is already supported:

```js
lock.show({
  languageDictionary: {
    error: {
      forgotPassword: {
        'user-not-active': 'your custom error message'
      }
    }
  }
});
```

![image](https://user-images.githubusercontent.com/941075/38102914-1eb7dbf8-335b-11e8-99f8-ca1d0bbe1d02.png)

**Comment by vincentdesmares** [comment]
Is it working for all custom-db scripts?

I followed your PR and use this code in my login script:

```
return callback(new ValidationError('custom-error-code', 'Some custom message'))
```

And updated my language dictionary:

```
languageDictionary: {
        error: {
          login: {
            'custom-error-code': 'your custom error message'
          }
        }
      },
```
(I'm not really sure the "login" key is the good one, I guessed it).

The response I receive is (while looking at the network):

```
{"error":"access_denied","error_description":"Some custom message"}
```

And the error I intercept with *lock.on('authorization_error'* is give me this result:

```
{
  code : "invalid_user_password",
  description: undefined,
  error: "invalid_user_password"
}
```

So at least the description is partially propagated, but it doesn't look like the error code is. What do I miss?

**Comment by luisrudge** [comment]
@vincentdesmares For login scenarios, I believe we only respond with error codes that are in the OIDC spec. Please reach out to our amazing support team at https://support.auth0.com so they can clarify this situation.

**Comment by vincentdesmares** [comment]
I understand that. I will find another way to handle my use case.

I still have some doubt on the error description, on the helper.js there is this code:
```
if (error.error === 'access_denied') {
    return {
      code: 'invalid_user_password',
      error: 'invalid_user_password',
      description: error.description
    };
  }```

*error.description* does not exists as the server always end *error_description* instead. I guess this should be:

```
error.description || error.error_description
```

Right?

**Comment by vincentdesmares** [comment]
I got it!

You fixed it on the Feb 2nd: https://github.com/auth0/auth0.js/commit/63c7486414d8119125a6ef6276c73d8305688e57#diff-d11e52f1fb3694d91e615158b2f418ec

Upgrading to the last version of auth0-lock solved it :)

**Comment by luisrudge** [comment]
awesome! 🎉
