### ISSUE TITLE
Unability to do anything after signup

### ISSUE THREAD

**Issue by rantiev** [auth0/lock#2393]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/lock#readme) and [Examples](https://github.com/auth0/lock/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/lock/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to create user profile in local DB after successful signup. How I can do this? 
Auth0 Actions dont seem to be useful as it requires to have additional config on 3d party and doesn't work with localhosts....

### Reproduction

1. use auth

### Lock version

v12.02

### Which browsers have you tested in?

Chrome

**Comment by stevehobbsdev** [comment]
👋🏻 If you just need this to happen on the client after the user has signed up, Lock has an `on` method that you can use to register a callback for a number of events, including `signup success`. Inside the callback you would just do what you need with LocalDB. See [the readme](https://github.com/auth0/lock/blob/master/EXAMPLES.md#onevent-callback) for more info on this callback.
