### ISSUE TITLE
"Reset Password" button invokes signin callback incorrectly

### ISSUE THREAD

**Issue by CPWeaver** [auth0/lock#240]
Hi, I'm using auth0-angular and lock together. When I call auth.signin(), the widget comes up. If a user clicks "Reset Password", it seems the success callback is transferred from the signin panel to the reset panel. The problem is that the semantics of the callback are totally different. So when the user submits the reset request, now the signin callback is invoked with reset parameters. This causes auth0-angular to read "We've just sent you an email to reset your password." as the user's profile and flip out.

Let me know if I can clarify anything here. Thanks!

**Comment by schwer** [comment]
I'm also seeing this problem. When integrating with auth0-angular- it means the profile promise is rejected prematurely.

**Comment by seawatts** [comment]
Also seeing this when integrating with ember.js

**Comment by hzalaz** [comment]
Please report this in auth0-angular if still happens since this repo is for vanilla js Lock
