### ISSUE TITLE
`usernameStyle: 'username'` disables validation of usernames

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#243]
Steps to reproduce:

1. Set up Lock for a database connection with "Require Username" enabled
2. Try to log in with an invalid username, e.g. `test.user` → fails
3. Set `username:Style: 'username'`
4. Try to log in with an invalid username, e.g. `test.user` → succeeds

**Comment by gnandretta** [comment]
With `usernameStyle: "username"` the Lock uses an `<input type="text">` for the username, then [lock._ignoreEmailValidations](https://github.com/auth0/lock/blob/0a5abf1957c9bb746b0710b274d0feed9b399958/index.js#L882-L884) returns `false` and the [code that performs the validation](https://github.com/auth0/lock/blob/0a5abf1957c9bb746b0710b274d0feed9b399958/lib/mode-signin/index.js#L351-L361) is not executed.

**Comment by hzalaz** [comment]
Fixed in Lock v10
