### ISSUE TITLE
Passwordless universal login on iOS Safari

### ISSUE THREAD

**Issue by laventnc** [auth0/lock#2444]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/lock#readme) and [Examples](https://github.com/auth0/lock/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/lock/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the passwordless universal login, iOS safari's auto-zoom on text field focus causes the submit button to not be visible without scrolling.

### Reproduction

Sometimes it takes more than one focus to trigger this auto-zoom oddly enough _(I'm guessing it has something to do with the attempt to autofill)_.

https://github.com/auth0/lock/assets/22279947/fc3c418b-9ab2-49ed-bea6-62918a95f967

### Additional context

Seems related to [this problem](https://github.com/auth0/lock/issues/1826). Although given the post, it looks like the culprit is [more likely safari](https://weblog.west-wind.com/posts/2023/Apr/17/Preventing-iOS-Safari-Textbox-Zooming).

I'm curious if there's a workaround in the meantime to just position the button close to the input _(instead of fixed to the bottom of the page)_, similar to the username & password login:
![login_2](https://github.com/auth0/lock/assets/22279947/69a0c5c3-174b-4e0f-a1d8-b030ade8faa6)

### Lock version

11.32

### Which browsers have you tested in?

Safari

**Comment by frederikprijck** [comment]
Thanks for reaching out and apologies for taking so long to get back to you, we must have missed this.

It looks like you can work around it in your own code base by applying the changes as per https://weblog.west-wind.com/posts/2023/Apr/17/Preventing-iOS-Safari-Textbox-Zooming.

Closing this for now, happy to reopen if more people experience the same problem and have a need for a more built-in solution.
