### ISSUE TITLE
12.5.0 script on CDN returns 403 error

### ISSUE THREAD

**Issue by KenCorbettTruepic** [auth0/lock#2552]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/lock#readme) and [Examples](https://github.com/auth0/lock/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/lock/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I try to load the https://cdn.auth0.com/js/lock/12.5.0/lock.min.js script like it shows in the Readme.  I get a 403 Access Denied error: 

<img width="817" alt="Screenshot 2024-05-06 at 4 43 09 PM" src="https://github.com/auth0/lock/assets/94476406/ecefbf7c-7627-4247-9003-2570172c85a9">

### Reproduction

1. Paste https://cdn.auth0.com/js/lock/12.5.0/lock.min.js into your browser
2. Observer Error

### Lock version

12.5.0

### Which browsers have you tested in?

Chrome

**Comment by IuraCPersonal** [comment]
Hey @KenCorbettTruepic , I ran into a similar problem but with an older version (12.3.1). However, when my React application starts - the request is still made to `https://cdn.auth0.com/js/lock/12.5.0/en.js`. I noticed the lock file from 12.3.1 version is still accessible. Any idea if I can choose where to make the request? I would really appreciate your or anyone's help.

**Comment by ewanharris** [comment]
Hey @KenCorbettTruepic, apologies for the inconvenience here. We're working to get that resolved, in the meantime I'd suggest using the 12.4.0 URL (https://cdn.auth0.com/js/lock/12.4.0/lock.min.js) until we fix this

**Comment by frederikprijck** [comment]
https://cdn.auth0.com/js/lock/12.5.0/lock.min.js works now!
