### ISSUE TITLE
Remove from repo generated css files

### ISSUE THREAD

**Issue by pose** [auth0/lock#27]
(translated from chat conversation, please correct if wrong)

---

We must make sure that npm/browserify still works:
> There is a transform https://github.com/auth0/lock/blob/master/package.json#L65 . The css should be present in the generated tgz when doing `npm publish`. A way to deal with that would be having .gitignore y .npmignore, ignoring it on git pero but not in npm.

**Comment by hzalaz** [comment]
No longer needed
