### ISSUE TITLE
"Invalid" string makes it hard to correct invalid email

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/lock#273]
In Lock, If the user types an invalid email address and presses the "Access" button, the "INVALID" message appears over the email and makes it hard to correct the invalid email.
As an example, I used an email like firstlastname@xyz1234  - e.g. no dot in the email domain name and the entire email address is long enough to fill most of the box.
Then I pressed the ACCESS button.  The "INVALID" covers up the part of the email address that needs to be fixed.  No obvious way to move the "INVALID" or make it go away so you can fix the problem.

I duplicated this issue invoking Lock from an SPA in Chrome browser Version 47.0.2526.73 (64-bit)
on Mac.
Customer encountered issue using chrome and Lock 7.12.4

This issue was originally filed by a customer - reference: 4040.

**Comment by cristiandouce** [comment]
@gnandretta I figure we could hide the word when the user hovers the input area... that would also allow them to click the input (cursor) and type.

**Comment by yvonnewilson** [comment]
Was just going through open issues - any update on this that I could share with customer?

**Comment by gnandretta** [comment]
@yvonnewilson a new look was introduced in version 8.0.0 and we no longer show the "invalid" message. Would it be possible for the customer to upgrade to the latest version?

<img width="373" alt="screen shot 2016-02-19 at 9 25 49 pm" src="https://cloud.githubusercontent.com/assets/120195/13192925/d7d04554-d74f-11e5-96ce-a71bb52a31fd.png">

**Comment by yvonnewilson** [comment]
Thx, I will just tell them that is the way to get the fix to give them incentive! ;-)

**Comment by cristiandouce** [comment]
:dancers:
