### ISSUE TITLE
`auth0Client` in authorization request parameter

### ISSUE THREAD

**Issue by caalberts** [auth0/lock#274]
I'm attempting to request authorization to Dropbox API endpoint `https://www.dropbox.com/1/oauth2/authorize`. Dropbox is returning error 400 with reason `unknown field "auth0Client"`. The query string to the authorization URL sent by Auth0  is `https://www.dropbox.com/1/oauth2/authorize?state=###&auth0Client=###&response_type=code&redirect_uri=###&client_id=###` (details masked).

How can I exclude auth0Client from the query string?

**Comment by gnandretta** [comment]
@caalberts thanks for reporting the issue. What version of Lock are you using? Can you provide the code that initializes and shows the Lock?

**Comment by caalberts** [comment]
@gnandretta, it's lock v8.
```
<script src="http://cdn.auth0.com/js/lock-8.min.js"></script>
```

```
const lock = new Auth0Lock(auth0ClientId, auth0Domain)

document.getElementById('btn-login').addEventListener('click', () => {
  lock.showSignin({ connections: ['facebook'] }, authCallback)

  // add custom connection
  lock.once('signin ready', function () {
    const link = document.createElement('a')
    link.className = 'a0-zocial a0-dropbox'
    link.setAttribute('href', '#')

    const text = document.createElement('span')
    text.textContent = 'Login with Dropbox'
    link.appendChild(text)

    link.addEventListener('click', (e) => {
      e.preventDefault()
      lock.getClient().login({
        connection: connectionName,
        popup: true
      }, authCallback)
    })
    document.querySelector('.a0-iconlist').appendChild(link)
  })
})
```

**Comment by siacomuzzi** [comment]
Hi @caalberts,

It should be fixed now. Please try again.

**Comment by gnandretta** [comment]
@siacomuzzi Thanks!

@caalberts I'm closing this, but feel free to reopen it if the issue persists.
