### ISSUE TITLE
Primary button uses inline style that cannot be overridden with theme css

### ISSUE THREAD

**Issue by smerchek** [auth0/lock#294]
In v8 of Lock, specifically at this [line](https://github.com/auth0/lock/blob/9fd0897bce40671a4705972c3ff8375979f84b6c/lib/mode-signin/signin.ejs#L77), the `a0-primary` button uses an inline style that cannot be overridden.

Related to #277 but that issue seems to be about more than just this specific inline style.

However, it seems that this change was intentional, but not documented.

To workaround this, you may set the `primaryColor` config option.

```
lock.show({
   primaryColor: '#EEE'
});
```

So maybe this isn't actually an _issue_?

**Comment by gnandretta** [comment]
@smerchek You're right, the `primaryColor` option was added on v8 to allow to quickly customize the lock appearance without using CSS, and the documentation wasn't updated. I'll fix that, thanks for reporting it.

**Comment by maxlapides** [comment]
@gnandretta in addition to updating the documentation, could you please add a way to disable this primary color? i've built a custom theme for my login page and this primaryColor option overrides by external CSS so I've had to resort to a shameful !important. thanks!

**Comment by gnandretta** [comment]
@maxlapides hi! the `primaryColor` is just the first of a couple of options that we will be adding to allow a more robust customization and should be favored over CSS. For instance, it is also used for the header's background in some situations.

I wouldn't recommend it but if you use a invalid color such as `"disabled"`as the `primaryColor` value, the browser will ignore the inline style declaration and use the next one.

**Comment by maxlapides** [comment]
@gnandretta are you planning on continuing to support the existing theming capabilities (https://auth0.com/docs/libraries/lock/ui-customization)? i really prefer to not set styles in javascript. maybe i'm old-school, but the classic method of writing themes using CSS is definitely my preferred method. this update and the others that you have described are incompatible with the theme i've already written. i would really like to see an option to properly disable this functionality. i understand that most users only want to make small tweaks and don't necessarily want to get into the CSS, but i don't think it makes sense to break existing functionality for existing advanced users.

**Comment by gnandretta** [comment]
@maxlapides thanks for your feedback! With the current customization mechanism an HTML or CSS change is all it takes to break a customization. The `primaryColor` option was a design decision made exclusively to improve that situation. It allows us to take care of the changes needed to make it work on newer versions of Lock. And, if for some reason we need to change it for another option, we will be able to provide a clear migration path.

We want to make the process of upgrading to a new Lock version as easy as possible. The use of customization options helps reducing the amount of CSS that you need to write, and thus test/debug before an upgrade.

**Comment by hzalaz** [comment]
Closing this since we already have CSS customisation in our backlog
