### ISSUE TITLE
Login page not updated

### ISSUE THREAD

**Issue by damirmehmedbasic** [auth0/lock#298]
Login page in my application does not reflect customization I made, I get the default version (without the sign up button), and this one works without problems (I can log in with users credentials, and reset password). My customized login page url is OK, showing the customized version, however it is not being implemented in the application itself.

**Comment by rolodato** [comment]
@damirmehmedbasic I believe you're confusing the Lock displayed on the login page hosted by Auth0 (e.g. `example.auth0.com/...`) and the Lock displayed in your application. They are not related or synchronized in any way.

If you want to redirect users to the hosted login page you'll need to redirect them to the `/authorize` endpoint: https://auth0.com/docs/auth-api#!#get--authorize_social. If a `connection` parameter is not specified, the login page will be displayed.
