### ISSUE TITLE
8.2.0 webpack not working due to unresolve 'fs' module

### ISSUE THREAD

**Issue by maoueh** [auth0/lock#301]
The version `8.2.0` does not work with webpack anymore. The example will fail with error message:

```
ERROR in .\~\auth0-lock\lib\insert-css\index.js
Module not found: Error: Cannot resolve module 'fs' in \work\auth0\lock\examples\webpack\node_modules\auth0-lock\lib\insert-css
 @ .\~\auth0-lock\lib\insert-css\index.js 5:9-22
```

To replicate, simply edit `examples/webpack/package.json` and change `"auth0-lock": "^7.5.5",` to `"auth0-lock": "^8.0.0",` and then issue the command to test the example (`npm install && npm start`). You will get the error mentionned above.

If you fix the version to `8.1.5` (via `examples/webpack/package.json` line `"auth0-lock": "8.1.5",`) error is not present.

The module in question (`lib\insert-css\index.js`) has a `require('fs')` line since a while, way before `8.1.5` which is working. This would mean that before, this module was not directly referenced while it is now in `8.2.0`. 

I will need further investigation to find the actual culprit but I need to step out for now.

Regards,
Matt

**Comment by gnandretta** [comment]
@maoueh sorry for the inconvenience, could you try with version `8.2.1`? it should be fixed

**Comment by maoueh** [comment]
@gnandretta Yep, just tested `8.2.1`, works like a charm.
