### ISSUE TITLE
Container should accept a DOM Node

### ISSUE THREAD

**Issue by ericclemmons** [auth0/lock#303]
> https://github.com/auth0/lock/blob/b4e2446b6899d25238d6066e613fca103ba5bf65/index.js#L350-L352

The code in question:

``` js
  // widget container
  if (cid) {
    this.$container = document.getElementById(cid);
```

Using React, it's best to pass a reference:

``` js
this.lock.show({ container: this.refs.lock });
```

The logic could be something like this to check for an element:

``` js
this.$container = (typeof cid == 'object' && cid.nodeType === 1) ? cid : document.getElementById(cid);
```

**Comment by ericclemmons** [comment]
Let me know if a PR would be acceptable.

**Comment by matthiasak** [comment]
+1 for this.

Hi @ericclemmons

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉

**Comment by obonyojimmy** [comment]
@luisrudge i think this PR raises an important issue with react users and should definately be accepted

**Comment by luisrudge** [comment]
@obonyojimmy there's no PR though 😬 I'll review and merge if someone sends a PR
