### ISSUE TITLE
A0WebKitViewController not calling failure block on timeout

### ISSUE THREAD

**Issue by mpretty-homepass** [auth0/lock#307]
When a connection has a timeout the A0WebKitViewController clears out the reference to it's failure block before it actually gets called:

<img width="817" alt="screen shot 2016-02-03 at 4 56 14 pm" src="https://cloud.githubusercontent.com/assets/15862619/12774280/652c58a4-ca97-11e5-9463-bad692bb07ee.png">

The issue is because 'dismissViewControllerAnimated:' won't call it's completion block until after the animation has completed, but the callbacks get set to nil immediately after. If you update the following method from:

```
- (void)dismissWithCompletion:(void(^)())completion {
    [self.presentingViewController dismissViewControllerAnimated:YES completion:completion];
    [self cleanCallbacks];
}
```

To this:

```
- (void)dismissWithCompletion:(void(^)())completion {
    [self.presentingViewController dismissViewControllerAnimated:YES completion:^{
        if (completion) {
            completion();
        }
        
        [self cleanCallbacks];
    }];
}
```

It will correctly call the failure block on timeouts.

**Comment by hzalaz** [comment]
@mpretty-homepass I think you posted in the wrong repo since this is the web implementation of Lock. I've added the same issue in the correct repo auth0/Lock.iOS-OSX#222 so I'm closing this one
