### ISSUE TITLE
Why pin node version

### ISSUE THREAD

**Issue by cancan101** [auth0/lock#308]
see: https://github.com/auth0/lock/blob/b0a587953370d746a9a446bf6730c824d3958d65/package.json#L83

this yields warnings.

**Comment by cristiandouce** [comment]
@cancan101 What warnings? Could you be more specific with context?

**Comment by itajaja** [comment]
when I do `npm install`:

```
WARN engine auth0-lock@8.1.5: wanted: {"node":"4.2.3"} (current: {"node":"5.3.0","npm":"2.14.15"})
```

pinning to a specific node version is not a convention in other npm packages as far as I know.

Maybe you want something less constraining, like https://github.com/webpack/webpack/blob/master/package.json#L63-L65 or is there a specific reason you are targeting 4.2.3 only (it must be a good one :D)?

**Comment by cristiandouce** [comment]
It was originally moved by the LTS from NodeJS. But you are right, we shouldn't be pinning that strict.

Although... changing it to `4.x` will still be throwing you that warning since you are using `node@5`...

**Comment by itajaja** [comment]
so why just not do `"node": ">=4"` ?

**Comment by cristiandouce** [comment]
https://github.com/auth0/lock/commit/b5b8d67f56a94ee8500cd103dacd950fbf267354
Fixed :point_up:

**Comment by itajaja** [comment]
thanks!

**Comment by cristiandouce** [comment]
:dancers: np!
