### ISSUE TITLE
Sign-in incorrectly switches to redirect mode after concatenating and uglifying "auth0-lock.js" (mangle: false) - resulting in broken sign-in process

### ISSUE THREAD

**Issue by motin** [auth0/lock#313]
Before concatenating and using uglify (mangle: false), sign-in with username+password works fine, no redirects, proper handling of sign-in events and token/profile are set properly in local storage. 

After concatenating and using uglify (mangle: false), auth0 incorrectly uses redirect mode after entering username+password resulting in a broken login flow, where the user is redirected to a blank page in the style of `http://localhost:9000/#access_token=...&id_token=...&token_type=Bearer`.

It is possible to reload the page at this stage and use the "Last logged in as" choice to actually get logged in. 

Using all the latest versions of auth0 deps as of now:
```
    "auth0.js": "~6.8.0",
    "auth0-angular": "~4.1.0",
    "auth0-lock": "~8.2.3",
    "a0-angular-storage": "~0.0.13",
    "angular-jwt": "~0.0.9",
    "angular-cookies": "~1.5.0",
    "angular-route": "~1.5.0",
```

Even though this is an angular app, trial and error showing that only "auth0-lock.js" needs to be excluded from the build for the sign-in process to work properly again. 

Could be related to https://github.com/auth0/lock/issues/94 but it is closed and it does not seem to be related to redirect-mode being incorrectly triggered.

**Comment by gnandretta** [comment]
Hi, if the concatenation in your build process keeps the order of dependencies try specifying them as follows:
```
"angular-cookies": "~1.5.0",
"auth0-lock": "~8.2.3",
"auth0.js": "~6.8.0",
"auth0-angular": "~4.1.0",
"a0-angular-storage": "~0.0.13",
"angular-jwt": "~0.0.9",
"angular-route": "~1.5.0",
```

If the previous doesn't work could you please provide us with a minimal sample project where the error is happening to make it easier to debug?

**Comment by hzalaz** [comment]
@motin is this still an issue?
