### ISSUE TITLE
Mocha testing with Auth0Lock

### ISSUE THREAD

**Issue by caalberts** [auth0/lock#314]
I'm testing an ES6 React application with Auth0Lock bundled through webpack based on this [example](https://github.com/auth0/lock/tree/master/examples/webpack#running-the-example).

Running mocha with `babel-register` gives me `Syntax Error: Unexpected Token <`
```
$ mocha test/components/app.spec.js --compilers js:babel-register

/app/node_modules/auth0-lock/lib/html/main.ejs:1
(function (exports, require, module, __filename, __dirname) { <div id="a0-lock" class="a0-lock<%= (locals && locals.options.theme) ? ' a0-theme-' + locals.options.theme : ''%>" dir="auto">
                                                              ^

SyntaxError: Unexpected token <
```

I added ejsify compiler and now I get `Error: Cannot find module 'package.version'`
```
mocha test/components/app.spec.js --compilers js:babel-register,ejs:ejsify
module.js:341
    throw err;
    ^

Error: Cannot find module 'package.version'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/app/node_modules/auth0-lock/index.js:114:21)

```

Any help will be much appreciated.

**Comment by gnandretta** [comment]
Hi, it looks like you are missing the [packageify transform](https://github.com/auth0/lock/blob/59dd50523d780430ce430e753d91443b101ecea6/examples/webpack/webpack.config.js#L16).

**Comment by caalberts** [comment]
How can I include packageify transform when running mocha? I'm using ES6 Babel transpiler too, so the current mocha script is `mocha --compilers js:babel-register,ejs:ejsify`.

**Comment by gnandretta** [comment]
I don't know if you can. It looks like you'll need to create the bundle with webpack before running the tests, see webpack [docs](https://webpack.github.io/docs/testing.html#compile-and-test).

**Comment by RobbertWolfs** [comment]
I have the same problem.. Any solutions yet?

**Comment by RobbertWolfs** [comment]
I tried bundling my files with webpack but It still failed on the package.version like above..
