### ISSUE TITLE
Feature request: ability to specify flash message when opening lock

### ISSUE THREAD

**Issue by viz** [auth0/lock#320]
I'd like to be able to specify a flash message through the options when opening lock.

Use Case:
When being redirected to the signup page on our application, we include an email address as a query parameter which we verify against our API before opening lock for signup. If the email address is taken, we display a flash message and then redirect to our login page which then displays lock in signin mode.

I'd like to be able to dispense with the intermediate flash message and simply display the signin view with the flash message displayed in lock itself.

**Comment by acacia314** [comment]
Use Case:

We have some features that are only available to logged in users. When someone who is not logged in tries to use such features, the login window shows. It would be nice to display a message like "Sign up to access premium features"

**Comment by glena** [comment]
It is ready on the latest release https://github.com/auth0/lock#showoptions
