### ISSUE TITLE
https-certs breaks build process for android

### ISSUE THREAD

**Issue by seiyria** [auth0/lock#322]
Today my gradle process for ionic builds updated and now I get this error on fresh builds:

```
:lintVitalRelease/Users/seiyria/GitHub/ionic/retro/platforms/android/assets/www/lib/auth0-lock/test/support/https-certs/server.key: Error: The https-certs/server.key file seems to be a private key file. Please make sure not to embed this in your APK file. [PackagedPrivateKey]
```

Can this be ignored by bower so it doesn't automatically install? [Ignoring files and folders is pretty simple](http://stackoverflow.com/questions/18245394/ignore-in-bowers-bower-json). This problem is also present on auth0.js, too.

**Comment by seiyria** [comment]
@gnandretta did you want me to open an issue on auth0/auth0.js too?

**Comment by gnandretta** [comment]
@seiyria there's no need for that, thanks!

**Comment by seiyria** [comment]
thank you for getting this taken care of so quickly!
