### ISSUE TITLE
signin:userClosedPopup and signin:userConsentFailed never displayed

### ISSUE THREAD

**Issue by dev101** [auth0/lock#325]
Condition to display [signin:userConsentFailed](https://github.com/auth0/lock/blob/master/index.js#L1309) and [signin:userClosedPopup](https://github.com/auth0/lock/blob/master/index.js#L1306) should be changed to inspect `err.details.error_description` instead of `err.message`, e.g.

from
`if (err.message === 'access_denied') {`
to
`if ('unauthorized' === err.code && err.details && err.details.error_description === 'access_denied') {`
, otherwise the i18n message is **never displayed**, as in `err.message` you always have _"unauthorized"_.
![image](https://cloud.githubusercontent.com/assets/459389/13427240/c0629cd8-dfc3-11e5-8d86-bd8c2c27a046.png)

Maybe other messages are affected as well.

**Comment by cristiandouce** [comment]
Please use *auth0-lock@10*.
