### ISSUE TITLE
Customizations to Lock don't show in change password screen

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/lock#332]
https://auth0.zendesk.com/agent/tickets/6150

Customer made style changes (color etc) to Login screen in Auth0 dashboard (Login page tab) and these changes show up in Lock for login mode but not for change password mode.
Customer needs the customizations to show up in change password mode also.

Changing something like dict: 'es' works for both, but style changes do not, so behavior is inconsistent.

**Comment by gnandretta** [comment]
@yvonnewilson I've tried setting the `primaryColor` option to change the color of the submit button and the header and it works on every screen. Is the customer using that option? how is changing the styles? is using CSS?

**Comment by arcseldon** [comment]
@gnandretta - primaryColor does not work for me :(

Here is code snippet:

```js
auth.signin({
     .....
      primaryColor: '#5323ea',   // dark blue
     ....
```

Then login / reset password looks like this:

![login1](https://cloud.githubusercontent.com/assets/2599332/13660898/79bec3a0-e6d1-11e5-8ce2-1ab2e052a127.jpg)

and the password reset screen (after clicking link in email to change password) looks like this:

![changepassword1](https://cloud.githubusercontent.com/assets/2599332/13660908/8e7584be-e6d1-11e5-9ece-fcd1fff4ef3d.jpg)

The icon is missing, the colours are incorrect including the button and header.

Please can you investigate? Feel free to ask if you have further questions etc.  Thanks for any assistance.

**Comment by gnandretta** [comment]
@arcseldon customization don't show up in the widget on the second screenshot becasue is not lock

**Comment by arcseldon** [comment]
@gnandretta - appreciate your reply, and I realise this.. but am getting a lot of tickets where users are basically saying this destroys the user experience to the extent that they cannot support our change password flow due to the inconsistencies in styling etc.  There is a valid point to be made that this is at odds with the rest of the Lock experience.... from an end-user perspective.

**Comment by gnandretta** [comment]
@arcseldon yes you're right, I've already let the design team know about this

**Comment by samjamead** [comment]
In case it helps anyone else struggling to customise the Auth0 password reset page, you can edit the page here: https://manage.auth0.com/#/login_page

**Comment by hzalaz** [comment]
Change password widget is now customizable via dashboard

**Comment by broyeztony** [comment]
I would rather say it is relatively customizable.
I don't see clearly if and how it is possible to customize the component that gets loaded in 
        
        <div id="change-password-widget-container">
        </div>
        

I'm looking for a deeper styling than just setting the icon, primary color.

Can we customize further ? how ?
Is it possible to create our own password_change.html based on the template and host it ?
Thank you for shading some lights on the topic

**Comment by hzalaz** [comment]
@broyeztony please contact our support team in https://support.auth0.com

**Comment by tim-soft** [comment]
Why can't Lock contain the change password flow? Like others have said, the hosted widget breaks the experience.

**Comment by luisrudge** [comment]
@tim-soft that's something that we want to achieve eventually, but we're not there yet.

**Comment by mclark-nfocus** [comment]
As an additional note, it would be great to have the same settings for the button at the bottom to show a label like on the Login page:

`loginSubmitLabel: 'Sign In',`

If we could do that for the Password reset it keeps the same look and feel.

**Comment by theythinkimmexican** [comment]
any update on this? i need to be able to change the text on the button rather than using an image...

**Comment by juliano-g-lopes** [comment]
Hi, I'm facing the same issue.

For I'd read until now, there are some options that the auth0 dev team could do, but none are applied.

There's a ETA or something like that for this kind of customization?

**Comment by luisrudge** [comment]
Sorry, no ETAs on this.
