### ISSUE TITLE
Error: 0:

### ISSUE THREAD

**Issue by benjick** [auth0/lock#333]
Getting this not so helpful error "sometimes".

```js
lock.getProfile(token, (err, profile) => {
  if (err) {
    console.log('getProfile failed', err); // Error: 0:
    reject(err);
    return;
  }
  resolve(profile);
});
```

How can I debug this?

**Comment by hzalaz** [comment]
Please ask for support in https://support.auth0.com, we leave Github for issues with the library

**Comment by benjick** [comment]
It's still a bad error without explanation, in the library
