### ISSUE TITLE
Inconsistency between browsers & hovering over forgotten password text

### ISSUE THREAD

**Issue by arcseldon** [auth0/lock#334]
The links on the default login page for forgotten password or "not my account" do not look to uses like they are clickable in Firefox. the cursor does not even change when hovering over the text. This is different than in Chrome, is it known and will it be addressed?

I am using Firefox 44.0.2 and this is a sample of the screen I am talking about with my cursor over the clickable text.

When I use Chrome version 48.0.2564.109 I get this experience.

**Comment by arcseldon** [comment]
Images show below:

![image001](https://cloud.githubusercontent.com/assets/2599332/13728272/60222c1c-e955-11e5-82f7-c895edfceeb5.png)


![image002](https://cloud.githubusercontent.com/assets/2599332/13728274/66bfb6fc-e955-11e5-9dfa-0fcf6ee1ccc5.png)

**Comment by rickyrauch** [comment]
@arcseldon thanks for reporting this, we are working to fix it.

**Comment by hzalaz** [comment]
Already fixed in latest version of Lock
