### ISSUE TITLE
Submitting login form via return in mobile safari causes infinite spinner

### ISSUE THREAD

**Issue by michaek** [auth0/lock#339]
This is happening at least in Lock 9.0.0 and 9.0.1, and can be reproduced in the [Playground](http://auth0.github.com/playground). I was not able to reproduce this issue with the iOS simulator, but I am reliably on a real device.

**Comment by raoabishay** [comment]
+1

**Comment by mattnull** [comment]
+1

**Comment by donjerick** [comment]
+1

**Comment by lobo** [comment]
+1 from a customer as well.

**Comment by michaek** [comment]
@gnandretta Are you aware that this issue means that Lock is broken in iOS*?

* Unless a user is aware of this issue, and takes the extraordinary step of closing the keyboard and tapping the submit button. I expect almost every user will attempt to submit via the keyboard, thus encountering this issue.

**Comment by hzalaz** [comment]
@michaek Can you provide more details on how you are configuring lock so we can try to reproduce this? (a link besides the playground will be helpful)

**Comment by michaek** [comment]
Hi, @hzalaz. I'm not sure why a link besides the playground would be helpful - what I mean is that there's a bug that is reproducible on the playground, and it seems that any other configuration would just introduce spurious variables.

Steps:

1. Visit the playground in Safari on an iOS device.
2. Enter credentials.
3. Submit via the keyboard (pressing return, for example).

Result:

Infinite Auth0 progress icon, no authentication.

**Comment by hzalaz** [comment]
@michaek because I didn't know if the default options of the playground were enough to reproduce it, since you only said that it could be reproduced there, and I didn't want to introduce spurious variables myself.

Not onto the issue at hand, seems if the popup and sso is disabled it works as expected and also tried with lock 10 to see if we still have the issue but we don't. So a temporary workaround is either disable popup/sso while we fix it or use the new lock (https://auth0.com/docs/libraries/lock/v10).

Thanks for adding more info

**Comment by michaek** [comment]
Thanks, @hzalaz, I'll try either or both of those approaches.

**Comment by michaek** [comment]
I had a hard time upgrading to Lock 10, as the documentation is still mostly focused on 9 and the migration guide is incomplete. Once I sorted out the new options API, I never got `parseHash()` to return anything other than null (despite having a correctly formed hash redirected from Auth0), so I returned to Lock 9 to try its redirect mode.

How to switch to redirect mode isn't completely clear in the documentation, as there seem to be circular links that don't add up to a complete approach. This is the configuration that ended up working for me:

```
lock.show({
    callbackURL: window.location.protocol + "//" + window.location.host + "/",
    responseType: "token",
    authParams: {
        state: destination,
        scope: "openid",
    },
})
```

The callbacks were a nice feature of popup mode, and refactoring to support redirect / `lock.parseHash()` has made my application a little harder to reason around (so far), but it's an improvement over failing on mobile Safari.

I'm going to mark this as closed.

**Comment by hzalaz** [comment]
@michaek 

>  I never got parseHash() to return anything other than null (despite having a correctly formed hash redirected from Auth0)

Happened with lock 10 or Lock 9?

**Comment by michaek** [comment]
@hzalaz That happened with Lock 10. Lock 9 returned a properly structured object (based on the same hash).

**Comment by hzalaz** [comment]
I think there is no `parseHash` in Lock 10 anymore. The auth result will be available in `authenticated` callback

```
lock.on("authenticated", function(authResult) {
  localStorage.setItem('idToken', authResult.idToken);
});
```

**Comment by woloski** [comment]
https://auth0.com/docs/libraries/lock/v10/installation

**Comment by michaek** [comment]
@woloski I did read that page, but there's a lot of information there. I see what you're calling out now that @hzalaz posted an example here, but I didn't see it before. That explains my confusion!

**Comment by michaek** [comment]
Might I suggest changing "You no longer need to call parseHash" to "You should no longer call parseHash". If the function doesn't work, it seems like it should fail more dramatically?

**Comment by michaek** [comment]
Ah. As it turns out, I read the docs before https://github.com/auth0/docs/commit/6951ede3ed451d1ca6c5d730cb3180c5be697316#diff-596b752a6189b71d69784fdd714cb71e, so most of the info that would have been most useful to me just wasn't there yet.

**Comment by michaek** [comment]
@hzalaz I've been thinking about this, and it seems like it could be a problem to replace the synchronous `parseHash` with the async `on("authenticated")`. In the synchronous version, you know immediately when the hash is present and valid, but in the asynchronous version you need to wait for the event - so you can't know immediately that the hash is **not** present or **not** valid. I understand this may be a design choice that's intended to make the redirect and popup APIs as similar as possible, but the two approaches are not similar in terms of application lifecycle, and if I must use the asynchronous approach it would make me seriously consider not upgrading to Lock 10.

I realize this is not strictly related to the original issue, so if this is worthy of discussion I'll open a new issue.

**Comment by woloski** [comment]
what's exactly the problem with the new interface? is there something you can't achieve with this API that you were able to achieve before? what would be that use case?

**Comment by michaek** [comment]
@woloski I'm using the redirect to start the application in a state that's informed by the user data and authParams.state contained in the Auth0 hash. In Lock 9 that's pretty straightforward as parseHash is synchronous, and the branching is just an if statement. In Lock 10, one branch (starting in the session-informed state) is in the on("authenticated") callback, but it's not clear to me how to manage the other branch (starting in the application default state).

It makes me a little uncomfortable to delay starting the application based on something asynchronous inside of lock, but it also doesn't seem ideal to start the application in its default state only to change that state (and re-render) moments later based on the on("authenticated") event.
