### ISSUE TITLE
using 'last time sign-in' after period of time in pop-up mode, switches to re-direct

### ISSUE THREAD

**Issue by doapp-ryanp** [auth0/lock#341]
Steps to reproduce:
1. Put lock widget into pop-up mode, use Auth0 database connection. 
2. login
3. Logout from web app (but not Auth0)
4. Go back to login page, modal shows "Last time you signed in using..."
5. Do no login, leave page with modal open for a while (I left it over night, but my guess is the bug happens if you are in modal when token expires)
6. After token expires, click on the "Last time you signed in using..." connection
7. Pop-up window opens, but displays input boxes to put in email/pw.  Put in creds and hit login
8. Error page shows inside the pop-up window

You can get around this issue by refreshing the page after token expires (before step 6 above), then clicking on the "Last time you signed in using..." connection.

My guess is this bug exists with social connections but I have not tested it out

FWIW I get around this issue by putting the following JS on my login pages:

``` js
setInterval(function(){
  document.location.reload(true);
},900000); //15 min
```

**Comment by hzalaz** [comment]
Will close it since it's not something we won't be fixing right now. It's not a common case and it's properly denying the login since the session expired
