### ISSUE TITLE
password requirements tooltip covers the password field instead of appearing above it on IE9

### ISSUE THREAD

**Issue by eugeniop** [auth0/lock#348]
I've gotten a report from one of our users that when attempting to reset their password, the password requirements tooltip covers the password field instead of appearing above it. I've confirmed that this only appears to happen on IE9.

We are currently using v7 of Lock. I attempted to check if this issue persists on a newer version of Lock, but the playground page does not work for IE9 (or when emulating IE9 on a newer version of IE)

**Comment by hzalaz** [comment]
Seems to be fixed in later releases of Lock
