### ISSUE TITLE
Popup freezes when Yandex permissions are not granted

### ISSUE THREAD

**Issue by gnandretta** [auth0/lock#355]
##### Steps
1. Enable a Yandex connection.
2. Show Lock in popup mode.
3. Attempt to login with Yandex, enter user and pass but in the next screen forbid permissions.

**Comment by luisrudge** [comment]
@gnandretta are you still having this issue? Can you share your lock options?

**Comment by luisrudge** [comment]
Ops.. Sorry to bother @gnandretta - I didn't recognize you at first 😊

**Comment by gnandretta** [comment]
@luisrudge haha this was reported by @rolodato

**Comment by luisrudge** [comment]
@gnandretta what a memory! 😲

**Comment by hzalaz** [comment]
Reported to backend since there is an issue there while parsing the error response in russian
