### ISSUE TITLE
Uncaught TypeError: Cannot read property 'connections' of undefined

### ISSUE THREAD

**Issue by am17torres** [auth0/lock#356]
I have a lock widget that only has an ADFS connection enabled as a parameter to locks `show` method:

```javascript
lock.show({
    container: 'root'
  , callbackURL: get_callback_url
  , responseType: 'code'
  , connections: ['MyADFSConnection']
  , authParams: {
    scope: 'openid profile app_metadata connection'
  }
});
```

When a user types in `email@gmail.com` I get the following error:
Uncaught TypeError: Cannot read property 'connections' of undefined index.js:1225 which I traced back [this line](https://github.com/auth0/lock/blob/5e8f910e3b12375bb9ddd5aa723fbd0d03c7eb30/lib/options-manager/index.js#L520).

In my case, `this.$client.strategies` is:

```javascript
[{
    connections: Array[1]
    css: "windows"
    name: "adfs"
    social: false
    title: "ADFS"
    __proto__: Object
}]
```
When a user types `email@gmail.com` the strategy provided to `Auth0Lock.prototype._signinSocial` is 'google-oauth2'. `_getClientStrategyByName` does not have a client defined for 'google-oauth2' which causes a javascript error. So rather than falling the login, the form errors silently without attempting to submit leading to a confusing UX.

Additionally, I'm using the latest lock.js 9.0.3

**Comment by hzalaz** [comment]
Already fixed in latest version of Lock. It won't prompt for email when a single enterprise connection is available
