### ISSUE TITLE
Call callback with error if user closes auth dialog

### ISSUE THREAD

**Issue by colllin** [auth0/lock#357]
What do you think about this feature?

Is there some other way to detect that the user abandoned the lock dialog?

The idea is that when I call `lock.show(...)`, I want the callback to be called when the lock flow ends, regardless of the outcome.  Right now, there's no way to know that the user abandoned the login, so if I wanted to redirect somewhere if the user abandons the flow, there's no way to capture that event.

**Comment by hzalaz** [comment]
@colllin there is a `hide` event that might be useful https://github.com/auth0/lock#onevent-callback

**Comment by hzalaz** [comment]
Closing this one please reopen if https://github.com/auth0/lock/issues/357#issuecomment-247702930 is not enough
