### ISSUE TITLE
uncaught error: cannot find module 'undefined' --> using gulp, react and flux

### ISSUE THREAD

**Issue by Harendra108** [auth0/lock#360]
I didn't get any compilation error
But when I am running gulp, the browser opens and nothing comes up except for the above error in the bundle.js file
Did anyone face the similar issue ever using gulp, react and flux?
If yes, please let me know how to resolve it

**Comment by hzalaz** [comment]
Please, if this is still an issue, ask for support in https://support.auth0.com
