### ISSUE TITLE
Privacy badger blocks lock.js

### ISSUE THREAD

**Issue by Brightergy-SamarAcharya** [auth0/lock#362]
I just discovered that auth0 integration is not working on firefox when I've [Privacy Badger](https://www.eff.org/privacybadger) installed. On firebug, I can see that the http://cdn.auth0.com/js/lock-9.0.min.js is not loaded when privacy badger is enabled. I've not gone into more details on why privacy badger is preventing loading of this javascript but its weird to me. Any idea?

**Comment by jpsilvashy** [comment]
We've also run into the same issue.

**Comment by luisrudge** [comment]
@Brightergy-SamarAcharya @jpsilvashy Are you still having this issue? I just added the privacy badger to my browser and it works with this website: https://auth0-repro-809.now.sh/

If you're still having this issue, please reach out so we can reopen this issue

**Comment by luisrudge** [comment]
![screen shot 2017-01-31 at 17 28 54](https://cloud.githubusercontent.com/assets/941075/22481161/51d05c3a-e7db-11e6-94b2-132b6f3d8b16.png)

Actually, what is being blocked is our call to the cdn to fetch the client information. I just hit that. Not sure what we can do in our part. Maybe try to whitelist our cdn with the PB folks? cc @hzalaz

**Comment by luisrudge** [comment]
What's super weird is that it only blocks this url when I'm loading from localhost. If I load directly from https://auth0-repro-809.now.sh/, it works as expected

**Comment by glena** [comment]
cross protocol maybe?

**Comment by luisrudge** [comment]
No. I just removed the comment because it is indeed blocking with that website as well.

**Comment by luisrudge** [comment]
I opened an issue in the PB repo. I'll close this issue since there's nothing we can do. Please subscribe to the PB issue if you want to see how that goes.

**Comment by ekevoo** [comment]
Is there an issue for implementing the EFF Do Not Track?

**Comment by luisrudge** [comment]
@ekevoo No. This has to be implemented in our backend. It's on our backlog but there's no estimates.

**Comment by Fthree** [comment]
@luisrudge Hi Luis, are there any plans for pushing this into the backend? Or has this issue entered the backlog black hole?

**Comment by luisrudge** [comment]
It probably has a super low priority. If you all want to make your voices heard, you should open a ticket with our amazing support team [here](https://support.auth0.com/). They'll route your requests to the appropriate team and we'll see how it goes from there.
