### ISSUE TITLE
[v10] lock.getProfile throws TypeError if passed a token without a . character

### ISSUE THREAD

**Issue by brentshields** [auth0/lock#366]
I realize that this is not a valid token, but I think the callback should be called with the error instead of throwing here. It already checks for a falsy token or a token that is not a string and in those cases it invokes the callback with an error. But if you pass a string without a `.` it throws:

`Uncaught TypeError: Cannot read property 'length' of undefined`

This is because `Auth0.decodeJwt` calls `split('.')[1]` on the token and then passes it to `decode` without checking if the result is defined.

**Comment by hzalaz** [comment]
Should be fixed in latest releases of Lock
