### ISSUE TITLE
Resend confirmation emails when attempting to re-register an unconfirmed user

### ISSUE THREAD

**Issue by rolodato** [auth0/lock#37]
Confirmation emails should be resent (or at least prompted) when users try to register a preexisting account with an unconfirmed email, only when email verification is turned on for that application.

**Comment by ened** [comment]
What is auth-users? A forum, link.. ?

**Comment by luisrudge** [comment]
@ened sorry, this is our private repo. If you need that, please get in touch with https://support.auth0.com/
