### ISSUE TITLE
Signup. Username is sent even when it is not required

### ISSUE THREAD

**Issue by ziluvatar** [auth0/lock#373]
On signup, Lock shouldn't send the username to the server when the username is not required/needed by the connection.

So that instead of [Lock copying the email value if username is not required](https://github.com/auth0/lock/blob/dc63665752eec8d90c884b8282f9a112f988d98b/lib/mode-signup/index.js#L283) it should not send the username at all.

**Comment by hzalaz** [comment]
Fixed in auth0.js
