### ISSUE TITLE
Auth0 Widget/Lock redundant home realm discovery

### ISSUE THREAD

**Issue by mnoecc** [auth0/lock#38]
When an app only has a single enterprise connection, it should show a button to redirect the user to the login page rather than to ask them for their email address, since there is no need for it to discover the home realm.

**Comment by hzalaz** [comment]
Implemented in Lock 10

<img width="689" alt="screenshot 2016-08-30 12 08 22" src="https://cloud.githubusercontent.com/assets/895992/18094612/7fa71a68-6eaa-11e6-9f06-c964b749a9ef.png">
