### ISSUE TITLE
feature request: more flexible show

### ISSUE THREAD

**Issue by charlierudolph** [auth0/lock#395]
I would like to show lock with both the login and sign up tabs, but have it start in the sign up tab.

As far as I can tell this is impossible with the current API.

**Comment by gnandretta** [comment]
Hi, this is possible in v10, you need to specify the `initialScreen: "signUp"` option.

The final version has not been released yet but a beta is available. More information is available at https://auth0.com/docs/libraries/lock/v10.

**Comment by charlierudolph** [comment]
Awesome. Thanks! Any idea when the official version of v10 will be released?

**Comment by gnandretta** [comment]
Soon 😄 
In a couple of weeks we will push a release candidate.

**Comment by virtser** [comment]
Why does `rememberLastLogin: true` is not respected when `initialScreen: "signUp"` option is chosen?
