### ISSUE TITLE
need _isUsernameRequired() part of locals for ejs templates

### ISSUE THREAD

**Issue by monteslu** [auth0/lock#396]
Current npm version has error after bundling.  The template is trying to refer to _isUsernameRequired in a `with(locals)` block (ejs template output stuff).  

Likely have to add this function to the OptionsManager:

![locals](https://cloud.githubusercontent.com/assets/423800/15378998/54dd55e2-1d1d-11e6-9708-8d93d9fbd15e.png)

Otherwise error is thrown when trying to bring up lock dialog:

![undefined_function](https://cloud.githubusercontent.com/assets/423800/15379003/58d46118-1d1d-11e6-915c-08b7faa5bb67.png)

**Comment by monteslu** [comment]
Found it.

calling ` _.extend({}, foo, bar)`  will strip any prototype functions off of `foo`.

In this case, the `OptionsManager` just becomes  a plain object and we no longer have `_isUsernameRequired()` as a member function.

So a couple of options:

### Remove that empty object in places like:
```javascript
Auth0Lock.prototype.render = function(tmpl, locals) {
  var _locals = _.extend({}, this.options, locals);
  return tmpl(_locals);
};
```
and

```javascript
SigninPanel.prototype.resolveOptions = function(options) {
  return _.extend({}, this.widget.options,  this.options, options);
};
```

### Alternatively swap underscore for lodash, which I believe keeps the prototype functions on the result.

**Comment by gnandretta** [comment]
Hi! thanks for the detailed report, i'll take at look at this as soon as I get a chance.

**Comment by monteslu** [comment]
any movement on this?  

Kinda scary having to maintain my own fork :)

**Comment by gnandretta** [comment]
@monteslu Hi! i wasn't able to reproduce this. I've also verified that underscore's `extend` copies all properties, as stated in the [docs](http://underscorejs.org/docs/underscore.html#section-103).

Can you provide a sample project with the issue?

**Comment by hzalaz** [comment]
Please reopen with a sample if the issue persists (or open a new one)
