### ISSUE TITLE
Password Policy panel covers the fields above it

### ISSUE THREAD

**Issue by theopak** [auth0/lock#397]
![image-2016-05-19-13-12-20-203](https://cloud.githubusercontent.com/assets/693878/15404276/b4fcdf80-1dca-11e6-8043-3cdc01a4ad79.png)

Hi. Our developers have really been enjoying how easy it is to use Auth0 Lock! However, our users have been complaining about the signup experience. Above is a screenshot that someone sent me. 

See how the password policy panel covers the email address that they just typed in? It's a minor inconvenience but it's really important to our work that we remove friction in the signup/registration process. 

I want to move the password policy panel so that it doesn't cover any part of the form. Is this something the team is already thinking about? Do you have any recommendations on how to solve this issue?

**Comment by gnandretta** [comment]
Hi, thanks for the feedback. An alternative is to show the password policy popup to the right of the field, or not to use a popup, like we do for smaller screens
<img width="450" alt="screen shot 2016-05-19 at 4 07 10 pm" src="https://cloud.githubusercontent.com/assets/120195/15406232/026237be-1ddc-11e6-8b0d-c3de2e0364d4.png">

**Comment by theopak** [comment]
Perfect! Thanks for the prompt reply.
