### ISSUE TITLE
changelog format

### ISSUE THREAD

**Issue by charlierudolph** [auth0/lock#399]
In the future, please update the changelog format to not just be a list of the commits (you can look at the commit history for that or just give a link that compares the release with its previous) and instead list the changes from a user / developer perspective.

For examples 9.2.1 could be

```
[9.2.1](https://github.com/auth0/lock/compare/v9.2.0...v9.2.1) - 2016-05-14

* Prevent sections from overlapping on mobile devices with a small vertical height 
* Use optimized version of auth0 logo
```

The changelog doesn't provide much value if the user has to figure out for themselves what actually changed. The commit message is valuable most of the time, but in my experience it typically needs updates to make it more easily understood by someone not familiar with the codebase. The changelog is also the place to explain to the user if they need to do anything when upgrading.

**Comment by hzalaz** [comment]
We'll change this for the new version following the conventions of http://keepachangelog.com, probably using https://github.com/skywinder/github-changelog-generator or something similar.

**Comment by hzalaz** [comment]
Added to our backlog
