### ISSUE TITLE
In popup mode the popup does not close in IE11

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/lock#401]
Related to closed issue: #185 
@nicosabena:

I'm finding the exact opposite behavior: the popup window is not closed (fails) when Protected Mode is disabled.
The "Local Intranet" zone (the one IE uses when browsing localhost, and possible internal sites in a corporate environment) has Protected Mode disabled by default. When enabling it, it works ok.

This is the default:
![image](https://cloud.githubusercontent.com/assets/6582826/15487174/44bef216-219f-11e6-81e4-4a337767fee7.png)

**Comment by nicosabena** [comment]
I think @gnandretta got it right: the problem arises when the application site and the popup site (served from `https://{tenant}.auth0.com`) end up in security zones **with different Protected Mode settings**.

When that happens, `windows.opener` returns `undefined` and the popup can't communicate with its parent. 

Usually `localhost` and sites in a corporate network belong to the **Local intranet** zone, with Protected Mode `off`, while `https://{tenant}.auth0.com` belongs to the **Internet** zone, with Protected Mode `on`.

The workaround is either adding `https://{tenant}.auth0.com` to the **Trusted sites** zone (that also has Protected Mode `off`), or using the same Protected Mode setting in both **Local intranet** and **Internet** zones.

Recommended approach is to avoid popup mode if possible and use [redirect mode](https://auth0.com/docs/libraries/lock/authentication-modes#redirect-mode).
