### ISSUE TITLE
[Question] Custom fields for SSO (lock 10)

### ISSUE THREAD

**Issue by Aedaeum** [auth0/lock#404]
I have a site that I want to set up as invite only. I want to add a mandatory field where the user must enter an invite which is sent with the signup request. This will then be validated through a webhook using an Auth0 rule request to my server. Is it possible to do this with social logins as well (google, facebook, github, etc...)?

**Comment by gnandretta** [comment]
This is for lock issues only, please [contact support](https://support.auth0.com) for questions about Auth0.
