### ISSUE TITLE
Lock does not work with ember-cli-mirage

### ISSUE THREAD

**Issue by psteininger** [auth0/lock#413]
When ember-cli-mirage is enabled in Ember JS app, the login process hangs, and does not succeed.
Apparently there is an issue between `pretenderjs` and `reqwest` library. https://github.com/auth0/auth0-ember-simple-auth/issues/40.

I will try to investigate further, but not sure how to detect the underlying issue

**Comment by hzalaz** [comment]
Please ask for support for Ember in https://support.auth0.com if the issue persists. This repo is for vanilla js Lock

**Comment by psteininger** [comment]
@hzalaz Already done that and we arrived at the conclusion that the issue is with the use of reqwest library in the vanilla JS lock. That library causes issues with the Pretender JS lib, NOT Ember itself.

**Comment by seawatts** [comment]
@psteininger did you get anywhere with this?
