### ISSUE TITLE
display is not a function

### ISSUE THREAD

**Issue by beornborn** [auth0/lock#417]
react 0.15
failed on 3rd step of quickstart 
http://prntscr.com/bb1xr1

on clicking sign in I receive lock-9.1.min.js:4Uncaught TypeError: this.display is not a function

**Comment by hamuk** [comment]
I think it's unrelated to your issue but I had the same error and fixed it by changing how I called show in my Redux Saga:

Changed from:
`yield call(lock.show, lockCallback)`

To simply:
`yield lock.show(lockCallback)`

Just in case anyone was doing what I was doing!

**Comment by hzalaz** [comment]
Please reopen if this is still an issue
