### ISSUE TITLE
Lock doesn't work in a cluster of apps

### ISSUE THREAD

**Issue by hguillermo** [auth0/lock#431]
I have a cluster (4 boxes running the app) and the login doesn't work correctly. It is logging in correctly because I see in the Auth0 Dashboard Logs that the login was okay. However the login in windows shows up again and again.

I stopped the app in 3 boxes and left 1 running. Everything works great that way. Any ideas?

**Comment by woloski** [comment]
Hi guillermo, this has nothing to do with Lock. Please open a support ticket.
