### ISSUE TITLE
[Security Vulnerability] Dependency on qs needs to be updated

### ISSUE THREAD

**Issue by chapati23** [auth0/lock#444]
There are 2 known security vulnerabilities in `qs < 1.0.0`:
* https://snyk.io/vuln/npm:qs:20140806
* https://snyk.io/vuln/npm:qs:20140806-1

any reason these shouldn't be updated to 1.0.0?

btw, i'd suggest adding snyk as a git pre-push hook (not affiliated). Been using it in our projects for some months now and it already caught a bunch of critical vulnerabilities in our dependencies that we'd never have caught

**Comment by hzalaz** [comment]
Moved to auth0.js for update
