### ISSUE TITLE
[v10] The .auth0-lock-last-login-pane button is missing a background color.

### ISSUE THREAD

**Issue by colllin** [auth0/lock#449]
![image](https://cloud.githubusercontent.com/assets/185923/16202766/64141fac-36d4-11e6-9485-1bc9df1c6a95.png)

When I hover, I see this:

![image](https://cloud.githubusercontent.com/assets/185923/16202777/6d188c0a-36d4-11e6-9b2c-2ea8e76028ec.png)

**Comment by dshorowitz** [comment]
Also in lock v9, the button with your email is a blue-ish color, not the grey. The blue color is much easier to read.

![untitled-1](https://cloud.githubusercontent.com/assets/11761476/16277392/ba937276-3880-11e6-8ca9-b097c50918b1.png)

**Comment by gnandretta** [comment]
@colllin Could you try `10.0.0-rc.1`? If the issue is still there, please let me know in which browsers is happening.

**Comment by dshorowitz** [comment]
@gnandretta The issue of the grey color is still there in rc.1

**Comment by gnandretta** [comment]
@dshorowitz I've already passed on your feedback to the design team. In the mean time you override the  background color with CSS.

**Comment by dshorowitz** [comment]
@gnandretta Great, thanks

**Comment by colllin** [comment]
@gnandretta So is this fixed/released?  Or planned for release?

**Comment by gnandretta** [comment]
@colllin this was fixed in `10.0.0-rc.1` in all the browsers that we support, see [this comment](https://github.com/auth0/lock/issues/449#issuecomment-227827105).

**Comment by colllin** [comment]
Got it.  I thought dshorowitz was saying the issue was still there, but maybe he was saying that it's now gray and expected it to be a color.  Seems it should probably make use of the primary color in Lock settings though, right?  The gray looks disabled.

**Comment by gnandretta** [comment]
@colllin sure, I've opened issue #542 for that
