### ISSUE TITLE
[v10] Forgot password doesn't display a "success" screen

### ISSUE THREAD

**Issue by dshorowitz** [auth0/lock#456]
In v10, if I click on "Forgot password" and enter a password, it shows the following screen:

![untitled-2](https://cloud.githubusercontent.com/assets/11761476/16277473/1a35bd4c-3881-11e6-8894-8ae02af6d7a7.png)

There should be a "check your email" success screen after submitting the forgot password prompt, no?

**Comment by gnandretta** [comment]
Hi, when you submit the password to start the reset password flow you should get back to the login screen and see a success alert.

Could you please let us know,

- Which version of lock are you using? 
- Do you see any errors in the console?
- In which browsers is this happening?

**Comment by dshorowitz** [comment]
> Hi, when you submit the password to start the reset password flow you should get back to the login screen and see a success alert.

I assume you mean "submit your email" instead of "submit the password", but just wanted to make sure.

There is no success alert that shows for me, instead it shows the image I attached in my initial post.

Which version of lock are you using? v10 rc1
Do you see any errors in the console? There is an error relating to "_blueimpMd.md5 is not a function" from gravatar_provider.js on line 43.
In which browsers is this happening? I'm using the latest version of Chrome

**Comment by gnandretta** [comment]
Yes, sorry, I meant "submit your email". This might be related to #457 so let fix that first.

**Comment by gnandretta** [comment]
Is this still happening with the [blueimp fix](https://github.com/auth0/lock/issues/457#issuecomment-227851149) you tried in #457?

If not, it looks like it might be related to the `Warning: ReactTransitionGroup: `ref` is not a prop.` error that is shown in the [screenshot](https://cloud.githubusercontent.com/assets/11761476/16278013/4150433c-3883-11e6-965b-1c0c45a10e73.png) from that issue's description.

To narrow it down, can you try using the script from our CDN? also are you using Lock in a React application?

The CDN script URL is 
```
https://cdn.auth0.com/js/lock/10.0.0-rc.1/lock.min.js
```

**Comment by dshorowitz** [comment]
Good news ... the error doesn't happen anymore after I implemented the blueimp fix. However, I'm still getting React warnings and errors after submitting the password reset screen.

![untitled-1](https://cloud.githubusercontent.com/assets/11761476/16309855/3adc3f28-3938-11e6-8cb7-15fed706a8b2.png)

I'm not running this in a React app, but I am bundling with webpack.

**Comment by gnandretta** [comment]
Good. I'll close this and follow up in #458.
