### ISSUE TITLE
[v10] Uncaught TypeError (0, _blueimpMd.md5) is not a function

### ISSUE THREAD

**Issue by dshorowitz** [auth0/lock#457]
I'm bundling v10 using webpack and I'm getting a bunch of React warnings and uncaught errors

![untitled-3](https://cloud.githubusercontent.com/assets/11761476/16278013/4150433c-3883-11e6-965b-1c0c45a10e73.png)

The React warnings are happening when the lock is initially shown and the errors are happening when you try to enter a password in the forgot password screen.

**Comment by gnandretta** [comment]
Looks like a problem in the bundling process. Do you see those errors when using the [webpack example](https://github.com/auth0/lock/tree/v10/examples/bundling/webpack) from this repo?

**Comment by dshorowitz** [comment]
I just downloaded the code for the webpack example you linked to, and ran it. Then I tried resetting my password and got the following errors:

![untitled-4](https://cloud.githubusercontent.com/assets/11761476/16280487/aee2eae4-388d-11e6-99cc-49d852b31bd0.png)

Notice the same error about md5?

I noticed in lib\avatar\gravatar_provider.js you have:

`var _blueimpMd = require('blueimp-md5');`

and then

`_blueimpMd.md5)(email)`

But requiring blueimp-md5 should allow you to do 

`md5(email)`

directly, shouldn't it?

**Comment by gnandretta** [comment]
You are right, when bundling with webpack `require('blueimp-md5')` is the function that we need. However, when bundling with browserify `require('blueimp-md5')`is an object which has the function in the `md5` property. This has been fixed in #459 and will get into the next release.

**Comment by dshorowitz** [comment]
Great. Any ETA on the next release?

**Comment by gnandretta** [comment]
As soon as I can get rid of all the bugs that have been reported
