### ISSUE TITLE
[v10] Can't type in login form after password reset

### ISSUE THREAD

**Issue by dshorowitz** [auth0/lock#458]
In lock v10, if you complete the reset password flow, it takes you back to the login screen.

Once there, I am unable to type in the username or password input fields. When I type a character on my keyboard, the cursor in the input field jumps to the end and the character doesn't appear in the input box.

**Comment by dshorowitz** [comment]
This still happens after the blueimp fix, fyi

**Comment by gnandretta** [comment]
I think the errors that are shown in [this screenshot](https://github.com/auth0/lock/issues/456#issuecomment-228093788) from #456 are responsible for this issue. However, I can't reproduce them.

The first thing I want to clear up is if this is coming from a bundling issue. Have you tested if using the CDN script fixed the issue?

**Comment by dshorowitz** [comment]
CDN works fine, so its a bundling issue. Looking into it now. Can you try with the exact webpack config you recommend?

**Comment by gnandretta** [comment]
I don't see the issue with our example. Could you please tell me what node and npm version are you using? Also the output of `npm ls` would be great.

**Comment by dshorowitz** [comment]
OK I've narrowed down the problem. I'm using npm3. In the example, when you run `npm install` the auth0-lock dependencies are installed at the root level of node_modules. In my project (the one that has the error), they are installed in a node_modules subdirectory of the auth0-lock folder (because their versions conflict with already installed versions of the same modules).

Once the node_modules are installed as a subdirectory, you'll see the error I'm talking about. (You can manually recreate this scenario by putting the following node_modules in the auth0-lock\node_modules subdirectory:

asap
auth0-js
core-js
fbjs
promise
qs
react
react-addons-css-transition-group
react-dom
xtend

The fix has to do with the webpack configuration file. That's where I'm stuck. Not sure how to resolve it.

**Comment by gnandretta** [comment]
I could not recreate the issue with your instructions. However, I could see the errors when the project depends on an older version of React (as in f50ba21ac2be319811518c190efef8c3dd3c792c)

<img width="461" alt="screen shot 2016-06-24 at 10 52 10 am" src="https://cloud.githubusercontent.com/assets/120195/16341788/49135752-3a05-11e6-8dd7-a294a3958e61.png">

This is happening because different versions of React are included in the bundle at the same time. 

From your comments, it looks like you have another dependency that depends on React besides lock. But I can be sure, that's why I asked you for the output of `npm ls`. Can you confirm this is the case? Thanks

**Comment by dshorowitz** [comment]
I think you're right. We are using react 0.14 elsewhere in the code (npm ls shows it). I guess the question then is how do we instruct webpack to bundle only the correct version of react?

**Comment by gnandretta** [comment]
You can instruct webpack to bundle only one version of React by adding to _webpack.config.js_  something like: 
```js
resolve: {
  alias: {
    react: path.resolve('./node_modules/auth0-lock/node_modules/react'),
  }
}
```
Upgrading the library that depends on the old version of React will be the right thing to do. How do you know that the library will work with the new React version? Also, in npm3 the `node_modules` depends on installation order.

**Comment by dshorowitz** [comment]
We're using auth-lock in a single JS bundled file, but our webpack config bundles a lot of different JS scripts. All of the other scripts rely on the older version of react.

So the question is how can I set my webpack config to ensure that the only entry point which uses the newer version of react is the one that includes auth0-lock?

Aren't the resolve aliases in webpack global?

**Comment by dshorowitz** [comment]
Update: The problem was that webpack was bundling an older version of React. Once I upgraded, this problem went away. I do think it would be helpful in your webpack example to make sure people know to bundle the right version of react. Thanks!
