### ISSUE TITLE
[v10-beta.5, v10-rc.1] Did you mean authentication_error?

### ISSUE THREAD

**Issue by colllin** [auth0/lock#460]
Seems you're careful in other places at differentiating between authentication and authorization.  Do you think the `authorization_error` event should be called `authentication_error` instead?

**Comment by gnandretta** [comment]
If, for instance, you enter the wrong username/password combination, Lock will show an error saying _Wrong username or password_. That is what we would call an "authentication error".

Now, when you enter the right credentials, you are redirected to Auth0 and rules are executed. Rules that deal with authorization will interrupt the login flow. Hence the name "authorization error".

Another example of an authorization error is when you are redirected to a social provider site and you don't grant consent.

Hope this helps, I will make sure this gets documented properly.
