### ISSUE TITLE
[v10] Registration - Error for valid passwords after switching from Login to Signup

### ISSUE THREAD

**Issue by leilafi** [auth0/lock#462]
Password error appears for a valid password if you first try to log in with a new email and then switch to log in with that email.

##### to repro
1. Go to Login
2. Try logging in with an email that doesn't exist
3. Once you got  the expected error switch to Sign up
4. Enter the same email
5. Enter a valid password

---- you get an error password validation

**Comment by gnandretta** [comment]
@leilafi Hi, I followed the steps but I didn't get the error. Could you provide more information to help us debug this?

- What version of Lock are you using?
- What is the exact error you are seeing? Where is it being shown? Could you provide a screenshot?
- Does the database connection require an username?
- What is the password strength policy of the database connection?

**Comment by leilafi** [comment]
Thanks for getting back to me. Please find the answer to the questions inline.

- What version of Lock are you using?
--- v10

- What is the exact error you are seeing? Where is it being shown? Could you provide a screenshot?
![screen shot 2016-07-01 at 10 35 09](https://cloud.githubusercontent.com/assets/16544365/16517849/8ccf760c-3f77-11e6-8a03-129f64459dd2.png)

- Does the database connection require an username?
--- does not need username just email

- What is the password strength policy of the database connection?
--- password policy is Must Have: 6 characters in length any type.

**Comment by gnandretta** [comment]
@leilafi are you using webpack to bundle your app?

**Comment by leilafi** [comment]
@gnandretta Yes we are.

**Comment by gnandretta** [comment]
The error you are seeing in the console has been fixed in #459. I believe this is what is preventing the password error to go away. We will publish a new version containing the fix early next week. Thanks.

**Comment by leilafi** [comment]
@gnandretta  Can you please notify me when the new release is out.

Thanks.

**Comment by gnandretta** [comment]
Should be fixed on 10.0.0-rc.2. Please reopen if the problem persist.
