### ISSUE TITLE
[v10] handleAuthCallback() removes hash

### ISSUE THREAD

**Issue by musshush** [auth0/lock#463]
Found a problem while using with React Router.

When `lock.getProfile()` is called, `handleAuthCallback()` removes hash (https://github.com/auth0/lock/blob/v10.0.0-rc.1/src/core/actions.js#L26) and does not place it back.
The same issue happens when the lock is opened for the first time (both in embedded and popup mode).

(It redirects to `/account` on the below screen capture because we have a redirect set to `/account` if a user is logged in and on the root page)
![remove-hash](https://cloud.githubusercontent.com/assets/864185/16491188/c7f5cbf8-3ed4-11e6-97e0-6c774d2e141f.gif)

**Comment by gnandretta** [comment]
Should be fixed on 10.0.0-rc.2. Please reopen if the problem persist.
