### ISSUE TITLE
Despite claims, documentation is not 'full' and 'complete'

### ISSUE THREAD

**Issue by Recmo** [auth0/lock#465]
The simplest example (Vanilla JS SPA) references the function `lock.getProfile`.

I'd like to know more about this function, and have a list of other functions I might use. (In particular I'm looking for a function that can tell me if a token is expired purely client side).

So I click on links labeled "Complete API" and "full API documentation" and search for the phrase `getProfile`. Nothing.

It seems the documentation is not complete. I will now resort to reading the source code.

**Comment by hzalaz** [comment]
We have updated our docs for Lock 10
