### ISSUE TITLE
Setting loginAfterSignup to false creates user successfully but gives empty page

### ISSUE THREAD

**Issue by Brightergy-BrishaPote** [auth0/lock#476]
I'm pretty much using auth0 lock as per the react quickstart however when I set `loginAfterSignup` to false, I can see that the user is created but I see an empty page immediately after the POST succeeds. I could not find any good documentation if I can specify signup callback or something. I'm using `lock.show()` and have `disableSignupAction` set to false so that I can have both login and signup on same page. I want to disable auto login after signup but instead show some friendly message (or redirect to some info page). I'm using lock 9.2.1.

**Comment by gnandretta** [comment]
Hi, you can listen to the `"signup success"` event with:
```
lock.on("signup success", function() {
  // do something
});
```
There are other sign up events, which are documented [here](https://auth0.com/docs/libraries/lock/events).

With the configuration you described, Lock v9 will close itself after the user signs up. In Lock v10 we have better support for this flow and we show a confirmation message.

![screen shot 2016-07-07 at 10 08 40 am](https://cloud.githubusercontent.com/assets/120195/16655142/63e75bda-442f-11e6-95c9-7ce121261ad1.png)

We are currently working on Lock v10 docs, but you can check https://auth0.com/docs/libraries/lock/v10 and https://github.com/auth0/lock/blob/v10/README.md.

**Comment by Brightergy-BrishaPote** [comment]
@gnandretta perfect thanks! This works. And, lock10 looks good. We'll probably soon upgrade to lock 10 anyway.
