### ISSUE TITLE
[v10-rc2] Global error message is not customisable

### ISSUE THREAD

**Issue by musshush** [auth0/lock#480]
We want to change the following two login error messages

<img width="329" alt="screen shot 2016-07-11 at 15 39 19" src="https://cloud.githubusercontent.com/assets/864185/16734516/bc6e4664-477d-11e6-8420-2632cdf7052b.png">
<img width="325" alt="screen shot 2016-07-11 at 15 39 02" src="https://cloud.githubusercontent.com/assets/864185/16734519/beaf22b8-477d-11e6-88a6-b6d77780dc3b.png">

Tried to change these
```
login: {
    'lock.fallback': 'Something went wrong blah',
    'lock.invalid_email_password': Check your email or password blah.',
}
```
but it does not seem to do anything.

**Comment by gnandretta** [comment]
Hi, I don't see anything wrong with the sample code you provided (besides it is missing a quote) but it is incomplete. This is how the `languageDictionary` option should be specified when you want to override an error message.

```js
languageDictionary: {
  error: {
    login: {
      'lock.fallback': 'Something went wrong blah',
      'lock.invalid_email_password': 'Check your email or password blah.',
    }
  }
}
```

If that didn't help, please provide more information.

**Comment by musshush** [comment]
Oh, yeah, I missed `error`. It is working. 😄

**Comment by gnandretta** [comment]
great!
