### ISSUE TITLE
[v10] title in languageDictionary should depend on the selected tab

### ISSUE THREAD

**Issue by dshorowitz** [auth0/lock#482]
If you want different titles for sign in and sign up, that's currently not possible because there's only one title attribute in languageDictionary. Shouldn't there be a different entry in the dictionary, one for each tab?

**Comment by gnandretta** [comment]
Hi, by design there is only one title for the widget. The segmented control indicates whether you are logging or signing in.

**Comment by dshorowitz** [comment]
Not sure I understand. If you configure the widget to allow both sign up and log in, how can you switch the title depending on which tab is selected?

For example, suppose I want the title for the sign up tab to be "Sign up here!" and the title for the login tab to be "Welcome Back. Sign In below." (or something similar).

How can I do that without two title config options?
