### ISSUE TITLE
[v10] On single page apps, click on links within lock modal, changes url

### ISSUE THREAD

**Issue by shadabahmed** [auth0/lock#483]
I'm using lock with `redirect: false`

The problem is whenever I click any of the links like-
 * Don't remember your password?
 * Not your account?
 
It change my page location to `/#` and thus changes the state. Inspect the link shows that the href is set to `#`:

![image](https://cloud.githubusercontent.com/assets/830679/16787886/d1972c36-4854-11e6-918b-ffc8dd5b5617.png)

**Comment by gnandretta** [comment]
Hi, can you provide a minimal sample that reproduces the issue?

**Comment by hzalaz** [comment]
@shadabahmed is this still an issue?

**Comment by hzalaz** [comment]
closing this one, please reopen (or submit a new one) with a sample we can use to reproduce this issue
