### ISSUE TITLE
Auth0 Lock v 9.2.1: CallbackURL never invoked

### ISSUE THREAD

**Issue by pree011235** [auth0/lock#494]
I am trying to set up the redirect URL after successful Authentication from Auth0 Lock on the UI's side. The redirect URL is to my backed service. I am obviously missing something silly here:

I've configured Auth0 Lock as:
`this.lock = new Auth0Lock(clientId, domain, {});`
and showing it as (triggered by an onClick event):
`      this.lock.show ( {
        icon: 'logo_url',
        callBackURL: 'http://my_service1.my_domain:my_port/signin-auth0',
      });
`
I've added the following config on the dashboard:
- Chosen Regular Web App with Token Endpoint Authentication Method set to 'None'
- The Allowed Callback URLs has `http://my_service1.my_domain:my_port/signin-auth0` as well as my UI's URL `http://www.my_domain:my_port`
- The redirect URL is on my backend Ruby on Sinatra service and I can access the route via Postman.  i.e. `GET /signin-auth0`
This simply does not seem to redirect after successful authentication.

**Comment by stephenniemans** [comment]
Dar pree011235,

If this is the exact code snippet you're using, try removing the comma at the end, like so:

`this.lock.show({
    icon: 'logo_url',
    callBackURL: 'http://my_service1.my_domain:my_port/signin-auth0'
});`

Perhaps that will help? Your script might be expecting another entry otherwise.

**Comment by gnandretta** [comment]
Hi @pree011235 , try using `callbackURL` with a lowercase "b" instead of `callBackURL`.

**Comment by pree011235** [comment]
Thanks guys! That solved it. I have one last Q- After the successful authentication and redirection, on my Ruby route, how do I read the profile details and parse the jwt token?

**Comment by gnandretta** [comment]
I'm glad it worked. Lock documentation is hosted at https://auth0.com/docs/libraries/lock. Also check https://auth0.com/docs, it is the best way to get started.
