### ISSUE TITLE
[V10] - There is no specific message for non existing user

### ISSUE THREAD

**Issue by leilafi** [auth0/lock#495]
There is no message specific for non existing user on logging in or forget password.
On previous version there used to be a 'user doesn't exist' message.

#### to reproduce
1. Log in with an invalid email or hit forgot password

---- The error message is the same as wrong email/password

**Comment by gnandretta** [comment]
Hi, that is intentional. The previous version of lock doesn't show a "user doesn't exist" message for login/reset password.
