### ISSUE TITLE
Listing two ad/enterprise connections should display email for HRD

### ISSUE THREAD

**Issue by pose** [auth0/lock#50]
Use the following snippet:

```js
widget.show({
  focusInput: false,
  closable: false,
  connections: ['adconn', 'adconn2'],
  responseType: 'token',
  callbackURL: 'http://localhost:3000'
});
```

**What should happen?** An email and password lock should be displayed where user can enter their emails. Then deciding on the email domain that the user has input, it should display the HRD mode.

**What happens instead?** The following screenshot:
![screen shot 2014-09-19 at 19 16 04](https://cloud.githubusercontent.com/assets/419703/4342813/91ed112c-404a-11e4-8d4b-7b5d780646d9.png)

**Comment by hzalaz** [comment]
Fixed in Lock 10 
<img width="375" alt="screenshot 2016-08-30 12 14 34" src="https://cloud.githubusercontent.com/assets/895992/18094864/5c87022c-6eab-11e6-9b26-5401d755d267.png">
