### ISSUE TITLE
[v10]set allowedConnections dynamically, like on show()

### ISSUE THREAD

**Issue by hughred22** [auth0/lock#501]
The new V10 do not allow set any option dynamically... Everything has to do in setup. But my app listen to what user pick and then show the allowedConnections dynamically. How is this possible now?! 

Also, my login function waiting for a promise (Ionic 2 app). Then the app redirect user. But now, login does not return anything and the promise pattern now wokring anymore and it is breaking my app hardcore... Everything just feel super not flexible in v10.

**Comment by gnandretta** [comment]
Hi,

You can construct a new lock with the connections you need just before showing it. We know this requires a little more work and we plan to allow to set `allowedConnections` when calling `show` in a future version. Maybe you can stick with lock v9 until we add this feature?

Can you provide more information about your second issue? Lock doesn't have a `login` method and it doesn't use promises.

**Comment by hughred22** [comment]
How do I cancel the old lock and construct a new lock with the same instance name? I can not use v9 b/c it won't work with Ionic 2 - as your tutorial of Ionic 2 is using v10 and v9 has some serious bug. 

For the second issue, it is b/c now lock.show does not use promises, how won't I know when the login successfully so I can redirect user in my app?

**Comment by gnandretta** [comment]
The `show` method never used promises. To construct a new lock  and to know when the user has been logged in you need something like this:

```js
lock.destroy();
lock = new Auth0Lock(cid, domain, options);
lock.on("authenticated", function(authResult) {
  // user has logged in
});
```

I've created issue #503 which you can use to keep track the progress of the feature to pass `allowedConnections` to the `show` method. I'll close this now, please contact support (https://support.auth0.com/) if you have more questions.
