### ISSUE TITLE
Issue Logging In When Remembering Last Login

### ISSUE THREAD

**Issue by nickabond** [auth0/lock#504]
I'm having an issue when logging in and remembering the last login. I'm using Auth0 Lock 10.0.0 with Cordova and Jquery. After I login once it asks me if I would like to login with the user that I logged in with last time. I think that's an excellent feature, but every time I click on the email of that (in order to login with the user I logged in with last time).

<img width="371" alt="screen shot 2016-07-25 at 3 43 37 pm" src="https://cloud.githubusercontent.com/assets/4335602/17116790/e8b9ae3c-527e-11e6-9fa0-077585ccada2.png">

It opens a login link through the InAppBrowser plugin just like you guys suggest. I then I have to tap the email I last logged in with again. After I tap it just reloads the page without actually logging me in? Not sure how to fix this or if it is a bug on your guy's end?

<img width="369" alt="screen shot 2016-07-25 at 3 43 43 pm" src="https://cloud.githubusercontent.com/assets/4335602/17116799/eff77472-527e-11e6-9c65-368d5cff34ba.png">

These are the settings I'm using:

```
var options = {
						   auth: {
						   	redirect:false,
						   	sso:true
						   },
						   additionalSignUpFields: [{
						      name: "Full_Name",                              // required
						      placeholder: "Please enter your full name",            // required
						      validator: function(value) {                  // optional
						        if(value != ""){
							        return true;
						        }
						      }
						    }],
						    rememberLastLogin:true
						}
```

Everything was working fine before I upgraded to Lock 10.0.0

Please let me know how to fix this.

**Comment by gnandretta** [comment]
Hi, sso is intended to be used in web sites, have you considered using a [refresh token](https://auth0.com/docs/refresh-token)?

**Comment by soulbeing** [comment]
exactly same thing is happening to me. anyone has a solution?

lock = new Auth0Lock('key........', 'host........', {
        loginAfterSignup:true,
        allowForgotPassword: true,
        rememberLastLogin: true,
        auth: {
          redirect: false,
          params: {
            scope: 'openid offline_access',
          }
        },
        languageDictionary: {
          title: "My APP"
        }
      });

**Comment by hzalaz** [comment]
@soulbeing you need to disable SSO since it won't work in an ionic app, if you have a different setup can you provide us more details on where and how you are using Lock. A sample application in a repo will be really helpful

**Comment by hzalaz** [comment]
Closing this one please reopen (or open a new one) if needed
