### ISSUE TITLE
Callback URL mismatch

### ISSUE THREAD

**Issue by ydoshi91** [auth0/lock#508]
I am using version 10
```javascript
"auth0-lock": "^10.0.0"
```
Initialization and lock show:
```javascript
import Auth0Lock from 'auth0-lock'
this.lock = new Auth0Lock(clientId, domain);
...
this.lock.show();
```
But on every successful authentication, I end up on a page _https://login.auth0.com/login/callback?code=xyz_ which tells me the following 
*Callback URL mismatch. The url _pageUrl_ is not in the list of allowed callback URLs: [Allowed Url List]. *
where  _pageUrl_ is the url of the current page

I even tried passing an allowed url(http://localhost:8080/authCallback) such as 
```javascript
import Auth0Lock from 'auth0-lock'
this.lock = new Auth0Lock(clientId, domain, {auth: { params: {redirectUrl: 'http://localhost:8080/authCallback'}}} );
...
this.lock.show({callbackURL: 'http://localhost:8080/authCallback'});
```
Check Tracking Id : e6cc8224417dd10539a1 that I found under Technical details at the failure page

Everything worked marvellously before when I was going through the Tutorial/Getting started. Don't remember the version though

Additional Info : I am using react with react-router as of now.

**Comment by gnandretta** [comment]
Hi,

Is _http://localhost:8080/authCallback_ on the list of allowed callback urls?

Also, the option object should be:

```js
{
  auth: {
    redirectUrl: 'http://localhost:8080/authCallback'
  }
}
```

**Comment by ydoshi91** [comment]
Hey, 
yeah, sorry about the mishap in option object. redirectUrl does work now.
And this does redirect the browser to the redirectUrl.

But how do I make the first scenario work ?
I am trying to use the auth0-lock just like in getting started guide
```javascript
    this.lock = new Auth0Lock(clientId, domain, {} );
    this.lock.on('authenticated', this._doAuthentication.bind(this));
```

This still doesn't work. And I need this for SPA

**Comment by gnandretta** [comment]
Is http://localhost:8080/authCallback on the list of allowed callback urls?
