### ISSUE TITLE
With `authParams` in the constructor, how can you set state before each login?

### ISSUE THREAD

**Issue by chriswhong** [auth0/lock#517]
In previous versions, `authParams` were set in the `.show()` method, so every time I called `.show()` I could pass in a new state param in order to navigate to the correct page when login completed.

Now that options are passed into the constructor, it looks like I can't update `state` for each login because it's set to whatever it was when I first instantiated the lock.

Is there a way to change authParams before `.show()` is called?

**Comment by gnandretta** [comment]
Hi, I'll close this because is a duplicated of #488.
