### ISSUE TITLE
parseHash does not run in popup mode

### ISSUE THREAD

**Issue by doapp-ryanp** [auth0/lock#518]
cdn.auth0.com/js/lock/10.0.1/lock.js

Why does `parseHash` require `redirect` mode to be `true`?  I require popup mode but I also need to be able to use the "log in as" functionality from the auth0.com web ui dashboard.

Here is code:
![image](https://cloud.githubusercontent.com/assets/1036546/17224810/17c3dc84-54c8-11e6-9767-a2f96ac962b6.png)

As far as I can tell this is a regression from v9 as I do not see a workaround.

**Comment by gnandretta** [comment]
Hi,

This is how you parse the hash in v10:

```js
var client = new Auth0({clientID: clientID, domain: domain});
var hash = client.parseHash();
```

In redirect mode, lock needs to obtain the token from the url fragment to complete the authentication flow. In popup mode this is not the case so we don't parse the hash.

If you use redirect mode, impersonation will work out of the box like it did in v9. If you use popup mode instead, you'll need to manually parse the hash when impersonating a user, which is also required in v9.

**Comment by doapp-ryanp** [comment]
Ah makes sense.  The "The parseHash method was removed given that now it is automatically handled by Lock." in the [CHANGELOG.md](https://github.com/auth0/lock/blob/3fe59efdfe9101a5c8e7fe06b2de0a79edf9552e/CHANGELOG.md) confused me.  

Clear now though. thanks for the quick response

**Comment by syang** [comment]
@doapp-ryanp @gnandretta 
I am trying to parse the token as the following, but how can I achieve the same functionality of parseHash? (I am using v10, which parseHash is not available) 

Thanks


  getIdToken() {
    // First, check if there is already a JWT in local storage
    
    var idToken = localStorage.getItem('id_token');
    var authHash = this.lock.parseHash(window.location.hash);
    // If there is no JWT in local storage and there is one in the URL hash,
    // save it in local storage
    if (!idToken && authHash) {
      if (authHash.id_token) {
        idToken = authHash.id_token
        localStorage.setItem('id_token', authHash.id_token);
      }
      if (authHash.error) {
        // Handle any error conditions
        console.log("Error signing in", authHash);
      }
    }
    return idToken;
  }

**Comment by luisrudge** [comment]
Why are you parsing the hash yourself?
