### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by srollinet** [auth0/lock#521]
Is it planed to provide an official typescript definition file for use with frameworks like Aurelia or Angular2?

It seems that the definition on DefinitelyTyped is a bit outdated

**Comment by BenjaminGibbs** [comment]
I would also like to see this, we use a Typescript + Angular 1.5 at the moment and some up to date TS definitions would very welcome.

**Comment by valentinlup** [comment]
+1

**Comment by carusology** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10465

**Comment by carusology** [comment]
This will work for now until they accept the pull request over at DefinitivelyTyped
`typings install --save --global github:carusology/DefinitelyTyped/auth0.lock/auth0.lock.d.ts#14261aa459c36a258658d3c316eeedc9df8978c2`

**Comment by mikeesouth** [comment]
@carusology thanks! Great work. I'm also trying to get Auth0-lock to work with TypeScript. I'm trying to use it with webpack and npm. Your definition works so that I pass the TypeScript compilation and I have an import statement for the auth0 module like this: `import "auth0-lock";` but I get this error when I try to run my application: `Uncaught ReferenceError: Auth0Lock is not defined`.

I've also tried changing the import statement to `import * as Auth0Lock from "auth0-lock";` and it still compiles but I get this error when I try to run my application: `Uncaught TypeError: Auth0Lock is not a constructor`.

I have a [sample repo here](https://github.com/mikeesouth/lock/tree/master/examples/bundling/webpack-ts) that is forked from the [official webpack example](https://github.com/auth0/lock/blob/master/examples/bundling/webpack/) (that is using javascript, not typescript).

Does someone here have any idea on how I can import the auth0-lock package from npm and use it with TypeScript (+definitions)?

**Comment by carusology** [comment]
@mikeesouth Yeah, I ran into [that issue](https://github.com/Microsoft/TypeScript/issues/5285) with v9 of the auth0-lock as well. Here's what I did in my project to solve the problem:

1. Changing your import from `import * as Auth0Lock from "auth0-lock";` to `import Auth0Lock from "auth0-lock";` 
2. Set `allowSyntheticDefaultImports` to `true` in your `tsconfig.json` file.

**Comment by mikeesouth** [comment]
@carusology ah, thank you so much. It works. I've been at this issue for a while now :)

**Comment by carusology** [comment]
My changeset was merged into DefinitivelyTyped [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/auth0.lock).

This issue can be closed.

**Comment by SaltyDH** [comment]
To save others from the same pain.

```
typings install dt~auth0-js --global
typings install dt~auth0.lock --global

```
the auth0 typings were renamed a few days ago to auth0-js !

This is working for me with Auth0 lock v10.2.1 in a Webpack Angular2 project.

**Comment by mashaalmemon** [comment]
Great job @carusology and @mikeesouth . After scouring the net, this got it all going. Many thanks. 

@SaltyDH, coles notes also helpful re: auth0.js.

It might be helpful if the Auth0 folks updated their tutorials to reflect these nuggets of knowledge.

**Comment by hzalaz** [comment]
Closing this one, will update angular docs about it

**Comment by mikebridge** [comment]
@carusology Does this still work with the current `auth-js` type definitions?  When importing `@types/auth0-lock` I'm getting these errors:

```
Failed to compile.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(14,13): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(20,13): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(35,43): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(36,51): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(126,49): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(126,70): error TS2304: Cannot find name 'Auth0UserProfile'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(127,50): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(127,71): error TS2304: Cannot find name 'Auth0UserProfile'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(134,80): error TS2304: Cannot find name 'Auth0Error'.

Error in C:\Temp\src\Web\node_modules\@types\auth0-lock\index.d.ts
(6,1): error TS2688: Cannot find type definition file for 'auth0-js/v7'.
```

**Comment by carusology** [comment]
@mikebridge We ran into this too about a month ago. If I recall correctly, a DefinitivelyTyped contributor made a breaking change (represented as v8 of `auth0-js`), and the `auth0-lock` typings haven't been updated. What do your `@types/*` (i.e. `@types/auth0-lock`, `@types/auth0-js`, etc) dependencies look like in `package.json`?

**Comment by mikebridge** [comment]
@carusology I was pulling down the most recent one:

```json
"@types/auth0-lock": "*"
```

Npm does not download the `@types/auth0-js/v7` directory---I don't know enough of how it works to know why---but I was able to work around it by removing `@types/auth0-lock` and explicitly adding the dependency to `auth0-js` in `package.json`:

```json
"@types/auth0-js": "*"
```

... and then I copied your auth0-lock definitions locally, removed the 'v7' reference and added these lines:

```typescript
/// <reference types="auth0-js" />

import Auth0Error = auth0.Auth0Error;
import Auth0UserProfile = auth0.Auth0Error;
```

This seems to be working so far.

**Comment by carusology** [comment]
@mikebridge Yeah, that's what I figured. Here's our types in `project.json` that uses the lock:

```
    "@types/auth0": "^2.3.33",
    "@types/auth0-js": "^7.0.0",
    "@types/auth0-lock": "10.9.0",
```

The key to getting the v7 version of the auth0-js typing is setting your `@type/auth0-js` dependency as `"^7.0.0"`. You can see [here](https://www.npmjs.com/package/@types/auth0-js) that the most recent version is v8+.

**Comment by mikebridge** [comment]
@carusology Thanks!  In the meantime it looks like there is now a pending [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2b81d56713fb3c13bba3ce4a10cbb91daecee5de) to fix it.
