### ISSUE TITLE
[v10] no packageify

### ISSUE THREAD

**Issue by mattkrick** [auth0/lock#523]
Upgrading from v10 causes the following error. Using webpack to build and a dynamic require:

```
const Auth0Lock = require('auth0-lock');
```

```
ERROR in ./~/auth0-lock/lib/index.js
Module build failed: Error: Can't resolve 'packageify' in '/Users/mk/Code/action2/node_modules/auth0-lock/lib'
```

**Comment by carusology** [comment]
If you followed the [same demo](https://shellmonger.com/2016/03/18/integrating-auth0-into-a-webpack-project/) as I did, you had the following loaders in your webpack.config.js file:
```
{
    test: /node_modules[\\\/]auth0-lock[\\\/].*\.js$/,
    loaders: [
        'transform-loader/cacheable?brfs',
        'transform-loader/cacheable?packageify'
    ]
},
{
    test: /node_modules[\\\/]auth0-lock[\\\/].*\.ejs$/,
    loader: 'transform-loader/cacheable?ejsify'
}
```

I removed those loaders and the widget is now loading properly without errors.

**Comment by mattkrick** [comment]
tried that & i got about 12 errors instead of 1. 
the first being:
```
ERROR in ./~/auth0-lock/index.js
Module not found: Error: Can't resolve 'package.version' in '/Users/mk/Code/action2/node_modules/auth0-lock'
 @ ./~/auth0-lock/index.js 115:20-46
 @ ./src/universal/components/Auth0ShowLock/Auth0ShowLock.js
 @ ./src/universal/modules/landing/containers/Landing/LandingContainer.js
 @ ./src/universal/routes/landing.js
 @ ./src/universal/routes/index.js
 @ ./src/client/Root.js
 @ ./src/client/client.js
 @ multi app
```

**Comment by mcrawshaw** [comment]
Strange @mattkrick, removing the lines worked for me.

**Comment by gnandretta** [comment]
Hi,

You don't need to use any loader or transform for Lock v10, so you need to remove those lines. We have examples for bundling with [webpack](https://github.com/auth0/lock/tree/master/examples/bundling/webpack) and [browserify](https://github.com/auth0/lock/tree/master/examples/bundling/browserify).

**Comment by ajibs** [comment]
Removing the loaders and upgrading the auth0-lock package from v9 to v11 solved this problem for me.

Thanks @gnandretta @mcrawshaw
