### ISSUE TITLE
Signup terms checkbox overlays password field on small devices.

### ISSUE THREAD

**Issue by darkyen** [auth0/lock#525]
On small screen mobile phones Lock v10's accept signup fields checkbox and the field will overlay the password field. 

##### Minimum code to reproduce 
```javascript
// Try with a smaller vheight screen
var lock = new Auth0Lock(clientID, domain, {
  languageDictionary: {
    signUpTerms: "I agree to the <a href='/terms' target='_new'>terms of service</a> and <a href='/privacy' target='_new'>privacy policy</a>."
  },
  mustAcceptTerms: true
});

lock.show();
```

##### Screenshot

<img width="371" alt="screen shot 2016-08-03 at 12 06 55 am" src="https://cloud.githubusercontent.com/assets/1041315/17340617/99edc87e-590e-11e6-80a4-13b1727c1ed6.png">

**Comment by hzalaz** [comment]
Reproducible in v10.0.1
