### ISSUE TITLE
Registration (win8/ win7 + IE 10) - Typing in email field doesn't work 

### ISSUE THREAD

**Issue by leilafi** [auth0/lock#531]
Typing in email field doesn't work on wind8 and IE (tested on IE10). We are using lock v10.

Email input on the sample page does not work with IE10 either.
https://auth0.com/docs/libraries/lock

**Comment by gnandretta** [comment]
Hi, this has been fixed in #537 and published in version `10.0.2`. Thanks for the reporting it.

**Comment by leilafi** [comment]
Thanks Gabriel!
