### ISSUE TITLE
Custom connections should show up

### ISSUE THREAD

**Issue by runes83** [auth0/lock#544]
Custom connections should show up, instead of having to add them in code. 
This makes it simpler to add/disable connections without changing the application.

**Comment by runes83** [comment]
If you only want to use the custom connections you can't because it have to have one other before adding new ones.

**Comment by gnandretta** [comment]
We should provide a way to customize the color of the button, the connection label and the icon. By default  we can use the `primaryColor`, the connection name, and the auth0 badge.

**Comment by gnandretta** [comment]
Related to #542

**Comment by glena** [comment]
Custom oauth2 connections are supported in the latest release
