### ISSUE TITLE
Option to hide social buttons

### ISSUE THREAD

**Issue by TranquilMarmot** [auth0/lock#559]
Right now you can pass in an option to set `socialButtonStyle` to either `big` or `small`

It would also be nice to be able to pass in an option of `none`. We have some spots in our application where we want them to show up, and others where we don't, so it would be nice to have an option (hiding them with CSS isn't too bad, but an option would be better!)

**Comment by gnandretta** [comment]
Hi, you can use the `allowedConnections` option for that. You'll have to provide the names for the connections that are not social.
