### ISSUE TITLE
Initial Screen does not appear to work

### ISSUE THREAD

**Issue by gregorskii** [auth0/lock#579]
Hi there,

Hopefully this is simple. But I am finding that when using a VueJS implementation of the login similar to the example provided, the initialScreen option of the Lock is not working.

I am using Chrome 52.0.2743.116 (64-bit) on Mac OSX 10.11.6. VueJS version 1.0.26.

I am using VueRouter 0.7.13, compiling the code with Webpack 1.13.1 and using vue-loader 8.2.2.

**Code Snippets:**

I am defining the Lock Object in a config file:

```
const lockConfig = {
  theme: {
    logo: '/images/acustomimage.png',
    primaryColor: '#fe9297'
  },
  languageDictionary: {
    emailInputPlaceholder: 'you@example.com',
    passwordInputPlaceholder: 'password',
    title: 'App Name'
  }
};

const authZeroClientId = document.querySelector("meta[name='authZeroClient']").getAttribute('content');
const authZeroDomain = document.querySelector("meta[name='authZeroDomain']").getAttribute('content');

export const lock = new Auth0Lock(authZeroClientId, authZeroDomain, lockConfig);

export const checkAuth = () => {
  return !!localStorage.getItem('id_token');
};
```

Where the authZeroClientId and authZeroDomain are provided by the Express server when rendering the page as meta props.

The main app defines the Auth0 Handlers:

```
<template>
  <section id="container" container>
    <Navigation :theme="navTheme" :lock="lock" :authenticated="authenticated"></Navigation>
    <section id="content">
      <router-view></router-view>
    </section>
    <Foot></Foot>
  </section>
</template>

<script type="text/babel">
  import * as Auth from './config/auth';
  import Navigation from './components/navigation.vue';
  import Foot from './components/footer.vue';

  export default {
    data() {
      return {
        navTheme: 'dark',
        authenticated: false,
        lock: Auth.lock
      };
    },
    components: {
      Navigation,
      Foot
    },
    events: {
      'change-navigation-theme': function(theme) {
        this.navTheme = theme;
      },
      'logout': function() {
        this.logout();
      }
    },
    ready() {
      var self = this;
      this.authenticated = Auth.checkAuth();
      this.lock.on('authenticated', function(authResult) {
        self.lock.getProfile(authResult.idToken, function(error, profile) {
          if (error) {
            // TODO: Handle error
            return;
          }

          localStorage.setItem('id_token', authResult.idToken);
          localStorage.setItem('profile', JSON.stringify(profile));
          self.authenticated = true;
          self.lock.hide();
        });
      });

      // TODO: temp test to make sure API is working
      this.$http.get(this.$http.options.root).then((res) => {
        console.log(res);
      }, (err) => {
        console.error(err);
      });
    },
    methods: {
      logout() {
        var self = this;
        localStorage.removeItem('id_token');
        localStorage.removeItem('profile');
        self.authenticated = false;
        self.$route.router.go('/');
      }
    }
  };
</script>

<style lang="sass">

</style>
```

And a Navigation component is triggering the lock:

```
<script type="text/babel">
  export default {
    ready: function() { },
    props: ['theme', 'lock', 'authenticated'],
    methods: {
      login() {
        this.lock.show({
          initialScreen: 'login'
        });
      },
      logout() {
        this.$dispatch('logout');
      },
      signup() {
        console.log('signup?!');
        this.lock.show({
          initialScreen: 'signUp'
        });
      }
    }
  };
</script>
```

Relevant part of the template:

```
      <ul class="navigation__links navigation__links--right">
        <li class="navigation__link"><a @click="signup()" v-show="!authenticated">Sign Up</a></li>
        <li class="navigation__link"><a @click="login()" v-show="!authenticated">Log In</a></li>
        <li class="navigation__link"><a v-link="{ path: '/account' }" v-show="authenticated">Account</a></li>
        <li class="navigation__link"><a @click="logout()" v-show="authenticated">Log Out</a></li>
      </ul>
```

The lines:

```
this.lock.show({
  initialScreen: 'signUp'
});
```

Are not properly opening the lock widget on the signup tab, it always opens on the login tab.

Please let me know if any additional information is needed.

Thanks!

**Comment by woloski** [comment]
Quick question: does this work with plain lock? i.e. from the sample downloaded from the quickstart.

If you still have issues, then open a support ticket at support.auth0.com so we can properly prioritize it.

**Comment by gregorskii** [comment]
No it does not appear to work on https://auth0.com/docs/quickstart/spa/vuejs either.

I made these edits:

![screenshot 2016-08-30 13 15 05](https://cloud.githubusercontent.com/assets/1130448/18105329/dc4cd2a4-6eb3-11e6-8f57-0c942cfe24b9.png)

Will add a support ticket referencing this issue URL.

Thanks

**Comment by cristiandouce** [comment]
@gregorskii Apparently the download seed was using **Lock v9** which ofc does not support that `initialScreen` property. We have updated the seed to use **Lock v10** instead. Could you try again?

I was able to download the seed and set the `initialScreen: 'signUp'` without any problems.

![image](https://cloud.githubusercontent.com/assets/367429/18134998/b8f920b4-6f76-11e6-9677-e741f5438581.png)

**Comment by gregorskii** [comment]
This is resolved by using the most recent version of the lock script:

```
<script src="http://cdn.auth0.com/js/lock/10.2.1/lock.min.js"></script>
```

Per support the auth0 team is going to update the auto generated projects and the docs to detail this.

Thanks!

**Comment by JordashTalon** [comment]
Using:

`<script src="https://cdn.auth0.com/js/lock/10.9.1/lock.min.js"></script>`

And it's not working with this code:

`lock.show({initalScreen:'signUp'});`

It always goes straight to the login page.

Any ideas?

**Comment by devpascoe** [comment]
Same @JordashTalon did you resolve this one?

**Comment by ratebeerjoet** [comment]
@JordashTalon @devpascoe the issue with that implementation is a spelling error. Use:

`lock.show({initialScreen:'signUp'});`

I noticed the misspelling, corrected it, and now everything is fine, at least for me. Good luck!
