### ISSUE TITLE
[v10] Propagate signup errors from rules to lock widget

### ISSUE THREAD

**Issue by colllin** [auth0/lock#580]
Lock Version: v10.0
See https://auth0.com/forum/t/propagate-signup-errors-from-rules-to-lock-widget-v10/3108

**Comment by hzalaz** [comment]
Can you provide any more details like what error you see? how the rule returns the error or is it the a custom db script?

**Comment by colllin** [comment]
It's a rule returning an error using the callback. It worked great on v9. The error message displayed in the lock dialog. What other details would be helpful?

**Comment by rashfael** [comment]
Having the same problem.

I throw a `UnauthorizedError` in a rule.
In popup mode the error message gets rendered, but not in redirect mode.

Both the `hash_parsed` and `authorization_error` events get triggered with the error message, but the error never gets displayed.

**Comment by hzalaz** [comment]
Closing this one. 

It works for rules if the error is `UnauthorizedError` and lock will display that one. If the error returned from the rule is another one, e.g. `Error` it won't be displayed by Lock.

Errors raised in the custom db scripts, in this case signup, are not handled yet by Lock but it's in our backlog.

**Comment by rashfael** [comment]
I throw an UnauthorizedError, and it gets displayed, but only in *popup mode*, not in *redirect mode*.
Even the events get emitted, but the error is not displayed.

**Comment by colllin** [comment]
@hzalaz Did you see this latest comment?  Sounds like it should be reopened.

**Comment by hzalaz** [comment]
Yes, but is more related to #639 since for redirect lock is not displayed when you are redirected back to your site,  Lock does not store any auth result by itself, so you have to either show an error page of your choosing or open Lock with a flash message.
