### ISSUE TITLE
[v10] Email verification redirect not captured, no message

### ISSUE THREAD

**Issue by colllin** [auth0/lock#581]
When I set the verification email to redirect to our callback URL (which would be AWESOME, if it worked), the Lock dialog doesn't seem to know what's going on, and no message is displayed to the user indicating that the verification was successful or what to do next.  You're left staring at a login dialog wondering what you were doing a second ago.

**My settings:**
![image](https://cloud.githubusercontent.com/assets/185923/17939660/dacb5a6a-69e8-11e6-8698-36964a437778.png)

> Weird, the help text is different the first time I load that page. I only see the `@@application.callback_domain@@` instructions if I click to the Liquid template and back.

**Example of the URL I get redirected to after clicking verification link:**

```
/login?email=collin%2Bst1%40tomnod.com&message=Your+email+was+verified.+You+can+continue+using+the+application.&success=true&supportForgotPassword=false&supportSignUp=false
```

**Comment by hzalaz** [comment]
Lock now allows to specify a `flashMessage` using [`ui` options](https://github.com/auth0/lock#ui-options).

**Comment by colllin** [comment]
So do we need to capture the error using the lock events, and then set the flash message?
