### ISSUE TITLE
With RC5 the authenticated event is not received

### ISSUE THREAD

**Issue by ckapilla** [auth0/lock#584]
PR #585 fixes the issue that Lock does not work with Angular 2 RC5. It is a simple one line change. I'm unable to release the latest version of my site because of this error; is there something that is preventing the PR from being merged into a new release?

**Comment by hzalaz** [comment]
@ckapilla I believe you mentioned #583 right?. We are testing it in non-angular environment to avoid breaking other people and we'll release it asap.

**Comment by paulSambolin** [comment]
+1 for this merge.  We made the same change to a local copy of the code but are unable to properly   import/require it in angular (newbies)

**Comment by ckapilla** [comment]
yes #583, sorry about that. Thanks for your response; waiting with bated breath!

**Comment by ckapilla** [comment]
10.2.1 has been released and fixes the problem. Thanks to everyone who worked on this!
