### ISSUE TITLE
[v10] Allow opening external signup/reset links in new window

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#586]
Some customer's use cases require that links provided in `forgotPasswordLink` and `signUpLink` are opened in a separate window. This was achievable in v9 by dynamically adding a `target="_blank"` attribute to the links. 
An explicit option to achieve this would be needed in v10.

**Comment by oliviervaillancourt** [comment]
Hi guys,

@nicosabena is right and this request hails from the team I work on.  This is something that would be really useful to have.

Let me know if you need details.

**Comment by hzalaz** [comment]
@oliviervaillancourt we understand, it might be odd for the signup tab to open a new tab but we'll see what we can do

**Comment by oliviervaillancourt** [comment]
hey @hzalaz,

I understand.  And actually in my case the majority of the application flows would open both `forgotPasswordLink` and `signuplink` in the same browser tab.  Only 1 or 2 special workflow would need to open in a new tab.

As a suggestion, you could accept an either string a an object on these properties.  Something like `{url:'asdf', 'openInNewTab':true}`

Thanks

**Comment by rmiroballi** [comment]
I agree with @oliviervaillancourt, our flows will want the signup and forgot password to open in the same tab. For a signup, a return URL might be useful for some:

`{url: 'asdf', 'openInNewTab': false, returnUrl: 'asdf2'} `

Our flow requires the user to have a verified email before login.

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉

**Comment by bohdanbirdie** [comment]
+1 here
