### ISSUE TITLE
[Angular2 RC5] TS Auth0Lock is not defined

### ISSUE THREAD

**Issue by merrickfox** [auth0/lock#588]
Hi, I'm completely lost here and somewhat new to ng2 and typescript.

I've used the ng2 CLI (latest beta version creates RC5 project) to create a scaffold, I've lifted the auth service from the repo https://github.com/auth0/auth0-angular2 same as this tutorial: https://auth0.com/docs/quickstart/spa/angular2/01-login 

My auth service
```
import { Injectable, NgZone } from '@angular/core';
import { Router, CanActivate } from '@angular/router';
import { tokenNotExpired } from 'angular2-jwt';

// Avoid name not found warnings
declare var Auth0Lock: any;

@Injectable()
export class Auth {
  lock = new Auth0Lock('wn8VNyDDuEHIioxZCL0eG2evRnpAM32L', 'workremoteio.eu.auth0.com');
  refreshSubscription: any;
  user: Object;
  zoneImpl: NgZone;

  constructor(zone: NgZone, private router: Router) {
    this.zoneImpl = zone;
    this.user = JSON.parse(localStorage.getItem('profile'));
  }

  public authenticated() {
    // Check if there's an unexpired JWT
    return tokenNotExpired();
  }

  public login() {
    // Show the Auth0 Lock widget
    this.lock.show({}, (err, profile, token) => {
      if (err) {
        alert(err);
        return;
      }
      // If authentication is successful, save the items
      // in local storage
      localStorage.setItem('profile', JSON.stringify(profile));
      localStorage.setItem('id_token', token);
      this.zoneImpl.run(() => this.user = profile);
    });
  }

  public logout() {
    localStorage.removeItem('profile');
    localStorage.removeItem('id_token');
    this.zoneImpl.run(() => this.user = null);
    this.router.navigate(['/home']);
  }
}

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private router:Router) {
  }

  canActivate() {
    if (tokenNotExpired()) {
      return true;
    }

    this.router.navigate(['/home']);
    return false;
  }
}
```

And the login component
```
import { Component, OnInit } from '@angular/core';
import { Auth } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: 'login.component.html',
  styleUrls: ['login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private auth: Auth) { }

  ngOnInit() {
  }

}
```

And infact the entire project is here: https://github.com/merrickfox/angular2-auth0

the error:
```
zone.js:461Unhandled Promise rejection: EXCEPTION: Error in ./LoginComponent class LoginComponent_Host - inline template:0:0
ORIGINAL EXCEPTION: ReferenceError: Auth0Lock is not defined
ORIGINAL STACKTRACE:
ReferenceError: Auth0Lock is not defined
    at new Auth (http://localhost:4200/main.bundle.js:51254:25)
```

I've read some issues regarding this/similar here https://github.com/auth0/lock/issues/521 but nothing I try there seems to help.

If anyone could help take a look at my repo I would be really greatful

**Comment by chenkie** [comment]
hey @merrickfox, it looks like you've come across an old sample. We're actually migrating to a new org for our samples and you can find the Angular 2 stuff here: https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample

The auth services there have been updated to reflect Lock 10.

**Comment by merrickfox** [comment]
@chenkie Thanks for the reply, I will try and use this implementation in my RC5 project tomorrow, from a quick look I can see the lock lib is loaded via a script tag in the head tag rather than imported through a module, perhaps you can educate me a little, is this the best way to use the library in the project? Is this why I'm having problems currently?

Thanks again.

**Comment by chenkie** [comment]
Ultimately it's probably best to load via npm and bundle with your project, but it's up to you. We're also just about to cut a new release of Lock that solves an issue that has been experienced in Angular 2 RC5 with Lock. Look for v10.2.2, but use the code from Github directly if you need it right away.

**Comment by ckapilla** [comment]
@chenkie, while waiting for the 10.2.2 release, I tried doing the build from Github today, but my page does not load correctly even though the Token parsing issue has been solved. I don't have any more information -- there are no errors shown in the console, the page just doesn't load completely. With the 10.2.2 release coming soon ***hopefully*** I decided to wait for that rather than try to debug the issue, since I don't know where to begin. I know this isn't very helpful information, but wanted to bring it up in case @merrickfox encounters the same problem.

**Comment by amirma** [comment]
@merrickfox In case @ckapilla 's comment is not clear and to save you debug time, it's https://github.com/auth0/lock/issues/584
that's being referred to. The current release of 10.2.1 does not work with Angular 2 RC5.

**Comment by merrickfox** [comment]
@ckapilla @amirma thanks for the heads up on that one, I'll keep an eye out for that.

@chenkie simply adding the script tag has fixed the issue, although I would like to know why it's not recognised from npm/typings if possible, it's driving me nuts 😄

**Comment by ckapilla** [comment]
10.2.2 has been released and fixes the problem I had encountered so you should be able to use it in your script tag now.

**Comment by wieseknows** [comment]
Had the same problem.
Solved by pasting 
`<script src="https://cdn.auth0.com/js/lock/10.8/lock.min.js"></script>`
in index.html

**Comment by onursteknik** [comment]
@wieseknows  Thank you bro. I solved with your answer.

**Comment by DanielD** [comment]
That doesn't work in ASP.NET Core 2.0 with page prerendering.
