### ISSUE TITLE
Do not automatically inject styles

### ISSUE THREAD

**Issue by ianks** [auth0/lock#600]
When requiring Auth0Lock, styles are automatically appended to the DOM with no real way of opting out. I propose making stylesheet's loading be opt-in; by making the user include the CSS specifically. This avoids any confusion and prevents stange loading order errors that can occur with webpack users/etc.

https://github.com/auth0/lock/blob/456b0d8aded05c204b7f9683f730ea3c8cd5357a/src/index.js#L9,L21

For all of those who want a workaround to control load order of CSS:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>AdHawk: Web Dashboard</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="icon" type="/image/png" href="/favicon.png">

  <!-- FIXME: Hack to ensure that Auth0 CSS is loaded first -->
  <style id="auth0-lock-style" type="text/css"></style>

  <link rel="stylesheet" type="text/css" href="/assets/vendor.css">
  <link rel="stylesheet" type="text/css" href="/assets/app.css">
</head>
<body>
  <div id="app"></div>

  <script type="text/javascript" src="/assets/vendor.js"></script>
  <script type="text/javascript" src="/assets/app.js"></script>
</body>
</html>
```

**Comment by luisrudge** [comment]
We're actively investigating how to do multiple types of builds in a way that would accommodate anyone wanting to use the js bundle with and without the css styles. It's still a WIP and might not be merged, but we'll see what we can do to improve this scenario.
