### ISSUE TITLE
Missing documentation for embed mode

### ISSUE THREAD

**Issue by chrisvfritz** [auth0/lock#602]
On [the Lock marketing page](https://auth0.com/lock), an __Embed__ mode is advertised. When clicking on the link for an example, it leads to a non-existant `#overlay-mode` section in the README. Is the embed mode deprecated, not yet released, not documented, or just difficult to find?

**Comment by hzalaz** [comment]
@chrisvfritz thanks for reporting this, we missed those links and we'll fixed them. 
Searching the docs site, the missing doc about embed mode for v9 is here https://auth0.com/docs/libraries/lock/v9/display-modes#embedded-mode.
For our latest release (v10) we are still wrapping up the docs but the `container` option is available, check the following link to the README https://github.com/auth0/lock#ui-options.

**Comment by chrisvfritz** [comment]
@hzalaz Thanks!
