### ISSUE TITLE
V10 - User signUp error messages

### ISSUE THREAD

**Issue by bkniffler** [auth0/lock#603]
V10 doesn't seem to pick up messages for the different errors on signup (user_exists, ...), instead there is the generic `signUp.lock.fallback`.
It seems like [connection/database/actions.js](https://github.com/auth0/lock/blob/f24075224cde45f24a98ef3482972042f2a53769/src/connection/database/actions.js#L108) is lacking `user_exists`, `username_exists` and `invalid_password`.

Here is an example fix that works for me
```javascript
function signUpError(id, error) {
  const m = read(getEntity, "lock", id);

  const invalidPasswordKeys = {
    PasswordDictionaryError: "password_dictionary_error",
    PasswordNoUserInfoError: "password_no_user_info_error",
    PasswordStrengthError: "password_strength_error"
  };

  /* Old: Missing user_exists
   const errorKey = (error.code === "invalid_password"
    && invalidPasswordKeys[error.details.name])
    || error.code;
  */

  // Fixed user_exists
  let errorKey = error.code;
  if (error.code === "invalid_password" && invalidPasswordKeys[error.details.name]) {
    errorKey = invalidPasswordKeys[error.details.name];
  } else if (error.message === 'the user already exists') {
    errorKey = 'user_exists';
  }
  // end fix

  const errorMessage = i18n.str(m, ["error", "signUp", errorKey])
    || i18n.str(m, ["error", "signUp", "lock.fallback"]);

  swap(updateEntity, "lock", id, l.setSubmitting, false, errorMessage);
}
```

**Comment by hzalaz** [comment]
For `invalid_password`,  Lock should validate the password before making a request using the configured pwd policy so the error won't show up at all. (please provide us an example where it shows).

For the other two, we are evaluating if we add them in the future.

**Comment by bkniffler** [comment]
I hope you meant "how" instead of "if" :) not giving the user a clue wether it's a server error or input error doesn't provide a great experience.

The `invalid_password` didn't show up for me, I just saw it's not handled inside the mentioned `signUpError` function.

**Comment by AlexanderKozhevin** [comment]
Confirmed. I'm having the same issue.

**Comment by glena** [comment]
Cant repro, it is handling the errors correctly.

![image](https://cloud.githubusercontent.com/assets/5647310/19364971/e2c42fd0-9166-11e6-80e6-b87b07745add.png)
![image](https://cloud.githubusercontent.com/assets/5647310/19364974/e5d7cbbe-9166-11e6-958a-d2c8f9dbec80.png)
![image](https://cloud.githubusercontent.com/assets/5647310/19364979/eba7f3f2-9166-11e6-8c01-7c266e80706d.png)

Can you confirm @bkniffler @AlexanderKozhevin? Pleas try with the latest release (`10.4`).

**Comment by Jamesoncy** [comment]
not working on my end

**Comment by rcbdev** [comment]
This was broken by the below update. It removed the use of the code from the server and now only handles specific invalid password cases.

https://github.com/auth0/lock/commit/03fe1477945e9915534d51089ea61bcbbfa7dd96#diff-d9f03349fa2ff0e9d94c424f828564c7
