### ISSUE TITLE
French language not available

### ISSUE THREAD

**Issue by lehoule** [auth0/lock#610]
- Lock 10.2.2
- Chrome on Windows 7

The French language does not seem to be available from your server.

Here's my config :
`
lockProvider.init({
    domain: 'xxx'
    clientID: 'xxx',
    options: {
    language: 'fr'...
`

What I get in the console : 
![image](https://cloud.githubusercontent.com/assets/610052/18595370/6782b38c-7c12-11e6-87e0-a7ab614bbc48.png)

![image](https://cloud.githubusercontent.com/assets/610052/18595386/7e911eba-7c12-11e6-8392-246b59da04ee.png)

**Comment by hzalaz** [comment]
@lehoule we recently merged this and haven't released it yet. It will be out next week (we hope midweek)
