### ISSUE TITLE
lock.$auth0 deprecated in v10?

### ISSUE THREAD

**Issue by dinvlad** [auth0/lock#615]
I'm trying to follow the official example to enable SSO for a SPA (https://auth0.com/docs/sso/single-page-apps-sso), however when it comes to calling
```
lock.$auth0.getSSOData(...)
```
it complains with
```
Uncaught TypeError: Cannot read property 'getSSOData' of undefined
```
Does that mean the $auth0 reference has been deprecated in v10? More specifically, I'm using 10.2.2.

If it is, should I construct
```
var auth0 = new Auth0(...)
```
instead?

Thanks

**Comment by dinvlad** [comment]
I see, the migration guide does mention that:
https://auth0.com/docs/libraries/lock/v10/migration-guide
> The getClient method and the $auth0 property are no longer available. You can, instead, simply instantiate Auth0 when using functionality from auth0.js. If you need help with how to do this, see the Using Lock with auth0js page.

**Comment by dinvlad** [comment]
My only other comment is that importing `auth0.js` explicitly is not necessary in this case, since `lock.min.js` already provides the `Auth0` object.

**Comment by hzalaz** [comment]
Yes, the docs says that the import is only required if you included the file from cdn/bower

> If you included the script from the Auth0 CDN or installed Lock from bower, you only need to instantiate the Auth0 object to use it with Lock (see below).
>
> If you installed Lock from npm, you must include auth0-js in your project dependencies and import it. Before instantiating the Auth0 object, you will need to require auth0-js:

**Comment by hzalaz** [comment]
Will ask to rewrite it to make it more explicit when is required and when is not
