### ISSUE TITLE
Please add signInTerms to match signUpTerms

### ISSUE THREAD

**Issue by ritdaw** [auth0/lock#620]
Hi,

Love the new signUpTerms feature but it would be great if we could have the same function for signing in i.e.

```
languageDictionary: {
    title: "My App"
    signInTerms: "By logging in, I agree to the <a href='' target='_new'>terms of use</a>."
}
```

**Comment by hzalaz** [comment]
Terms were only meant for signup and we won't display the label also for login since we consider it to be enough for most cases. Added this to our nice to have features to review later.

**Comment by ritdaw** [comment]
Ah but what if someone is logging in "with Google"   for the first time but this also signs them up? Need to cover all basis.
