### ISSUE TITLE
Authenticated event not fired for Webpack, Vue, Vue-Router

### ISSUE THREAD

**Issue by Uptown76** [auth0/lock#622]
I can not get the authenticated event to fire when using Webpack 1.13.2, Vue 1.0.26, Vue-Router 0.7.13 and Auth0-lock 10.3.0. Other's have had similar issues. The sample code provided by Auth0 also does not work. The only code that works is from https://github.com/auth0/auth0-vue.

Below is a sample project that I am using. The source code is under the src directory. If you could please add a client id and domain to src/components/home.vue on line 20 to test.

https://github.com/Uptown76/Auth0VueWebpack

npm install
npm run dev

Thanks

**Comment by Uptown76** [comment]
It seems to be working when I remove hashbangs from vue-router via the `history: true` option in the vue-router initialisation. I suspect vue-router is having difficulties routing when there are two hashes in the url. I also had this issue when creating a custom login UI with Auth0-JS. Removing the hashbangs also fixed this issue.

However, not sure why https://github.com/auth0/auth0-vue, which also uses vue-router with hashbangs, works.

**Comment by rashfael** [comment]
One key difference between auth0-vue and your code is the `router.redirect`.
I guess the vue-router just throws out all unknown hashes then.
We had a similar problem, not just with vue, but also with polymer. It's probably the same for all router libraries that assume they "own" the location (which is a reasonable assumption).

My solution for vue-router was to initialize auth0 first, wait for the `hash_parsed` event (and check localStorage for a token) and then starting the router.

**Comment by Uptown76** [comment]
Thanks @rashfael, I'll give it a go.

**Comment by cristiandouce** [comment]
Please follow the discussion at auth0/auth0-vue/issues/12

**Comment by jsoncorwin** [comment]
@Uptown76 posted a resolution for this introduced in a later version of Auth0-lock. Comment is over in auth0/auth0-vue#12
