### ISSUE TITLE
Allow to change JWT algorithm 

### ISSUE THREAD

**Issue by jirikolarik** [auth0/lock#623]
Hi, I'm trying to get Auth-lock work with Horizon.io (more informations about that is on their github page) and I've found that auth-lock and Horizon.io use different algorithm. `HS256` is used here and `HS512` on horizon.io.

Would it be possible, to allow to change algorithm optionally?

- Code snippet: https://github.com/rethinkdb/horizon/issues/840
- Lock version: 10.2.0

**Comment by hzalaz** [comment]
@jirikolarik this is something that's outside what Lock does since the alg is used in the server to sign the tokens, Lock does not use it. Please contact support via https://support.auth0.com.
