### ISSUE TITLE
Single AD connection without domain shows undefined in message

### ISSUE THREAD

**Issue by hzalaz** [auth0/lock#627]
When the client only allows a single AD connection, Lock will display the form for username/password with the title `Please enter your coorporate credentials at {domain}`. We need to avoid showing the `undefined` by changing the message or hiding for this specific case

**Comment by jasonhjohnson** [comment]
+1

**Comment by sykesjd** [comment]
The fix in the linked PR does not actually fully fix the issue - it only checks for `null` domain and not `undefined` domain, so the issue as originally described still occurs.
