### ISSUE TITLE
css customization

### ISSUE THREAD

**Issue by jensoleg** [auth0/lock#63]
HI guys
 I want to customize the widget and have created a style sheet file which I include in the html header but  auth0 lock injects its styles at the end of the header and seems to over rule my custom css. Any hints how to solve this ?

**Comment by failpunk** [comment]
Is there any plans to have a simple theme?  The default lock theme is very dated and actually converts poorly when tested for signup conversion.

**Comment by luisrudge** [comment]
@failpunk the widget follows our design guidelines and there are no plans to change it at the moment.
