### ISSUE TITLE
build.js is excluded from this project

### ISSUE THREAD

**Issue by mikemichaelis** [auth0/lock#630]
Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [ ] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [ ] Lock version
- [ ] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by hzalaz** [comment]
@mikemichaelis care to elaborate a little more? the title provides little info
