### ISSUE TITLE
Using this with SystemJS

### ISSUE THREAD

**Issue by georgeedwards** [auth0/lock#633]
I want to use this with angular2, using SystemJS - as is by far the most common module loader for Angular2. So I followed the [quickstart guide](https://auth0.com/docs/quickstart/spa/angular2) which recommends using either the CDN or npm. The CDN sort of works, the issue is that I reference Auth-lock in my component's constructor, so if I navigate straight there, Auth0Lock is undefined, as the CDN link hasn't loaded yet. If I use `npm install --save auth0-lock`, then I end up with loads of bundling errors, as my system.config needs repeated dependencies of the auth0-lock package defined. I really need a bundled version on npm ... 

Currently using v10.4

**Comment by glena** [comment]
I guess you need to properly load Lock. Since you are loading it async, you should wait for it to complete. 

In this case 
```
SystemJS.import('...').then(function(m) {
  // Use lock
});
```

An example on how are you loading it might be useful to understand how are you building it.

**Comment by hzalaz** [comment]
Closing this one, please reopen if the issue still persists with more information on how you are building Lock or a sample project we can debug

**Comment by geminiyellow** [comment]
need more info. i try it in `auth0-samples/auth0-angularjs2-systemjs-sample` but fail.

**Comment by geminiyellow** [comment]
@hzalaz need more info. i try it in `auth0-samples/auth0-angularjs2-systemjs-sample` but fail.
