### ISSUE TITLE
auth0-lock 10.4.0 import errors

### ISSUE THREAD

**Issue by marcelorl** [auth0/lock#634]
I'm getting these errors when I just import auth0-lock like this:

`import Auth0Lock from 'auth0-lock'`

```
ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'net' in '/Users/marcelorizzardo/Development/projects/personal/Deliverer/react-boilerplate/node_modules/debug'
 @ ./~/debug/node.js 170:16-30
 @ ./~/auth0-js/~/jsonp/index.js
 @ ./~/auth0-js/index.js
 @ ./~/auth0-lock/lib/index.js
 @ ./app/utils/auth/AuthService.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main
```

```
ERROR in ./~/debug/node.js
Module not found: Error: Can't resolve 'fs' in '/Users/marcelorizzardo/Development/projects/personal/Deliverer/react-boilerplate/node_modules/debug'
 @ ./~/debug/node.js 163:15-28
 @ ./~/auth0-js/~/jsonp/index.js
 @ ./~/auth0-js/index.js
 @ ./~/auth0-lock/lib/index.js
 @ ./app/utils/auth/AuthService.js
 @ ./app/routes.js
 @ ./app/app.js
 @ multi main

```

Any clue?

Thanks.

**Comment by jashmenn** [comment]
@marcelorl You can get rid of this particular error by adding the following to your webpack file e.g. `webpack.base.babel.js`:

```javascript
  node: {
    fs: 'empty',
    net: 'empty'
  },
```

That said, I'm also using `react-boilerplate` and I'm also having trouble getting webpack to run when importing the `auth0-lock` library. See: https://github.com/mxstbr/react-boilerplate/issues/1042

**Comment by jashmenn** [comment]
As I mentioned [over here](https://github.com/mxstbr/react-boilerplate/issues/1042#issuecomment-254912011), I fixed this issue by adding `'browser'` to the `mainFields` array in my webpack config. Hope this helps!
