### ISSUE TITLE
additionalSignUpFields name with spaces prevents options to be loaded

### ISSUE THREAD

**Issue by kandros** [auth0/lock#635]
is case i use a string with spaces inside the name field the whole options are not recognised and used

```
    additionalSignUpFields: [{
        type: "select",
        name: "register as",
        placeholder: "Artist or venue owner",
        options: [
            {value: "artist", label: "Artist"},
            {value: "venue_owner", label: "Venue owned"},
        ]
    }]

```

`    "auth0-lock": "^10.4.0",`

**Comment by cristiandouce** [comment]
Attributes with spaces are considered invalid for Lock. We don't plan to support it in the short term. Please try to avoid spaces for name attributes.
