### ISSUE TITLE
[feature request] radio as alternative to select for additionalSignUpFields

### ISSUE THREAD

**Issue by kandros** [auth0/lock#636]
it would be great to have radio buttons as an alternative to select for additionalSignUpFields

**Comment by luisrudge** [comment]
- [ ] 
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉
