### ISSUE TITLE
Sometimes when installing via bower, `build` folder is missing

### ISSUE THREAD

**Issue by mgonto** [auth0/lock#64]
Sometimes, when we install `Lock` with Bower the build folder is missing. It has happend to 2 customers. It should work since the `build` folder exists in the tags.

https://app.intercom.io/a/apps/5543b80da436916e2d7fb2a94b5cd014b92f6b86/inbox/conversation/560157951

**Comment by webcaetano** [comment]
@mgonto that explanation helps me.
