### ISSUE TITLE
Specify relative path in redirectUrl

### ISSUE THREAD

**Issue by sedubois** [auth0/lock#656]
[Here](https://github.com/mxstbr/react-boilerplate/pull/1108) is a working code using auth0-lock. Now I intend to add the options below to the `Auth0Lock` constructor (for reasons described [here](https://github.com/auth0/lock/issues/655)):

```
auth: {
  redirectUrl: `<host>/?nextPathname=${nextPathname}`,
  responseType: 'token',
}
```

All I'm interested in, is to come back to the same host as before, but passing a `nextPathname` as query param. However, `redirectUrl` requires a full URL, and I don't know the host in advance (differs between dev, staging and prod).

I could pass this info to this code as environment variables, but it looks like an unnecessary hassle, seeing as Auth0-lock already accepts to omit this host information. Could it add support for passing query params without specifying the host? E.g just `redirectUrl: /?nextPathname=${nextPathname}` or adding an option like `params: { nextPathname }` which could be used instead of `redirectUrl`.

Lock 10.4.0, Chrome 54.0.2840.59 (64-bit), macOS Sierra.

**Comment by glena** [comment]
what about using `window.location`?

Something like `window.location.origin + "/?nextPathname=${nextPathname}"`

**Comment by sedubois** [comment]
Oh yes, silly me. Just forgot! 😊
