### ISSUE TITLE
[v10.4.0] Cannot read property 'get' of undefined. 

### ISSUE THREAD

**Issue by Dimarto** [auth0/lock#658]
Hi,

Was investigating new auth0 lock, but no validation effects are showing. For example when i click "log in" button, the email field does not highlight. I checked the browser console and found out, that every time i try to log in i get an javascript error: "Cannot read property 'get' of undefined"

My auth0 client in auth0 mangement portal has been configured to use only enterprise connections of type: Azure Ad, ADFS and LDAP.

Example can be reproduced on the sample project (ASP.NET) provided by Auth0.

Lock version: 10.4.0
OS: Windows 10 Enteprise 64 bit
Browser/Version: Chrome 53.0.2785.143

Step 1 - click "LOG IN >":
![image](https://cloud.githubusercontent.com/assets/5676955/19559885/93a02b56-96da-11e6-950f-34cc7dcd89f5.png)
Step 1 - alternative with wrong email entered and click "LOG IN >":
![image](https://cloud.githubusercontent.com/assets/5676955/19559927/c98eef36-96da-11e6-96f6-d8ec0c78ff9c.png)

Step 2 - check browser console:
![image](https://cloud.githubusercontent.com/assets/5676955/19559986/20f907e8-96db-11e6-9132-5fe2076492ac.png)
Note: I did not configure CORS on the sample project, because it does not affect the error.

Error stacktrace on unminimized version of lock.js:
Uncaught TypeError: Cannot read property 'get' of undefined
logInActiveFlow	@	lock.js:37100
logIn	@	lock.js:37090
(anonymous function)	@	lock.js:37681
handleSubmit	@	lock.js:42630
invokeGuardedCallback	@	lock.js:25372
executeDispatch	@	lock.js:16989
executeDispatchesInOrder	@	lock.js:17012
executeDispatchesAndRelease	@	lock.js:16444
executeDispatchesAndReleaseTopLevel	@	lock.js:16455
forEachAccumulated	@	lock.js:32323
processEventQueue	@	lock.js:16631
runEventQueueInBatch	@	lock.js:25441
handleTopLevel	@	lock.js:25452
handleTopLevelImpl	@	lock.js:25530
perform	@	lock.js:31578
batchedUpdates	@	lock.js:24646
batchedUpdates	@	lock.js:29279
dispatchEvent	@	lock.js:25607

Help would be appreciated.

**Comment by glena** [comment]
Hi @Dimarto we identified the reason and will be ready on the next release (probably next week).

Thx for reporting

**Comment by Dimarto** [comment]
Thanks for the quick response.

Closing for now.
