### ISSUE TITLE
Hide logo and title

### ISSUE THREAD

**Issue by sedubois** [auth0/lock#659]
Thanks for providing auth0-lock, I've been able to [integrate](https://github.com/mxstbr/react-boilerplate/pull/1108) it in a login flow 😊 

I'm displaying the form inline (using the `container` property), and now for better integration I'd like to get rid of the logo and title which are redundant with the website header as show below. I.e in this current form, only the Facebook button should be visible. How can this be done? I tried things like setting `languageDictionary: { title: null }` and `theme: { logo: null }`, but that didn't help.

Lock version: 10.4.0.

<img width="1247" alt="screen shot 2016-10-20 at 15 56 43" src="https://cloud.githubusercontent.com/assets/4217871/19560609/da75428e-96dd-11e6-85bf-58687a827e59.png">

**Comment by glena** [comment]
you can hide it with CSS if you need.

something like 
```css
.auth0-lock-header{
  display:none;
}
```

should do the trick. Note that the HTML structure and classnames might change in the future (nothing in the backlog but it is a posibility) so have it in mind to check for any mayor relase.

**Comment by sedubois** [comment]
Thanks! I got it working in React-boilerplate with a [`:global`](https://github.com/mxstbr/react-boilerplate/issues/1133#issuecomment-255321674) pseudo selector in front (although I don't know much about CSS and pseudo selectors, it works).

**Comment by ecdeveloper** [comment]
There's one problem with that. If you hide the entire header, then if you click on "Forgot password" - there won't be a "back" button (which is inside the header). Any thoughts on how to fix it?

**Comment by cmddavid** [comment]
@ecdeveloper the logo has a class as well, so you could decide to only hide that using `display: none`
