### ISSUE TITLE
Reduce font size (in kb)

### ISSUE THREAD

**Issue by pose** [auth0/lock#66]
Fonts when gzipping lock minified version take about ~50kb. What can we do to keep using the font but reducing its size?

Some links to research:

* [ ] http://graphicdesign.stackexchange.com/questions/12765/how-to-reduce-the-size-of-a-chinese-ttf-font-file
* [ ] http://stackoverflow.com/questions/2635423/way-to-reduce-size-of-ttf-fonts
* [ ] http://www.labnol.org/internet/reduce-google-fonts-size/21057/

**Comment by crrobinson14** [comment]
Is it really necessary to use custom fonts at all? This seems like something that, if people really wanted a bespoke option, they'd be overriding themselves anyway to match their site. Or at the very least themes could be an optional additional load.

This is like 10% of the entire plugin's compiled size, and it seems so unnecessary. If this was put to a vote, I'd vote to eliminate the whole "zocial" font set entirely and just use something simple, even "sans-serif".

**Comment by hzalaz** [comment]
No longer using custom font for social.
