### ISSUE TITLE
Keyboard does not close after successful login

### ISSUE THREAD

**Issue by klokoy** [auth0/lock#667]
This happens when I use the sample project provided here: https://auth0.com/docs/quickstart/native/ionic2

Lock version: 10.4
I have tried this only on ios 10.

![img_0559](https://cloud.githubusercontent.com/assets/973082/19627122/095b5c00-9940-11e6-8460-e476f76e841f.PNG)

**Comment by luisrudge** [comment]
Hi @klokoy are you still having this issue?

**Comment by luisrudge** [comment]
I just tested this with the latest QuickStart (it uses lock 10.9.1) and it works:

![lock-ionic](https://cloud.githubusercontent.com/assets/941075/22478953/2ada0318-e7d3-11e6-9167-bc399702b5ec.gif)

If you're still having this issue, please reach out so we can reopen the issue.
