### ISSUE TITLE
[v10.5.0] Unknown enterprise connection validation message missing

### ISSUE THREAD

**Issue by Dimarto** [auth0/lock#674]
Hi, 

Auth0 Account configuration - there are multiple enterprise connections of types: Azure Ad, ADFS and LDAP.
Lock version: 10.5.0
OS: Windows 10 Enteprise 64 bit
Browser/Version: Chrome 54.0.2840.71
Example can be reproduced on the sample project (ASP.NET) provided by Auth0.

User tries to connect to an enterprise connection, that has not been added to the connections list (for example "azurecustomad.onmicrosoft.com") and currently there is no indication from Auth0 lock, that the entered domain for the user is incorrect. 
So when user presses "LOG IN >" with username "johnthetester@azurecustomad.onmicrosoft.com", there is no response, that something is wrong.
![image](https://cloud.githubusercontent.com/assets/5676955/19677391/b8042234-9aa1-11e6-8f4e-c04f4a7dd7f6.png)

Not sure if this is bug or feature request. Is it possible to add a validation message "The azurecustomad.onmicrosoft.com domain is not registered in the system", that would clearly state a problem with Auth0 account configuration and it is not users fault?

Help would be appreciated.

**Comment by hzalaz** [comment]
Thanks for reporting. Closed in favor of #661
