### ISSUE TITLE
blocking syntax issues with IE11

### ISSUE THREAD

**Issue by fredoko** [auth0/lock#677]
The file https://cdn.auth0.com/js/lock/10.0/lock.js can't be parsed by IE11 (11.0.12)

I saw at least 2 blocking issues
1- 
Line 11776 to 11780
var defaultRuleset = {
  length:           require('./rules/length'),
  contains:         require('./rules/contains'),
  containsAtLeast:  require('./rules/containsAtLeast'),
  identicalChars:   require('./rules/identicalChars'),
};
The last comma is not accepted by IE11

2 - Line 35068, 35523,35512,...  : For IE11 "default" attribute is unauthorized or i don't know, anyway it doesn't like it.
I don't see how to fix that one, thus I don't know if any other blocking issue remains in this file.

It's not blocking, but I would also note that with a regular javascript editor many syntax problems come up. One in particular, the semi colon is often missed after each instruction.

Regards

**Comment by hzalaz** [comment]
@fredoko can you try with the latest Lock? also can you tell us how you are building lock (a sample project will help)

**Comment by fredoko** [comment]
It works fine with the http://cdn.auth0.com/js/lock/10.5.1/lock.min.js, thanks.
