### ISSUE TITLE
Social providers should be focuseable

### ISSUE THREAD

**Issue by pose** [auth0/lock#68]
Given the following Lock configuration:

```js
    lock.showSignin({
      popup: true,
      responseType: 'token',
      connections: ['google-oauth2', 'twitter']
    }, function (err, _profile, _idToken) {
      ...
    });
```

**What should happen?** As there is no user input focus should be obtained by social providers. Also, if the `rememberLastLogin` option is `true`, it should focus that by default. 
**What happens instead?** Focus remains in the page and is never acquired by Lock. The same happens when `rememberLastLogin` option is `true`.

**Comment by hzalaz** [comment]
Moved to internal backlog
