### ISSUE TITLE
[Lock 10.5.0] "TypeError: next is not a function" when closing social connection popup

### ISSUE THREAD

**Issue by ArnaudD** [auth0/lock#682]
What happens :
  * Uncaught TypeError: next is not a function
![image](https://cloud.githubusercontent.com/assets/40349/19733792/666e3f7c-9ba5-11e6-92a4-d8cdf34d4cdf.png)

  * Lock dialog stay in "loading mode", the user needs to reload the page to try again
![image](https://cloud.githubusercontent.com/assets/40349/19733739/32bd4ad8-9ba5-11e6-937a-7a70c3548caa.png)

Here is the stacktrace 

```
actions.js:205 Uncaught TypeError: next is not a function
    at logInErrorHandler (webpack:///./~/auth0-lock/lib/core/actions.js?:205:12)
    at logInError (webpack:///./~/auth0-lock/lib/core/actions.js?:239:3)
    at eval (webpack:///./~/auth0-lock/lib/core/actions.js?:213:18)
```

This error happens when :
  1. Lock v10.5.0 (from npm) is configured in popup mode
  1. We click on a social provider button in lock
  1. The popup opens
  1. We close the popup manually

Lock is used in a react app, bundled with webpack, here the code we use :

```javascript
const options = {
  auth: {
    params: {
      scope: 'openid email',
    },
    redirect: false,
  },
};

const lock = new Auth0Lock(process.env.AUTH0_CLIENT_ID, process.env.AUTH0_DOMAIN, options);

lock.show();
```

Browser : Chrome 54 - Ubuntu 16.04

**Comment by glena** [comment]
Thx for reporting, it will be fixed with the next release (10.5.1)
