### ISSUE TITLE
Enhancement: support passwordless as connection instead of engine

### ISSUE THREAD

**Issue by gdestuynder** [auth0/lock#689]
As of lock v10.5:

Currently passwordless requires instantiating a new lock using the passwordless engine (I think this is not documented, but its in https://github.com/auth0/lock/tree/master/src/engine and is instanciated like https://github.com/auth0/lock/tree/master/src/index.js)

It would be interesting to make passwordless a connection that can be loaded in the classic engine, so that a user can choose either social, passwordless, enterprise, etc. connections instead of having a to load different locks entirely (either via lock or via lock-passwordless).

**Comment by hzalaz** [comment]
Yes, It's not documented because it's not fully supported yet. 
Handling all the connections in a single engine is something we are considering but we need to figure out how to show the multiple options to the user when you have database and/or enterprise connections with passwordless.

**Comment by awmichel** [comment]
Has there been any progress on this, or a recommended approach for handling password-less + social + database currently?

IMO, doing something similar to Slack's login and splitting the email and password into 2 steps solves this problem. Social logins and a field for the user to enter their email come first. If they enter an email, they are then presented with password-less or a field to enter a password. The only drawback is that logging in requires an extra click from email to password and interrupting password managers. I've attached screenshots of a custom login I'm currently implementing to allow all 3 in the same flow.

<img width="575" alt="screen shot 2017-01-25 at 1 30 53 pm" src="https://cloud.githubusercontent.com/assets/228378/22303736/8e8e30c6-e302-11e6-9346-9a040729e309.png">
<img width="554" alt="screen shot 2017-01-25 at 1 31 02 pm" src="https://cloud.githubusercontent.com/assets/228378/22303735/8e8ac116-e302-11e6-8fe9-af3f89ef4e2a.png">

**Comment by hzalaz** [comment]
@awmichel I'd recommend you use auth0.js to achieve that layout since it will be hard to make lock look like that

**Comment by gdestuynder** [comment]
@awmichel if you're interested in a quick solution, this is what we're using until we rewrite it (as per @hzalaz - it's much cleaner to write the lock for your needs at this point):

https://github.com/mozilla-iam/auth0-deploy/blob/master/pages/login.html

**Comment by awmichel** [comment]
@hzalaz Sorry for the misunderstanding, I have implemented that interface with auth0.js. I was suggesting Auth0 adopt a similar UI for Lock to allow future users to use password-less + social login without having to build a custom login page.

@gdestuynder Thank you for sharing. I hadn't considered that option, but I may adopt something similar.

**Comment by hzalaz** [comment]
@awmichel it's something we are considering doing sometime this year but sadly the only sane way is something like @gdestuynder shared.

**Comment by milenkobeslic** [comment]
@hzalaz what is the status of completing passwordless integration into the lock? Any ETA? 
As far as the design issues (both lock and console), it would make it much simpler if we an choose only one, Database OR Passwordless, but not both at the same time. I would assume that vast majority use cases would use only one, not both at the same time.

**Comment by luisrudge** [comment]
@milenkobeslic we're actively working in adding passwordless support to lock. It's coming. 🎉

**Comment by dinvlad** [comment]
Thanks! Will that allow configuring passwordless + social?

**Comment by luisrudge** [comment]
Yes. Passwordless and everything else that Lock supports.

**Comment by milenkobeslic** [comment]
According to [this](https://github.com/auth0/lock/pull/1070) pull request it looks like it was planned for v10.20 which was already released. Any ETA?

**Comment by luisrudge** [comment]
Sorry, the milestone was wrongly assigned. There's no ETA on it yet. The code is almost done, but we need a lot of doc updates before releasing it.

**Comment by milenkobeslic** [comment]
It looks like that the examples (browserify and webpack) don't work. The login button is grayed out when using Auth0LockPasswordless and allowedConnections: ["email",...].  

But /support/index.html looks good.

**Comment by luisrudge** [comment]
We'll get there with the examples. I'm focusing on building a new support/index page. Examples will come next.

**Comment by luisrudge** [comment]
this is already supported ootb

**Comment by bdmac** [comment]
@luisrudge am I to understand that somehow Lock now supports passwordless as an option alongside standard database login? If so, how do you enable that and what does it look like? Is it documented somewhere? I don't see it in the changelog. :-/

**Comment by luisrudge** [comment]
@bdmac Well, yes and no. We support Passwordless logins with Lock, but it's not "alongside" database logins, as in, you can't use both at the same time. You have to choose between db+social or passwordless+social.

https://github.com/auth0/lock#new-auth0lockpasswordlessclientid-domain-options

**Comment by bdmac** [comment]
@lucascrespo gotcha thanks. I have a ticket open w/your support but it appears that the default implementation of passwordless + magic link does not properly pass through the `state` we are sending from our application. Using the "code" passwordless method the `state` is passed through to https://github.com/IdentityModel/oidc-client-js.

**Comment by luisrudge** [comment]
@bdmac do you have the ticket number?

**Comment by bdmac** [comment]
48542

**Comment by luisrudge** [comment]
@bdmac Thanks. Looks like we're waiting on a HAR file with the issue. Can you record it and send? I'll cc myself in the ticket.
