### ISSUE TITLE
Social providers should work with keybindings

### ISSUE THREAD

**Issue by pose** [auth0/lock#69]
Given the following Lock configuration:

```js
    lock.showSignin({
      popup: true,
      responseType: 'token',
      connections: ['google-oauth2', 'twitter']
    }, function (err, _profile, _idToken) {
      ...
    });
```

and forcing focus on a social provider:

```js
$('.a0-zocial').focus()
```

**What should happen?** By pressing <kbd>return</kbd> I should be able to pick that provider.
**What happens instead?** Nothing happens.

**Comment by hzalaz** [comment]
Moved to internal backlog
