### ISSUE TITLE
emailInputPlaceholder not working

### ISSUE THREAD

**Issue by bearcattom** [auth0/lock#697]
Hi Auth0 Friends - I'm having trouble w/ emailInputPlaceholder not working for some reason using Lock 10.5.

    <script src="//cdn.auth0.com/js/lock/10.5.0/lock.min.js"></script>
    <script src="//cdn.auth0.com/w2/auth0-7.3.min.js"></script>      

  var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN,
  {
      languageDictionary: { // allows to override dictionary entries
      emailInputPlaceholder: "test@test.com",
      title: "Link with:"
    }
  });

This is on Chrome 54.0.2840.71 (64-bit)

The title attribute IS working...however the email placeholder remains w/ the default "user name/email"

**Comment by glena** [comment]
try with `usernameOrEmailInputPlaceholder`

**Comment by bearcattom** [comment]
@glena - thank you so much!  works 👍
