### ISSUE TITLE
Issues integrating with Next.js

### ISSUE THREAD

**Issue by unicodeveloper** [auth0/lock#698]
All I did was import the `AuthService` helper into my index.js file like so:

```js
import AuthService from '../utils/AuthService'
```

And when I run `yarn run dev`, I get this error below:

<img width="999" alt="screen shot 2016-11-02 at 8 18 35 am" src="https://cloud.githubusercontent.com/assets/2946769/19925367/f55b2a3e-a0ef-11e6-8ab9-3a98694e6bcb.png">

My understanding is that every import you declare gets bundled and served with each page in Next.js.

What might be the issue?

I really need this to work to ensure this article has a complete Auth0 integration [https://auth0.com/blog/building-universal-apps-with-nextjs/#](https://auth0.com/blog/building-universal-apps-with-nextjs/#)

- Lock version 10.5.1
- Mac: Yosemite

**Comment by unicodeveloper** [comment]
@hzalaz Please can you help?

**Comment by glena** [comment]
@unicodeveloper where is the code?

**Comment by glena** [comment]
Lock is a client side library and wont work (at least for now) if you try to server side render it on isomorphic applications.
