### ISSUE TITLE
Auth0-lock with Ionic 2 error

### ISSUE THREAD

**Issue by HendrikGrobler** [auth0/lock#699]
Hi, I'm trying to use Auth0 with Ionic 2 (2.0.0-rc.1), but I get the error: `reqwest.js:15 Uncaught TypeError: Cannot use 'in' operator to search for 'window' in undefined(…)`

I am using `"auth0-lock": "^10.5.1"` and I am importing it as follows in my auth service:
`import Auth0Lock from 'auth0-lock';`

It seems like reqwest (which is dependency of auth0-js) is looking for a browser window when there is none.

Can anyone please assist / advise?

**Comment by chenkie** [comment]
Do you have a standard Ionic setup that comes via the Ionic CLI? If so, things should work ok. Have a look at this sample that imports `Auth0Lock` like you are doing: https://github.com/auth0-samples/auth0-ionic2-samples

**Comment by hzalaz** [comment]
@HendrikGrobler please contact our support team via https://support.auth0.com
