### ISSUE TITLE
Dismiss A0LockSignUpViewController

### ISSUE THREAD

**Issue by frederic-adda** [auth0/lock#702]
Using Lock on iOS:
When signing in, the A0LockViewController has a `closable` property which is very handy to dismiss this view controller.
However, when signing up, the **A0LockSignUpViewController** (instantiated via `A0Lock.sharedLock().newSignUpViewController()` does not have such a property and cannot be dismissed.

Android users have a "back" button to leave the sign up view controller, but iOS users don't.
Could you please add the possibility to dismiss the A0LockSignUpViewController ?

Thanks
Fred

**Comment by hzalaz** [comment]
@frederic-adda we are reworking the iOS lib and that's already in our backlog.

Also this is the Lock for Web repo
