### ISSUE TITLE
getDelegationToken method isn't supported by lock?

### ISSUE THREAD

**Issue by aschip** [auth0/lock#704]
I am using 10.4 version of Lock in an Angular JS SPA.
I have followed the quick start from [here](https://auth0.com/docs/quickstart/spa/angularjs).

We need to implement the delegation token scenario for the SPA to be able to access Asp.net Web API .
But I realised that _getDelegationToken_ method isn't implemented in lock.

Is there a plan to include it? If not, what is the recommended way to get it working by using _auth0-lock_
_angular-lock_ & _angular-jwt_ libraries, as per the quick start?

**Comment by hzalaz** [comment]
@aschip you need to use auth0.js (via [angular-auth0](https://github.com/auth0/angular-auth0))

**Comment by aschip** [comment]
Interesting, `auth0.js` version 8 no longer has `getDelegationToken` method. What's the migration?
