### ISSUE TITLE
Pop-up mode in iOS 8 does not close pop-up window

### ISSUE THREAD

**Issue by hzalaz** [auth0/lock#71]
From [intercom](https://app.intercom.io/a/apps/5543b80da436916e2d7fb2a94b5cd014b92f6b86/inbox/conversation/570318741)

> I’ve been testing using Lock in pop-up mode (which I much prefer because it doesn’t wipe out all the page data with a refresh). It works great in the following:

> Windows 8.1 - IE11, Chrome 38

> Windows 7 - Firefox 16 (old ‘n’ crappy)

> Mac OS X Yosemite - Safari

> Windows Phone 8.1 (also IE11)

> On both the iOS 8.1 simulators and our iPhone (8.0.2) Safari does not close the pop-up window. I’ve tried a few things but no luck. This would impact the user experience since they’d have no idea (usually) that the window is just hiding the original login page. When I close the window manually, I’m able to hit my API with a token so this is really just a UI/UX issue.

**Comment by oskosk** [comment]
I'm still perceiving this issue using [lock 7.4](http://cdn.auth0.com/js/lock-7.4.min.js) on latest Chrome for iOS. How may I report that to the auth0-server maintainers in case it's still an issue?

**Comment by mitya** [comment]
+1 — the popup is not closed on the latest Chrome for iOS.

**Comment by ewelaryba** [comment]
+1 - I've been seeing this same issue for months.

**Comment by will-hancock** [comment]
Is this bug still open? We are experiencing it on a high traffic site and is generating a large quality of Customer Support tickets.

Any info would be greatly appreciated.

**Comment by michaek** [comment]
I'm was seeing this as a current issue for Lock 9.2 in Chrome on iOS, but I updated the installed Chome to version 50, and I am no longer able to reproduce it. Are folks who were seeing this issue able to reproduce with a more recent version of Chrome?

**Comment by okonovalenko** [comment]
+1 can reproduce on Safari iphone 6 SE, the popup does not go away.

**Comment by hzalaz** [comment]
Closing in favor of #214
