### ISSUE TITLE
v10.6.0 not loading correctly

### ISSUE THREAD

**Issue by fkarlsson** [auth0/lock#710]
Latest version of lock, 10.6.0, does not load correctly for me.

Tested in OS X:
* Chrome Version 54.0.2840.87 (64-bit)
* Chrome Canary Version 56.0.2914.0 canary (64-bit)
* Firefox 38.0.1

Auth0Lock is just an empty Object {  }, watch console output in https://plnkr.co/edit/GFlL8QoH0vnsVVonjmqA?p=preview

**Comment by glena** [comment]
yes, we are rebuilding and uploading the new bundle to the cdn

**Comment by fkarlsson** [comment]
I'm using the bower repo, will that be fixed as well?

**Comment by glena** [comment]
yes, both cdn and brower

**Comment by fkarlsson** [comment]
Then I'll leave this for now and try again tomorrow. :)

**Comment by glena** [comment]
@fkarlsson 10.6.1 is out and fixes that issue. Sorry for the trouble
