### ISSUE TITLE
Lock v10 behaves differently on AD connection with and without domains

### ISSUE THREAD

**Issue by nicosabena** [auth0/lock#716]
When using Lock with a client that has both an AD/LDAP connection and a social connection, Lock v10 will display just an email field if the connection has a domain assigned:

![image](https://cloud.githubusercontent.com/assets/5222181/20186238/f314f4da-a74d-11e6-90dd-c53aa99fce45.png)

But will instead show an email/password if no domain is assigned to the AD connection:

![image](https://cloud.githubusercontent.com/assets/5222181/20186289/263a89ce-a74e-11e6-88bf-4b938850daf9.png)

In both cases, since it is only one enterprise connection it should probably just ask for username/password as described in https://github.com/auth0/lock/issues/712, but I wanted to document this behavior too in case in needs to be corrected.

**Comment by luisrudge** [comment]
Hi! I'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
