### ISSUE TITLE
looks like lock interprets window object as undefined

### ISSUE THREAD

**Issue by dagman** [auth0/lock#718]
i am trying to add `auth0` functionality to **existing project** and using [this tutorial]( https://auth0.com/docs/quickstart/spa/react/01-login)

1. i installed with `--save` the `10.6.1` version of `auth0-lock`.  
2. created `AuthService.js` with the same code as in tutorial and put it into `/src/utils/` directory
3.  changed  my  `routes.js`  to this 

```
import React from 'react';
import { Route, IndexRoute, Redirect } from 'react-router';
import AuthService from './utils/AuthService';
import App from './containers/App';
import Home from './components/Home';
import RecipeCards from './containers/RecipeCards';
import Recipe from './containers/Recipe';
import NotFound from './containers/NotFound';
import NewRecipe from './containers/NewRecipe';

const auth = new AuthService(__AUTH0_CLIENT_ID__, __AUTH0_DOMAIN__);

// onEnter callback to validate authentication in private routes
const requireAuth = (nextState, replace) => {
  if (!auth.loggedIn()) {
  	console.log('not allowed!');
    replace({ pathname: '/' })
  }
};

export default (
  <Route path="/" component={App} auth={auth}>
    <IndexRoute component={Home} />
    <Route path="recipes" component={RecipeCards} />
    <Route path="recipes/new" component={NewRecipe} />
    <Route path="recipes/:id/:title" component={Recipe} />
    <Route path="404" component={NotFound} />
    <Redirect from="*" to="404" />
  </Route>
);

``` 
4. changed my `App.js` to this 
```
import React, { PropTypes } from 'react';
import Helmet from 'react-helmet';
import styles from './App.scss';
import { Grid, Row, Col } from 'react-flexbox-grid';
import Bar from '../../components/Bar';
import config from '../../config';
import '../../theme/normalize.css';

class App extends React.Component {
	render() {
		console.log(this.props.route.auth);
		let children = null;

               if (this.props.children) {
                 children = React.cloneElement(this.props.children, {
                   auth: this.props.route.auth //sends auth instance to children
                 })
              }

              return (
		<Grid>
		  <Row>
		    <Col xs={12}>
	              <Helmet {...config.app} />
		      <Bar />
		    </Col>
		  </Row>
		    {children}
		</Grid>
		);
	}
}

App.propTypes = { children: PropTypes.node };

export default App;

```
5. saved all changes and run `npm start` to see what `console.log(this.props.route.auth);` will return 

and then i came across this error...

![auth0lock error](https://cloud.githubusercontent.com/assets/13398931/20232880/8336544e-a87c-11e6-8918-008092fc9b36.png)

i don't know what to do. Maybe i need  to add additional configuration to webpack? As far as i know adding `auth0-lock` to project doesn't suppose changing webpack configuration.

so this is [repo](https://github.com/dagman/You-R-ecipes) you can use to reproduce an error.

OS - **windows 10** 
Browser - **Chrome Canary** (latest version)

I like this plugin and wanna use it in my project. So help me out if you can. Thanks.

**Comment by martwetzels** [comment]
see https://github.com/auth0/lock/issues/242. Did the trick for me.

**Comment by glena** [comment]
Lock is meant to be used as a client side library and currently does not work in hybrid apps since it has a heavy dependency on the window object. It is in our backlog to change what is needed to make it work but curretly it is a lot of effort and a low prio.

Also, this is a dup of #592, I will close this one.
