### ISSUE TITLE
Social sign in button flickers when Lock modal loads

### ISSUE THREAD

**Issue by benthehenten** [auth0/lock#720]
I am having an issue where the Google sign in button briefly appears while the Lock modal is loading and then disappears. 

What happens is that the modal initially loads with the loading indicator spinning. Then, the "Log in with Google" button briefly appears and then disappears. Finally, the modal finishes loading. 

This video shows the issue occurring:
http://recordit.co/eXhh36YHvJ

I am using Lock v10.6.1. I have disabled all options to try to isolate the issue.

**Comment by glena** [comment]
which broser are you using?
is it posible for you to share a page reproducing this? (it could be a gh page, codepen, etc)

**Comment by benthehenten** [comment]
The issue occurs in Chrome, Firefox and Safari. 
Here is a demo page: https://fir-c5a83.firebaseapp.com/

Thanks for your help!

**Comment by hzalaz** [comment]
@benthehenten are you doing some customization in Lock? Is there any chance we can get a sample project so we can see what changed? (seems that lock is customized and that might be what broke the animation on load)

**Comment by benthehenten** [comment]
Ah- I did some digging and realized it was a bit of global css affecting the button. I had applied a transition to `button` which was causing the issue. 

Thanks for helping out here!

**Comment by glena** [comment]
Glad you find out
