### ISSUE TITLE
Submit button not showing

### ISSUE THREAD

**Issue by donratta** [auth0/lock#722]
When I try to manually set a flash message The Sign In Button disappears and the user cannot attempt to sign in. The login dialog renders with the error message as expected but the submit button does not show up and I get this error message in the log (view attached pic)

Auth Lock Ver: 10.6.0
React Ver: 0.14.8
Browser: All Browsers

Any help will be appreciated thanks.

<img width="887" alt="screen shot 2016-11-15 at 3 58 56 pm" src="https://cloud.githubusercontent.com/assets/1890260/20324050/111eaed2-ab4d-11e6-9d34-8085ea2ed598.png">

<img width="1265" alt="screen shot 2016-11-15 at 4 03 51 pm" src="https://cloud.githubusercontent.com/assets/1890260/20324148/66efbaea-ab4d-11e6-9188-8da9377d16ee.png">

**Comment by glena** [comment]
I can not reproduce it, can you share a snippet reproducing it?

Something like ```
var lock = new Auth0Lock(cid, domain, options);
lock.show({flashMessage:{type:'error', text: 'hello'}});````

**Comment by hzalaz** [comment]
Also if you are bundling Lock yourself @donratta  or using the CDN bundle

**Comment by donratta** [comment]
@glena Here you go Glen
`const REFRESH_TOKEN_INTERVAL = 60000 * 60;
import Auth0Lock from 'auth0-lock';
import Auth0 from 'auth0-js';
let _lock;
let _auth;

const willExpiresAt = () => Date.now() + REFRESH_TOKEN_INTERVAL;

function lock() {
  // auth0-lock requries window or document to load correctly
  if (!_lock && global.window) {
    _lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
      container: 'login-box',
      auth: {
        redirectUrl: (location.origin + '/auth-check'),
        responseType: 'token',
        params: {
          scope: 'openid roles email offline_access firstName lastName userExpiry'
        }
      },
      closable: false,
      gravatar: false,
      allowSignUp: false,
      rememberLastLogin: false,
      languageDictionary: {
        title: 'Log in',
        forgotPasswordAction: 'RESET PASSWORD',
        passwordInputPlaceholder: 'Password',
        emailInputPlaceholder: 'Email'
      },
      theme: {
        logo: 'https://res.cloudinary.com/hrscywv4p/image/upload/dpr_2.0,h_68/v1/266232/blue_j_nyn05n.png',
        labeledSubmitButton: false
      }
    });
  }
  return _lock;
}

function auth() {
  if (!_auth && global.window) {
    _auth = new Auth0({
      clientID: AUTH0_CLIENT_ID,
      domain: AUTH0_DOMAIN,
      responseType: 'token'
    });
  }
  return _auth;
}


const saveTokens = (idToken, dispatch, next) => {
  dispatch(updateConfig({
    userToken: idToken,
    expiresAt: willExpiresAt()
  }));
  lock().getProfile(idToken, (err, profile) => {
    if (err) {
      console.log('Cannot get user :(', err);
      next();
    }
    dispatch(updateConfig({user: profile, userToken: idToken}));
    
    next();
  });
};

export function parseHash(store) {
  const { dispatch } = store;
  return (nextState, replaceState, next) => {
    removeCredentials(store);
    const locationHash = R.path(['location', 'hash'], nextState);
    const hash = auth().parseHash(locationHash);
    if (hash) {
      if (hash.error) {
        console.log('There was an error logging in', hash.error);
        dispatch(updateConfig({ loginError: hash.error_description }));
        next();
      } else {
        dispatch(updateConfig({
          refreshToken: hash.refreshToken,
          userToken: hash.idToken,
          expires_in: willExpiresAt(),
          loginError: null
        }));
        saveTokens(hash.idToken, dispatch, next);
      }
    }
  };
}

export function login(error) {
  // Call the show method to display the widget.
  if (error) {
    lock().show({
      flashMessage: {
        type: 'error',
        text: error
      }
    });
  } else {
    lock().show();
  }
}

export function logout(store) {
  return () => {
    removeCredentials(store);
    retrieveCredentialsFromLocalStorage(store);
  };
}

export const getUserToken = getFromLocalStorage('userToken');
export const getUser = getFromLocalStorage('user');

export function retrieveCredentialsFromLocalStorage(store) {
  const { dispatch } = store;
  dispatch(updateConfig({
    userToken: getUserToken(store),
    user: getUser(store)
  }));
}

// private methods
function getFromLocalStorage(fieldName) {
  return (store) => store.getState().config.get(fieldName);
}

function removeCredentials(store) {
  store.dispatch(updateConfig({
    userToken: null,
    user: null
  }));
}`

**Comment by donratta** [comment]
hey @hzalaz We use webpack to bundle.

**Comment by glena** [comment]
@donratta it is hard to test that and there is no way to bundle it using your same configurations. If you can share a repo reproducing the issue (just initialize lock and show it with the flashMessage would be helpful, it should be ready to easily build and repro it).

**Comment by donratta** [comment]
@glena sounds good will get back to you with that

**Comment by hzalaz** [comment]
Closing this one please reopen the issue with more information so we can see that's wrong
