### ISSUE TITLE
how do I change redirect url while using react router

### ISSUE THREAD

**Issue by faysal515** [auth0/lock#723]
As per the react example of Auth0 10+, we have to pass the `options` parameter of in Auth0Lock constructor instead of `login.show(options)`. For this reason, i cannot dynamically set my redirect url as all my options are set on `constructor` how do I achieve dynamic option passing Auth0Lock service

**Comment by glena** [comment]
What is the use case for this? The callback url in your app should be unique (you can use the state to later redirect the user to where you need).
Anyway, instead of having one global instance, you can initialize lock before showing it once you know the redirect uri

**Comment by faysal515** [comment]
My login button is on the navigation bar which renders essentially everywhere. So my users could decide to signup/login potentially on anywhere of the app. Also if I initialize my Auth0Lock other than my router context, `authenticated` method never gets fired because Auth0 redirects to my callback url.

**Comment by hzalaz** [comment]
@faysal515 can you build a sample so we can check it?. Also please check the `hash_parsed` error event ([here](https://github.com/auth0/lock#onevent-callback) is the full list of lock events)

**Comment by hzalaz** [comment]
Please reopen if the issue is not solved

**Comment by lumberj** [comment]
@faysal515 was trying to do the same thing. I set my redirectUrl to `window.location.origin` when creating the instance of `lock` and I use the state parameter to store the redirectUrl.

**Comment by hsq125** [comment]
+1  ... not being able to specify the redirect URL as parameter of the lock.show() method is a big limitation. 

My use case: I have an action triggered by a button (let's say "order now") that requires the user to be authenticated. When the user click on the button, two scenario can happen
- either the user is already logged in > then the page allowing to prepare the order is displayed
- or user is not yet logged in > the login windows must be displayed, and upon successful login, the page allowing to prepare order is finally displayed. 

my url are RESTfull URL containing id's... so I cannot white list them all. Example /order/23

Do I try to do a silly thing?!
