### ISSUE TITLE
Link from "forgot password" to "login" screens?

### ISSUE THREAD

**Issue by jcamins-rp** [auth0/lock#728]
In previous versions of lock, it was possible to get back to the login screen if you remembered your password after clicking the "Forgot password?" link. This is no longer possible as far as I can tell. Would you consider adding a showReturnToLogin option that provides roughly equivalent functionality to that at https://github.com/auth0/lock/blob/master/src/connection/database/login_pane.jsx#L56 ?

**Comment by hzalaz** [comment]
@jcamins-rp you can go back to the login screen from the forgot password screen, even if you set forgot password as the initial scren

**Comment by jcamins-rp** [comment]
I can? I'm not seeing it, but maybe I'm just missing something. What option
do I need to set?

-- 
The information contained in this transmission and any attachments may be 
confidential, proprietary  or privileged, and may be subject to protection 
under applicable law. This transmission is intended for the sole use of the 
individual or  entity to whom it is addressed. If you think you have 
received this transmission in error, please alert 
compliance@remedypartners.com and then delete this e-mail immediately. 
Thank you.

**Comment by hzalaz** [comment]
No option, it's by default. There is a back button top-left corner

**Comment by jcamins-rp** [comment]
@hzalaz oh yeah. Sorry, I was expecting a link in the same place as "Don't remember your password?" so I didn't even look in the header area.
