### ISSUE TITLE
Dependencies changed for react-addons-test-utils

### ISSUE THREAD

**Issue by myobie** [auth0/lock#734]
I cannot get past this issue where an internal react dependency cannot be found https://github.com/facebook/react/issues/8314

I cannot seem to get any combination of versions of react, react-dom, and react-addons-css-transition-group to work. Is it possible to be more specific with the dependencies?

**Comment by myobie** [comment]
Here is an example repo showing the issue: https://github.com/myobie/react-loading-issue-example

**Comment by mattludwigs** [comment]
@myobie have you been able to figure this out?

**Comment by myobie** [comment]
@mattludwigs no. I tried again today and nothing worked. For now I am just redirecting to the hosted lock page and not embedding the lock directly.

**Comment by myobie** [comment]
I tested https://github.com/auth0/lock-passwordless today and it works fine. It has older react dependencies which do not have the breaking change (^0.14.0). I intend to use the passwordless flow so this is good news for me. However, I do recommend changing the react deps in this repo to pin them to specific versions known to not exhibit this issue.

**Comment by glena** [comment]
@myobie hi, and which versions would be? we dont want to tie to outdated dependencies. Also, lock is not tied to a certain version but only to the mayor `^15.0.0` so it should install the latest release so if they fix that at some point, it wont be restricted.

**Comment by myobie** [comment]
@glena https://github.com/alleyinteractive/simplechart/pull/81/files shows that pinning to 15.4.1 works for them. You can check the issue I linked to in the original description for a list of different things people have done to solve this problem.

**Comment by glena** [comment]
So far, it does not seems to be related to the version. Just tried your repo and it is downloading `15.4.1`. Looks like it should be something weird related to the brunch bundle since our webpack one is working without any issues.
