### ISSUE TITLE
Auth0 Lock not using "audience" parameter correctly

### ISSUE THREAD

**Issue by postalservice14** [auth0/lock#735]
When the lock screen shows and I click the "Last time you logged in with {{your_email}}" button, it works great. It returns a token that works for the audience specified. But when I click "Not your Account" and then type in my username and password and click submit. It sends the correct audience to auth0 but the token returned does not work for that audience.

Here is my lock configuration:

```js
this.lock = new Auth0Lock(
      config.clientId,
      config.auth0Domain,
      {
        theme: {
          primaryColor: '#8dc63f'
        },
        closable: false,
        allowSignUp: false,
        languageDictionary: {
          title: "Sign In"
        },
        auth: {
          params: {
            audience: config.apiBasePath
          },
          redirectUrl: BASE_PATH + '/auth/login',
          responseType: 'token id_token',
        }
      }
    );
```

Thanks in advance for your help.

**Comment by glena** [comment]
hi @postalservice14 currently the only way to work with that is using the hosted login page on `/authorize`. The `last time...` button works because it redirects the user to that url to do SSO.

**Comment by postalservice14** [comment]
So there is no way to use Lock to get a token for an audience?  I'm a little confused by your response.  How is it not a bug that the "Last Time..." button works differently than a manual login?

**Comment by glena** [comment]
> So there is no way to use Lock to get a token for an audience? 

No

> How is it not a bug that the "Last Time..." button works differently than a manual login?

Because it uses a different flow to do SSO. It is not a bug but a restriction. If you are doing API authorization the only way to accomplish is to use the `/authorize` endpoint which will go though the entire authorization flow (including consent step it is necesary). That is not posible with lock since there is no way to show the consent step in that scenario.

**Comment by postalservice14** [comment]
Well I have "Allow Skipping User Consent" checked on the API in Auth0.  I assumed it wouldn't need user consent in that case.

Maybe I'm going about what I'm trying to do the wrong way?

I have an SPA that I login with using lock.  It talks to one of our protected API's.  What we're currently doing is logging in with lock where the audience is the protected API's identifier in order to get back a token that is authorized with that API.  Is there another way to accomplish that using lock?

Thanks again for your help.

**Comment by glena** [comment]
Currently, the only way to make it work with Lock.js is using the hosted login page. You can build your own UI and use auth0.js v8 (currently in alpha) to authenticate the users using this method https://github.com/auth0/auth0.js/blob/v8/example/index.html#L187

Once auth0.js is released this will be supported by lock but we dont have an ETA for that.

**Comment by postalservice14** [comment]
But how do you set the audience using that method?  I'm trying this, but it's still not returning a token that works with the audience I'm passing.  Only a token that works with the client ID I'm passing.

```js
this.auth = new auth0.WebAuth({
      domain: config.auth0Domain,
      clientID: config.clientId,
      responseType: 'id_token token',
      redirectUri: BASE_PATH + '/auth/login',
      audience: config.apiBasePath,
    });
```

**Comment by glena** [comment]
You should send that in the login method
```
    this.auth = new auth0.WebAuth({
      domain: config.auth0Domain,
      clientID: config.clientId,
      responseType: 'id_token token',
      redirectUri: BASE_PATH + '/auth/login'
    });

      this.auth.client.login({
        connection: 'tests', // replace with the correct connection name
        username: '...',
        password: '...',
        audience: config.apiBasePath
      }, function(err, data) {

      ...

      });
```

**Comment by postalservice14** [comment]
Thanks @glena .  I feel like we're close, but still isn't working.  I was using `this.auth.redirect.login`.  When I add the audience to that method like so, it still doesn't give me back a token that works with that audience.

```js
this.auth.redirect.login({
        connection: 'postgres-staging',
        username: email,
        password,
        scope: 'openid',
        audience: config.apiBasePath
      }, (err, data) => {
        debugger;
        resolve(data);
      })
```

When I use `this.auth.client.login` like you have, the callback returns an error `Authorization server not configured with default connection.`

My configuration with that method is:

```js
this.auth.client.login({
        connection: 'postgres-staging',
        username: email,
        password,
        scope: 'openid',
        audience: config.apiBasePath
      }, (err, data) => {
        debugger;
        resolve(data);
      })
```

Thanks again for helping me out...  Hoping we're close!

**Comment by glena** [comment]
`this.auth.redirect.login` is the same flow Lock uses so it wont work.

for `this.auth.client.login` I forgot the connection is not sent as a param, it should be configured in the dashboard (https://manage.auth0.com/#/account) in `Default Directory ` under `API Authorization Settings`

**Comment by postalservice14** [comment]
but the connection is different for different environments.  I can't have the connection dynamic depending on what environment the application is deployed to?  e.g. Staging/Beta, Product, etc

**Comment by glena** [comment]
in that case you can use `this.auth.client.loginWithResourceOwner` https://github.com/auth0/auth0.js/blob/v8/src/authentication/index.js#L149

Also we recommend to have different accounts for different environments, more info here https://auth0.com/docs/tutorials/development-lifecycle-with-auth0

**Comment by postalservice14** [comment]
So I'm using `loginWithResourceOwner`, but the token is still not for the audience I'm passing.  :-(

```js
this.auth.client.loginWithResourceOwner({
      connection: 'postgres-staging',
      username: email,
      password,
      scope: 'openid',
      audience: config.apiBasePath
    }, (err, data) => {
      debugger;
      console.log(data);
    })
```

**Comment by glena** [comment]
Sorry for the back and forth. The way to go is using `this.auth.client.login` and you will only be able to set one default directory per account. This is something being discussed internally as we speak.

**Comment by postalservice14** [comment]
No problem, I appreciate you hanging with me to help me solve this.

I tried `login` with a default directory and now I'm getting a "Bad Request" response back in the callback.

```js
this.auth.client.login({
      username: email,
      password,
      scope: 'openid',
      audience: config.apiBasePath
    }, (err, data) => {
      debugger;
      console.log(data);
    })
```

**Comment by glena** [comment]
Do you get any error message besides bad request?

can you check the dev tools and copy the payload sent and the entire response

I just run a test and this request

```
POST https://account.auth0.com/oauth/token
{"client_id":"...","connection":"tests","username":"johnfoo@gmail.com","password":"...","scope":"openid","audience":"urn:test","grant_type":"password"}
```

is returning a valid token

**Comment by postalservice14** [comment]
I think you're messing with me ;-)  I swear, I didn't change anything and now it's working.  Now I'm getting back a token for the correct audience. :-)

One problem.  When I use that token to get the user info, it's not working.  It's saying unauthorized.

```js
this.auth.client.userInfo(accessToken, (err, data) => {
          console.log('userInfo', data);
          resolve(data);
        });
```

![image](https://cloud.githubusercontent.com/assets/46067/20762192/97052baa-b6f3-11e6-9ccb-67827c5e147a.png)


I even tried hitting the endpoint directly with the token.  And it's returning an "Unauthorized"

**Comment by glena** [comment]
hahahaha I swear I didnt do anything. can you decode the token payload paste it here? you can use jwt.io

**Comment by postalservice14** [comment]
Sure

```json
{
  "iss": "https://carsaver-beta.auth0.com/",
  "sub": "auth0|ad382bfe-55b7-40a4-bb21-ce226c27c62a",
  "aud": [
    "https://api-beta.carsaver.com/"
  ],
  "azp": "5BPPLJTTc1lsL7Y4M3ajxpYMaf9nhJeQ",
  "exp": 1480611481,
  "iat": 1480525081,
  "scope": "openid"
}
```

**Comment by glena** [comment]
Got it, If the Api configured in auth0 is set to use HS256 that token will not work to call user info. It only works with RS256 because of how the token is signed and decoded. 

When the Api uses RS256 you will find 2 audiences, the one for your api and one for the userinfo endpoint.

**Comment by postalservice14** [comment]
Ahh, interesting.  Okay, I've switch to RS256 - looks like everything's working.  Last question....I assumed hitting the `/userinfo` endpoint would get me back all the user info my database connection is setting up, but it's not.  Is there any way to get back the roles from my database connector?  Either from `/userinfo` or better yet from the initial login request?  I've tried messing with the scopes, but can't seem to get the right configuration.

To give some context, here is the result of the "Test" command in my database connector to show you structure.

```json
The profile is:
{
  "id": "ad382bfe-55b7-40a4-bb21-ce226c27c62a",
  "email": "********",
  "app_metadata": {
    "roles": [
      "admin"
    ]
  }
}
```

Thanks again so much for your help.

**Comment by glena** [comment]
No, the only info returned by userinfo so far is 

```js
{
    "sub": "...",
    "name": "..."
    "nickname": "...",
    "picture": "...",
    "updated_at": "..."
}
```

In the future you should be able to map metadata to the root level and access it with custom claims but this is not public yet.

**Comment by postalservice14** [comment]
Okay thank you for your help!
