### ISSUE TITLE
Lock Widget on IE 11 does not correctly display title.

### ISSUE THREAD

**Issue by gosub3000** [auth0/lock#736]
We are developing an Angular2 app using the lock widget, pulled in by npm. This code is largely based on the Auth0 example/quickstart for Angular2.

Lock options are defined as:
```javascript
private _lockOptions = {
    allowSignUp : true,
    allowForgotPassword : true,
    loginAfterSignup : false,
    allowedConnections : ['Username-Password-Authentication'],
    auth : {
      params : {scope : 'openid roles'},
    },
    theme: {
      logo: 'assets/images/apc-logo.svg',
      primaryColor: '#3DCD58'
    },
    languageDictionary: {
      title : 'SmartConnect Support'
    }
  };
lock = new Auth0Lock(this._clientId, this._clientDomain, this._lockOptions);
```

Screenshots compare Internet Explorer 11, Firefox 50 and Chrome 46 on Windows 7 Professional Service Pack 1.  As can be seen from the IE screenshot, the title area is not displaying the title correctly.

![chrome-46-lock](https://cloud.githubusercontent.com/assets/6809472/20668742/4f85cde8-b568-11e6-99d8-449f606ffcfc.png)
Chrome 46 Screenshot.

![firefox-50-lock](https://cloud.githubusercontent.com/assets/6809472/20668741/4f85c38e-b568-11e6-96a6-e824a6224d3c.png)
Firefox 50 screenshot

![ie-11-lock](https://cloud.githubusercontent.com/assets/6809472/20668743/4fa18c54-b568-11e6-9132-80acd263f98b.png)
Internet Explorer 11 screenshot.

Lock version in use is auth0-lock@10.7.0

Any advice on how to make the IE experience more consistent with other browsers is gratefully received.

**Comment by woloski** [comment]
That seems to be Lock9. In lock10 we dont have the pill to change between signup and login. Can you make sure?

**Comment by gosub3000** [comment]
Npm ls reports as auth0-lock@10.7.0 and auth0-js@7.5.0.  I can't find any other versions in the project file tree.

**Comment by woloski** [comment]
there must be some caching going on, that screenshot for sure is Lock9

**Comment by gosub3000** [comment]
Ok, did some digging, and found that while we're importing auth0-lock@10.7.0 in the package.json, we're also importing the lock from the CDN in our index.html as:
```html
<!-- Auth0 Lock script -->
<script src="https://cdn.auth0.com/js/lock/10.0.0/lock.min.js"></script>
```

I've updated both to the latest release (10.7.1) and the issue seems to be addressed.

I'm slightly embarrassed that I didn't check this first.  Thanks for your help.
