### ISSUE TITLE
Double Tabbing necessary when filling out username/password in IE11 with keyboard only

### ISSUE THREAD

**Issue by MaximRouiller** [auth0/lock#741]
**Version:** Lock10
**Issue:** When tabbing between username and password, SVG gets focused
**Browser:** IE11 only

**Workaround:**

```javascript
var lock = new Auth0Lock(appConfig.clientID, appConfig.domain, options);
lock.on('signin ready', function () {
    $('svg').attr('focusable', false);
});
```
**Root cause:** SVG elements can get focus when tabbing in IE11.

**Comment by hzalaz** [comment]
Should be fixed in latest Lock
