### ISSUE TITLE
Request to add user-facing error message.

### ISSUE THREAD

**Issue by sjudson** [auth0/lock#751]
For cases where the a session is necessary, e.g. if some stored context is needed to process the login information.

Example JSON error body:

```
{ name: "ValidationError",
  code: "session_missing",
  description: "Session missing. Close all open login dialogs and try again."
  statusCode: 400}
```

**Comment by glena** [comment]
Done, but we need a proper error message for english and translations.

**Comment by joshuatantonflynn** [comment]
I'm getting this error when attempting login. Refreshing the page will allow me to login. However, even though login is successful loginResult.IsError is true. I tell my code that when this happens just relaunch the auth0 endpoint, the second time loginResult is good. I assume this is due to refresh of page, how else can one avoid getting this session_missing error???

**Comment by luisrudge** [comment]
this issue is very old. what version of lock are you using? can you point me some steps so I can reproduce the issue locally?

**Comment by joshuatantonflynn** [comment]
I'm using the Auth0.OidcClient.Android v1.2.0 NuGet Package. I've even reproduced this error using the SampleApp from Auth0. However recent tests have only reproduced it on Galaxy Notes (8 & 5). I think it might be a problem with samsung browser, as when I tried on my personal phone (nexus 5) which has chrome as the default browser this problem did not occur. I am going to attempt forcing it to open on chrome, but if the error isn't with the browser I don't know what it would be. It only occurs when the app was logged out and closed.

**Comment by luisrudge** [comment]
This repo is for lock web, not lock android. Are you talking about https://github.com/auth0/Lock.Android?

**Comment by joshuatantonflynn** [comment]
oh, my bad I found this page through googling "auth0 session_missing". My Xamarin project is using a NuGet package to use auth0.
