### ISSUE TITLE
Run something specifically on a successful sign up

### ISSUE THREAD

**Issue by jimmiebtlr** [auth0/lock#755]
When a user sign's up for the first time via social login or database, is it possible to detect this?  Is the best way to achieve this looking at my own database, or is this provided in some way with the lock?

**Comment by glena** [comment]
You should be able to do that using [rules](https://auth0.com/docs/rules) in the [auth0 dashboard](https://manage.auth0.com).

something like this will do the trick

```js
function (user, context, callback) {
  if (context.stats.loginsCount === 1 && user.identities[0].isSocial) {
    // your own logic


    // or you can add a flag to the user to do something in your backend
    user.first_login = true;
    
    callback(null, user, context);
  }
}
```
