### ISSUE TITLE
Emit event on setScreen

### ISSUE THREAD

**Issue by elger** [auth0/lock#759]
We integrated Lock in our component but we want to know which screen is active in order to be able to define the outer component content dependent on active screen. To be able to do this we could emit an event on the setScreen function:

```
diff --git a/src/core/index.js b/src/core/index.js
index 8feba69..20e0332 100644
--- a/src/core/index.js
+++ b/src/core/index.js
@@ -491,6 +491,10 @@ export function emitAuthorizationErrorEvent(m, error) {
   emitEvent(m, "authorization_error", error);
 }
 
+export function emitSetScreenEvent(m, screenName) {
+    emitEvent(m, 'setScreen', screenName);
+}
+
 export function emitUnrecoverableErrorEvent(m, error) {
   emitEvent(m, "unrecoverable_error", error);
 }

diff --git a/src/connection/database/index.js b/src/connection/database/index.js
index bdc2f33..3b1c140 100644
--- a/src/connection/database/index.js
+++ b/src/connection/database/index.js
@@ -251,6 +251,8 @@ export function setScreen(m, name, fields = []) {
   m = l.clearGlobalSuccess(m);
   m = clearFields(m, fields);
 
+  l.emitSetScreenEvent(m, name);
+
   return tset(m, "screen", name);
 }
```

Is that something that would be integrated by PR or do we have to rethink because it is not compliant to Lock.

**Comment by hzalaz** [comment]
@elger I'd rethink it a bit to emit the event for more than databases screen and maybe the event name but that's the easy part

**Comment by elger** [comment]
Ok, I will adapt it to a more general event emitter that can be used in needed places, or do you think of a more central place to emit the events?

**Comment by hzalaz** [comment]
@elger I forgot we had these [two events](https://github.com/auth0/lock/blob/430d912e0834d5c5ed00beb2f98d677162b26b70/src/core.js#L44) do they work for you or you need an extra one?

**Comment by elger** [comment]
No problem, meanwhile we implemented a solution without using events.
