### ISSUE TITLE
add specific scope in auth  Lock params 

### ISSUE THREAD

**Issue by mahdiraddadi** [auth0/lock#763]
I have an attribute under app_metadata named "profile", the last days I am facing a problem of large scope while logging in and I am trying to reduce the unnecessary elements but the element "app_metadata.profile" is required for the communications with the backend.
is there a way to specify the "app_metadata.profile" in the scope params without getting the whole profile user ??

**Comment by hzalaz** [comment]
There is little lock can do here since profile is a predefined scope and this is handled by auth0 server. The only workaround I can think is to use a different metadata name or fetch the user in your server via api v2

**Comment by mahdiraddadi** [comment]
should I add the scope app_metadata in the lists of auth params scopes ?? because I dont it all, I need only some attributes
