### ISSUE TITLE
Username-Password works but social buttons don't/spin

### ISSUE THREAD

**Issue by nonsenseless** [auth0/lock#765]
The basic issue I'm facing is that the social login buttons don't work in Android. I can use the username/password fields, but when I press "Log in with facebook" or "Log in with google" a spinner comes onscreen and spins indefinitely.

I'm working from the auth0-Ionic guide here: https://auth0.com/docs/quickstart/native/ionic/00-intro

I've installed the components via bower and am using the following versions (which are included in index.html):
```
    "auth0-lock": "^10.7.3",
    "angular-lock": "^1.0.5",
    "angular-jwt": "^0.1.8",
```

My config has:
```
        lockProvider.init({
            domain: 'appname.auth0.com',
            clientID: 'token',
            options: {
                auth: {
                    redirect: true,
                    params: {
                        scope: 'openid',
                        device: 'Mobile device'
                    }
                }
            }
        });

        // Configuration for angular-jwt
        jwtOptionsProvider.config({
            tokenGetter: function() {
                return localStorage.getItem('id_token');
            },
            whiteListedDomains: ['localhost'],
            unauthenticatedRedirectPath: '/main/login'
        });

```

My auth service ('Authentication') has the following (which is not fully fleshed out):

```
 this.login = function() {
            lock.show();
        }

        this.logout = function() {
            localStorage.clear();
            $state.go("main.login");
        }

        this.registerAuthenticationListener = function() {
            console.log("Registering listener");
            lock.on('authenticated', function(authResult) {
                console.log('authenticated');
                localStorage.setItem('id_token', authResult.idToken);
                authManager.authenticate();
                lock.hide();

                // Redirect to default page
                location.hash = '#/';

                lock.getProfile(authResult.idToken, function(error, profile) {
                    if (error) {
                        console.log(error);
                    }

                    localStorage.setItem('profile', JSON.stringify(profile));
                });
            });
        }

        this.checkAuthOnRefresh = function() {
            var token = localStorage.getItem('id_token');
            if (token) {
                if (!jwtHelper.isTokenExpired(token)) {
                    if (!$rootScope.isAuthenticated) {
                        authManager.authenticate();
                    }
                }
            }
        }
```

Authentication.registerAuthenticationListener is called within ionicPlatform.ready and my login controller calls Authentication.login().

We were previously using auth0-angular and seeing the same behavior--it worked fine on iOS--and I switched over to the version in the auth0-ionic guide to see if that worked any better. I'm a little stumped as to what might be causing the problem, so any insight would be greatly appreciated.

[Note: This is a duplicate of the issue submitted here: https://github.com/auth0/angular-lock/issues/16]

**Comment by hzalaz** [comment]
Hi seems that this is not a lock issue. I see that you are setting redirect to true but for cordova apps it should be false. Also please check that you have the inappbrowser plugin installed.

**Comment by nonsenseless** [comment]
I've actually tried it with both redirect false and true to the same effect. Inappbrowser is definitely installed.

**Comment by hzalaz** [comment]
Try checking any js error to get additional info

**Comment by nonsenseless** [comment]
Using chrome devtools to inspect the app on the device, there are no errors
listed. I also don't see anything in network inspector.

**Comment by nonsenseless** [comment]
For additional context, I found that when I unintalled InAppBrowser, I the google/facebook buttons *would* send me to their respective login pages, but then I'd get stuck at the "OK" page and it wouldn't redirect back into the app.

**Comment by nonsenseless** [comment]
I believe I've resolved this issue. At this time, it appears to be a bug caused by serving the device using LiveReload which behaved differently than when directly installing an APK.
