### ISSUE TITLE
Make nonce first class param

### ISSUE THREAD

**Issue by glena** [auth0/lock#771]
Right now the only way to send the nonce to auth0.js is using auth.params:

```js
lock.show({
  auth:{
    params: {nonce: '1234'}
  }
});
```

we need to make it first class param

```js
lock.show({
  auth:{
    nonce: '1234'
  }
});
```

and make sure it is being sent to auth0.js during authentication.

Also we need to send it to the parseHash function to verify the token.

**Comment by luisrudge** [comment]
@glena can you please assign this to me?

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/commit/c0d332eee5828f56b1bb3820b804ad335ba3185a

Thanks @glena
