### ISSUE TITLE
responseType = "token" does not send idToken anymore

### ISSUE THREAD

**Issue by mcbain** [auth0/lock#781]
We use the 10.7.2 version where currently the  responseType must be set to "id_token" since "token" does send only a access-token.

**Comment by glena** [comment]
Are you asking for the `openid` scope?

**Comment by mcbain** [comment]
Just using the sample code. e.g.

```
this.lock = new Auth0Lock(clientId, domain, {
      auth: {
        redirectUrl: `${resolve("app.authUrl")}`,
        responseType: 'id_token'
      }
    });
```

**Comment by glena** [comment]
try with

```
this.lock = new Auth0Lock(clientId, domain, {
      auth: {
        redirectUrl: `${resolve("app.authUrl")}`,
        responseType: 'id_token',
        params: {
             scope: 'openid'
        }
      }
    });
```

**Comment by mcbain** [comment]
Also the accessToken send in the "token" case seems to be valid. this.lock.getUserInfo(authResult.accessToken, ...) returns the user profile data.

**Comment by mcbain** [comment]
Did you mean scope: openid with response "token"?

**Comment by hzalaz** [comment]
@mcbain first in what version you were getting the id_token using `response_type: token` and what is the snippet you were using?. 

Also please try with v10.7.2 setting response type to `token` and passing the scope `openid` as @glena  mentioned (And make sure you **don't** have the OAuth 2.0 Authorization feature enable (https://auth0.com/docs/api-auth/tutorials/configuring-tenant-for-api-auth) in your tenant

**Comment by mcbain** [comment]
```
 responseType: 'token',
				params: {
					scope: 'openid'
				}
```

Works !

**Comment by hzalaz** [comment]
cool, glad it worked

**Comment by mcbain** [comment]
Thank you !
