### ISSUE TITLE
upgrading to lock 10.9 seems to be broken

### ISSUE THREAD

**Issue by adrianchia** [auth0/lock#782]
Thank you for using Lock! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [x] Lock version
- [x] Browser & OS

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

I am playing with Angular 2 Quickstart generated from the web console, and set the Auth0 Lock script (referenced from CDN <script src="http://cdn.auth0.com/js/lock/10.9/lock.min.js"></script>). 

Upon login successfully from the popup, the application remain on "You are not logged in, please click 'Log in' button to login". I tried to downgrade to both lock 10.7 and lock 10.8 and they both works. 

Lock version: 10.9 [CDN](http://cdn.auth0.com/js/lock/10.9/lock.min.js)
Browser: Chrome Version 55.0.2883.87 m
OS: Windows 10

**Comment by glena** [comment]
I will review the seed project, but changing how lock is initialized should be enough in the auth.service.ts, line ~11 

```
this.lock = new Auth0Lock(auth_config_1.myConfig.clientID, auth_config_1.myConfig.domain, {
          auth: {
            responseType:'token',
            params: {
              scope: 'openid'
            }
          }
        });
```

**Comment by adrianchia** [comment]
Updating the options does fix the issue. Thanks a lot!

**Comment by glena** [comment]
awesome
