### ISSUE TITLE
`authenticated` event isn't longer triggered

### ISSUE THREAD

**Issue by Grmiade** [auth0/lock#786]
With the latest version, 10.9.0, the `authenticated` event isn't longer triggered :/

```
class SignIn extends Component {
  constructor() {
    super()
    const { REACT_APP_AUTH0_CLIENT_ID, REACT_APP_AUTH0_DOMAIN } = process.env
    this._lock = new Auth0Lock(REACT_APP_AUTH0_CLIENT_ID, REACT_APP_AUTH0_DOMAIN)
    this._lock.on('authenticated', ({ accessToken, idToken }) => {
      localStorage.setItem('auth0IdToken', idToken)
      this._lock.getUserInfo(accessToken, (error, profile) => {
        if (error) logger.warn(error)
        else {
          const { router } = this.context
          const { saveProfile } = this.props
          saveProfile(profile)
          router.replace('sign-up')
        }
      })
    })
  }

  _showLogin = () => {
    this._lock.show()
  }

  render() {
    return (
      <Button onClick={this._showLogin} primary>Let&apos;s go!</Button>
    )
  }
}
```

**Comment by glena** [comment]
It is working fine in my tests. The only thing I can think of is that something in your app is cleaning the url hash before lock is initialized after the redirection.

is this using react router or something similar?
can you add `console.log(window.location.hash);` right after initializing lock to see if it is empty or not?

also, can you hook to the `authorization_error` event to see if there is any error?

you can try disabling the redirection
```js
{
    auth: { redirect: false }
}
```

**Comment by carusology** [comment]
We also aren't getting the `authenticated` event as of v1.9.0 using aurelia. When I reverted our auth0-lock version to v1.8.1 explicitly it worked. Here's the relevant bits stripped out of the application.

```ts
import { inject } from 'aurelia-framework';
import { Router } from 'aurelia-router';
import Auth0Lock from 'auth0-lock';

import Config from '../configuration/config';
import AuthenticationContext from './context';

@inject(AuthenticationContext, Router, Config)
export default class Login {
  redirectUrl: string;
  lock: Auth0LockStatic;

  constructor(
    private context: AuthenticationContext,
    private router: Router,
    private config: Config) {

    this.lock = new Auth0Lock(
      this.config.get("AUTH_0.CLIENT_ID"),
      this.config.get("AUTH_0.DOMAIN"),
      {
        auth: {
          sso: false,
          params: {
            scope: 'openid email'
          }
        },
        closable: false
      }
    );

    this.lock.on("authenticated", this.onAuthenticated.bind(this));
  }

  activate(params: any): void {
    this.redirectUrl = params.redirect_url || '/';
  }

  attached(): void {
    if (!this.context.isAuthenticated) {
      this.lock.show();
    } else {
      this.redirect();
    }
  }

  redirect() {
    this.router.navigate(this.redirectUrl);
  }

  onAuthenticated(authResult: any): void {
    this.lock.getProfile(authResult.idToken, (error, profile) => {
      if (error) {
        console.log(error);
        return;
      }

      this.context.login(profile, authResult.idToken);
      this.redirect();
      this.lock.hide();
    });
  }

}
```

**Comment by glena** [comment]
Can you try with v 10.9.1?

Get Outlook for iOS




On Tue, Jan 10, 2017 at 1:48 PM -0300, "Brian Caruso" <notifications@github.com> wrote:












We also aren't getting the authenticated event as of v1.9.0 using aurelia. When I reverted our auth0-lock version to v1.8.1 explicitly it worked. Here's the relevant bits stripped out of the application.
import { inject } from 'aurelia-framework';
import { Router } from 'aurelia-router';
import Auth0Lock from 'auth0-lock';

import Config from '../configuration/config';
import AuthenticationContext from './context';

@inject(AuthenticationContext, Router, Config)
export default class Login {
  redirectUrl: string;
  lock: Auth0LockStatic;

  constructor(
    private context: AuthenticationContext,
    private router: Router,
    private config: Config) {

    this.lock = new Auth0Lock(
      this.config.get("AUTH_0.CLIENT_ID"),
      this.config.get("AUTH_0.DOMAIN"),
      {
        auth: {
          sso: false,
          params: {
            scope: 'openid email'
          }
        },
        closable: false
      }
    );

    this.lock.on("authenticated", this.onAuthenticated.bind(this));
  }

  activate(params: any): void {
    this.redirectUrl = params.redirect_url || '/';
  }

  attached(): void {
    if (!this.context.isAuthenticated) {
      this.lock.show();
    } else {
      this.redirect();
    }
  }

  redirect() {
    this.router.navigate(this.redirectUrl);
  }

  onAuthenticated(authResult: any): void {
    this.lock.getProfile(authResult.idToken, (error, profile) => {
      if (error) {
        console.log(error);
        return;
      }

      this.context.login(profile, authResult.idToken);
      this.redirect();
      this.lock.hide();
    });
  }

}

**Comment by Grmiade** [comment]
@glena with the `10.9.1` version, it works for me 👍

**Comment by glena** [comment]
awesome!

**Comment by carusology** [comment]
@glena Works for the aurelia case I listed above as well. 👍  h/t
