### ISSUE TITLE
10.9.* results in getProfile is not a function with webpack 

### ISSUE THREAD

**Issue by sinkpoint** [auth0/lock#791]
auth0-lock results in 
platform.bundle.js:136 Uncaught TypeError: f.default.getProfile is not a function
When bundled with webpack 1

With release 10.9. Problems does not exist with 10.8.1 and earlier

Code snippet:
```    return dispatch => {
        let LOCK = new Auth0Lock(AUTH_CLIENT_ID, AUTH_DOMAIN, Auth0Options)
        // define the auth event here to pass dispatch into it
        LOCK.on('authenticated',(authRes)=>{
            LOCK.getProfile(authRes.idToken, function(err, profile) {
                if (err) {
                    dispatch(loginError(err))  
                }
                else {
                    dispatch(receiveLogin(profile, authRes.idToken))
                }
            })
            LOCK.hide()
        })

        LOCK.show()        
    }
````

**Comment by hzalaz** [comment]
@sinkpoint we might need how you are bundling lock or a sample we can debug to see why is not a function.

**Comment by cuongquay** [comment]
The same result when building with bower
```
bower auth0-lock#>= 10.0.0         not-cached https://github.com/auth0/lock.git#>= 10.0.0
bower auth0-lock#>= 10.0.0            resolve https://github.com/auth0/lock.git#>= 10.0.0
bower angular-material#~1.0.9         extract archive.tar.gz
bower auth0-lock#>= 10.0.0           download https://github.com/auth0/lock/archive/v10.9.1.tar.gz
```

```javascript
TypeError: f.default.getProfile is not a function
    at t.getProfile (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:23:6505)
    at Object.t [as getProfile] (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:41:953)
    at t.<anonymous> (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:42:6932)
    at http://192.168.99.100/js/app.min.js?r=R1-ba026f2:41:694
    at f.$eval (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:28:5581)
    at f.$apply (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:28:5814)
    at t (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:41:570)
    at t.function.e.(anonymous function) (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:41:679)
    at t.n.emit (http://192.168.99.100/js/app.min.js?r=R1-ba026f2:22:12416)
    at http://192.168.99.100/js/app.min.js?r=R1-ba026f2:8:13980
```


I bundle it all into one single file app.min.js

**Comment by glena** [comment]
Hi @cuongquay, what @hzalaz meant is that we don't have enough context from your comments to assess what is the issue.

Since our blundle is bundling it correctly and the code published in NPM, CDN and Bower exposes that method, we think there might be an issue with your bundler configuration and how are you requiring lock in your app.

Can you provide a sample project which only contains the lock usage that reproduces the issue?

**Comment by petrvolny** [comment]
Same problem here.
Bundling with webpack (almost unchanged config from [create-react-app](https://github.com/facebookincubator/create-react-app))

**Comment by glena** [comment]
I was able to repro, thx @petrvolny.

I will push a fix and will release a patch version.

Anyway, I suggest you both to use getUserInfo (it receives the access token, not the id_token) instead:

```
    LOCK.on('authenticated',(authRes)=>{
        LOCK.getUserInfo(authRes.accessToken, function(err, profile) {
            console.log(err,profile);
        })
        LOCK.hide()
    })
```

**Comment by petrvolny** [comment]
@glena Thanks for quick response and for the getUserInfo suggestion.

**Comment by cuongquay** [comment]
I wrote my own $http.get("../tokeninfo?id_token=") to retrieve its profile object.

Anyway, thanks for your quick fix.

**Comment by glena** [comment]
we will release the patch soon tho, I will let you know

**Comment by glena** [comment]
Hi, `10.9.2` was release with the fix.

**Comment by elnobun** [comment]
Please could the Auth0 team update their website to reflect these changes. The documentation there is outdated, and very misleading. Thanks for your understanding.
