### ISSUE TITLE
`loginWithResourceOwner` will be soon deprecated, user `login` instead.

### ISSUE THREAD

**Issue by bragma** [auth0/lock#792]
I use lock embedded in my SPA application. I am using DB connection with login/password pairs. I do not want any redirect, but lock0 to just post on the api and the all required tokens.
My problem is that, at login, I receive this warning:

`loginWithResourceOwner` will be soon deprecated, user `login` instead.

I don't have any clue on what I am doing wrong. Can you help?
Thanks a lot!

**Comment by hzalaz** [comment]
@bragma is just a warning from auth0.js that should be disabled from lock. Just ignore it for the time being unless there is an issue

**Comment by bragma** [comment]
Good to know, thanks!
