### ISSUE TITLE
getSSOData will be soon deprecated

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#793]
seeing this in my console:

```
`getSSOData` will be soon deprecated.
```

when will this be fixed?

**Comment by hzalaz** [comment]
We'll make a release soon, since it's a warning you can either ignore it or downgrade to v10.8 till we patch it

**Comment by wags** [comment]
When I tried v10.9, my single sign-on to Office 365 broke. Dropping the version back down to v10.8.1 works properly.

**Comment by hzalaz** [comment]
@wags can you clarify what broke? what was the error? your setup of Lock? Otherwise we can't help fixing the issue

**Comment by wags** [comment]
@hzalaz sorry, my comment there was pretty vague. I set up my tests again and shared what I found over in issue #818 since it seems to be different from this issue.

**Comment by aaaa0441** [comment]
@hzalaz do you know what replacement method I should use with "auth0-lock 10.13.0"?

BWT, I am also using below libraries in my Angular 1.6 application.

* "auth0.js 8.4.0"
* "angular-lock 2.0.0-beta.1"
* "angular-jwt 0.1.9"

Is getSSOData or a replacement method in any of these libraries? Thanks a lot.
