### ISSUE TITLE
Custom Connection Button in Lock V10

### ISSUE THREAD

**Issue by adamtay** [auth0/lock#797]
Is 'Adding a new UI element using JavaScript' still supported in lock V10? I am after a login button that will allow a user to login using their enterprise connection account. 

https://auth0.com/docs/libraries/lock/v9/ui-customization#adding-a-new-ui-element-using-javascript

**Comment by glena** [comment]
hi @adamtay, it might be tricky for how it works internally (for example if the user changes the tab you will loose the element).

Which kind of enterprise connection is it?
Does it have an email configured?

**Comment by adamtay** [comment]
@glena We have a ldap connector set up but prefer users to log in using their sAMAccountName/windows login rather than email address. So ideally, we would like to add a new login icon that when clicked, would redirect to a hosted lock page which then authenticates using the enterprise connection.

**Comment by glena** [comment]
ok I got it. No right now it is not posible using lock.
