### ISSUE TITLE
getUserInfo returns data with a different naming convention than direct Auth0 api calls

### ISSUE THREAD

**Issue by Markus-ipse** [auth0/lock#798]
Lock version: 10.9.1

When calling `lock.getUserInfo()` the returned objects' keys are camelCased, e.g. `userMetadata`,
but when I try to update the `userMetadata` by using the[ Auth0 API ](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id) it expects the patch objects' keys to be snake_cased, e.g. `user_metadata` and also the response from the  call is snake_cased.

Sample code:
```typescript
@Injectable()
export class AuthService {
  // Configure Auth0
  lock = new Auth0Lock(authConfig.clientID, authConfig.domain, {...});

  profile: any;

  constructor(private authHttp: AuthHttp) {

    this.profile = JSON.parse(window.localStorage.getItem('profile'));

    // Add callback for lock `authenticated` event
    this.lock.on('authenticated', (authResult) => {

      this.lock.getUserInfo(authResult.accessToken, (error, profile) => {

        console.log('lock.getUserInfo:', Object.keys(profile));
        // ["emailVerified", "email", "clientID", "userMetadata", "updatedAt", "name", "picture", "userId", "nickname", "identities", "createdAt", "sub"]

        window.localStorage.setItem('profile', JSON.stringify(profile));
        this.user = profile;

      });
    });
  }

  private updateUser(data) {

    this.authHttp.patch(
      withBaseUrl(`/users/${this.profile.userId}`),
      JSON.stringify(data),
      { headers: headers }
    )
      .map(response => response.json())
      .subscribe(
        response => {
          // Update profile
          console.log('authHttp /users/:user_id', Object.keys(response));
          // ["email_verified", "email", "user_metadata", "updated_at", "name", "picture", "user_id", "nickname", "identities", "created_at", "last_ip", "last_login", "logins_count"]
          this.profile = response;
          localStorage.setItem('profile', JSON.stringify(response));
        },
        error => console.error(error.json().message) // Todo: Add error real handling/logging
      );
  }
}

```

Is this intended behavior? 
Do I have to forgo lock.getUserInfo and do a "manual" API-request to get user info instead or is there way I can update user which utilize the same naming convention as `lock.getUserInfo`?

**Comment by glena** [comment]
Good catch, auth0.js (the js sdk used underneath by Lock) is normalizing all the responses to be camel case but it should not do it with the response from userInfo.

I will fix this on auth0.js and the next release (`10.10.0` next week) it will be fixed.

Thank you for reporting.

**Comment by rashfael** [comment]
Additionally, the `toCamelCase` helper seems to be transforming arrays into objects.
`{app_metadata: {groups: ["a","b","c"]}}`
becomes
`{appMetadata: {groups: {0:"a", 1:"b", 2:"c"}}}`

**Comment by glena** [comment]
can you check that last one thing with `10.9.2`?

I cant repro that one

**Comment by glena** [comment]
nvm, I just did
