### ISSUE TITLE
Lock versions after 10.8.1 *sometimes* break Windows AD SSO to Office 365

### ISSUE THREAD

**Issue by wags** [auth0/lock#818]
I have noticed strange behavior with the Auth0 Lock if I use any version higher than 10.8.1. First, here are some details about my particular use case:

- We are using Auth0's `Hosted Pages` feature to host a slightly-customized Lock interface (basically just logo and primary color... see code below). 
- Auth0's AD Connector is used to authenticate employees via Active Directory credentials.
- The Office 365 SSO Integration is configured (and has been working properly) under `SSO Integrations` in the Auth0 dashboard.
- Windows 10 is the OS in use for my tests, and both Edge and Chrome browsers were used.

When someone on a domain-registered computer navigates to our special Auth0 URL for O365 SSO, they are presented with the Lock widget, like this:
![image](https://cloud.githubusercontent.com/assets/727113/22037119/03a5fd66-dcc4-11e6-98ef-11090a113f90.png)

⚠️ Things get weird when that big blue **Windows Authentication** button is clicked.

The _first_ request (e.g. clear browser cache) ends up stopping at the default Office 365 login page, as if you had navigated to https://portal.office.com directly.

The Chrome console shows the following information:
![image](https://cloud.githubusercontent.com/assets/727113/22037603/d95be2a8-dcc5-11e6-93df-94f1f0086c58.png)

It's not clear to me if this error mentioning a cross-origin fame is related, but it doesn't happen when I use version 10.8.1 of the Lock script:
```
Uncaught DOMException: Blocked a frame with origin "https://portal.office.com" 
from accessing a cross-origin frame.
    at https://prod.msocdn.com/16.00.1589.009/en-US/js/ConciergeHelper.js:1:24665
```

Instead of seeing this:
![image](https://cloud.githubusercontent.com/assets/727113/22037818/d0d75288-dcc6-11e6-8b28-c32c535eb11a.png)

the expected behavior is to be signed-in automatically and shown the Office 365 Welcome dashboard.

Strangely enough, navigating to the Auth0 SSO URL again _usually_ leads to a successful login... you just have to work at it a bit.

The logout (from Office 365)  _sometimes_ seems to be affected as well. Instead of fully logging out properly, I have to select the account to sign out of:
![image](https://cloud.githubusercontent.com/assets/727113/22038175/2ad2530e-dcc8-11e6-9259-ac394f756057.png)
_I must note that I have seen this before when doing testing and logging in and out of a couple different accounts._

I tested versions `10.9.0`, `10.9.1` and `10.10.0` of the Lock and got the same results. Again, with version `10.8.1`, the single sign-on login process works smoothly every time.

Not sure if the regression came along with the newer versions of Lock, or if I need to update the my custom code to keep up with the new versions. I figured I would share what I'm seeing and kick off the conversation! 😄 

Here is the (working) Lock code from my Auth0 dashboard (Hosted Pages):
```html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Sign In with Auth0</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

    <!--[if IE 8]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ie8/0.2.5/ie8.js"></script>
    <![endif]-->
    <!--[if lte IE 9]>
    <script src="https://cdn.auth0.com/js/base64.js"></script>
    <script src="https://cdn.auth0.com/js/es5-shim.min.js"></script>
    <![endif]-->

    <script src="https://cdn.auth0.com/js/lock/10.8.1/lock.min.js"></script>
    <script>
        var authParams = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));
        var connection = authParams.connection;
        var languageDictionary;
        var language;
        if (authParams.dict && authParams.dict.signin && authParams.dict.signin.title) {
            languageDictionary = {
                title: authParams.dict.signin.title
            };
        } else if (typeof authParams.dict === 'string') {
            language = authParams.dict;
        }
        var lock = new Auth0Lock(authParams.clientID, authParams.auth0Domain, {
            closable: false,
            language: language,
            languageDictionary: languageDictionary,
            theme: {
                logo: 'https://s3.amazonaws.com/custom-logo.png',
                primaryColor: '#444'
            },
            auth: {
                redirectUrl: authParams.callbackURL,
                responseType: authParams.callbackOnLocationHash ? 'token' : 'code',
                params: authParams.internalOptions
            }
        });
        lock.show();
    </script>
</body>
</html>
```

Thanks for reading all this. I'm looking forward to helping identify the cause and a solution, if possible.

**Comment by glena** [comment]
hi @wags would it be posible for you to provide two HARs files for this flow with two versions (one working -version 10.8.1- and one which doesnt -version 10.10.0-)?

Please submit a ticket in our support center (https://support.auth0.com) and paste here the ticket id so I can follow up there.

**Comment by wags** [comment]
Hi @glena! I saved the HAR files for you and opened an Auth0 ticket. It is number # 19216 in your support system. Thank you for looking into this for me.

**Comment by glena** [comment]
Got the ticket, will take a look tomorrow.

Thank you

**Comment by glena** [comment]
@wags one of the HARs seems to be corrupted, I shoot you an email.

**Comment by wags** [comment]
@glena sorry about that. I managed to get a good HAR for `v10.8.1` and updated that support ticket.

**Comment by glena** [comment]
hi @wags, we just released `10.10.1` with the fix. 
Let me know if the kerberos flow works properly.
Thank you

**Comment by wags** [comment]
@glena I tested the Kerberos login flow and it works nicely. Thank you for the quick fix!

**Comment by glena** [comment]
great! Thank you for reporting and helping us to troubleshoot! 🍻
