### ISSUE TITLE
Release v10.10 ?

### ISSUE THREAD

**Issue by theopak** [auth0/lock#824]
Hey can someone publish v10.10.latest? I don't see it on npm.

- auth0-lock v10.10.1 is the latest tag in this repo: https://github.com/auth0/lock/releases/tag/v10.10.1
- auth0-lock v10.9.2 is the latest/highest release published to npm: https://www.npmjs.com/package/auth0-lock
- this repo's [CHANGELOG](https://github.com/auth0/lock/blob/master/CHANGELOG.md) states that all auth0-lock v10.9.x versions are broken because they do not include a fix that v10.10.0 included
    - > for those who updated to v10.9 you need to revert the changes made to handle the case changes.

**Comment by glena** [comment]
Something should go wrong with the CI. Let me check

**Comment by hzalaz** [comment]
@theopak thanks for the heads up, will publish them manually shortly and review our CI.

**Comment by theopak** [comment]
I see v10.10 on npm now. Thanks for the quick response!
