### ISSUE TITLE
Lock v10.10.1 fails on IE 10

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#825]
Logging in with Auth0 Lock v10.10.1 fails on Internet Explorer 10:

<img width="401" alt="screen shot 2017-01-20 at 2 10 42 pm" src="https://cloud.githubusercontent.com/assets/1874682/22167322/760176c6-df1a-11e6-96a6-c67915fc75b1.png">

A workaround is to add an `auth.state` param. But, as mentioned in https://github.com/auth0/lock/issues/801, this issue was supposed to be resolved with the 10.10 release.

**Comment by hzalaz** [comment]
@maxlapides that is the line of the non-minified file?

**Comment by maxlapides** [comment]
@hzalaz i'm not sure what the line number it's referring to is. i'm using webpack, and IE doesn't really support sourcemaps.

**Comment by hzalaz** [comment]
@maxlapides the error is different as the `state` issue we had so I am curious on what it is since you say that specifying a state fixes that issue. If you can provide us the line in Lock where it fails it will help us know what's wrong.

**Comment by maxlapides** [comment]
i'm not sure how much this will help, but here's a stack trace from IE dev tools:

<img width="1552" alt="screen shot 2017-01-20 at 2 29 25 pm" src="https://cloud.githubusercontent.com/assets/1874682/22167685/e2230c00-df1c-11e6-82f3-367e3c87f7da.png">

unfortunately, i don't have much time to troubleshoot this in detail. have you been able to reproduce this issue?

**Comment by glena** [comment]
@maxlapides I was able to reproduce. We will release a patch with the fix.
