### ISSUE TITLE
Lock v10.8.1 not returning refresh_token in callback hash

### ISSUE THREAD

**Issue by gforster1993** [auth0/lock#829]
Hi 

We're running a SPA using Auth0 Lock v10.8.1 and have not enabled your 0Auth 2.0 flow. We've previously been using a refresh token to improve usability and renew the user's id token in the background. This was working fine with Lock v10 however in the past week I've been having the issue that no refresh_token is included in the callback hash from a database connection authorization request. 

Our configuration object which we initiate Auth0Lock with looks like this
```
 {
      auth: {
        redirectUrl: redirectUrl,
        responseType: 'token',
        scope: 'openid offline_access ...'
      },
      closable: false,
      autofocus: true,
      rememberLastLogin: false,
      theme: {
        logo: clientLogo,
        primaryColor: highlightColor
      }
  }
```
Completing the Lock form for a database connection results in a post request (internal to Auth0Lock) to `https://animus-technology.auth0.com/usernamepassword/login` which returns a hidden form and the callback to yourselves before returning with a hash which when parsed looks something like this:

```
{
  access_token: 'eyJ...',
  expires_in: 36000
  id_token: 'eyJ...'
  token_type: 'Bearer'
}

```

So for some reason a refresh token isn't been returned. To try and debug this I added a console log in a Auth0 rule to see what was the issue but looking at the field `context.request.scope` I see that `offline__access` is definitely specified as a scope.

Any idea what could be causing this?

Thanks

**Comment by hzalaz** [comment]
@gforster1993 can you try

```js
 {
      auth: {
        params: {
          scope: 'openid offline_access ...'
        }
      }
  }
```

instead of 

```js
 {
      auth: {
        scope: 'openid offline_access ...'
      }
  }
```

**Comment by gforster1993** [comment]
@hzalaz thanks. Just looked and I copied the auth object across wrong. These are the auth options we are using
```
 auth: {
        redirectUrl: redirectUrl,
        responseType: 'token',
        sso: true,
        params: {
          scope: `openid offline_access email boxUserId stripeUserId globalPermission memberships domainPermission domainMembership_id admin user`,
          device: 'animus',
          state: '/'
        }
      },
```

Which results in a request to `https://animus-technology.auth0.com/usernamepassword/login`, with the following form data:

![request](https://cloud.githubusercontent.com/assets/14568655/22243413/23606c58-e21f-11e6-86ac-d19204036ce0.png)

So the offline_access scope is definitely there.

Is the `/usernamepassword/login` route capable of processing offline_access requests? I cant see any documentation for it in the [docs](https://auth0.com/docs/api/authentication)

**Comment by hzalaz** [comment]
@gforster1993 everything works on my end with all connection types. Just answered your zendesk ticket asking for more information.

**Comment by gforster1993** [comment]
That's weird. I've sent you a response on zendesk now, thanks @hzalaz. As mentioned, I would still really appreciate some guidance with some undocumented stuff but as I've migrated from refresh tokens I will close this issue.
