### ISSUE TITLE
Doesn't work in cordova / phonegap / ionic2

### ISSUE THREAD

**Issue by dobesv** [auth0/lock#830]
I tried to update to auth0-lock 10.10.2 in my project, and found that the login popups no longer work because the new auth0 code doesn't have cordova InAppBrowser support any more: https://github.com/auth0/auth0.js/issues/331

However, even after monkeypatching `window.open` to use `InAppBrowser` properly, the login still fails, leaving me on a "something went wrong" page, and auth0 logs show an error "Unsupported response mode: auth0_owp"

I kind of reached the limit of how long I could try and debug this.  Downgrading to auth0-lock 10.8.1 fixes the problem, because it uses the auth0 v7 branch.

Hopefully anyone else having trouble with auth0-lock will find this issue helpful in understanding their problem.

**Comment by darkyen** [comment]
We are working on a QS that does not the explicit InAppBrowser support (which uses implicit auth) and instead uses PKCE which is more secure option for authenticating native applications.

**Comment by dobesv** [comment]
OK I guess I will continue with the older version of lock for now.

**Comment by hzalaz** [comment]
This should be fixed in v10.11.0 please reopen if it still fails

**Comment by ihsansatriawan** [comment]
![screenshot from 2017 02 09 12 10 00](https://cloud.githubusercontent.com/assets/5369464/22821177/890acef0-efac-11e6-90f3-533fba96383d.png)

it's happen in cordova android

**Comment by ihsansatriawan** [comment]
@hzalaz
