### ISSUE TITLE
React warning when using Auth0-lock

### ISSUE THREAD

**Issue by sedubois** [auth0/lock#832]
I get the warning below when adding Auth0-lock on my login page, how can I get rid of it?

```
Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
```

Here is the code: https://github.com/relatenow/relate/blob/ad8156e16e25eaea915280d9ca95864b5c4ef10c/pages/auth/login.js

Tested on macOS Chrome, Auth0-lock 10.10.2.

**Comment by hzalaz** [comment]
@sedubois could it be how you are using lock inside your react component? since its the root of that component and that's probably why react is complaining about

**Comment by sedubois** [comment]
@hzalaz yes, but then how should I use it instead?

**Comment by hzalaz** [comment]
Not sure but I'd say you need to wrap lock in a div so it's not the root of the component (like the warning says) but this might cause some issues. Another alternative is use Lock in overlay mode (without specifying the container)

**Comment by sedubois** [comment]
I tried wrapping in a div but still same warning. I prefer to keep inline. What I don't understand is that it seemed to work a few weeks ago.

**Comment by hzalaz** [comment]
Odd, we didn't change anything about react recently

**Comment by sedubois** [comment]
Maybe something changed on my side, but what could it be? This error is driving me nuts 😢 

This is how I modified to add an extra `div` wrapper ([see original code here](https://github.com/relatenow/relate/blob/master/pages/auth/login.js#L55)):
```js
  render() {
    return (
      <div>
        <div id={LOCK_CONTAINER_ID}>
          <style jsx>{`
            #lock-container {
              margin: 2em 0 0;
            }
          `}</style>
          <style jsx global>{`
            .auth0-lock-header {
              display: none;
            }
          `}</style>
        </div>
      </div>
    );
  }
```

But as mentioned, I still get `Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.`

How do React users inline the lock? Is there some example somewhere?

**Comment by sedubois** [comment]
I think this is due to some interaction with `styled-jsx`?

**Comment by luisrudge** [comment]
If you remove the style, does it work?

**Comment by sedubois** [comment]
Ah got it! It works when moving styled-jsx outside of the lock div:
```js
  render() {
    return (
      <span>
        <div id={LOCK_CONTAINER_ID} />
        <style jsx>{`
          #lock-container {
            margin: 2em 0 0;
          }
        `}</style>
        <style jsx global>{`
          .auth0-lock-header {
            display: none;
          }
        `}</style>
      </span>
    );
  }
```

**Comment by luisrudge** [comment]
Cool! 😎
