### ISSUE TITLE
Show options are overriding instead of merging with existing ones

### ISSUE THREAD

**Issue by glena** [auth0/lock#833]
Context:

The `show` method allows to override some configurations set in the constructor (https://github.com/auth0/lock/#showoptions). That configurations are stored in a transient state (https://github.com/auth0/lock/blob/master/src/core/index.js#L565) and later when it reads that info it checks if there is any transient info and if not gets that from the state (https://github.com/auth0/lock/blob/master/src/core/index.js#L201).

This transient info is deleted when lock is closed (https://github.com/auth0/lock/blob/master/src/core/actions.js#L111).

Issue:

when we set in `lock.show`, for example, `auth.params`, it will override all the `auth.params` set in the constructor (and the defaults like the `scope`). Instead, it should merge with existing `auth.params` and only override the existing attributes instead of the entire obj.

Also, check if there is any other allowed configuration that overrides instead of merge.

https://github.com/auth0/lock/issues/809#issuecomment-275476091

**Comment by k7n4n5t3w4rt** [comment]
I'm not sure if this is related, but I'm experiencing a problem with the scope values being overwritten in version 9.2.3, having recently updated from an earlier version.

I'm using auth0-angular with Google (only) and a popup, configured like this:

```
prvt.auth.signin({
      popup: true,
      connection: "google-oauth2",
      scope: "openid name email"
    }, _this.onLoginSuccess, _this.onLoginFailed);
```

Login is successful but at some point the scope is changed. I've tracked the options that I've passed in to signin() as far as I can, but they don't get passed to the _getMode() method of lock and _getMode() sets them to a default of "openid".

```
/**
 * Resolve response type as `token` or `code`
 *
 * @return {Object} `scope` and `response_type` properties
 * @private
 */

Auth0.prototype._getMode = function (options) {
  return {
    scope: 'openid',
    response_type: this._getCallbackOnLocationHash(options) ? 'token' : 'code'
  };
};
```

If I hack _getMode() like this, everything works fine and I have JWT with name and email in it:

```
    scope: 'openid name email',
```

**Comment by glena** [comment]
It is intended behaviour and by design. We are going to improve the docs since it might be confusing https://github.com/auth0/lock#showoptions in despite of it clearly says it will override the options.

In case of `auth.params` or `laguageDictionary` it will override the entire option and not the inner properties.
