### ISSUE TITLE
Do we still need the es2015-loose preset? 

### ISSUE THREAD

**Issue by iamkevingreen** [auth0/lock#837]
Currently this package is installing  both:

```
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-es2015-loose": "^7.0.0",
```

but in the `.babelrc` it's still using es2015-loose? es2015-loose has been depreciated. Is there any reason why this is still using -loose? (I actually had to manually set it to just use es2015 for a project of mine because loose was causing issues and seems like loose has been cooked directly into es2015 as of v6.13 and you guys are using 6.16:

```
{ presets: [ ["es2015", {"loose": true}] ] }
```

Is Loose still needed for this package? I have it running correctly in my application without it but I assume it could possibly break for older use cases.

**Comment by hzalaz** [comment]
@iamkevingreen please submit a PR and we'll take a look. Should be ok but we will test it a bit more. Is it causing some issue or is just for the sake of cleaning?

**Comment by iamkevingreen** [comment]
With -loose in the `.babelrc` I was getting the following warnings:

```
resolve failed for "caniuse-db": Error: Cannot find module 'caniuse-db'
resolve failed for "babel-runtime": Error: Cannot find module 'babel-runtime'
resolve failed for "webpack-core": Error: Cannot find module 'webpack-core'
```
which was resolved after removing the -loose

but changing it to:

```
  "presets": [ ["es2015", {"loose": true}], "stage-0", "react"]
```
or
```
"presets": ["es2015", "stage-0", "react"]
```

both worked for me. I'll PR and if it's nonbreaking I see no reason to not bump it up.

**Comment by hzalaz** [comment]
Was asking if it breaks so we can fix it faster, will wait for the PR and review it. Thanks

**Comment by hzalaz** [comment]
Part of last release
