### ISSUE TITLE
Close lock on overlay click instead of 'close icon' 

### ISSUE THREAD

**Issue by Rahul-Sagore** [auth0/lock#839]
I don't want to use `closable` option, which renders a cross icon on top right corner. When I set it to false, I see Lock widget but there is no way to close widget now.

It would be awesome to have an option like `closeOnOutsideClick`, so when anyone clicks the transparent overlay, lock widget should get closed. 

Currently I am handling it like this:

```js
function initCloseAuthModal() { // Closing auth0 lock modal on overlay click
    $('.auth0-lock-overlay').on('click', function(){
      $('.auth0-lock-container').remove();
    });
}

function displayLock() {
  lock.show();
  setTimeout(function() {
     initCloseAuthModal()
  }, 500);
}

$('.submit-button', $form).on('click',  displayLock);
```

This works fine for normal cases. But creates a problem when I click on overlay as soon as It appears, what happens it immediately removes the lock widget, but after few seconds it reappears. I am guessing there is some logic in lock.min.js.

**Comment by GeorgeKagan** [comment]
+1
Surprised it's not supported, as it's a common UI feature.

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but I'm cleaning up some stale issues. 🗑 
It's been a while since this issue was opened. We'd love to receive a PR with this if someone is willing to do it. I'll review it in a few days so we can get it released once it's ready. Thanks! 🎉
