### ISSUE TITLE
Better handling of script load/error events for client's configuration

### ISSUE THREAD

**Issue by cristiandouce** [auth0/lock#84]
There are no `removeListener`s neither the script get's removed from the DOM, making it hard to debug whether there actually was a network error or just a network timeout. And be able to handle it better.

The current behavior is the following:

![image](https://cloud.githubusercontent.com/assets/367429/5093750/bb5c644a-6f39-11e4-84ed-56519f2aadb2.png)

Where it is obvious that the timeout was executed, yet the configuration was loaded later.

Also, the timeout should be able to be disabled from options, but the only way to support it is from the `Auth0Lock` constructor (since the first request is made there to save UX and time). Meaning we may start supporting the parameter both again in the constructor and the methods `.show()` or just the constructor.

cc @jfromaniello @pose

**Comment by hzalaz** [comment]
Already fixed in v10
