### ISSUE TITLE
Service not found: http://localhost:8080 Error

### ISSUE THREAD

**Issue by ndelvalle** [auth0/lock#842]
I got a `Service not found: http://localhost:8080` error when trying to login using lock:

<img width="1280" alt="screen shot 2017-01-29 at 11 46 19 pm" src="https://cloud.githubusercontent.com/assets/6719053/22410936/31828d40-e67d-11e6-8e0f-b33914d59b94.png">

Related code:

```javascript
const lock = new Auth0Lock(
  'rl8Kjiy21AZOd62jNXGuNgIU********',
  '*******.auth0.com',
  {
    allowedConnections: ['Username-Password-Authentication'],
    rememberLastLogin: true,
    languageDictionary: { title: 'FindEarth' },
    language: 'en',
    closable: false,
    theme: {
      primaryColor:'#3A99D8',
      logo: 'https://avatars2.githubusercontent.com/u/19509447?v=3&s=200'
    },
    auth: {
      redirect     : false,
      responseType: 'token',
      sso: true
    }
  }
);

lock.on('authenticated', (err, authResult) => {
  console.log('err', err);
  console.log('authenticated', authResult);
});

lock.on('authorization_error', (error) => {
  console.log('authorization_error', error);
});

lock.show(); // to display the lock view
```
Note that the console.log's are from the `authenticated` event, Im not sure if that is ok or the error should come from `authorization_error` event.

I followed the tutorials and even downloaded the sample project and I got the same error, I already add my localhost url to `Allowed Callback URLs`. I assume Im missing something in the configuration.

Im using Google Chrome Version 55.0.2883.95 (64-bit), in a macOS Sierra. The lock version that im using is `10.10.2`.

**Comment by glena** [comment]
Do you have any active rule in your account or maybe a custom db?

**Comment by ndelvalle** [comment]
Yes I have a rule configured, but I disabled it and the error keep happening. No I don't have a custom db.
More Info: 
When I click the `try all rules with` button, and select Username-Password-Authentication (the one Im using) it redirects me to this page, even If I disable my rule:

<img width="1280" alt="screen shot 2017-02-02 at 12 36 26 pm" src="https://cloud.githubusercontent.com/assets/6719053/22555966/5365a4e6-e944-11e6-8ff2-52b92cebb617.png">

**Comment by glena** [comment]
Can you share your account name?

**Comment by ndelvalle** [comment]
`keepers-co`

**Comment by glena** [comment]
seems that you set that as your default audience but you dont have an API with that identifier

![image](https://cloud.githubusercontent.com/assets/5647310/22556277/5b6f373c-e945-11e6-9e91-62b2925245f0.png)

Clear that setting and it should work fine

**Comment by ndelvalle** [comment]
It worked! thank you very much @glena!

**Comment by snolangps** [comment]
@glena where's the "Default Audience" section located?

**Comment by glena** [comment]
go to https://manage.auth0.com, click on the right top corner and it will unfold a menu. 
Click on settings, and you should see it in the second section of the first tab 

![image](https://user-images.githubusercontent.com/5647310/35074184-7881edd0-fbcb-11e7-8d04-becc47ea366e.png)
