### ISSUE TITLE
Broken rendering of login mechanism due to library clash

### ISSUE THREAD

**Issue by patoncrispy** [auth0/lock#848]
Hey, I have a bit of a weird issue. I have a library (Stimulsoft) that seems to be causing issues with the rendering of Auth0-lock. There are no errors in the console and you can still log in, despite the broken rendering. I have already raised a ticket with Stimlusoft's support team but I thought I'd post it here to see if I can get some added insight. I have attached the images of the problem. I guess I'm curious about what could possibly cause a conflict that wouldn't show up in the logs but would still prevent Auth0-lock from rendering correctly.

Please let me know if more information is required. I have also attached a sample application that can be run to replicate the problem, with step by step instructions on how to do so.

![auth0-render-2](https://cloud.githubusercontent.com/assets/2559414/22476970/3b2d2412-e7dc-11e6-901a-3fdcbf2b9bc8.PNG)
![auth0-render-1](https://cloud.githubusercontent.com/assets/2559414/22476969/3b26ccc0-e7dc-11e6-9fc8-2ac9e9a7e2e3.PNG)

[sampleapp.zip](https://github.com/auth0/lock/files/742723/sampleapp.zip)

**Comment by glena** [comment]
Looks like it is not loading the css... maybe...

Can you check if the css is being injected into the page after you initialize lock?

**Comment by patoncrispy** [comment]
Yeah, that seems to be there alright. Has `id="auth0-lock-style"`, so I presume that is the right one.

**Comment by patoncrispy** [comment]
At the moment I have the Auth0 code injected after the Stimulsoft stuff, but I've also tried the other way around and the same problem.

**Comment by glena** [comment]
and if you remove the Stimulsoft one does it work properly?

**Comment by patoncrispy** [comment]
Yeah. Perfectly.

**Comment by glena** [comment]
We just checked the code you sent and seems fine. Cant tell what is Stimulsoft doing that might break lock (if the css is being loaded fine, maybe there is something changing the classnames of lock).

**Comment by patoncrispy** [comment]
Strange that it works for you... Thanks anyway for getting back to me. Will soldier on and if I can figure out what the problem is I'll update this.
