### ISSUE TITLE
prefill option gives "Please use your corporate email to login"

### ISSUE THREAD

**Issue by larsthorup** [auth0/lock#854]
The prefill option appears to no longer work correctly. The prefill email is correctly filled out in the Lock dialog, but when the user then presses "tab", enter password, "return", a validation error is shown for the email field with the text "Please use your corporate email to login", see the attached screenshot. If the user then clicks the email field, deletes and retypes a single character, and then click "return" then validation succeeds and the form is submitted.

The issue can be reproduced with the HTML code below. Note that the clientId / domain combination that I use is configured for "Username-Password-Authentication" connection.

Browser: Seen in Firefox and Chrome
OS: Seen on Windows

    <script src="http://cdn.auth0.com/js/lock/10.11.0/lock.min.js"></script>
    <script>
    var clientId = '(my clientId)';
    var domain = '(my domain)';
    var options = {
      allowedConnections: [
        'Username-Password-Authentication'
      ],
      prefill: {
        email: 'lars@example.com'
      }
    };
    var lock = new Auth0Lock(clientId, domain, options);
    lock.show();
    </script>
![2017-02-02 21_49_34-mozilla firefox](https://cloud.githubusercontent.com/assets/1202959/22568189/1b75b838-e993-11e6-8d66-2fe69bc08b26.png)

**Comment by larsthorup** [comment]
Thanks for getting to this quickly. Looking forward to test it in the next release.

**Comment by larsthorup** [comment]
So, when do you plan to cut the next release?

**Comment by luisrudge** [comment]
Hi @larsthorup! This will be in the next release (this week)
