### ISSUE TITLE
Autocorrect enabled for username field in Safari on iOS

### ISSUE THREAD

**Issue by garie** [auth0/lock#864]
- Lock version: 10.9
- Browser & OS: Safari, iOS 9.3, iPad 2

We are using the Lock widget for login on a mobile app. On iOS, autocorrect is enabled for the username field. Here is a demonstration of the recommended HTML for disabling autocorrect across all browsers: https://davidwalsh.name/disable-autocorrect

From a look through the codebase, `autocomplete` and `autocapitalize` are disabled but `spellcheck` and `autocorrect` are not.

Sorry I'm not submitting a PR for this - the fix seems simple. I started to make one and then decided that I should probably stop since I have no idea what I'm doing.

**Comment by luisrudge** [comment]
Thanks @garie. This was fixed and will be in the next release
