### ISSUE TITLE
Rules aren't being checked when using the Lock

### ISSUE THREAD

**Issue by halt-hammerzeit** [auth0/lock#865]
I've set up a rejecting rule in the dashboard.
While the "Try" button fails the Lock component still authenticates "successfully".
Isn't it checking the rules?
I can see the logged-in users in the dashboard.

```js

const auth0LockOptions = {
  auth: {
    redirect: false
  }
};

    const lock = new Auth0Lock('key', 'domain', auth0LockOptions);
    lock.show();
    lock.on('authenticated', (authResult) => {
      console.log(authResult)
    });
```

**Comment by halt-hammerzeit** [comment]
And the `accessToken` is:

```js
Object 
error: "unauthorized"
errorDescription: "Access denied."
state: "lIC.dSEoKp6HYJfztEFx9yf8zFDEZA-J"
__proto__: Object

```

**Comment by halt-hammerzeit** [comment]
I'm using 10.9.1

**Comment by hzalaz** [comment]
@halt-hammerzeit can we get a minimal code for the url and the login page we can use to see what's wrong? (maybe a codepen is enough). Also the `console.log` of https://github.com/auth0/lock/issues/865#issuecomment-278762305 is from the `lock.on('authenticated', fn)` call? could it be that is from the `lock.on('authorization_error', fn)` call by chance?

**Comment by halt-hammerzeit** [comment]
We have since moved on to another authentication approach because the initial design was found to be overengineered.
And the code is different now.
So I'm closing this for now.

**Comment by jkehler** [comment]
I'm also experiencing this issue. "authorization_error" hook is not called when using redirect: false option on auth0-lock.
