### ISSUE TITLE
authorization_error not firing on user login in user migration scenario

### ISSUE THREAD

**Issue by mohrtan** [auth0/lock#866]
We're using Auth0's custom database to migrate accounts. When switching to Auth0 lock (version 10.11.0) we found that the "authorization_error" event is not firing when users already migrated attempt to login a 2nd time using non-auth0 credentials (our custom DB values). We tracked this to the following lines of code in the 10.11.0 version of the lock.js file:

Line 8374 - 8376
```
if (["blocked_user", "rule_error", "lock.unauthorized"].indexOf(error.code) > -1) {
  l.emitAuthorizationErrorEvent(m, error);
}
```

There are two issues on line 8374.
1) The error returned in this scenario is "invalid_user_password", which is not accounted for in the current statement. The error.description contains the text indicating the user has already been migrated.
2) The actual error is found in "error.error" not "error.code", which is the value being scanned. "error.code" does not seem to be a valid reference in this scenario.

I don't know how common this is, but we're using a custom version of the script currently for testing and have fixed this with the following code on line 8374:

Line 8374 - 8376
```
if (["blocked_user", "rule_error", "lock.unauthorized", "invalid_user_password"].indexOf(error.error) > -1) {
  l.emitAuthorizationErrorEvent(m, error);
}
```

However, we don't know under what circumstances "error.code" may contain a valid value, so simply checking error.error may not be sufficient in our minds. Otherwise we would have submitted a potential fix via a pull request.

Please advise if our assertions above are incorrect and there is in fact a better way to handle this scenario.

**Comment by hzalaz** [comment]
@mohrtan can you explain why you need to handle that error in the `on` event? This error is usually handled by Lock by displaying a customizable message so that's why is not reported back (but we can review your change after knowing a little more your use case)

**Comment by hzalaz** [comment]
@mohrtan any news?
