### ISSUE TITLE
Error messages do not allow html formatting

### ISSUE THREAD

**Issue by dariobanfi** [auth0/lock#878]
Hi,

Is there any reason why error messages displayed by the lock do not allow html formatting?

For example, given this lock parameters:

```
error: {
  login: {
     'lock.invalid_email_password': '<b>Error</b>, Invalid Email or Password'
  }
}
```

Which results as:

![screen shot 2017-02-23 at 17 06 25](https://cloud.githubusercontent.com/assets/4538567/23267242/7102e976-f9ea-11e6-8365-281f7ed3ae04.png)

This could be easily changed by using `i18n.html` here: https://github.com/auth0/lock/blob/master/src/core/index.js#L511 and it's what most of other messages do (for example `success.signUp`).

**Comment by luisrudge** [comment]
Thanks @dariobanfi. I added a PR to support html messages (both error and success). We'll discuss internally if we want to support more stuff as html or not, but this should be in the next release.
