### ISSUE TITLE
typos in Italian language

### ISSUE THREAD

**Issue by alkaest2002** [auth0/lock#880]
Lock version 10.0
-------------------------

Hi,
there are several typos in the Italian language localization.
I'll throw in few examples. 

_Google sign-in button_: the current Italian version says "**Accede** con Google". It should be "**Accedi** con Google". 

_Google sign-up button_: the current Italian version says "**Registra** con Google".  It should be  "**Registrati** con Google".

_Password field placeholder_ :  the current Italian version says "La **sua** password". But it might better be "La **tua** password".

While the first two examples are typos, the last one is a matter of stylistic choice between formal and informal register (the latter being way more common in internet pages).

Please, bear in mind that there are other issues.

Hope these sparse suggestions help your "translations guys".

**Comment by hzalaz** [comment]
Thanks @alkaest2002 most of ours translations are done by using Google translate plus some community/employee contributions. If you find typos please submit a PR and we'll merge it quickly.
