### ISSUE TITLE
App rejected by Apple because Auth0 signUpLink doesn't open in Cordova InAppBrowser but in system browser (Safari)

### ISSUE THREAD

**Issue by bryandh** [auth0/lock#883]
Our Ionic 2 mobile app was rejected by apple because of the following reason:
> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience. 
Please revise your app to enable users to sign in or register for an account in the app. 

As Auth0 seems to support usage of the Lock in Ionic 2, I think this issue is worth mentioning here.

Auth0 Lock version: 10.6 (have also tried on 10.11, didn't solve the issue)  
Ionic version: 2.1.0
OS: iOS

The Auth0 Lock provides the user with a sign up button that we configured through the `signUpLink` option of the Lock. This button opens a registration page in the system browser (Safari) outside of the application, which apparently isn't acceptable for Apple.

Before we upgraded to the latest version of Ionic 2 (Ionic 2 beta 11), the lock would open the link in the InAppBrowser, which **is** acceptable for Apple.

I made sure I had the [Cordova InAppBrowser plugin](https://github.com/apache/cordova-plugin-inappbrowser) installed. It's present in my config.xml as `<plugin name="cordova-plugin-inappbrowser" spec="~1.6.1" />` and when I open the .xcproject file in XCode, the plugin is present in the Plugins folder. I have also tested using the InAppBrowser manually using `open('https://www.google.com/, '_blank');` which opened the InAppBrowser as it should.

Neither the code regarding the Auth0 Lock, nor the URL to the registration page changed.

Fixing issue #586 might resolve this issue.

**Comment by ihsansatriawan** [comment]
@bryandh maybe you need upgrade auth0-lock version to v10.11, they said it's fix inAppBrowser problem

but in my case (cordova) it's still not work

**Comment by bryandh** [comment]
@ihsansatriawan I've upgraded to Auth0 Lock version 10.11 but that didn't solve the problem.

**Comment by bryandh** [comment]
I have come up with a dirty temporary workaround by adding an `onclick` attribute to the button that opens the link in the `window.open` function:
```
        this.lock.on('show', () => {
            let parent: Element = undefined;
            let intervalIndex = 0;
            let interval = setInterval(() => {
                parent = document.getElementsByClassName('auth0-lock-tabs')[0];

                if (parent) {
                    let item = parent.children.item(1).children.item(0);
                    item.setAttribute('onclick', `window.open('${AppSettings.registrationUrl}', '_blank'); return false;`);
                    item.removeAttribute('href');

                    clearInterval(interval);
                }

                if (intervalIndex == 20)
                    clearInterval(interval);

                intervalIndex++;
            }, 500);
        });
```

**Comment by hzalaz** [comment]
@bryandh the signUpLink is only meant to be used inside a browser since its just a common redirect and in Cordova based app this will probably break your app since it will navigate away from it (if allowed by the cordova whitelist plugin). Sadly there are no plans to enable this feature in Cordova for the time being.
