### ISSUE TITLE
Auth0 Lock unexpectedly closes on pressing the sign up button since 10.5

### ISSUE THREAD

**Issue by bryandh** [auth0/lock#885]
The Auth0 Lock is the login screen for my Ionic 2 mobile application, which is an SPA. When the user presses the sign up button, an InAppBrowser opens at a registration URL where the user can enter information in a form. Upon returning from the InAppBrowser, the lock would be closed, exposing the underlying application. This caused some concern as I tried to find out why this happened.

I noticed this was implemented in release 10.5 whereas the lock wouldn't close in release 10.4 by testing the sign up button on several versions of the lock and therefore stumbled upon this closed issue: #619 which doesn't really explain why this behaviour was implemented.

I have configured the Auth0 Lock to not be closable, not autoclose and not login after sign up.

Why is closing the Lock on pressing the sign up button the expected behavior? Shouldn't the Auth0 Lock 'lock' the user out of the SPA **until** the user logs in and gets authenticated?

If this is the desired behaviour for the lock, how am I supposed to reopen it on returning to the SPA?

For now, I'll have to remain on lock version 10.4.

Auth0 Lock version: 10.5-10.11
Ionic version: 2.1.0
OS: iOS

**Comment by hzalaz** [comment]
@bryandh maybe related to the other issue you submitted, the `signUpLink` option was meant to be used inside a cordova app so we added this auto-close to fix a customer issue regarding this https://github.com/auth0/lock/issues/619 in a web spa. Since you wired up a custom window open you could potentially know when that window is closed and then show lock.

**Comment by hzalaz** [comment]
Closing this one since when a custom signup link is used, the app should take care of the rest of the auth flow and showing Lock again if needed
