### ISSUE TITLE
Clicking the Login tab redirects the page when Lock is embedded in a container

### ISSUE THREAD

**Issue by ianstigator** [auth0/lock#887]
I have embedded the Lock widget in a container on a page that has a url of "**https://mysite.com/#/login**". 

The href link for the Login tab is href="#" which then redirects the page to "**https://mysite.com/#/**". Is there a way to configure a link for the Login tab so it doesn't unnecessarily redirect the page?

**Comment by hzalaz** [comment]
@ianstigator can you build as a small sample to repro it (or provide us with complete instructions on how to build it and reproduce the issue)? We are unable to repro it
