### ISSUE TITLE
Android Custom Theming 

### ISSUE THREAD

**Issue by ispam** [auth0/lock#888]
Hello,

I want to say theres a bug on Android Custom Theming using Lock Version: 'com.auth0.android:lock:2.0.0', but when changed to Version: 'com.auth0.android:lock:2.+' It fixes.
The relevant code is unchanged when trying different version.
**Android Manifest**

     `<activity
        android:name="com.auth0.android.lock.LockActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:screenOrientation="portrait"
        android:theme="@style/MyTheme">
        </activity>`
**MyTheme**

    `<resources>
        <style name="MyTheme" parent="Lock.Theme">
        <item name="Auth0.HeaderLogo">@drawable/com_auth0_lock_header_logo</item>
        <item name="Auth0.HeaderTitle" parent="Lock.Theme.Text.Title">@string/app_name</item>
        <item name="Auth0.HeaderTitleColor">@color/com_auth0_lock_text</item>
        <item name="Auth0.HeaderBackground">@color/com_auth0_lock_header_background</item>
        <item name="Auth0.PrimaryColor">@color/colorPrimary</item>
        <item name="Auth0.DarkPrimaryColor">@color/colorPrimaryDark</item>
    </style>
</resources>`

**Comment by hzalaz** [comment]
@ispam this is the repo for lock.js, the repository for the android version is https://github.com/auth0/Lock.Android. Also it could be a bug fix in a latest release that fixes your issue so please check the CHANGELOG.md
