### ISSUE TITLE
auth0-lock 10.12.1 breaking

### ISSUE THREAD

**Issue by mikeedwards** [auth0/lock#896]
Version 10.12.1 of auth0-lock creates an error:
```
Uncaught Error: clientID is required.
    at required (assert_required.js:17)
    at new Auth0 (index.js:142)
    at ~~our_client_id_here~~:526
    at ~~our_client_id_here~~:416
```
 in the auth0 pop-up after logging in from our site.

The error (which is wicked hard to catch since it happens on the pop up) happens near line 399 of the generated javascript at the auth0.com url that resembles `https://ourcompany.auth0.com/sso_dbconnection_popup/~~our_client_id_here~~`:

```javascript
function onMessage(e) {
          // only one message gets through, but let's make sure it's actually
          // the message we're looking for (other code may be using
          // postmessage) - we do this by ensuring the payload can
          // be parsed, and it's got an 'a' (action) value of 'request'.
          var d;
          try {
            d = JSON.parse(e.data);
          } catch(err) { }
          if (!d || d.a !== 'request') return;
          removeListener(window, 'message', onMessage);
          o = e.origin;
          if (cb) {
            // this setTimeout is critically important for IE8 -
            // in ie8 sometimes addListener for 'message' can synchronously
            // cause your callback to be invoked.  awesome.
            setTimeout(function() {
              cb(o, d.d, function(r) {
                cb = undefined;
                doPost({a: 'response', d: r});
              });
            }, 0);
          }
        }
```

The value `d.d` is undefined, which is usually the object that carries the clientId value. Only `d.a` gets set to anything (`'request'`). Otherwise, the `d` object is empty.

It's a little difficult to describe this error any more beyond this, but reverting back to 10.11.0 solved the issue for us. I saw issues on here from a year or so ago that showed similar errors due to something with minification, and I noticed that 10.12.1 included transpilation changes, so that _may_ be the culprit here.

Hope that helps!

**Comment by hzalaz** [comment]
@mikeedwards it might be related to https://github.com/auth0/lock/pull/897. Can you try again with latest release? If its not working can you pass along how you configured Lock and if you are using the CDN bundle or you import it from npm?

**Comment by mikeedwards** [comment]
Yup, 10.12.2 fixes the issue for me. Thanks!

**Comment by mikeedwards** [comment]
Argh, looks like I spoke too soon--I may have left an earlier version of auth0-lock in my node-modules by mistake. Testing it more thoroughly, I can get auth0-lock to work up to `10.11.0`, but subsequent versions fail, including the latest `10.12.2`.

I'm using the version straight from npm, no CDN. If there are specifics you need from my Lock config, let me know.

**Comment by hzalaz** [comment]
@mikeedwards a repro project where we can debug it since you are bundling it yourself and we can't be sure if something you did affected Lock.

If you can repro it with the CDN bundle, maybe using one of our quickstarts, will help too (since it will be a Lock issue not your bundle issue )

**Comment by leafchild0** [comment]
Facing the same issue using latest:
auth0-lock 10.12.2 
angular-lock 1.0.5

Works fine for any social providers, though.

**Comment by hzalaz** [comment]
@mikeedwards @leafchild0 sadly I need at least repro steps and how you initialized lock so we can at least try to build something to reproduce it.

**Comment by XaserAcheron** [comment]
Just bonked my head against this too. `ember-simple-auth-auth0` exhibits the same issue; if it helps, here's the lock options (slightly-anonymized) I'm using:
```javascript
var lockOptions = {
	container   : 'lock'
,	avatar      : null
,	allowSignUp : false
,	autoclose   : true
,	auth: {
		params: {
			scope: 'openid email'
		}
	,	redirect: false
	}
,	theme: {
		logo        : 'assets/images/logo.png'
	,	primaryColor: '#004828'
	}
,	languageDictionary: {
		title: "Sign in"
	}
};

// i'm technically not calling this line directly (the Ember
// addon's doing it), but virtually-speaking...

var clientId = "[insert_client_id_here]";
var domain = "[insert_domain_here]";
var lock = new Auth0Lock(clientId, domain, lockOptions);

// ...
```

Dunno if this helps. There could be some magic going on in the ember addon that's futzing with things, though I haven't been able to pick out anything suspicious after some basic spelunking.

Pinning the version back to 10.11.0 fixed the issue, for the record. I'm also on version 8.3.0 of auth0.js, in case that's relevant. 

Apologies for the quick drive-by. I'm also in that annoying situation where my project is behind closed-source doors. Not sure if I'll have time in the near future to put together a quick sample; the current dev train is going at breakneck speed.

**Comment by hzalaz** [comment]
@XaserAcheron thanks, this helps a bit. What are the repro steps I need to do in Lock to reproduce the error?

**Comment by XaserAcheron** [comment]
I don't suppose "use it" is a helpful answer. :P

In seriousness, my own use of Lock is abstracted behind [a framework](http://emberjs.com) and [two](github.com/simplabs/ember-simple-auth) [addons](https://github.com/seawatts/ember-simple-auth-auth0), so there's no real way for me to answer the question aside from setting up a sample project. I'll try, but can't guarantee the time.

Just in case, my repro plan would be to set up an ember.js project using:
- [Ember/Ember-CLI 2.11](http://emberjs.com)
- [ember-simple-auth](github.com/simplabs/ember-simple-auth)
- [ember-simple-auth-auth0](https://github.com/seawatts/ember-simple-auth-auth0)

...and use that to bring up the Lock. That more or less matches my environment in all the relevant areas, though it's a non-trivial bit of setup to make the app.

Bit sledgehammer-y, so I may try using Lock "raw" to see if it comes up. Still though -- time crunch. :<

**Comment by hzalaz** [comment]
@XaserAcheron I mean what are the UI actions I need to do in lock to trigger the error, e.g. Login with Google only or Login with Email/Password or Signup or Login first with a connection and then use the remember last login

**Comment by XaserAcheron** [comment]
Email/Password login (Auth0-hosted database). Only seems to happen from the username+password prompt; the handy last-login button bypassed the issue the one time I tried it.

**Comment by chriswhong** [comment]
I am also experiencing this issue using Lock 10.12.3, bundling with webpack, no add-ons or anything.  

Lock options look like this:

```
const clientId = appConfig.auth0_client_id;
const domain = appConfig.auth0_domain;

const lockOptions = {
  allowSignUp: true,
  allowLogin: true,
  autoclose: true,
  loginAfterSignUp: true,
  auth: {
    redirect: false,
  },
  theme: {
    logo: '/img/logo_80.png',
    primaryColor: '#EA6200',
  },
  languageDictionary: {
    title: 'Please log in',
  },
  additionalSignUpFields: [
    {
      name: 'name',
      placeholder: 'Your Name',
    },
    {
      name: 'organization',
      placeholder: 'Your Organization',
    },
    {
      type: 'select',
      name: 'industry',
      placeholder: 'Your Industry',
      options: [
        { value: 'government', label: 'Government' },
        { value: 'planning', label: 'Planning' },
        { value: 'nonprofit', label: 'Non-Profit/Civic Group' },
        { value: 'realestate', label: 'Real Estate' },
        { value: 'technology', label: 'Technology' },
        { value: 'student', label: 'Student' },
        { value: 'independent', label: 'Independent' },
        { value: 'other', label: 'Other' },
      ],
      prefill: 'us',
    },
  ],
};
```

As mentioned earlier, it only happens when the login + password prompt appears, if it has your username saved then the login works as expected.

**Comment by chriswhong** [comment]
Rolled back to 10.11.0 as @mikeedwards noted, and the issue is no longer present

**Comment by XaserAcheron** [comment]
A bit belated, but I'm posting to confirm that everything works fine after updating to the the latest version of Lock (10.13.0). Thanks, @hzalaz!

**Comment by Floby** [comment]
Same here :)

**Comment by luisrudge** [comment]
Thanks for the feedback folks!
