### ISSUE TITLE
10.12.2 requires node 6.9.1, but 6.10 is LTS release

### ISSUE THREAD

**Issue by davidascher** [auth0/lock#899]
Greenkeeper just tried to update my project w/ the latest auth0, and that broke the build because auth0-lock requires node 6.9.1, but on Travis node 6 is at 6.10.

See https://travis-ci.org/participedia/frontend/builds/207501671

Is this dependency correct, or is this just overly aggressive version locking?

**Comment by hzalaz** [comment]
It is added that since it's what most of our lock developers are using as a start since before there was no indication of the minimum version. 
Will try to lessen the restriction of it in a future release.

**Comment by hzalaz** [comment]
Also it is compatible with anything after v6.9.1 (like `^6.9.1`)

**Comment by davidascher** [comment]
Hmm Travis is reporting:

```
$ node --version
v6.10.0
error auth0-lock@10.12.2: The engine "node" is incompatible with this module. Expected version "~6.9.1".
```

which makes sense as the current requirement is `~6.9.1`, not `^6.9.1`, and so doesn't consider `6.10.0` as compatible.

Would you accept a PR that changes the `~` to a `^`?

**Comment by davidascher** [comment]
Never mind, i see you already changed it.  Thanks.
