### ISSUE TITLE
Version 10.12.1 popup mode fails after authentication

### ISSUE THREAD

**Issue by Burneh** [auth0/lock#900]
Version 10.11.1 works fine

In popup mode, things start off normally. I select a social login (we tried both LinkedIn and Git Hub) then proceed through their login. After the login happens, instead of the pop up disappearing (and the check mark happening), it redirects the popup to the website with the url + access token, as if the lock was in redirect mode.  So now the Popup has our website in it, and the main website window still has the lock, waiting for the authenticate call to happen.

**Comment by hzalaz** [comment]
@Burneh check latest patch release

**Comment by ihsansatriawan** [comment]
Yup...use latest patch...everything ok...thx @hzalaz and auth0 team... :+1:
