### ISSUE TITLE
Does a native Lock exist (without react?)

### ISSUE THREAD

**Issue by gebrits** [auth0/lock#905]
I'm getting a React warning in my console when adding Lock. 
Double checking using webpack dependency graph, it indeed seems that `auth0-lock` adds react + react-dom. 

Not sure if I'm including the correct version or are all versions build on top of react?
Dependencies are rather big for this it seems.

**Comment by hzalaz** [comment]
@gebrits, no there is no such version and we don't have plans to remove react from lock from the time being. You can try building your own lock with https://github.com/auth0/auth0.js
