### ISSUE TITLE
How to configure CSP for lock

### ISSUE THREAD

**Issue by roryprimrose** [auth0/lock#906]
I'm using 10.12.2 and trying to show the lock UI in a CSP controlled https site. There are a couple of issues with this. 

Firstly lock was trying to load the logo as http://cdn.auth0.com/styleguide/1.0.0/img/badge.png which would produce a mixed content warning on my site. I got around this by doing the following:

```
        let options = {
            theme: {
                labeledSubmitButton: false,
                logo: "https://cdn.auth0.com/styleguide/1.0.0/img/badge.png"
            }
        };
        let lock = new Auth0Lock(this.config.clientId, this.config.authDomain, options);
```

The next issue is that lock uses inline styles for dynamically created elements which violates my CSP. 

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= 'sha256-drxkAgexP3vnyyGpnrTDzfU4RVDNGsNBpVWCC4e5DJo=". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= 'sha256-drxkAgexP3vnyyGpnrTDzfU4RVDNGsNBpVWCC4e5DJo=". Either the 'unsafe-inline' keyword, a hash ('sha256-drxkAgexP3vnyyGpnrTDzfU4RVDNGsNBpVWCC4e5DJo='), or a nonce ('nonce-...') is required to enable inline 
```

I am reluctant to allow inline styles. Is there an alternative? Is there a CSS reference that can be pulled in?

**Comment by roryprimrose** [comment]
I've added the following to my CSP config which seems to work on chrome at least.

```

        styleSrc: [
            "'self'",
            "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='", // Auth0 lock
            "'sha256-drxkAgexP3vnyyGpnrTDzfU4RVDNGsNBpVWCC4e5DJo='"  // Auth0 lock
        ],
```

**Comment by hzalaz** [comment]
@roryprimrose sadly there is no other way for the inline styles but I will push in our backlog to have a cdn bundle without the css so it can be added via script.

About the logo we won't do a lot since its more likely for you to use your own 😄 .

Will close the issue since we don't track here our backlog

**Comment by cherring** [comment]
Did this ever get made so it can be added via script @hzalaz?
