### ISSUE TITLE
Uncaught Error: clientID is required. when clientID is there...

### ISSUE THREAD

**Issue by Floby** [auth0/lock#911]
When updating from 10.10 to >=10.11, then login with a previously unknown username/password fails with the error 

    Uncaught Error: clientID is required.

We are using `redirect: false` so the error happens in the popup window even though the popup url is:

    https://<account>.eu.auth0.com/sso_dbconnection_popup/<valid client id>

**Comment by hzalaz** [comment]
Closed as dupe of #896
