### ISSUE TITLE
Checkbox in additional fields ignored on signup with social provider

### ISSUE THREAD

**Issue by d-winter** [auth0/lock#914]
Hi,
i use the lock widget for the authorization of our app.
I noticed, that when using social providers as signup method, the additional fields are not passed to the auth0 rule, which parses the request.
When I signup with email/password, the additional fields are passed correctly.
Any ideas why those fields are ignored?

**Comment by hzalaz** [comment]
They are, because those fields are only used for database signup and not for social. Sadly this is a change we need to do in our backend so I'd suggest reaching us via https://support.auth0.com to request the feature.

**Comment by d-winter** [comment]
Thanks for the info. I will create an issue at auth0.
