### ISSUE TITLE
Broken client consent avatar

### ISSUE THREAD

**Issue by pacey** [auth0/lock#917]
When I add scopes to lock auth.params, the consent dialog shows an avatar for the client that is requesting the permission. In this instance the client is called "V-Hub".

It looks like there is a bug (or lack of docs/warnings) as the avatar that is generated fails to load, because it takes the first 2 characters from the client name "V-Hub". I'm not sure what the current logic is, but I'd assume it should take the characters "VH".

The requested avatar url is `https://cdn.auth0.com/avatars/v-.png` which fails to load with a 403 Forbidden.

![screen shot 2017-03-10 at 12 42 12](https://cloud.githubusercontent.com/assets/3204561/23795953/2063d348-0590-11e7-857f-36bec65e1695.png)

This is using Lock 10.12.3 running in Chrome on Mac.

I'd be happy to fix this (if it is indeed a bug) with a point in the right direction.

Thanks

**Comment by hzalaz** [comment]
@pacey that is not lock 😄  (even if it looks similar) but besides that it's an issue and I reported it to our backend team. As a workaround try setting an image for your tenant in your [dashboard account settings](https://manage.auth0.com/#/account)

**Comment by pacey** [comment]
@hzalaz Woops - sorry. I didn't know where the boundaries of lock end :) Thanks for flagging it up with the backend team
