### ISSUE TITLE
When registering with known breached password you get a bad error message

### ISSUE THREAD

**Issue by ntotten** [auth0/lock#929]
When breached password detection is enabled, you cannot register with a known compromised username/password - which makes sense. However, what happens under the covers is actually the account gets created, but it cannot be authenticated. The error message given by lock is also not helpful.

Ideally the account shouldnt be allowed to register, but if not at least the error message needs to be useful.

![image](https://cloud.githubusercontent.com/assets/282782/23972614/b61c3e2c-098f-11e7-9dc9-eca3a8b76ed3.png)

**Comment by hzalaz** [comment]
Was fixed in https://github.com/auth0/lock/pull/817
