### ISSUE TITLE
prefill option is lost after reset password

### ISSUE THREAD

**Issue by larsthorup** [auth0/lock#933]
The prefill option does not carry through the reset password flow, so after requesting a password reset, Auth0 redirects back to the login screen but now with an empty email field. I would expect email to still be filled out, to minimize the chance of typos in the email field during login (which is why we are using prefill in the first place). See the screen shots below for details.

The issue can be reproduced with the HTML code below. Note that the clientId / domain combination that I use is configured for "Username-Password-Authentication" connection.

Browser: Seen in Chrome
OS: Seen on Windows

```
<script src="https://cdn.auth0.com/js/lock/10.11.0/lock.min.js"></script>
<script>
var clientId = '(my clientId)';
var domain = '(my domain)';
var options = {
  allowedConnections: [
    'Username-Password-Authentication'
  ],
  prefill: {
    email: 'lars@example.com'
  }
};
var lock = new Auth0Lock(clientId, domain, options);
lock.show();
</script>
```
![login-prefill-before-reset](https://cloud.githubusercontent.com/assets/1202959/24052811/15eadcb6-0b37-11e7-8011-b724d08a04df.png)
![login-prefill-reset](https://cloud.githubusercontent.com/assets/1202959/24052824/1dc0527c-0b37-11e7-9833-cb9bce3afbe7.png)
![login-prefill-after-reset](https://cloud.githubusercontent.com/assets/1202959/24052835/23294e4e-0b37-11e7-8bb7-6b5796c4e6a4.png)

**Comment by luisrudge** [comment]
I just opened a PR to fix this. It won't use the `prefill` value. It will use the actual email the user submitted. So, if you have `prefill: 'foo@bar.com'` and the user changes the email input to `bar@foo.com`, it will keep `bar@foo.com` when it goes back to the login page.

**Comment by larsthorup** [comment]
@luisrudge Thank you! That makes perfect sense. Looking forward to try it out soon.

**Comment by luisrudge** [comment]
This will be in the next release on Monday, if everything goes according to plan. 🎉  :shipit:

**Comment by nlake44** [comment]
@larsthorup Did this fix work for you? I'm seeing that the prefill option is only filling in the forgot password email and not the login email for version 10.16.0.

**Comment by larsthorup** [comment]
@nlake44 I am not actively using this feature at the moment, so I don't know.

**Comment by luisrudge** [comment]
@nlake44 this is working. PLease open another issue with a repro project if it's not working for you.
![prefill](https://cloud.githubusercontent.com/assets/941075/26355878/a5e2f2e8-3fa0-11e7-8ecf-6ccb3c6263fb.gif)

**Comment by luisrudge** [comment]
@nlake44 it also does that:
![prefill](https://cloud.githubusercontent.com/assets/941075/26362250/bc915990-3fb3-11e7-801a-aa52195da4ab.gif)

**Comment by nlake44** [comment]
@luisrudge Thanks for the quick response. I meant coming from the email redirect after the user has changed their password.

**Comment by luisrudge** [comment]
Ah, right. Yeah, that is not supported 😭

**Comment by nlake44** [comment]
Any suggestions on how to make it happen?

**Comment by luisrudge** [comment]
Maybe if you edit your email template and add some info (probably the email) in the redirect link, then in your page you can check if the link exists in the url, if it exists, you add it to the prefill option. It's a long shot, but might work
