### ISSUE TITLE
Authentication fail due to `BLOCKED (BRUTEFORCE)` or invalid credentials does not trigger error event when using Popup Mode.

### ISSUE THREAD

**Issue by wyqydsyq** [auth0/lock#938]
So during testing of my integration with Auth0Lock I managed to get locked out of my account, recieving the message: `YOUR ACCOUNT HAS BEEN BLOCKED AFTER MULTIPLE CONSECUTIVE LOGIN ATTEMPTS.`

I noticed that strangely when this occurs, Auth0Lock does not trigger either of it's error events (`unrecoverable_error` and `authorization_error`) making this uncatchable to end-developers.

With the given promise, one would expect it to reject when this error occurs, but the Promise is actually left pending. `auth` here is my configured instance of `Auth0Lock`
```
new Promise((resolve, reject) => {
  auth.on('authenticated', result => {
    resolve(result)
  })

  auth.on('unrecoverable_error', error => {
    reject(error)
  })

  auth.on('authorization_error', error => {
    reject(error)
  })

  auth.show()
})
```

Fiddle:
https://jsfiddle.net/0vkbLg3y/2/

**Comment by luisrudge** [comment]
Ouch. referenced the wrong issue 😭

**Comment by luisrudge** [comment]
@wyqydsyq What version are you using? How are you instantiating Lock? How are you calling lock.show()?

I tested this and it's working as expected:

```html
<!DOCTYPE html>
<html>
<title>Dev</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />

<body>
  <div id="container"></div>
  <script src="http://cdn.auth0.com/js/lock/10.13.0/lock.min.js"></script>
  <script>
    let domain = 'luisrudge-auth0.auth0.com';
    let cid = 'FUshIKv4fCTzWUs9EgF9kPJ8etf9yImk';
    //email: block-me@block-me.com
    //pass:  block

    const lock = new Auth0Lock(cid, domain);

    lock.on("authenticated", function (authResult) {
      console.log(authResult);
    });

    lock.on("authorization_error", function (error) {
      console.log('authorization_error', error);
    });

    lock.on("unrecoverable_error", function (error) {
      console.log('authorization_error', error);
    });

    lock.show();
  </script>
</body>

</html>
```

![image](https://cloud.githubusercontent.com/assets/941075/24165013/1504e87c-0e4e-11e7-9152-2a553bfd7127.png)

![image](https://cloud.githubusercontent.com/assets/941075/24165028/214c09e4-0e4e-11e7-9fa4-43ce321cd6aa.png)

**Comment by wyqydsyq** [comment]
The integration is implemented as a `redux-observable` Epic:
https://gist.github.com/wyqydsyq/f8978dc600e27b3fc02eb7811c58bcaf

To make it easier to reproduce, I've just tried to set up a pen at:
http://codepen.io/anon/pen/rydvxq
There's a blocked account with details:
User: `blocked@codafication.com`
Pass: `Blocked123`

But it seems even if you provide invalid login credentials (resulting in a 401 Unauthorized response) it doesn't fire the error handlers. I can't reproduce my exact issue in this because when providing the correct login details for a blocked account, it seems to try to go to the login callback URL (which I can't whitelist being a generated codepen url) even though it should still be Unauthorized as the account is blocked.

There's a screenshot of the two different tags below. I believe I've also found a UI bug, when an account is `BLOCKED` manually and then also gets the `BLOCKED (BRUTEFORCE)` tag and then you go ACTIONS → Unblock User, both `BLOCKED` tags disappear when actually only the first one should be removed. Upon refreshing the `BLOCKED (BRUTEFORCE)` tag reappears.
![image](https://cloud.githubusercontent.com/assets/621277/24179844/6ba438f4-0efd-11e7-95da-0d5c21aa504b.png)

So in the fiddle, when trying to login as a user that has explicitly been blocked, I get:
![image](https://cloud.githubusercontent.com/assets/621277/24180885/3d02d3c4-0f03-11e7-862f-303cb5b638ed.png)

But when trying to login as a user that has been auto-blocked by brute-force protection, there is no error event or exception thrown, and I see:
![image](https://cloud.githubusercontent.com/assets/621277/24180933/9597fde8-0f03-11e7-9a07-2219d72224c1.png)

It also behaves the same way when failing due to incorrect credentials; no error event is fired.

**Comment by wyqydsyq** [comment]
This appears to be a bug with the Popup Mode; removing `redirect: false` from my options causes the event to get fired correctly when returning to the callback URL. But in Popup mode these error event handlers never get fired even though the Lock UI correctly recieves them.

**Comment by wyqydsyq** [comment]
I've changed my code to use Redirect mode to work around this however using popup mode in my case would be ideal as we're building a large SPA where loading and initializing the entire app again in response to authentication would negatively impact UX.

**Comment by luisrudge** [comment]
Thanks for investigating this! I'll let you know when this bug is fixed. 🐛

**Comment by luisrudge** [comment]
Hi. I did some digging and we don't emit any events for this error indeed. We only emit events for error codes `"blocked_user", "rule_error", "lock.unauthorized"` as you can see [here](https://github.com/auth0/lock/blob/master/src/core/actions.js#L196).

The error we receive is:
<img width="217" alt="screen shot 2017-03-24 at 11 14 23" src="https://cloud.githubusercontent.com/assets/941075/24297896/164a4a56-1083-11e7-88fe-4cf9f2ae2c56.png">


I did the same thing as you did, but I still don't see the events with `redirect: true`.  You shouldn't get this specific event either. Can you share how are you catching this events? The code below doesn't fire any events:

> email: block@blockme.com
> password: test

<img width="879" alt="screen shot 2017-03-24 at 11 16 44" src="https://cloud.githubusercontent.com/assets/941075/24297985/659f54fc-1083-11e7-9b14-88b3d3f9163e.png">

```html
<!DOCTYPE html>
<html>
<title>Dev</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
<body>
  <div id="container"></div>
  <script src="http://cdn.auth0.com/js/lock/10.13.0/lock.min.js"></script>
  <script>
    const cid = "FUshIKv4fCTzWUs9EgF9kPJ8etf9yImk";
    const domain = "luisrudge-auth0.auth0.com";

    const lock = new Auth0Lock(cid, domain, { auth: { redirect: true } });

    lock.on("authenticated", function (authResult) {
      console.log(authResult);
    });

    lock.on("authorization_error", function (error) {
      console.log('authorization_error', error);
    });

    lock.on("unrecoverable_error", function (error) {
      console.log('unrecoverable_error', error);
    });

    lock.show();
  </script>
</body>

</html>
```

**Comment by wyqydsyq** [comment]
Then maybe either additional errors should be added or the documentation should have a note to reflect this, the docs don't specify that the "BLOCKED (BRUTEFORCE)" tag does not trigger any error events even though the Lock UI displays an error message. I had the impression that any errors represented in the Lock UI would also trigger an event handler.

**Comment by eHealthManny** [comment]
The lock documentation also shows an example where a blocked user triggers the "authorization_error" event: 
https://auth0.com/docs/libraries/lock/v11/api#flashmessage

"So, if tester@example.com were now to try to sign in, being a user who is blocked, the user will be shown Lock again, and receive the following error message:"
