### ISSUE TITLE
Implement callback argument for `Lock.hide()` or remove callback argument from docs

### ISSUE THREAD

**Issue by wyqydsyq** [auth0/lock#941]
https://auth0.com/docs/libraries/lock/v10/api#hide-
Currently the docs say that `hide()` has a callback method as it's first argument. This is incorrect according to the actual implementation as well as the TypeScript definition:
```typescript
interface Auth0LockStatic {
    new (clientId: string, domain: string, options?: Auth0LockConstructorOptions): Auth0LockStatic;

    // deprecated
    getProfile(token: string, callback: (error: auth0.Auth0Error, profile: auth0.Auth0UserProfile) => void): void;
    getUserInfo(token: string, callback: (error: auth0.Auth0Error, profile: auth0.Auth0UserProfile) => void): void;
    // https://github.com/auth0/lock#resumeauthhash-callback
    resumeAuth( hash: string, callback: (error: auth0.Auth0Error, authResult: any) =>  void): void;
    show(options?: Auth0LockShowOptions): void;
    hide(): void;
    logout(query: any): void;

    on(event: "show" | "hide", callback: () => void): void;
    on(event: "unrecoverable_error" | "authorization_error", callback: (error: auth0.Auth0Error) => void): void;
    on(event: "authenticated", callback: (authResult: any) => void): void;
    on(event: string, callback: (...args: any[]) => void): void;
}
```

`hide()` should either implement this callback argument as documented (preferred) or the callback arg should be removed from the docs.

I think actually implementing the callback would be good because it would allow developers to do stuff in response to it hiding. For example my `lock.on('unrecoverable_error', err => { ... })` handler is calling `lock.show()` again with a `flashMessage` specified, but I have to create a whole new lock instance for this to work as calling `show()` on an already `show()`n lock does nothing, and if I try to `hide()` it before I `show()` again, the second `show()` will not do anything and I'm left with no lock UI at all, seemingly due to a race condition with the call to `hide()`. If `hide()` had a working callback I could just do something nice and clean like this in my error handler:
```typescript
lock.hide(() => lock.show({flashMessage: {type: 'error', text: errorMessage}}))
```

**Comment by luisrudge** [comment]
I added this but after giving more thought about it, you can use the `hide` event to do that:

```js
lock.on('hide', () => lock.show({flashMessage: {type: 'error', text: errorMessage}}));
```

Does that work for you?

**Comment by wyqydsyq** [comment]
I'm not sure if that would really work as intended - I only want to call `lock.show()` with the `flashMessage` after calling `lock.hide()` in a particular scenario.

Doing this on the `hide` event would cause it to happen every time the lock is hidden because my instance of `Auth0Lock` is a singleton and binding that `hide` handler would mutate the singleton making it so whenever the Lock is closed (say, upon a later successful login) it would re-open with that `flashMessage`.

So in my use case I'm wrapping the Lock in a Promise like so:
```javascript
new Promise((resolve, reject) => {
  auth.on('authenticated', result => {
    resolve(result)
  })

  auth.on('unrecoverable_error', error => {
    reject(error)
  })

  auth.on('authorization_error', error => {
    reject(error)
  })

  auth.show()
})
```

When the promise rejects (`unrecoverable_error` or `authorization_error` event fires) I'm sending the error to my external logger and re-showing Lock with the error message from the auth response.

This way I can initialize it the same generic way on initial load, saving me from parsing the `location.hash` to determine the result and allowing me to handle all errors from Lock in the same way.

From what I see here my options are:
- Ugly way: Parse the URL hash myself on initial load before `show()` is ever called, and make the first call to `show()` have the `flashMessage` specified from what I extracted, this duplicates my error handling because I need to account for errors on initial page load (from Auth0 callback redirect) as well as async ones that occur and prevent the redirect (e.g. ones that trigger a 401 XHR request that gets emitted by the `lock` event handlers without a redirect).
- Nice way: Call `show()` with no options on every page load and let Lock parse the URL hash and fire it's error events when it detects an error, my code wraps that up as a nice promise which if it resolves, calls `hide()` and sets the user details in my app state, or if it rejects, calls `hide()` and then `show()` with the `flashMessage` specified from the error that gets emitted.

I'm doing it the nice way but for it to work I need to create a new Lock instance because it seems calling `show()` on the same Lock instance a second time has no effect instead of causing it to re-render with the new options which is what I expected.

If I simply bind the `show()` with `flashMessage` inside `lock.on('hide')` that would also cause successive ones (even if there aren't errors) to also show a new lock after hiding that unless I explicitly set `lock.on('hide')` to a noop in my success case.

What I [have now](https://gist.github.com/wyqydsyq/f8978dc600e27b3fc02eb7811c58bcaf) does work, I'm just proposing the callback be available because I feel it would enable a far more ergonomic use, for example I currently have this in my `loginFailed` action handler:
```typescript
lock = undefined
return dialogActions.showLogin({
  rememberLastLogin: false,
  flashMessage: {
    type: 'error',
    text: action.payload.error_description
  }
})
```
But if `hide()` had a callback, I could wrap it in a Promise:
```typescript
const hideLogin = () => new Promise(res => lock.hide(() => res(true)))
```
And then change my `loginFail` action handler to a more readable async function like:
```typescript
await hideLogin()
return dialogActions.showLogin({
  rememberLastLogin: false,
  flashMessage: {
    type: 'error',
    text: action.payload.error_description
  }
})
```

Or an even cleaner solution would be if calling `show()` on the same `lock` instance successively causes it to re-render. It seems currently calling `show()` on an already visible Lock screen does nothing.

If you're adamant on keeping the existing behaviour then I'd say just remove the callback argument from the [documentation on `hide()`](https://auth0.com/docs/libraries/lock/v10/api#hide-) and close this issue 😄

**Comment by luisrudge** [comment]
I get your reasoning but I feel that having two ways to do the same thing (subscribe to the `hide` event and use a callback in the `hide` method) is too confusing.

Have you considered not using a Promise in this case? Something like:

```js
const handleAuthSuccess = (authResult) => console.log(authResult);

const handleError = (error) => auth.show({
  rememberLastLogin: false,
  flashMessage: {
    type: 'error',
    text: error.error_description
  }
})

auth.on('authenticated', handleAuthSuccess);

auth.on('unrecoverable_error', handleError);

auth.on('authorization_error', handleError);
```

Then you call the `show` method when the user clicks a specific button or loads a specific page. Does that work for you?
