### ISSUE TITLE
Lock doesn't catch the callback with Angular-CLI --prod enviornment

### ISSUE THREAD

**Issue by tomtobac** [auth0/lock#944]
Thank you for using Lock! Please read the following before creating a new issue.

- [x] Is this a question about Auth0 in general.
- [ ] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Otherwise, create a new issue with the following information:
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [x] Lock version (10.13.0)
- [x] Browser & OS (Linux && chrome Version 57.0.2987.110 (64-bit))

Hello guys, 
Actually we've a few enterprise projects with auth0 and looks like when we build project with prod environments doesn't works like with dev environment. The lock doesn't catch the callback and never gets authenticated. I provide an minimum example that you can play with. Just install dependencies, and execute `ng server` (it will take dev environment by default) and creates an account, "works fine" but when I use `ng serve --prod` with prod environment it builds ok but when I try to get the callback, the lock never catch it...

https://github.com/tomtobac/auth0-example

Thank you!

**Comment by luisrudge** [comment]
Hi! This is a problem with the angular code. I know you got it from our samples, so I already opened an issue in their repo and pinged @chenkie internally about this. Please subscribe to this issue (https://github.com/auth0-samples/auth0-angular-samples/issues/18) to get news about this issue.
