### ISSUE TITLE
Lock header inconsistent across browsers

### ISSUE THREAD

**Issue by riyaznet** [auth0/lock#954]
I am using latest version of Auth0 Lock (v10). When specifying custom theme color like so:

```
options = { 
         ...
        theme: {
            primaryColor: '#3A99D8',
            labeledSubmitButton: false
        },
         ...
     }
```

The Lock header background shows up with blurred version of primaryColor in all browsers except Chrome.

I noticed that div with class="auth0-lock-header-bg-solid" is not positioned correctly on the Lock header in Chrome while in other browsers it gets placed correctly. In Chrome, an extra css class "auth0-lock-blur-support" gets added to the div above the div.auth0-lock-header-bg-solid which pushes it down.

It seems the Lock on auth0.com's homepage also has same behavior. 

Is there a way we can turn off this blur-support without overriding css locally?

Please see the screenshots below:

![other-browsers](https://cloud.githubusercontent.com/assets/4646860/24375119/cfb6e1b0-1354-11e7-83f8-202438c987c5.JPG)

![chrome](https://cloud.githubusercontent.com/assets/4646860/24375118/cfb2ca26-1354-11e7-969a-4f178860ccfa.JPG)

Thanks.

Riyaz

**Comment by hzalaz** [comment]
As stated in the PR this is not an issue but how lock works on browsers that does not support the blur. We will add some options to remove the blur and specify a custom color for the header background in #974. 

The only way now is to customize the CSS to remove the blur so it picks the primary color
