### ISSUE TITLE
Lock RN will break for Google Authentication on April 20

### ISSUE THREAD

**Issue by lukecwilliams** [auth0/lock#955]
Need a reply here urgently so posting on broader Lock thread.  Google third-party authentication will be broken with Lock for React Native on April 20.  We don't have an answer on [this thread](https://github.com/auth0/react-native-lock/issues/105#issuecomment-289135772) since Nov 2016.

Can someone put our minds at ease and confirm that Lock RN will support the change very soon, so we'll have time to integrate, verify, and deploy the change with time to spare before the changeover?  That would mean we need action from Auth0 very soon, like this week.  Thanks in advance.

**Comment by hzalaz** [comment]
This is not the proper place since its used for tracking lock for browser so there is little to be done here
