### ISSUE TITLE
Scroll to error message when not in viewport

### ISSUE THREAD

**Issue by selaux** [auth0/lock#959]
We noticed that on smartphones it happens that when you try to login an have invalid credentials, the error message might appear outside the very small viewport that you have when the on-screen keyboard is shown. So the user basically gets no feedback on his login attempt. This could be fixed by scrolling to the lock container top when an error message is shown outside the viewport. What do you think?

**Comment by luisrudge** [comment]
maybe we can instead remove the focus from the keyboard and (hopefully) close it?

**Comment by luisrudge** [comment]
fixed by #1023
