### ISSUE TITLE
Please consider using namespaced css

### ISSUE THREAD

**Issue by tomjkidd** [auth0/lock#960]
In a project that I'm working on, a `fade` CSS animation class was being used and auth0's css injection trampled our project's. In order to better insulate users of this repo from encountering some of these issues, this is mostly just a formal request to consider creating namespaced versions of the CSS you will be injecting to reduce these types of collisions.

https://github.com/auth0/lock/blob/master/css/_transitions.styl#L154

**Comment by luisrudge** [comment]
I agree with you and I'm sad that we didn't think about this before. However, this would be a breaking change since LOTS of customers are relying on our css classes (maybe not the animation classes). I'll add this to our backlog but I can't see us changing this in the near future. Thanks!
