### ISSUE TITLE
this.clients[lockID].logout is not a function

### ISSUE THREAD

**Issue by theamazingfedex** [auth0/lock#968]
I'm trying to enable users to log out from auth0, but it seems like there is something not set up right. I keep getting this error:
![ErrorImage](https://cloud.githubusercontent.com/assets/6488706/24675677/554b9210-193d-11e7-99d2-c5f4ff8b284b.png)

- [x] Code snippet or sample project that reproduces the bug

**lockHelper.js:**
``` javascript 
const options = {
  auth: {
    responseType: 'token',
    redirectUrl: `${getBaseUrl()}/auth/signed-in`,
    params: {
      scope: 'openid email',
      state: secret
    }
  }
}
const lock = new Auth0Lock(clientId, clientDomain, options);
const logout = () => lock.logout({ returnTo: getBaseUrl() });
```
- [x] Lock version
`v10.7.2`
- [x] Browser & OS
Browser: `chrome v56.0.2924.87`
OS: `windows7`

**Comment by luisrudge** [comment]
`logout` is not a documented method, but it will be. It's not working now because it was supposed to be removed in the v9-v10 upgrade but it wasn't (and it still has the old api). This PR will fix and document this. It will be in the next release: https://github.com/auth0/lock/pull/966

**Comment by theamazingfedex** [comment]
Oh. well that's nifty to know.. How do I handle logging out in my current version?

**Comment by luisrudge** [comment]
you can use auth0-js directly: https://auth0.com/docs/libraries/auth0js/v8#logout

**Comment by theamazingfedex** [comment]
So can I use the lock to log in, and then use auth0-js to log out? or do I have to implement logging in with auth0-js as well?

**Comment by theamazingfedex** [comment]
Well, it works, I suppose my question is more of, does this introduce any problems with the lock, having login happen through the lock and logoff happen directly with the auth0 api?

**Comment by luisrudge** [comment]
Yep! You can use lock to log in and auth0-js to logout. This will work just fine. Lock calls auth0-js internally. The main issue here is that our method `logout` is calling a method that doesn't exist in auth0-js, because it's an old API we forgot in the code. If you can't wait, use lock + auth0-js. If you can wait, our next release will be next monday, then you'll be able to call logout directly into your lock instance.

**Comment by theamazingfedex** [comment]
Cool! thanks for the prompt responses Luis! I was following your example in [next.js-auth0](https://github.com/luisrudge/next.js-auth0); you may want to make a note to update that once the API update hits. Thanks again! :+1:

**Comment by luisrudge** [comment]
Yesssssssssssss! That's exactly how I found the logout error! Also, if you don't mind, you can just rollback your lock version to `10.7.2`. `logout` works in that version!

**Comment by theamazingfedex** [comment]
Neat! I just tried with 10.7.2, and I still get the same error. I'll be fine just keeping this as a todo in my project til monday.

**Comment by luisrudge** [comment]
You have to remove auth0js from your project to make it work with 10.7.2

**Comment by MarcMagnin** [comment]
Hey, I just dropped an issue on https://github.com/luisrudge/next.js-auth0/issues/15 as I'm facing the same issue. Basically is it recommended to just use auth0-js? If yes then that would be ideal to have an example using it instead.
Many thanks

**Comment by luisrudge** [comment]
Just make sure to use the latest release, which includes: https://github.com/auth0/lock/pull/966
