### ISSUE TITLE
Login callback does not fire in popup mode

### ISSUE THREAD

**Issue by mikegleasonjr** [auth0/lock#969]
My system is working properly in redirect mode. As soon as I switch to popup mode my login callback does not get called and I'm stuck on this screen (no js error in console):

![2017-04-06 at 5 29 am](https://cloud.githubusercontent.com/assets/1644534/24737914/0b591256-1a8a-11e7-94ba-3a861985b9b9.png)

**Comment by mikegleasonjr** [comment]
Issue is on my end, sorry :)

**Comment by luisrudge** [comment]
Can you share what the problem was? Thanks!

**Comment by mikegleasonjr** [comment]
I was using the callback method (redirect = true). In react I was manually calling `lock.resumeAuth()` in a route dedicated to the callback from auth0.

Sometimes I am embedding my app in an iframe. So when it is embedded I set `redirect: false` to open a pop-up and prevent a cross domain issue when my users are using Facebook.

But since there is no redirect in pop-up mode, in that case, I just have to listen to the `authenticated` event to "resume" my auth.

So this was a miscomprehension on my end. Thanks for caring about the problem!

**Comment by luisrudge** [comment]
Thanks for explaining!
