### ISSUE TITLE
Playground page is not working in IE11

### ISSUE THREAD

**Issue by alexsorokoletov** [auth0/lock#97]
http://auth0.github.io/playground/
![shot_141225_172528](https://cloud.githubusercontent.com/assets/1788581/5555042/1535ae66-8c5b-11e4-932a-0fd518b69dda.png)

**Comment by alexsorokoletov** [comment]
Now it's working! :) Is this fix applicable to login pages based on lock script?

**Comment by cristiandouce** [comment]
It was not a lock issue, but with the playground itself... if that's what you ask @alexsorokoletov

**Comment by alexsorokoletov** [comment]
I see. Let me check our login page in IE (that was the reason I came for the playground) and maybe report another issue. Thank you.

**Comment by alexsorokoletov** [comment]
Hi! Should I open related issue or reopen this one if my auth0 lock login page (basically default one, almost without customizations) renders wrong in IE10+?
https://hipaachat.auth0.com/login?client=xlgC789SYNCN1NMxQcfgT2CFQE8zLK4g&redirect_uri=https://hipaachat.auth0.com/mobile&scope=openid+profile&response_type=token

**Comment by pose** [comment]
Hi @alexsorokoletov,

Can you open a new issue? Also, can you send us an screenshot that shows how the render is wrong on IE10+?

Thanks in advance,
