### ISSUE TITLE
There was an error processing the password reset.

### ISSUE THREAD

**Issue by halt-hammerzeit** [auth0/lock#972]
Our company uses Auth0 for user authentication and when a user clicks "Don't remember your password?" they get emailed a link:

```
https://jitu.auth0.com/lo/reset?ticket=adfasdfasdfasdfasdfasdfsadfasd
```

On this password reset page an error is shown after submitting the form:

> There was an error processing the password reset.

This page is the default one, no customization

The actual response is status 400:

```
<h3>Change Password</h3>
<p><span>The operation cannot be completed. Please try again.</span></p>
```

And no other info on what actually happened.

**Comment by luisrudge** [comment]
Did you see the logs in your dashboard? Is there anything there?

**Comment by luisrudge** [comment]
Also, this is not a Lock issue. Please open a ticket here: https://support.auth0.com/
Thanks!

**Comment by halt-hammerzeit** [comment]
Oh, it has logs....

So, it says:

```js
{
  "date": "2017-04-14T18:44:32.544Z",
  "type": "fcp",
  "description": "The operation cannot be completed. Please try again.",
  "connection": "Username-Password-Authentication",
  "connection_id": "xxxxx",
  "details": {
    "title": "Change Password",
    "body": {
      "ticket": "xxxxxx"
    },
    "query": {
      "client_id": "xxxxx",
      "connection": "Username-Password-Authentication",
    }
  },
  "user_id": "",
  "user_name": "fasdfasd",
  "strategy": "auth0",
  "strategy_type": "database",
  "log_id": "49560429270835143462025656395989475672350324906931519490"
}
```

Ok, opening a ticket there.
I agree that it's their issue because the error message could be more verbose in the logs.

**Comment by anshupitlia** [comment]
Hey, I know it is closed. I'm facing a similar issue. Were you able to find a solution?

**Comment by catamphetamine** [comment]
We bought auth0 support plan and they somehow fixed that for us.
