### ISSUE TITLE
Additional Header customization options

### ISSUE THREAD

**Issue by hzalaz** [auth0/lock#974]
Add headerBackgroundColor option (or similar) that forces Lock to have a solid header color (removes the blur). By default is `undefined` which means lock continues to work as it works now:

- Blurs the logo and applies a gray mask on Chrome and Mobile
- On browsers where blur does not work it just uses the primary color.

Also we can add, if possible, an option to remove gray mask so the blur tries to pick the image colors.

**Comment by beneliflo** [comment]
Looking in the css we have a class ready to use here to remove grayscale and just let the header blured with the icon color: https://github.com/auth0/lock/blob/master/css/index.styl#L235

**Comment by luisrudge** [comment]
Can we make it so it works like IE/mobile everywher? I mean.. Just use the primary color and that's it?

**Comment by hzalaz** [comment]
It's part of the design so we will stick with it for the time being

**Comment by ened** [comment]
I'd like to weigh in for an option to remove the blur altogether which then will look better for simple logos.

**Comment by fsargent** [comment]
I also would like to remove the blur. Most of the time it's just a splotchy grey blob. Compare:

![image](https://user-images.githubusercontent.com/273880/28423601-78b3bf5c-6d39-11e7-93f1-91628ecc5926.png)

![image](https://user-images.githubusercontent.com/273880/28423583-69955e9a-6d39-11e7-84f6-b6e857afc436.png)

**Comment by luisrudge** [comment]
@fsargent You can override the css for now: https://github.com/auth0/lock/issues/1058#issuecomment-314789990

**Comment by fsargent** [comment]
That's great - should be part of the official docs!
