### ISSUE TITLE
Email validation errors restricted to English only

### ISSUE THREAD

**Issue by missCarrieMah** [auth0/lock#976]
In addition to the missing customizability with the email validation errors, the language support is missing as well. This seems like a bug, because most of the content appear to be customizable in the files [lock/src/i18n/](https://github.com/auth0/lock/tree/388ff1beb3e3670834a440d420a36470f7a5fe69/src/i18n)). 

However, the email validation content appears to not be customizable. This is found in [lock/test/out-of-date/cred/index.js](https://github.com/auth0/lock/blob/0149fe9dd741a29e36f1191efed6fe4ebf8ca581/test/out-of-date/cred/index.js) starting from [Line 267](https://github.com/auth0/lock/blob/0149fe9dd741a29e36f1191efed6fe4ebf8ca581/test/out-of-date/cred/index.js#L267).

While testing auth0's Lock screen, you can add the parameter `&lang=fr` to the url (domain.auth0.com). If I enter an invalid email format, the error is in English, not French. If I were a French user, I would expect the error in that language. This also applies to other languages.

![Screenshot](https://cloud.githubusercontent.com/assets/7146212/25192433/6340b184-24f0-11e7-9987-29ec5c2b0299.png)

**Comment by hzalaz** [comment]
@missCarrieMah could that be a browser validation instead of Lock's?

**Comment by luisrudge** [comment]
This is the standard html5 validation and probably user your browser's language to show the message.
![image](https://cloud.githubusercontent.com/assets/941075/25192691/a15e8dd2-250a-11e7-933a-f9e634e06aca.png)

**Comment by missCarrieMah** [comment]
Thanks for the reply!
