### ISSUE TITLE
v10.15.0 - Move eslint dependencies into devDependencies

### ISSUE THREAD

**Issue by danthegoodman** [auth0/lock#983]
I just upgraded to v10.15.0 and the dependencies added from issue #977 are conflicting with some of the ESlint dependencies in my own project. Can these be moved to dev dependencies? 

Dependencies introduced in #977:
* babel-eslint
* eslint-config-prettier
* eslint-plugin-react
* husky
* lint-staged

**Comment by luisrudge** [comment]
Ouch! Totally my fault. Will fix this tomorrow ASAP. Sorry about the inconvenience!

**Comment by luisrudge** [comment]
This was just released as v10.15.1

**Comment by danthegoodman** [comment]
🎉 Nice! Thank you for the super quick fix!
