### ISSUE TITLE
Add option to enable autocomplete for username/email inputs

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#987]
I've received a number of questions from our users on why the login page isn't autocompleting their username like it used to (before we upgraded Lock). After taking a look, I discovered that the `autocomplete` attribute is set to `off` on the username field. I did some digging and traced it back to this commit: https://github.com/auth0/lock/commit/70c0b0eee60b883e86b28c8f8b37aef9548b6486

I'm not sure why autocomplete was disabled. Is there a reason for this? If not, can we switch autocomplete back on? Thanks!

**Comment by luisrudge** [comment]
We might consider an option to enable autocomplete for the username/email field. Does that work for you?

**Comment by maxlapides** [comment]
That would work! And out of curiosity, why is it disabled by default? Thanks.
On Thu, Apr 27, 2017 at 7:06 AM, Luís Rudge <notifications@github.com> wrote:
We might consider an option to enable autocomplete for the username/email field. Does that work for you?

**Comment by luisrudge** [comment]
I think it broke some styles or validations when we were migrating to v9 to v10. I wasn't here, so I'm not sure.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/lock/pull/1022
