### ISSUE TITLE
The project must be updated to work with OIDC

### ISSUE THREAD

**Issue by nnats** [auth0/lock#991]
Steps to reproduce the error:

- Turn on OIDC conformant toggle.
- Run the seed project.
Expected result: The log in works.
Result: The Logs from Auth0 show this message: " Password login is disabled for clients using externally
 hosted login pages with oidc_conformant flag set."

![image](https://cloud.githubusercontent.com/assets/20141842/25602338/6bad1be0-2ec9-11e7-89b5-4c67dbc24e50.png)

**Comment by hechanghong** [comment]
Hi, I'm facing the same issue. But not sure why this is closed without solutions. Please kindly share your solutions, thanks.

**Comment by sonvirc** [comment]
Disable the OIDC Conformant in advanced settings of Clients

![screen shot 2017-10-06 at 12 25 34 pm](https://user-images.githubusercontent.com/28830195/31266496-abb5f3bc-aa91-11e7-9e85-f459ecc0df25.png)

**Comment by luisrudge** [comment]
Lock now fully supports OIDC Mode. Docs [here](https://github.com/auth0/lock#oidc-conformant-mode)

**Comment by AdvinRoz** [comment]
@luisrudge I still get the same error-message with an externally
hosted login page. Is the externally hosted login page also oidc conformant?

**Comment by luisrudge** [comment]
What is the "externally hosted login page"?

**Comment by AdvinRoz** [comment]
If you embed lock as an popup into your own webpage, instead of using the hosted page of Auth0

**Comment by luisrudge** [comment]
Ah, right. If you use lock in embedded mode, when you host it yourself, we also support both OIDC and non-OIDC clients. If you want to use with an OIDC client, just follow the instructions [here](https://github.com/auth0/lock#oidc-conformant-mode)
