### ISSUE TITLE
Multiple audience in Auth0Lock

### ISSUE THREAD

**Issue by anitchanana** [auth0/lock#992]
Hi
I have a  jquery SPA using auth0. I have been able to create a token and use it to access an API

  var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
    auth: {
        params:
            {
                scope: 'openid profile',
                audience: 'API Url'
            }
           
    },
    
  });

I can access API specified in the audience using the token generated .
Now I want to access another API (other API is also the client of same auth0 domain that the client is of).
but with that token , i am only able to access API specified in audience property.
How can i specify mutliple audience so that token can be used to access mulitple APIs.

**Comment by hzalaz** [comment]
@anitchanana for now there is only support for a single audience in our server (not a limitation of this library). Can you please ask via https://support.auth0.com?
