### ISSUE TITLE
react-addons-css-transition-group deprecated

### ISSUE THREAD

**Issue by mikebridge** [auth0/lock#994]
Updating to React 15.5.4 gave me this warning (when running `yarn upgrade`):

<blockquote>
warning auth0-lock > react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.
</blockquote>

Looks like [this](https://facebook.github.io/react/docs/animation.html) is the relevant documentation.

**Comment by luisrudge** [comment]
Thanks for the heads up.

**Comment by eoinmurray** [comment]
This would be very useful to fix.

**Comment by luisrudge** [comment]
Hi! Sorry, this isn't a priority right now, but I can certainly review a PR if you send one. Thanks!
