### ISSUE TITLE
Not all errors trigger an event

### ISSUE THREAD

**Issue by Gertt** [auth0/lock#998]
When reading the documentation, I was given the impression that the `authorization_error` event would be triggered whenever a user failed to authorize. However, it does not trigger when the user enters a wrong email/password combo for a database connection.

Not sure if you would consider this a bug or expected behaviour. In case it's expected:

- maybe the documentation should be a bit clearer on this,
- would you guys consider adding a way to listen to more errors?

**Comment by luisrudge** [comment]
I added the username/pass error to the event. We'll evaluate other events on a case by case basis.
